### ISSUE TITLE
registry.rb fails due to inadequate Fiddle wrapper

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7308] opened 2022-08-12 22:52 UTC
registry.rb's functions currently fail to work, ever since we updated this library from CRuby and it started using Fiddle instead of our FFI-based win32api to make calls. See #7307 for the root issue.

In the absence of a complete fix for Fiddle, a shorter-term fix to get things working again would be to revert the registry.rb logic back to using win32api, or directly using FFI.

Note that this prevents most networking from functioning on Windows, since as part of the 3.0/3.1 update, those libraries now use resolv.rb for DNS lookups, which in turn depends on registry.rb.

**Comment by eregon** [comment] 2022-08-12 22:54
It'd be great if this is fixed soon.
Otherwise I think we'll need to remove jruby-head on Windows in setup-ruby because it doesn't work for too long, and it prevents getting newer jruby-head on other platforms.

**Comment by headius** [comment] 2022-08-15 16:29
@eregon The build of JRuby for Windows can be done on any platform.

**Comment by eregon** [comment] 2022-08-15 16:48
That's not a problem, the problem is jruby head on Windows is broken for any networking, and so completely unusable in CI. The open-uri check I have is just a sanity check and that fails.

**Comment by eregon** [comment] 2022-08-15 17:16
Specifically, see the steps and error at https://github.com/ruby/jruby-dev-builder/actions
and e.g. https://github.com/ruby/jruby-dev-builder/runs/7828556975?check_suite_focus=true

My thinking is if open-uri/net-http/resolv don't work then `gem/bundle install` won't work either.
In fact, it seems to error while trying to `require 'net/http'`, which `require 'resolv'`, which errors out:
```
Run ruby -ropen-uri -e 'puts URI.send(:open, %{[https://rubygems.org/})](https://rubygems.org/%7D)) { |f| f.read(1024) }'
ArgumentError: cannot convert parameter to native pointer
         OpenKey at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/win32/registry.rb:289
            open at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/win32/registry.rb:431
            open at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/win32/registry.rb:542
   get_hosts_dir at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/win32/resolv.rb:142
  get_hosts_path at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/win32/resolv.rb:15
   <class:Hosts> at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/resolv.rb:176
  <class:Resolv> at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/resolv.rb:172
          <main> at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/resolv.rb:38
         require at org/jruby/RubyKernel.java:1017
         require at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
          <main> at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/net/http.rb:25
         require at org/jruby/RubyKernel.java:1017
         require at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
       open_http at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/open-uri.rb:268
     buffer_open at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/open-uri.rb:741
       open_loop at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/open-uri.rb:212
           catch at org/jruby/RubyKernel.java:1238
       open_loop at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/open-uri.rb:210
        open_uri at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/open-uri.rb:151
            open at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/open-uri.rb:721
            open at D:/a/jruby-dev-builder/jruby-dev-builder/jruby-head/lib/ruby/stdlib/open-uri.rb:29
          <main> at -e:1
```

**Comment by enebo** [comment] 2022-08-15 18:27
Going back to 9.3 registry using win32/importer instead of fiddle.  #7307 will allow us to go back to what MRI is using but for now we will continue using what is working.  Speculatively closing since I can now build on windows again and @eregon URI command-line runs as expected.

@eregon If we still have an issue let us know.  We think it is just registry but 9.4 work has had a lot of changes done.

**Closed by enebo** 2022-08-15 18:27 UTC
Labels: windows, stdlib, ffi

**Comment by eregon** [comment] 2022-08-16 16:20
It works, thank you!
https://github.com/ruby/jruby-dev-builder/actions/runs/2869258010
