### ISSUE TITLE
Disabling Fixnum cache seems broken

### ISSUE THREAD

**Issue by Mahaswami** [jruby/jruby#6186] opened 2020-04-22 16:33 UTC
**Environment Information**

JRuby 9.2.11 / Ubuntu 18.04 / JDK 14
  
Flags: -Djruby.fixnum.cache=false
Rails: 4.2.x

**Expected Behavior**

Rails app to function normally with the flag setting -Djruby.fixnum.cache=false. 

**Actual Behavior**

Note: We were originally using this flag when Benchmarking using GraalVM. Once we found this issue we tried it again in JDK 14 and issue still exists.

When this flag is turned on, the app blows up with the following exception

org.jruby.exceptions.TypeError: (TypeError) no implicit conversion of nil into Integer

Please see the attached trace.

[jrub-fixnum-cache-disabling-exception-trace.txt](https://github.com/jruby/jruby/files/4517538/jrub-fixnum-cache-disabling-exception-trace.txt)

**Comment by headius** [comment] 2020-04-22 22:44
Thank you for the report. Given that this mode is recommended for numeric performance on some JVM JIT configurations, we probably should get tests passing with fixnum cache turned off.

**Comment by headius** [comment] 2020-05-16 06:45
@Mahaswami I was not able to reproduce this running the racc tests, so I'm wondering if this may have been fixed in a more recent version. Could you find out what version of racc that is, and if you can reproduce it with the property `jruby.backtrace.style=full` set I might be able to dig deeper.

**Comment by headius** [comment] 2020-06-09 13:07
Closing until there's an updated error on the current version of racc.

**Closed by headius** 2020-06-09 13:07 UTC
