### ISSUE TITLE
Exceptions raised from within Tempfiles change original path on macOS

### ISSUE THREAD

**Issue by kyrylo** [jruby/jruby#5436] opened 2018-11-11 11:09 UTC
```rb
tf = Tempfile.new
#=> #<Tempfile:/var/folders/gk/0g887jcx5jdcdfn8fvjfmctc0000gn/T/20181111-62383-wlw4o0>
tf << 'raise'
tf.flush
load tf.path
# RuntimeError:
# from /private/var/folders/gk/0g887jcx5jdcdfn8fvjfmctc0000gn/T/20181111-62383-wlw4o0:1:in `<main>'
```

My tempfile was created in `/var/folders/...` but the raised exception reports `/private/var/folders`. Ruby maintains the original path. I suspect this issue is only related to macOS because when I run Pry tests on Linux they don't fail. However, locally, on macOS they do.

* jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]
* Darwin Kyrylos-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

**Comment by kyrylo** [comment] 2018-11-11 17:42
Apologies, I didn't realise 9.2.3.0 was the latest one. https://github.com/postmodern/chruby/wiki/JRuby gave me a false impression that 9.2.0.0 was the latest one.

Anyway, I've tried it again and it still has the same problem on:

> jruby 9.2.3.0 (2.5.0) 2018-11-09 5833e2d Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]

**Comment by headius** [comment] 2018-11-12 00:37
Just to clarify, you only saw this because Pry's tests are expecting the error path to be the same, right?

**Comment by kyrylo** [comment] 2018-11-12 08:21
That's correct, however it doesn't break anything in Pry (but a few tests).

**Comment by headius** [comment] 2018-11-12 17:02
This is unrelated to Tempfile, other than the fact that it is used to create the file in a system-default temp location, which on MacOS is a symlinked directory. The main issue is that the RuntimeError raised within the temp-located file gets the full canonicalized path to the current file. I believe the cause of the problem is probably the same as #5240, canonicalizing "too much" when loading files out of symlinked paths.

**Comment by headius** [comment] 2018-11-12 17:05
This appears to be a regression from 9.1 to 9.2. JRuby 9.1.17 produces an error with the "var" path instead of the "private/var" path.

**Comment by headius** [comment] 2018-11-12 17:06
Closing as a dupe of #5240.

**Closed by headius** 2018-11-12 17:06 UTC
