### ISSUE TITLE
proc.call doesn't work as CRuby

### ISSUE THREAD

**Issue by ntysdd** [jruby/jruby#5794] opened 2019-07-17 11:41 UTC
This code snippet doesn't work on JRuby.
```
def f
  proc.call
end

f {
  puts 'ok'
}

```
Tested on 9.2.7.0, OpenJDK 12
An error is raised.
`yield` worked as expected.

**Comment by Adithya-copart** [comment] 2019-07-17 22:10
Possible duplicate of https://github.com/jruby/jruby/issues/3915

I guess this explanation applies here too: https://github.com/jruby/jruby/issues/3915#issuecomment-275169961

**Comment by ntysdd** [comment] 2019-07-18 08:50
Reasonable.

Adithya Pentela <notifications@github.com> 于2019年7月18日周四 上午6:10写道：

**Comment by headius** [comment] 2019-07-20 16:03
Yes, this is the same as #3915 and can be worked around the same way by capturing the block in the definition of "f". We have no plans to support this feature, since it doesn't make a whole lot of sense anyway.

**Closed by headius** 2019-07-20 16:03 UTC
