### ISSUE TITLE
Intermittent JSON::ParserError: unexpected token with Java 11+

### ISSUE THREAD

**Issue by kalenp** [jruby/jruby#6554] opened 2021-02-10 21:15 UTC
We're seeing intermittent JSON::ParserError exceptions when parsing valid json strings.  Unfortunately we don't have a good reproduction on this, we just see it coming from production error logs.  It appears that when a system gets into this state, that it is fairly persistent, and it will continue producing ParserErrors until rebooted.  Rebooting a process will clear up the issue.

We believe this is related to the Java version, as we started seeing this after upgrading from Java 8 to Java 11.

The particular ParserError message seems to include all of the remaining JSON to be processed, but does not necessarily start at the beginning of the string.  One example from our logs:
```
JSON::ParserError: unexpected token at '{"message_stats.date_hour_date":"7 days"}'
```

We encounter these errors on internal data as well as external, so it seems to be a processing issue, as the internal data should always be fixed, valid json.

JRuby - 9.2.13.0
JSON gem - 2.3.0-java

**Comment by Freaky** [comment] 2021-02-10 22:53
I've been seeing similar errors, even on fixed static strings directly embedded in Ruby source, though the presentation here is different - tending to occur early in process lifecycle, and being seemingly one-off events.

I'm only able to reproduce the issue on OpenJDK 15 - 14 and lower don't show the same problem.  I'm also only able to reproduce it in the context of an app, not a minimal testcase:

```
❯ bin/freshbsd bork
Warming up --------------------------------------
            JSON gemJSON::ParserError: unexpected token at '{"took":37,"timed_out":false}'
                                getStackTrace at java/lang/Thread.java:1598
                             getBacktraceData at org/jruby/runtime/backtrace/TraceType.java:242
                                 getBacktrace at org/jruby/runtime/backtrace/TraceType.java:53
                             captureBacktrace at org/jruby/RubyException.java:371
                                     preRaise at org/jruby/exceptions/RaiseException.java:115
                                       <init> at org/jruby/exceptions/RaiseException.java:65
                                       <init> at org/jruby/exceptions/RaiseException.java:215
                                 newException at json/ext/Utils.java:72
                                 newException at json/ext/Parser.java:2365
                              unexpectedToken at json/ext/Parser.java:310
                           parseImplemetation at json/ext/Parser.java:2333
                                        parse at json/ext/Parser.java:2338
                                        parse at json/ext/Parser.java:238
                                         call at json/ext/Parser$INVOKER$i$0$0$parse.gen:-1
                                         call at org/jruby/runtime/callsite/CachingCallSite.java:141
                           invokeOther1:parse at home/freaky/$_dot_rbenv/versions/jruby_minus_9_dot_2_dot_14_dot_0/lib/ruby/gems/shared/gems/json_minus_2_dot_5_dot_1_minus_java/lib/json//home/freaky/.rbenv/versions/jruby-9.2.14.0/lib/ruby/gems/shared/gems/json-2.5.1-java/lib/json/common.rb:216
                                        parse at /home/freaky/.rbenv/versions/jruby-9.2.14.0/lib/ruby/gems/shared/gems/json-2.5.1-java/lib/json/common.rb:216
                                         call at org/jruby/internal/runtime/methods/CompiledIRMethod.java:80
                                         call at org/jruby/internal/runtime/methods/CompiledIRMethod.java:103
                                         call at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:140
                                         call at org/jruby/internal/runtime/methods/DynamicMethod.java:200
                                         call at org/jruby/runtime/callsite/CachingCallSite.java:172
                           invokeOther0:parse at home/freaky/code/freshbsd/v4_minus_2021//home/freaky/code/freshbsd/v4-2021/repro.rb:9
```

repro.rb is basically just:

```ruby
require 'benchmark-ips'
require 'json'

Benchmark.ips do |b|
  b.report("JSON gem") do
    JSON.parse('{"took":37,"timed_out":false}').to_json
  end
end
```

I can run it on its own until the cows come home, but `load 'repro.rb'` from my app and it tends to happen within the first 5-10 runs, always within the warmup phase.

json (2.5.1)
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 15.0.2+7-1 on 15.0.2+7-1 +jit \[freebsd-x86_64]
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-1)
OpenJDK 64-Bit Server VM (build 15.0.2+7-1, mixed mode, sharing)

**Comment by n8agrin** [comment] 2021-02-10 23:56
@Freaky is there anything notable about your app? Eg is it a Rails app?

**Comment by Freaky** [comment] 2021-02-11 00:05
Frontend is Roda, backed by Sequel talking to Postgres, ElasticSearch 7, and Redis, with some concurrent-ruby use, rendered by Slim.

Backend is in the same codebase and is plain Ruby glued together by dry-system and concurrent-ruby.

Very little of it is active when I reproduce this, the source code is required but none of it beyond service connections and logger are active.

**Comment by headius** [comment] 2021-02-12 05:20
> I can run it on its own until the cows come home, but load 'repro.rb' from my app and it tends to happen

@Freaky Identical JVM flags?

**Comment by Freaky** [comment] 2021-02-12 14:54
@headius Indeed.

**Comment by headius** [comment] 2021-02-12 15:04
@Freaky Was it also json 2.3.0?

You mentioned switching to jrjackson... are you still able to reproduce the json issue if need be?

I want to help figure this out but we still have no good leads and no consistent reproduction. 😞

**Comment by Freaky** [comment] 2021-02-12 19:55
@headius No, json 2.5.1, latest release.

Working on a minimal test case.  Seems to be related to having previously parsed a large JSON document and with JIT tier 4.

**Comment by Freaky** [comment] 2021-02-12 20:10
This triggers it for me: https://github.com/Freaky/jruby-issue-6554

**Comment by Freaky** [comment] 2021-02-13 19:37
JVM flags which appear to stop it:

* `-XX:-TieredCompilation`
* `-XX:TieredStopAtLevel=3`
* `-XX:+UseParallelGC` (and other non-G1 GCs)

I'm also unable to trigger it with jdb attached having set a breakpoint at the exception location.  I'm yet to reproduce it on JVM's earlier than 15.

The tiered compilation flags would seem to support what I saw in a compilation log during a run with `JRUBY_OPTS="-Xbacktrace.style=full -J-XX:+PrintGCDetails -J-XX:+PrintCompilation"`:

```
   6201 7132       4       json.ext.Parser$ParserSession::parseObject (962 bytes)
   6227 6952       3       json.ext.Parser$ParserSession::parseObject (962 bytes)   made not entrant
   6227 7133       4       json.ext.Parser$ParserSession::parseValue (990 bytes)
   6227 7132       4       json.ext.Parser$ParserSession::parseObject (962 bytes)   made not entrant
   6228 7134       3       org.jruby.runtime.backtrace.BacktraceData::packagedFilenameFromElement (82 bytes)
   6228 7135       3       org.jruby.runtime.backtrace.RubyStackTraceElement::<init> (15 bytes)
   6229 7136       3       org.jruby.runtime.backtrace.RubyStackTraceElement::asStackTraceElement (41 bytes)
   6229 7137       3       java.lang.StackTraceElement::<init> (13 bytes)
   6229 7138       3       java.lang.StackTraceElement::<init> (65 bytes)

JSON::ParserError at iter 1329
```

parseObject was compiled to level 4, then parseValue, followed by a parseObject deopt.  No GC was observed nearby.  But it *was* observed prior to warmup in the line that seems to be causing the problem:

```
4911 6897 %     3       json.ext.Parser$ParserSession::parseObject @ 132 (962 bytes)   made not entrant
4911 6900 %     4       json.ext.Parser$ParserSession::parseObject @ 502 (962 bytes)
4931 6862       4       org.jruby.RubyHash::op_aset (16 bytes)   made not entrant
4931 6901       3       org.jruby.RubyHash::op_aset (16 bytes)
4949 6902 %s    4       org.jruby.RubyHash::resize @ 31 (89 bytes)
4956 6903       4       org.jruby.RubyHash::op_aset (16 bytes)
4964 6901       3       org.jruby.RubyHash::op_aset (16 bytes)   made not entrant
5028 6834       4       org.jruby.RubyHash::op_asetForString (51 bytes)   made not entrant
5028 6904       3       org.jruby.RubyHash::op_asetForString (51 bytes)
5031 6905 %s    4       org.jruby.RubyHash::resize @ 13 (89 bytes)
5051 6906       4       org.jruby.RubyHash::op_asetForString (51 bytes)
5066 6126       4       org.jruby.RubyHash::internalGetEntry (60 bytes)   made not entrant
5067 6907       3       org.jruby.RubyHash::internalGetEntry (60 bytes)
5078 6908       4       org.jruby.RubyHash::internalGetEntry (60 bytes)
5110 6125       4       org.jruby.RubyHash::internalKeyExist (42 bytes)   made not entrant
5110 6909       3       org.jruby.RubyHash::internalKeyExist (42 bytes)
5112 6907       3       org.jruby.RubyHash::internalGetEntry (60 bytes)   made not entrant
5114 6904       3       org.jruby.RubyHash::op_asetForString (51 bytes)   made not entrant
5197 6910  s    4       org.jruby.RubyHash::resize (89 bytes)
[5.249s][info   ][gc,start    ] GC(5) Pause Young (Normal) (G1 Evacuation Pause)
[5.249s][info   ][gc,task     ] GC(5) Using 5 workers of 18 for evacuation
[5.305s][info   ][gc,phases   ] GC(5)   Pre Evacuate Collection Set: 0.1ms
[5.305s][info   ][gc,phases   ] GC(5)   Merge Heap Roots: 0.1ms
[5.305s][info   ][gc,phases   ] GC(5)   Evacuate Collection Set: 52.3ms
[5.305s][info   ][gc,phases   ] GC(5)   Post Evacuate Collection Set: 2.9ms
[5.305s][info   ][gc,phases   ] GC(5)   Other: 0.2ms
[5.305s][info   ][gc,heap     ] GC(5) Eden regions: 3->0(3)
[5.305s][info   ][gc,heap     ] GC(5) Survivor regions: 1->1(1)
[5.305s][info   ][gc,heap     ] GC(5) Old regions: 1->3
[5.305s][info   ][gc,heap     ] GC(5) Archive regions: 2->2
[5.305s][info   ][gc,heap     ] GC(5) Humongous regions: 2->2
[5.305s][info   ][gc,metaspace] GC(5) Metaspace: 32885K(34304K)->32885K(34304K) NonClass: 27644K(28672K)->27644K(28672K) Class: 5240K(5632K)->5240K(5632K)
[5.305s][info   ][gc
] GC(5) Pause Young (Normal) (G1 Evacuation Pause) 116M->103M(1136M) 55.663ms
[5.305s][info   ][gc,cpu      ] GC(5) User=0.18s Sys=0.09s Real=0.06s
[5.714s][info   ][gc,start    ] GC(6) Pause Young (Normal) (G1 Evacuation Pause)
[5.714s][info   ][gc,task     ] GC(6) Using 18 workers of 18 for evacuation
[5.760s][info   ][gc,phases   ] GC(6)   Pre Evacuate Collection Set: 0.1ms
[5.760s][info   ][gc,phases   ] GC(6)   Merge Heap Roots: 0.6ms
[5.760s][info   ][gc,phases   ] GC(6)   Evacuate Collection Set: 44.5ms
[5.760s][info   ][gc,phases   ] GC(6)   Post Evacuate Collection Set: 0.6ms
[5.760s][info   ][gc,phases   ] GC(6)   Other: 0.2ms
[5.760s][info   ][gc,heap     ] GC(6) Eden regions: 3->0(3)
[5.760s][info   ][gc,heap     ] GC(6) Survivor regions: 1->1(1)
[5.760s][info   ][gc,heap     ] GC(6) Old regions: 3->5
[5.760s][info   ][gc,heap     ] GC(6) Archive regions: 2->2
[5.760s][info   ][gc,heap     ] GC(6) Humongous regions: 2->2
[5.760s][info   ][gc,metaspace] GC(6) Metaspace: 32885K(34304K)->32885K(34304K) NonClass: 27644K(28672K)->27644K(28672K) Class: 5240K(5632K)->5240K(5632K)
[5.760s][info   ][gc
] GC(6) Pause Young (Normal) (G1 Evacuation Pause) 151M->142M(1136M) 46.121ms
[5.760s][info   ][gc,cpu      ] GC(6) User=0.35s Sys=0.45s Real=0.05s
5864 6891       4       org.jruby.util.ConvertBytes::byteListToInum (371 bytes)   made not entrant
5864 6893       4       org.jruby.util.ConvertBytes::calculateLength (299 bytes)   made not entrant
5864 6911       3       org.jruby.util.ConvertBytes::calculateLength (299 bytes)
5865 6912       3       org.jruby.util.ConvertBytes::byteListToInum (371 bytes)
5867 6913       4       org.jruby.Ruby::newFixnum (6 bytes)
5869 6016       3       org.jruby.Ruby::newFixnum (6 bytes)   made not entrant
5882 6914       4       org.jruby.util.ConvertBytes::calculateLength (299 bytes)
5884 6911       3       org.jruby.util.ConvertBytes::calculateLength (299 bytes)   made not entrant
5885 6915       4       org.jruby.util.ConvertBytes::byteListToInum (371 bytes)
5905 6912       3       org.jruby.util.ConvertBytes::byteListToInum (371 bytes)   made not entrant
[6.010s][info   ][gc,start    ] GC(7) Pause Young (Normal) (G1 Evacuation Pause)
[6.010s][info   ][gc,task     ] GC(7) Using 18 workers of 18 for evacuation
[6.036s][info   ][gc,phases   ] GC(7)   Pre Evacuate Collection Set: 0.1ms
[6.036s][info   ][gc,phases   ] GC(7)   Merge Heap Roots: 0.5ms
[6.036s][info   ][gc,phases   ] GC(7)   Evacuate Collection Set: 25.2ms
[6.036s][info   ][gc,phases   ] GC(7)   Post Evacuate Collection Set: 0.4ms
[6.036s][info   ][gc,phases   ] GC(7)   Other: 0.2ms
[6.036s][info   ][gc,heap     ] GC(7) Eden regions: 2->0(4)
[6.036s][info   ][gc,heap     ] GC(7) Survivor regions: 1->1(1)
[6.036s][info   ][gc,heap     ] GC(7) Old regions: 5->7
[6.036s][info   ][gc,heap     ] GC(7) Archive regions: 2->2
[6.036s][info   ][gc,heap     ] GC(7) Humongous regions: 2->2
[6.036s][info   ][gc,metaspace] GC(7) Metaspace: 32885K(34304K)->32885K(34304K) NonClass: 27644K(28672K)->27644K(28672K) Class: 5240K(5632K)->5240K(5632K)
[6.036s][info   ][gc
] GC(7) Pause Young (Normal) (G1 Evacuation Pause) 174M->170M(1136M) 26.454ms
[6.036s][info   ][gc,cpu      ] GC(7) User=0.35s Sys=0.07s Real=0.02s
6073 6875       4       json.ext.Parser$ParserSession::parseValue (990 bytes)   made not entrant
6073 6898 %     4       json.ext.Parser$ParserSession::parseObject @ 132 (962 bytes)   made not entrant     
```

I'm guessing this is why the size of the initial JSON parse makes the difference - it needs to be big enough to trigger a GC.

**Comment by headius** [comment] 2021-02-16 18:27
I'm going to pull in some JVM JIT and GC folks at this point since it no longer appears to be a bug in JRuby or the json library.

**Comment by headius** [comment] 2021-02-16 18:49
I have posted this to hotspot-compiler-dev to get some feedback before opening an issue with OpenJDK proper:

https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2021-February/044182.html

**Comment by Freaky** [comment] 2021-02-18 00:08
I applied https://github.com/openjdk/jdk/pull/2610 to FreeBSD's OpenJDK 16 port and can no longer reproduce it.

**Comment by shipilev** [comment] 2021-03-04 09:34
The OpenJDK fix is on track to be delivered in JDK 17 (Sep 2021), 16.0.1 (April 2021), 11.0.11 (April 2021). JDK 8 does not seem to be affected. I think this issue can be closed now?

**Comment by headius** [comment] 2021-03-04 19:27
@shipilev Thanks for the update... we will close this issue and hopefully anyone affected can upgrade their JVM soon to avoid the issue.

**Closed by headius** 2021-03-04 19:27 UTC
Labels: stdlib
