### ISSUE TITLE
ENV.replace not working as expected

### ISSUE THREAD

**Issue by nateberkopec** [jruby/jruby#4634] opened 2017-05-30 16:14 UTC
### Environment

[TravisCI build with failure](https://travis-ci.org/puma/puma/jobs/236365102#L456)

### Expected/Actual Behavior

https://github.com/puma/puma/pull/1305

**Comment by kares** [comment] 2017-05-31 07:50
Thanks Nate, reading through comments and some code its not clear what exactly is the problem.
Maybe a simple reproducable piece of .rb would be better than build/issue links, if you have some?

**Comment by preetpalS** [comment] 2017-06-06 03:15
Aren't `workers` in Puma exclusive to Puma's clustered mode which is not supported when using JRuby due to a lack of [fork(2)](https://github.com/puma/puma#platform-constraints)?

The single [file](https://github.com/puma/puma/blob/master/test/test_integration.rb) (which is a test file) that changed in that referenced pull request seems to contain many instances of tests being skipped if JRuby and Windows are detected. Maybe this is an issue of code being run when it shouldn't.

**Comment by headius** [comment] 2017-06-06 16:04
Nothing obvious from the error, but this seems like some encoding oddity. However I was unable to make MRI produce any ENV strings in ASCII-8BIT, even when forced to be.

```
~/projects/jruby $ ruby -e 'p ENV["HOME"].encoding'
#<Encoding:UTF-8>

~/projects/jruby $ ruby -e 'ENV["HOME"] = "/Users/headius".force_encoding("ASCII-8BIT"); p ENV["HOME"].encoding'
#<Encoding:UTF-8>

~/projects/jruby $ ruby -e 'ENV["HOME"] = "/Users/headiusø".force_encoding("ASCII-8BIT"); p ENV["HOME"].encoding'
#<Encoding:UTF-8>
```

**Comment by headius** [comment] 2017-06-06 16:09
I'm confused about the line numbers in that build. When I clone puma master, there is no line 254 in test/test_integration.rb. The failing test is in there, but has a `skip_jruby` call. There's a comment about a bug on JRuby wrt setting `nil` or `'delete'` not clearing values in ENV – and we should fix that – but I'm not sure if it has been filed anywhere.

So...not sure what to do on JRuby's end.

**Comment by nateberkopec** [comment] 2017-06-06 16:29
Thanks for looking at this guys. I filed this issue just kinda quickly so what *looked* like a possible JRuby bug didn't get lost in the shuffle. I'll do some work to clear things up on what's ahppening on our side.

**Comment by kares** [comment] 2018-09-25 13:13
recent [Puma built](https://travis-ci.org/puma/puma/builds/430235219) seems to be all green using 9.1.17.0 as well as jruby-head (9.2.1.DEV)
since there wasn't more info I am inclined to close this one.

**Closed** 2018-10-09 15:49 UTC
