### ISSUE TITLE
No Such Method org.jruby.ir.runtime.IRRuntimeHelpers.freezeLiteralString in jruby-9.4.8.0

### ISSUE THREAD

**Issue by iromanycheva-eng** [jruby/jruby#8380] opened 2024-10-21 22:21 UTC
* jruby upgrade from 9.4.3.0 to 9.4.8.0
* Ubuntu2204

No errors when running locally. When running the same code in the docker container, I am seeing an error 

"Java::JavaLang::NoSuchMethodError: 'org.jruby.RubyString org.jruby.ir.runtime.IRRuntimeHelpers.freezeLiteralString(org.jruby.RubyString, org.jruby.runtime.ThreadContext, java.lang.String, int)'
    home.ci_minus_user.$_dot_rbenv.versions.jruby_minus_9_dot_4_dot_8_dot_0.lib.ruby.gems.shared.gems.haml_minus_5_dot_2_dot_2.lib.haml.attribute_compiler_dot_rb.RUBY$method$static_build$0(/home/ci-user/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/haml-5.2.2/lib/haml/attribute_compiler.rb:125)
    org.jruby.dist/org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:165)
    org.jruby.dist/org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:185)
    org.jruby.dist/org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:220)
    org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:466)
    org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:244)
    org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.fcall(CachingCallSite.java:248)
"
This method was deleted here: https://github.com/jruby/jruby/pull/7903 

But looks like it's still called from here: https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ir/targets/JVMVisitor.java#L1198

Not sure if that's the root cause for the error. And it's not clear for me why it's working ok locally, but failing in the container. Any advice would be greatly appreciated! 

PS. It is indeed related. So with the JRUBY_OPTS="--debug" frozen strings don't work correctly.

**Comment by headius** [comment] 2024-10-22 18:41
You are correct, the JVM bytecode JIT compiler was not updated for the removed method. The JIT needs to be updated the same way as the other parts of #7903 or the method needs to be restored.

**Comment by headius** [comment] 2024-10-24 21:38
I will fix this for 9.4.9.0.

**Comment by headius** [comment] 2024-10-26 14:32
Weirdly enough I cannot reproduce this, and it seems that dynamic strings (such as in your failure) are no longer frozen. So you are correct that the code should no longer call the removed `freezeLiteralString` method, but I'm not sure how it got there in the first place!

I do see your error passes through `MixedModeIRMethod`, which means it was interpreted for a while and later JIT-compiled, so that may indicate that lazy JIT is required to trigger it. Still investigating, but the fix is trivial and will land soon.

**Comment by headius** [comment] 2024-10-26 14:44
Aha, it wasn't related to JIT but to multi-line string combination!

This reproduces with --debug:

```
# frozen_string_literal: true
"asdf" \
  "foo#{$$}qwer"
```

As of Ruby 3.0, dynamic strings (strings with interpolation) are no longer marked as frozen when using `frozen_string_literal` pragma, per https://bugs.ruby-lang.org/issues/16047. JRuby 9.4, with its leap to 3.1 compatibility, followed suit... except for one place we missed: https://github.com/jruby/jruby/blob/e29c8fb1f1bcb3f619ee7c170ad0f50825cd4383/core/src/main/java/org/jruby/parser/RubyParserBase.java#L1418

The logic here is for combining two literal strings one right after the other (which gets combined into a single string by the parser), and the line of code in question fires when the second string is a dynamic string (so the parser must make a single dynamic string for both parts). It's such a rare situation apparently no tests ever noticed that we were still freezing this string, and so when we later reworked how *debug* frozen strings are handled, we missed some code.

The removed `freezeLiteralString` was removed because debug frozen strings now get their own subclass of RubyString and those instances are all constructed for regular (non-dynamic) literal strings. It was incorrect for us to continue calling it in the JIT, but the actual IR also was in error because it marked a dynamic string as frozen.

So I will simply remove all logic for marking dynamic strings frozen and this bug will go away.

**Comment by headius** [comment] 2024-10-26 14:56
So it turns out there's one last place where we use the freezing feature of a dynamic string: producing a particular pattern-matching error here:

https://github.com/jruby/jruby/blob/b7d88af083227eab5f3edf1638651f1e06538aae/core/src/main/java/org/jruby/ir/builder/IRBuilder.java#L324-L329

This could probably be replaced with a separate instruction to freeze the newly-constructed error string, or better yet a call to a utility method that both constructs the string and freezes it, but for now I will leave the capability in place.

@enebo Maybe you can look into changing that so it's not a DStr but a utility call?

**Closed** 2024-10-28 15:20 UTC
