### ISSUE TITLE
NameError: uninitialized constant ActiveSupport::ArrayInquirer Did you mean? ActiveSupport::ArrayInquirer

### ISSUE THREAD

**Issue by cmthakur** [jruby/jruby#4788] opened 2017-09-14 11:56 UTC
**Scenario**
Recently we had switched to jRuby(jruby-9.1.7.0), but due to [SSL handshake](https://github.com/jruby/jruby-openssl/issues/137) issues bug we upgrade java from 1.7x to 1.8.0_131. This leads to issue like "NameError: uninitialized constant ActiveSupport::ArrayInquirer Did you mean? ActiveSupport::ArrayInquirer". 

Is this due to upgrade of java version or there any bug in jRuby itself? 

**Environment**
Production 

**jRuby version**: 
jruby-9.1.7.0

**OS**:
 Ubuntu 16.04.3 LTS

**JAVA version:**
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
**Framework:**
 Rails 5.0.0.1 (api)

**Application Server**
Passenger Entreprise

**Comment by kares** [comment] 2017-09-17 06:08
please try latest on 9.1 (9.1.13 ATM) ... this is an auto-loading issue that might go away.
if it persist than try to eager load your application -> as (lazy) loading in multiple threads, without a GIL, will always have some (more or less visible) race conditions ...

**Comment by cmthakur** [comment] 2017-09-18 07:54
@kares The application is already configured to use eager load and it should be able to work with the threaded web server in my case `passenger` server. 

**config/environments/production.rb**
```
  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true
```

Am I missing anything here, except upgrading **jRuby** to the latest version?

**Comment by kares** [comment] 2017-09-18 10:27
nope, except maybe activerecord-jdbc-adapter not supporting Rails 5.x ... depends on particular adapter on how well it works. anyways just give upgrade a try and if the issue persist try to come up with a minimal reproducer piece.

**Comment by kares** [comment] 2018-06-20 06:15
since there's finally some AR-JDBC 50.x releases, this should be re-evaluated using those (and latest 9.1)

**Comment by kares** [comment] 2018-09-25 09:30
... no further feedback here and since desc is very vague - closing. we ideally need a reproducer.
anyway before doing that you should re-run with latest 9.1/9.2 as well as updated activerecord-jdbc-adapter.

**Closed by kares** 2018-09-25 09:30 UTC
Labels: feedback needed
