### ISSUE TITLE
bundle exec fails on Bundler 2 with config path and deployment

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6349] opened 2020-08-01 19:07 UTC
**Environment Information**
  
Provide at least:
* JRuby version: `jruby 9.2.12.0 (2.5.7) 2020-07-01 db01a49ba6 OpenJDK 64-Bit Server VM 25.262-b10-jvmci-20.2-b03 on 1.8.0_262-b10 +jit [linux-x86_64]`

**Expected Behavior**

It works, like on CRuby.

**Actual Behavior**

```
gem install bundler:2.1.4
git clone --branch debug https://github.com/eregon/memo_wise.git
cd memo_wise
bundle config --local deployment true
bundle config --local path vendor/bundle
bundle install --jobs 4
...
$ bundle exec rubocop -h 
bundler: failed to load command: rubocop (/home/eregon/code/memo_wise/vendor/bundle/jruby/2.5.0/bin/rubocop)
Gem::Exception: can't find executable rubocop for gem rubocop. rubocop is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /home/eregon/.rubies/jruby-9.2.12.0/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in find_spec_for_exe'
  /home/eregon/.rubies/jruby-9.2.12.0/lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in activate_bin_path'
  /home/eregon/code/memo_wise/vendor/bundle/jruby/2.5.0/bin/rubocop:23:in `<main>'
  org/jruby/RubyKernel.java:1009:in `load'
zsh: exit 1     bundle exec rubocop -h
```

From https://github.com/ruby/setup-ruby/issues/72.
This means `JRuby` doesn't work in `ruby/setup-ruby` with `bundler-cache: true` and an existing `Gemfile.lock`.

Maybe related to #6053 ?

**Comment by eregon** [comment] 2020-08-01 19:09
It seems to work if `bundle config --local deployment true` is omitted, but obviously this is still an issue.

**Comment by headius** [comment] 2020-08-03 17:35
This appears to be a bug in Bundler. During the process of setting up the bundle, it is filtering out gems that do not match the "generic_local_platform". Since that platform is "java" on JRuby, none of the dependencies are added.

The issue is in `expand_dependencies` called during setup.

The following patch, applied to bundler, demonstrates the problem:

```
--- /Users/headius/.rvm/gems/ruby-2.5.7/gems/bundler-2.1.4/lib/bundler/definition.rb	2020-08-03 10:54:09.000000000 -0500
+++ ../lib/ruby/gems/shared/gems/bundler-2.1.4/lib/bundler/definition.rb	2020-08-03 12:28:11.000000000 -0500
@@ -901,6 +901,8 @@
             "run `bundle lock --add-platform #{mapped_platforms.join " "}`."
         end
         platforms.each do |p|
+          puts "platform p: #{p}, generic_local_platform: #{generic_local_platform}"
+          puts "dependency #{dep} will be added: #{p == generic_local_platform}"
           deps << DepProxy.new(dep, p) if remote || p == generic_local_platform
         end
       end
```

With this patch, the reported command prints:

```
platform p: ruby, generic_local_platform: java
dependency memo_wise (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency panolint (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency rspec (~> 3.0) will be added: false
platform p: ruby, generic_local_platform: java
dependency memo_wise (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency panolint (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency rspec (~> 3.0) will be added: false
platform p: ruby, generic_local_platform: java
dependency memo_wise (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency panolint (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency rspec (~> 3.0) will be added: false
platform p: ruby, generic_local_platform: java
dependency memo_wise (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency panolint (>= 0) will be added: false
platform p: ruby, generic_local_platform: java
dependency rspec (~> 3.0) will be added: false
```

The same output under CRuby:

```
platform p: ruby, generic_local_platform: ruby
dependency memo_wise (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency panolint (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency rspec (~> 3.0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency memo_wise (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency panolint (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency rspec (~> 3.0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency memo_wise (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency panolint (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency rspec (~> 3.0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency memo_wise (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency panolint (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency rspec (~> 3.0) will be added: true
```

There may be additional issues with platform filtering in this file, but this is one of the root causes since it results in an empty dependency list.

It works on TruffleRuby only because TruffleRuby reports a platform of "ruby".

**Comment by headius** [comment] 2020-08-03 17:47
Forcing the "ruby" platform allows it to get further, but then of course it can't find gems specific to the "java" platform for JRuby:

```
$ BUNDLE_FORCE_RUBY_PLATFORM=1 bundle exec rubocop -v
platform p: ruby, generic_local_platform: ruby
dependency memo_wise (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency panolint (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency rspec (~> 3.0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency memo_wise (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency panolint (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency rspec (~> 3.0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency memo_wise (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency panolint (>= 0) will be added: true
platform p: ruby, generic_local_platform: ruby
dependency rspec (~> 3.0) will be added: true
Could not find thread_safe-0.3.6 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by JacobEvelyn** [comment] 2020-08-03 18:18
Thanks for investigating, @headius! Are you planning to file an issue with bundler or should I?

**Comment by headius** [comment] 2020-08-03 18:23
@JacobEvelyn Just finished doing that! See rubygems/rubygems#3874.

**Comment by headius** [comment] 2020-08-03 18:24
I will leave this open in case there's some changes needed on the JRuby side. I suspect that this is a bug specific to local bundling since normal globally-bundled applications work fine.

**Comment by JacobEvelyn** [comment] 2020-08-03 18:57
Amazing, thank you so much @headius !

**Comment by deivid-rodriguez** [comment] 2020-08-27 17:58
I added a fix for this at https://github.com/rubygems/rubygems/pull/3909 (hopefully CI will work :crossed_fingers:).

The fixed behavior should work in the same way as if `BUNDLE_FORCE_RUBY_PLATFORM=1` is used. Note however, that the preferred way would be to unfreeze the bundle, re-resolve under jruby, commit the updated lockfile, and freeze the bundle again. That way, platform specific dependencies will be considered.

If you can double check the fix, I appreciate it!

**Comment by deivid-rodriguez** [comment] 2020-08-31 13:10
By the way, thanks for your investigation @headius! It was on point!

**Comment by headius** [comment] 2020-09-01 16:32
@deivid-rodriguez Thank you for looking into this! I will try to verify your fix today.

**Comment by headius** [comment] 2020-09-16 20:08
The fixes from rubygems/rubygems#3909 appear to have resolved this issue.

```
$ jruby -S bundle exec rubocop -h 
Usage: rubocop [options] [file1, file2, ...]
...
```

We will need to update RubyGems on any branches that need this fix.

**Comment by headius** [comment] 2020-09-16 20:09
Note that JRuby 9.2.x does not ship Bundler, so users will get the fix when they update the installed version.

JRuby 9.3 will ship bundler alongside RubyGems as it is in Ruby 2.6.

**Comment by headius** [comment] 2020-09-16 20:11
@deivid-rodriguez It does not appear that this fix has gotten into any RubyGems or Bundler release yet, is that true? We can update JRuby once the fix has made it into a release.

**Comment by deivid-rodriguez** [comment] 2020-09-16 20:16
Yes, that's true. I can ping you when we release it.

**Comment by headius** [comment] 2020-12-03 20:07
@deivid-rodriguez Ping? We would like to address this for 9.2.14.0 which could come out as early as next week.

**Comment by deivid-rodriguez** [comment] 2020-12-03 20:17
Hi @headius, I just proposed to the team to release final versions of both rubygems & bundler next week, will keep you posted.

**Comment by deivid-rodriguez** [comment] 2020-12-03 20:19
Also, this particular fix was shipped in the latest bundler release candidate (2.2.0.rc2) in case that's helpful.

**Comment by headius** [comment] 2020-12-03 21:45
@deivid-rodriguez It is not crucial for this to ship in 9.2.14 since both RG and Bundler can be updated indepdently, and this issue was not filed by an end user. If the release comes out next week or later we will not really have time to evaluate it for 9.2.14 so I will bump this for now.

**Comment by headius** [comment] 2021-02-23 22:22
This will be resolved for master by #6533. JRuby 9.2 does not ship with a bundler default gem, so it should be sufficient to just install latest bundler.

@kares @deivid-rodriguez Does that sound right?

**Comment by deivid-rodriguez** [comment] 2021-02-24 09:28
Yes, sure. I think whether bundler is shipped by default or not doesn't change the fact that installing the latest bundler fixes this issue?

**Comment by headius** [comment] 2021-02-24 21:27
@deivid-rodriguez Yes, as long as the bundler shipped with 9.3 is set up as a default gem. See my comment: https://github.com/jruby/jruby/pull/6533#issuecomment-785381120

**Comment by deivid-rodriguez** [comment] 2021-02-25 14:55
Something else to be noticed is that issue happens when running `bundler` directly (not when using `-rbundler/setup` as an entrypoint, or using bundler programatically in other ways). So bundler being a default gem and thus upgradeable by rubygems require is irrelevant I think.

**Comment by headius** [comment] 2021-08-19 18:44
Fixed on master some time ago.

**Closed** 2021-08-19 18:44 UTC
