### ISSUE TITLE
Instance variable or local variable updates inside a finalizer are not reflected after it is invoked

### ISSUE THREAD

**Issue by Adithya-copart** [jruby/jruby#6353] opened 2020-08-09 01:18 UTC
**Environment Information**
  
* **JRuby version:** `jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc`
* **Operating system and platform:** `Darwin MB-ADPENTELA.local 18.7.0 Darwin Kernel Version 18.7.0`

**Test Script:**
```
class A
  def initialize
    ObjectSpace.define_finalizer(self, self.class.finalizer_proc)
  end

  def self.finalizer_proc
    proc { p "Finalizer called" }
  end
end

finalized = false
finalizer =  proc { finalized = true }

a = A.new
ObjectSpace.define_finalizer(a, finalizer)
a = nil

# Request GC run
RUBY_PLATFORM.casecmp?('java') ? java.lang.System.gc : GC.start

p "Finalized? #{finalized}"
```
**Expected Behavior**

* Output in ruby `2.7.1`:
```
"Finalizer called"
"Finalized? true"
```

**Actual Behavior**

* Output in JRuby `9.2.13.0` when using an instance variable or a local variable or a thread local variable defined on the main thread is the same.
```
"Finalizer called"
"Finalized? false"
```

**Comment by Adithya-copart** [comment] 2020-08-09 07:20
Looks like a race-condition between the main thread and the thread in which the finalizers are executed in JRuby. The finalizers are executed on the main thread in MRI.

Adding a `sleep 0.01` before the last debugging statement alters the output and matches MRI.

**Comment by headius** [comment] 2020-08-09 16:40
As you found, this is likely due to the finalizers being run in a separate thread. They are also run out of a queue that the GC manages, so you should not make assumptions about the order or timing of when they will run.

This is a JVM behavior we cannot really change, so I will close this.

**Closed by headius** 2020-08-09 16:40 UTC

**Comment by Adithya-copart** [comment] 2020-08-09 17:45
@headius Thanks for the clarification.

I'm using the following approach in a test which does not work in JRuby but works in MRI `2.7.1`. The object is not marked for GC until the next GC cycle outside the block. I used `jruby -J-XX:+PrintGC -S finalizer_test.rb` to validate a GC run.

Is this expected in JRuby?

```
class A
  def initialize
    ObjectSpace.define_finalizer(self, self.class.finalizer_proc)
  end

  def self.finalizer_proc
    proc { p "Finalizer called" }
  end
end

def it(*args, block)
  yield
end

def finalizer_proc
  proc { @cleared = true }
end

def test_finalizer
  it "do something" do
    @cleared = false
    a = A.new
    ObjectSpace.define_finalizer(a, finalizer_proc)
    a = nil
    p "Requesting GC run"
    RUBY_PLATFORM.casecmp?('java') ? java.lang.System.gc : GC.start
    p "Requested GC run"
    sleep 0.01
    # Asserting here does not work in JRuby but works in MRI
    p "Cleared?: #{@cleared}"
  end
end

test_finalizer

RUBY_PLATFORM.casecmp?('java') ? java.lang.System.gc : GC.start
sleep 0.01

p "Cleared?: #{@cleared}"
```

**Comment by headius** [comment] 2020-08-12 18:02
@Adithya-copart The general rule of thumb when it comes to JVM GC is "assume nothing". I am not surprised by the behavior you show here...but more importantly, I would not be surprised by just about any other behavior.

In this case, the behavior is likely caused by the handling of the finalizer. When the GC sees that an object is no longer referenced, it can be cleared. If that object has a finalizer, it must not be cleared before that finalizer runs, and finalizers run as normal JVM bytecode against the same heap. So finalizable objects will be pushed onto a work queue and usually have to wait an extra cycle (at least) to be collected.

This is in part due to the fact that the JVM's GC never runs directly on user threads. It runs in the background, occasionally pausing user threads to perform its actions, or in the case of truly-concurrent GCs, running concurrently without pausing user threads at all. The price you pay for having parallel or concurrent GC is that you can't generally reason about when objects will get collected or finalized... so don't do that. 😀

Incidentally, this is also why we implement `GC.start` as a no-op. People make assumptions about what will happen, and forcing the JVM's GC to run interferes with its efficient operation. Also, there exists an optional JVM setting to ignore `System.gc` for the same reasons.

**Comment by Adithya-copart** [comment] 2020-08-12 18:19
@headius Thanks for the explanation as always and for taking your time to explain it elegantly.

> The general rule of thumb when it comes to JVM GC is "assume nothing".

:+1:
