### ISSUE TITLE
Strange error in implicit return of match variable

### ISSUE THREAD

**Issue by gavin-scott** [jruby/jruby#3104] opened 2015-07-04 00:35 UTC
In some cases implicitly returned match variables ($1) are being incorrectly returned as nil. Using an explicit return fixes the issue. This was seen on jruby 9.0.0.0.rc1.

Here is a simple script that reproduces the issue:

    [gscott@dev tmp]$ jruby --version
    jruby 9.0.0.0.rc1 (2.2.2) 2015-06-10 a0bf3b3 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [linux-amd64]
    [gscott@dev tmp]$ cat test.rb
    def parse_char_with_return(string)
      if string =~ /Prefix (\w)/
        puts "++> parse_char_with_return(#{string}) = #{$1}"
        return $1
      end
    end
    
    def parse_char_wo_return(string)
      if string =~ /Prefix (\w)/
        puts "++> parse_char_wo_return(#{string}) = #{$1}"
        $1
      end
    end
    
    ret = parse_char_with_return("Prefix A")
    puts "==> parse_char_with_return(Prefix A) = #{ret.inspect}"
    raise(Exception, 'Failed to return correct value') if ret.nil?
    
    puts ''
    ret = parse_char_wo_return("Prefix A")
    puts "==> parse_char_wo_return(Prefix A) = #{ret.inspect}"
    [gscott@dev tmp]$ jruby test.rb
    ++> parse_char_with_return(Prefix A) = A
    ==> parse_char_with_return(Prefix A) = "A"
    
    ++> parse_char_wo_return(Prefix A) = A
    ==> parse_char_wo_return(Prefix A) = nil

Both parse_char_with_return and parse_char_wo_return should return "A" but the latter returns nil as shown above.

**Comment by donv** [comment] 2015-07-06 06:39
Duplicate of https://github.com/jruby/jruby/issues/3031 I think.

**Comment by enebo** [comment] 2015-07-06 15:12
@donv you think so?  Yours implies a concurrency issue but this one I do not see that happening.  Same result but perhaps different problem.

**Comment by enebo** [comment] 2015-07-06 15:21
Ok startup interpreter does not have this issue:

```text
jruby -X-C ../snippets/cat1.rb 
++> parse_char_with_return(Prefix A) = A
==> parse_char_with_return(Prefix A) = "A"

++> parse_char_wo_return(Prefix A) = A
==> parse_char_wo_return(Prefix A) = "A"
```

Full build interpreter does have this issue:

```text
jruby -X-C -Xjit.threshold=0 -Xjit.background=false ../snippets/cat1.rb 
++> parse_char_with_return(Prefix A) = A
==> parse_char_with_return(Prefix A) = "A"

++> parse_char_wo_return(Prefix A) = A
==> parse_char_wo_return(Prefix A) = nil
```

This is good because it means yet again we can fix this without dipping into the bytecode layer (yay IR).  I just tested this on master so it is still broken.

I also verified this does not affect 1.7 so @donv issue has same behavior but it is something broken in concurrent access (in #3031)

**Closed** 2015-07-07 00:44 UTC
Labels: ir, JRuby 9000
