### ISSUE TITLE
Compilation error due to too long file name on truffle-head

### ISSUE THREAD

**Issue by quezacoatl** [jruby/jruby#2613] opened 2015-02-20 20:41 UTC
I am getting the following compilation error:

```bash
/home/quezacoatl/jruby/truffle/target/generated-sources/org/jruby/truffle/nodes/rubinius/EncodingPrimitiveNodesFactory.java:[189,33] error: error while writing EncodingGetObjectEncoding0Node_: /home/quezacoatl/jruby/truffle/target/classes/org/jruby/truffle/nodes/rubinius/EncodingPrimitiveNodesFactory$EncodingGetObjectEncodingPrimitiveNodeFactory$EncodingGetObjectEncodingPrimitiveNodeGen$EncodingGetObjectEncoding0Node_.class (File name too long)

```

**Comment by monkstone** [comment] 2015-02-21 08:43
This looks like this issue https://github.com/jruby/jruby/issues/2483 I got when I compiled in encrypted system the alternative branch was OK.

**Comment by headius** [comment] 2015-03-12 21:03
Dupe of #2483.

**Closed by headius** 2015-03-12 21:03 UTC
