### ISSUE TITLE
LoadError: load error: psych -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.psych.PsychEmitter

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6023] opened 2020-01-08 19:56 UTC
**Environment**

Note this happens in GitHub Actions.

Provide at least:
* JRuby version: 9.2.9.0
* Operating system and platform (e.g. `uname -a`): GitHub Actions on Ubuntu 16.04, 18.04. It seems to work in macOS.

**Expected Behavior**

`gem install bundler -v '~> 1' --no-document` and `bundle install` should work.

**Actual Behavior**

But instead they fail with:
https://github.com/eregon/ruby-install-builder/runs/380064532
https://github.com/eregon/ruby-install-builder/runs/380064626
```
/home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant SNAKEYAML_VERSION
/home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant ANY
/home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant UTF8
/home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant UTF16LE
/home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/psych.rb:7: warning: already initialized constant UTF16BE
/home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: load error: psych -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.psych.PsychEmitter
           require at org/jruby/RubyKernel.java:978
           require at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
            <main> at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/yaml.rb:6
           require at org/jruby/RubyKernel.java:978
           require at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
         load_yaml at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems.rb:724
         load_file at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/config_file.rb:349
        initialize at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/config_file.rb:202
  do_configuration at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/gem_runner.rb:79
               run at /home/runner/.rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/gem_runner.rb:44
            <main> at /home/runner/.rubies/jruby-9.2.9.0/bin/jgem:21
              load at org/jruby/RubyKernel.java:1013
            <main> at /home/runner/.rubies/jruby-9.2.9.0/bin/gem:4
##[error]Process completed with exit code 1.
```

Also noticed by @pkuczynski in https://github.com/rubyconfig/config/pull/228/checks?check_run_id=380015086 for `bundle install`.
Note that that version used to work fine, maybe it's a change in GitHub Actions virtual environments that triggered this?

**Comment by eregon** [comment] 2020-01-08 19:57
Just to be sure, JRuby is using SnakeYAML right, not libyaml?

**Comment by headius** [comment] 2020-01-08 20:00
This is very strange. Psych is built and distributed with JRuby and has no external dependencies (yes, we use SnakeYAML and not libyaml, which is built into the Psych jar). Any environment that can run the JDK can take a JRuby dist and start it up.

The errors make me think it must be some environment issue. The warnings about redefining Psych constants seems to indicate it's loading some other Psych (rather than the one shipped with JRuby). Perhaps it's loading the C ext version from a GEM_HOME? That would contain all the same Ruby code but no .jar file for our extension. I'd expect it to fail much earlier than this, though.

**Comment by pkuczynski** [comment] 2020-01-08 20:02
So I have two commits with no changes between them:

https://github.com/rubyconfig/config/compare/31a2fae85daaf92af65bad534fd6930aa953473c..8ae80e94e54139eedb55ba7df8498785e5fdc385?expand=1

Yet one build failed and second didn't!

https://github.com/rubyconfig/config/commit/31a2fae85daaf92af65bad534fd6930aa953473c/checks?check_suite_id=390716490

https://github.com/rubyconfig/config/commit/8ae80e94e54139eedb55ba7df8498785e5fdc385/checks?check_suite_id=390620653

**Comment by headius** [comment] 2020-01-08 20:09
As mentioned [here](https://github.com/rubyconfig/config/pull/228#issuecomment-572234220) and followed up by me, this could be related to how GHA caches gems. I noticed that the failed build @pkuczynski mentions above was able to retrieve a bundler cache, and the successful build was not. That seems to be the key difference between the two builds.

**Comment by headius** [comment] 2020-01-08 20:13
Also this comment from @enebo might indicate that there's some maven library problem causing this: https://github.com/bundler/bundler/issues/6878#issuecomment-451589519

Basically the error can be caused by the wrong version of SnakeYAML loading when we boot Psych. If it's an older version with an incompatible API it will blow up this way.

**Comment by headius** [comment] 2020-01-08 20:15
Yeah it looks like the Maven problem. It's picking up an older SnakeYAML from the environment somehow.

**Comment by eregon** [comment] 2020-01-08 20:17
`CLASSPATH=/usr/share/java/selenium-server-standalone.jar:.:` sounds like a likely culprit.

**Comment by headius** [comment] 2020-01-08 20:17
😭

**Comment by eregon** [comment] 2020-01-08 20:19
Unsetting CLASSPATH helps as a workaround:
```
jobs:
  build:
    env:
      CLASSPATH: ""
```
https://github.com/eregon/ruby-install-builder/runs/380137158

**Comment by enebo** [comment] 2020-01-08 20:20
I don't recall if there was a reason we do not shade our copy as a different package but I suspect there was a reason.

**Comment by eregon** [comment] 2020-01-08 20:21
https://github.com/actions/virtual-environments/pull/185 seems a likely cause

**Comment by headius** [comment] 2020-01-08 20:24
This is an environment issue, so I'm going to close it as invalid.

Thanks for the patience on this...I'm glad it's not our issue, but I will try to modify our Psych to provide a better/earlier error if the SnakeYAML version doesn't match expectations.

**Closed by headius** 2020-01-08 20:24 UTC

**Comment by pkuczynski** [comment] 2020-01-08 20:26
Indeed! Nice catch. Unsetting `CLASSPATH` fixed my build. @eregon do you plan to fire up PR in https://github.com/actions/virtual-environments?

**Comment by headius** [comment] 2020-01-08 20:27
@pkuczynski I'm filing a bug now. I don't know anything about the structure of GHA so I'm not sure I can do a PR today.

**Comment by pkuczynski** [comment] 2020-01-08 20:28
@headius please CC me so I can follow. I will keep my own PR open for testing.

**Comment by eregon** [comment] 2020-01-08 20:31
I think we need to let GitHub figure out how they want to fix this one.
