### ISSUE TITLE
Break in block passed to Thread doesn't cause LocalJumpError

### ISSUE THREAD

**Issue by toy** [jruby/jruby#7009] opened 2022-01-17 22:49 UTC
Following code doesn't cause a `LocalJumpError` in JRuby unlike in MRI:

```ruby
proc do |&block|
  Thread.new{ block.call }.join
end.call{ break }
```

Using docker to compare behaviour:

```shell
cat << 'RUBY' > test.rb
puts '#' * 60, "Using #{RUBY_DESCRIPTION}"
$stdout.flush

proc do |&block|
  Thread.new{ block.call }.join
end.call{ break }

puts "Still alive!"
RUBY

cat test.rb | docker run -i --rm ruby:2.7 ruby
cat test.rb | docker run -i --rm ruby:3.0 ruby
cat test.rb | docker run -i --rm ruby:3.1 ruby
cat test.rb | docker run -i --rm jruby:9.2 jruby
cat test.rb | docker run -i --rm jruby:9.3 jruby
```

Gives following output:

```
############################################################
Using ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
#<Thread:0x000055eb7e475698 -:5 run> terminated with exception (report_on_exception is true):
-:6:in `block in <main>': break from proc-closure (LocalJumpError)
	from -:5:in `block (2 levels) in <main>'
-:6:in `block in <main>': break from proc-closure (LocalJumpError)
	from -:5:in `block (2 levels) in <main>'
############################################################
Using ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
#<Thread:0x00005632073b3668 -:5 run> terminated with exception (report_on_exception is true):
-:6:in `block in <main>': break from proc-closure (LocalJumpError)
	from -:5:in `block (2 levels) in <main>'
-:6:in `block in <main>': break from proc-closure (LocalJumpError)
	from -:5:in `block (2 levels) in <main>'
############################################################
Using ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
#<Thread:0x00007f5f06b234e8 -:5 run> terminated with exception (report_on_exception is true):
-:6:in `block in <main>': break from proc-closure (LocalJumpError)
	from -:5:in `block (2 levels) in <main>'
-:6:in `block in <main>': break from proc-closure (LocalJumpError)
	from -:5:in `block (2 levels) in <main>'
############################################################
Using jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 OpenJDK 64-Bit Server VM 25.312-b07 on 1.8.0_312-b07 +jit [linux-x86_64]
Exception in thread "Ruby-0-Thread-1: -:1" org.jruby.ir.runtime.IRBreakJump
Still alive!
############################################################
Using jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905 OpenJDK 64-Bit Server VM 25.312-b07 on 1.8.0_312-b07 +jit [linux-x86_64]
Exception in thread "Ruby-0-Thread-1: -:1" org.jruby.ir.runtime.IRBreakJump
Still alive!
```

Related to #4686 and #4697

**Comment by headius** [comment] 2022-01-18 14:20
Good find! Not critical but should be easy to fix.

**Comment by headius** [comment] 2022-01-24 16:12
So the problem here is that we usually detect that a break will go nowhere by checking if the block it occurs within has "escaped", like when it is turned into a Proc object or the surrounding scope has otherwise gone away (e.g. returned normally). In your example, the block and its surrounding scope are still "live" because it has been passed into `end.call` which in turn makes it available for the thread to `block.call`. We do not detect that the break was intended for a target frame that does not exist on this thread, so it propagates internally as an `IRBreakJump` exception, which never gets turned into a Ruby `LocalJumpError` and instead percolates all the way out of the thread.

There's no opportunity to mark the block as escaped (and it really shouldn't be marked such) so there's no way to tell at the time of the `break` that it won't go anywhere.

The simplest fix here would be to catch all internal flow-control exceptions at the top of the RubyThread runnable RubyRunnable, turning them into LocalJumpError on the way out of the thread. This will mean they cannot be caught within the thread, which does differ from CRuby. We may want to look into how they detect that the break should be an error in this case.

**Comment by headius** [comment] 2022-01-24 18:33
I should clarify something here as well... the thread is not still alive in the broken cases, but it does not properly report via `join` or `value` that the thread terminated due to an exception.

**Comment by headius** [comment] 2022-01-24 18:52
I have merged #7029 to get the simple fix in. Whether we need to do a more elaborate fix would depend on your use case here.

@toy Did you run into this in real-world code, or just discover it accidentally? Clearly a break here is an invalid, error-worth action, but the main question is if it should be a recoverable error within the thread.

**Closed** 2022-01-24 18:52 UTC

**Comment by headius** [comment] 2022-01-24 20:02
Filed https://github.com/jruby/jruby/issues/7030 for the additional behavior, which we will debate fixing.

**Comment by toy** [comment] 2022-01-24 21:42
> I should clarify something here as well... the thread is not still alive in the broken cases, but it does not properly report via join or value that the thread terminated due to an exception.

I think this it the main problem in my case.

> Did you run into this in real-world code, or just discover it accidentally? Clearly a break here is an invalid, error-worth action, but the main question is if it should be a recoverable error within the thread.

I've run into it in my gem [in_threads](https://github.com/toy/in_threads), the idea is to allow running block of Enumerable method in threads (`100.times.in_threads.map{ … }`), but calling break in such block would cause condition which I tried to shorten to the example in the issue.

**Comment by headius** [comment] 2022-01-25 16:03
@toy OK, thank you for the extra information. It does not sound like you expect to be able to rescue the LocalJumpError from within the thread, so I think our simple fix is good enough. The patch will be available in JRuby 9.3.4 but you can grab it from snapshot builds here: https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/9.3.4.0-SNAPSHOT/

**Comment by toy** [comment] 2022-01-30 21:57
@headius Unfortunately after trying against the snapshot I understood that I was wrong and my case at least currently (due to using thread pool) requires to rescue inside the thread.

**Comment by headius** [comment] 2022-02-01 21:56
@toy Ok, we will discuss and try to figure out a path forward.
