### ISSUE TITLE
backtrace of exceptions with causes is lost in IRB

### ISSUE THREAD

**Issue by rdp** [jruby/jruby#6673] opened 2021-05-13 15:23 UTC
When running jruby IRB, I can get the following output if an exception has a "caused by" (getCause) exception:

```
>> org.x.y.Class.method
Traceback (most recent call last):
       16: from uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.bin.jirb.<main>(uri:classloader:/META-INF/jruby.home/bin/jirb:13)
       15: from uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.bin.jirb.invokeOther6:start(uri_3a_classloader_3a_/META_minus_INF/jruby_dot_home/bin/uri:classloader:/META-INF/jruby.home/bin/jirb:13)
       14: from org.jruby.RubyKernel$INVOKER$s$rbCatch.call(org/jruby/RubyKernel$INVOKER$s$rbCatch.gen)
       13: from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1189)
       12: from org.jruby.RubyKernel$INVOKER$s$rbCatch.call(org/jruby/RubyKernel$INVOKER$s$rbCatch.gen)
       11: from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1189)
       10: from org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(org/jruby/RubyKernel$INVOKER$s$0$0$loop.gen)
        9: from org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1442)
        8: from org.jruby.RubyKernel$INVOKER$s$0$3$eval.call(org/jruby/RubyKernel$INVOKER$s$0$3$eval.gen)
        7: from org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:1048)
        6: from org.jruby.RubyKernel.evalCommon(org/jruby/RubyKernel.java:1086)
        5: from RUBY.evaluate((irb):17)
        4: from org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:363)
        3: from org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:441)
        2: from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        1: from org.x.y.Class.method(org/x/y/Class.java:43)
Java::JavaLang::ExceptionInInitializerError ()
>>
```

It show me there was an exception in initializing a class.  But doesn't tell me which exception, I can't see immediately what happened.  Dunno if that'll be easy though.  Java by default outputs the stacktrace of exceptions with their causes to the console FWIW.  Thanks!

Demo:
```
$ cat Bad.java
public class Bad {
  static Bad bad1 = new Bad();
  Bad() {
    throw new RuntimeException("hello");
  }
}
$ cat Bad2.java
public class Bad2 {

  public static void main(String[] args) {
    new Bad();
  }

}
$ jruby -S irb
> java_import 'Bad2'
=> [Java::Default::Bad2]
>  Bad2.main([])
Traceback (most recent call last):
       16: from Users.packrd.Downloads.jruby_minus_9_dot_2_dot_11_dot_0.bin.jirb.<main>(/Users/packrd/Downloads/jruby-9.2.11.0/bin/jirb:13)
       15: from Users.packrd.Downloads.jruby_minus_9_dot_2_dot_11_dot_0.bin.jirb.invokeOther6:start(Users/packrd/Downloads/jruby_minus_9_dot_2_dot_11_dot_0/bin//Users/packrd/Downloads/jruby-9.2.11.0/bin/jirb:13)
       14: from org.jruby.RubyKernel$INVOKER$s$rbCatch.call(org/jruby/RubyKernel$INVOKER$s$rbCatch.gen)
       13: from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1189)
       12: from org.jruby.RubyKernel$INVOKER$s$rbCatch.call(org/jruby/RubyKernel$INVOKER$s$rbCatch.gen)
       11: from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1189)
       10: from org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(org/jruby/RubyKernel$INVOKER$s$0$0$loop.gen)
        9: from org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1442)
        8: from org.jruby.RubyKernel$INVOKER$s$0$3$eval.call(org/jruby/RubyKernel$INVOKER$s$0$3$eval.gen)
        7: from org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:1048)
        6: from org.jruby.RubyKernel.evalCommon(org/jruby/RubyKernel.java:1086)
        5: from RUBY.evaluate((irb):2)
        4: from org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:368)
        3: from org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:456)
        2: from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        1: from Bad2.main(Bad2.java:4)
Java::JavaLang::ExceptionInInitializerError () # cause exception is not printed out
```

**Comment by headius** [comment] 2021-05-13 21:37
This might be something to fix at the level of the IRB gem.

As near as I can tell the exception output here is printed by `handle_exception` in IRB, which lives [HERE](https://github.com/jruby/jruby/blob/7b964fdd9c07e2af3d94d300bd676cde847d621a/lib/ruby/stdlib/irb.rb#L524) in the 9.2 branch (with IRB vendored into stdlib) and [HERE](https://github.com/ruby/irb/blob/3df2285c20ce5ad05ff9f7e10d679f3390ffa08f/lib/irb.rb#L631-L648) in the IRB gem.

My preference would be to just work with @aycabta and @koic and others on the gem to get the proper formatting in place for exceptions with causes, since cause has been available in Ruby for some time.

The gem relies on the `Exception#full_message` output, which we have partial support for, but I am unsure if that function is supposed to print the cause as well or not.

**Comment by edipofederle** [comment] 2021-06-26 20:45
This is still valid? my tested with, I can see the cause: `Java::JavaLang::ExceptionInInitializerError ()`

```
 $ bin/jruby -S jirb
2.3.4 :001 > java_import 'Bad2'
 => [Java::Default::Bad2]
2.3.4 :002 > Bad2.main([])
Traceback (most recent call last):
       16: from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1234)
       15: from org.jruby.RubyKernel$INVOKER$s$rbCatch.call(org/jruby/RubyKernel$INVOKER$s$rbCatch.gen)
       14: from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1234)
       13: from org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(org/jruby/RubyKernel$INVOKER$s$0$0$loop.gen)
       12: from org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1504)
       11: from org.jruby.RubyKernel$INVOKER$s$0$3$eval.call(org/jruby/RubyKernel$INVOKER$s$0$3$eval.gen)
       10: from org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:1088)
        9: from org.jruby.RubyKernel.evalCommon(org/jruby/RubyKernel.java:1126)
        8: from RUBY.evaluate((irb):2)
        7: from org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:369)
        6: from org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:457)
        5: from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:564)
        4: from jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
        3: from jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:64)
        2: from jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        1: from Bad2.main(Bad2.java:4)
Java::JavaLang::ExceptionInInitializerError ()```

Not sure if I got @rdp right, please let me know if any works on it is still necessary. Thanks

**Comment by headius** [comment] 2021-06-29 21:25
Perhaps this was fixed by @kares in #6660?

**Comment by headius** [comment] 2021-07-23 21:21
This does appear to still be broken on current master, based on the original example.

**Comment by headius** [comment] 2021-12-02 16:09
I believe this is a simple problem with the `backtrace` implementation we attach to Java exceptions. They run through the normal stack trace, converting the lines to strings, but do nothing for the cause.

**Comment by headius** [comment] 2021-12-02 16:12
Ok, this actually appears to be a flaw in IRB itself. Here is some example output showing that it does not show the cause even for Ruby exceptions:

```
irb(main):003:0> begin; 1/0; rescue; raise 'foo'; end
Traceback (most recent call last):
        6: from /Users/headius/projects/jruby-9.3/bin/jirb:13:in `<main>'
        5: from org/jruby/RubyKernel.java:1237:in `catch'
        4: from org/jruby/RubyKernel.java:1237:in `catch'
        3: from org/jruby/RubyKernel.java:1507:in `loop'
        2: from org/jruby/RubyKernel.java:1091:in `eval'
        1: from (irb):3:in `evaluate'
RuntimeError (foo)
irb(main):004:0> begin; begin; 1/0; rescue; raise 'foo'; end; rescue; p $!.cause; end
#<ZeroDivisionError: divided by 0>
=> #<ZeroDivisionError: divided by 0>
```

This may be fixed in a newer IRB. If not, I think it would be best to file an issue there.

**Closed by headius** 2021-12-02 16:12 UTC
