### ISSUE TITLE
WEBrick HTTPServer only binds to localhost on JRuby 9.2.18.0 and later

### ISSUE THREAD

**Issue by ptribble** [jruby/jruby#7383] opened 2022-09-29 08:41 UTC
After a recent update to JRuby (from a working 9.2.17.0 system) a simple WEBrick HTTPServer will only bind to localhost, rather than the expected all addresses.

(I noted this on twitter, so have done further checks against CRuby and am reporting it here.)

**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

JRuby 9.2.17.0 and earlier works as expected, 9.2.18.0 and later (inc 9.2.21.0 and 9.3.8.0) fail. Running under both OpenJDK8 and OpenJDK11.

* Operating system and platform (e.g. `uname -a`)

This is on illumos (both Tribblix and OmniOS), x86.

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

**Expected Behavior**

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.

I expect to be able to connect to the webserver by IP address.

* Provide an executable Ruby script or a link to an example repository.

```ruby
require 'webrick'
server = WEBrick::HTTPServer.new(:Port => 8888,
                                 :Logger => WEBrick::Log::new("/dev/null", 7),
                                 :AccessLog => [])
server.start
```

**Actual Behavior**

For 9.2.18.0 and later, it's only listening on localhost:

# netstat -na | grep 8888
::ffff:127.0.0.1.8888                   *.*                              0      0 128000      0 LISTEN      
::1.8888                                *.*                              0      0 128000      0 LISTEN      

For 9.2.17.0 and earlier, and CRuby (both 2.7.6 and 3.0.4), it binds to all addresses as expected:

# netstat -na | grep 8888
      *.8888               *.*                 0      0 128000      0 LISTEN
      *.8888                            *.*                              0      0 128000      0 LISTEN      

Explicitly telling it what to bind to (ie, :BindAddress => "0.0.0.0") restores expected behaviour. Which solves the problem we hit.

Given the version at which the behavior changed, I would initially suspect https://github.com/jruby/jruby/pull/6664

**Comment by headius** [comment] 2022-10-02 14:43
Thank you for filing this!

This may be a simple fix, like we just need to pass in a default "all local addresses" address for the bind if none is given. Should be fixed in 9.3.x though.

**Comment by headius** [comment] 2022-10-13 14:48
A bit different on my machine, since it's using ipv6, but the result is the same:

```
$ netstat -na | grep 8888
tcp6       0      0 :::8888                 :::*                    LISTEN
```

**Comment by headius** [comment] 2022-10-13 20:57
Ok I am confused... I cannot reproduce this on JRuby 9.3 HEAD:

JRuby running your script:
```
$ jruby -J-Djava.net.preferIPv4Stack=true blah.rb
```

netstat:
```
$ netstat -na | grep 8888
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN
```

Even trying this with the released 9.3.8.0 works like you want it.

Can you show me a complete command line session with `jruby -v` to get version numbers and such?

**Comment by enebo** [comment] 2023-01-26 21:54
@ptribble ping

**Comment by headius** [comment] 2023-09-10 10:53
No follow-up since the initial report almost a year ago, so marking as invalid.

@ptribble If you can provide an example that fails with a current version of JRuby we'll be happy to look into it.

**Closed by headius** 2023-09-10 10:53 UTC
