### ISSUE TITLE
format string with no format token errors when a nil parameter is passed.

### ISSUE THREAD

**Issue by NullVoxPopuli** [jruby/jruby#3712] opened 2016-03-06 16:36 UTC
### Environment

https://travis-ci.org/rails-api/active_model_serializers/jobs/111938627
https://github.com/rails-api/active_model_serializers/blob/master/.travis.yml#L35

### Expected Behavior

```ruby
format('string with no format token', nil)
# => 'string with no format token'
```
It's a little awkward, but it's how regular ruby works.

### Actual Behavior

Exception and stack trace:
https://travis-ci.org/rails-api/active_model_serializers/jobs/111938627

### Work Around

https://github.com/bf4/active_model_serializers/pull/3/files

**Comment by enebo** [comment] 2016-03-07 19:05
Looks like we gratuitously capture exceptions and when -d (cli.debug) is enabled we can see that we have a bug in format:

```text
jruby -Xcli.debug=true -e 'p format("aaa", nil)'
```
A workaround for now would also be to disable cli.debug but this should not be too difficult to fix.

**Comment by enebo** [comment] 2016-03-07 19:09
Resolving as not a bug.  MRI also does this:

```text
ruby -d -e 'p format("aaa", nil)'
```
I think the confusing part of this is -Xcli.debug looks like a JRuby specific option when it is just a property longhand for -d.  So if you enabled -d in the C Ruby runs you should see the same problem in your CI runs.

**Closed by enebo** 2016-03-07 19:09 UTC
