### ISSUE TITLE
Possible race condition defining a Class and a block's binding in #initialize

### ISSUE THREAD

**Issue by estolfo** [jruby/jruby#5881] opened 2019-09-18 09:10 UTC
## Question
I was wondering if the JRuby team could help me understand why I sometimes get a `NoMethodError` when a method is called from a block created in an object’s `initialize` method.

### Environment

* JRuby version 9.2.7.0
* Docker image used for the test: https://github.com/elastic/docker-jruby/blob/9f007a8fa403adf81a0c3490cced6fe9e3eb8b5a/9000/jdk/8-jdk/Dockerfile#L1-L8
* Based on `openjdk:8-jdk`, which has these specs:

```
docker run --rm -ti openjdk:8-jdk /bin/bash
Unable to find image 'openjdk:8-jdk' locally
8-jdk: Pulling from library/openjdk
092586df9206: Already exists 
ef599477fae0: Already exists 
4530c6472b5d: Already exists 
d34d61487075: Already exists 
272f46008219: Already exists 
12ff6ccfe7a6: Pull complete 
f26b99e1adb1: Pull complete 
Digest: sha256:350761f9310c2b6665ac5e62b15d03dce859bc20dff59d6dbc63b114d9c39001
Status: Downloaded newer image for openjdk:8-jdk
root@daf9f3405098:/# uname -a
Linux daf9f3405098 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
root@daf9f3405098:/# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Here is the code in question: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/agent.rb#L74-L77

```ruby
  def initialize(config)
      @config = config

      @stacktrace_builder = StacktraceBuilder.new(config)
      @context_builder = ContextBuilder.new(config)
      @error_builder = ErrorBuilder.new(self)

      @central_config = CentralConfig.new(config)
      @transport = Transport::Base.new(config)
      @instrumenter = Instrumenter.new(
        config,
        stacktrace_builder: stacktrace_builder
      ) { |event| enqueue event }
      @metrics = Metrics.new(config) { |event| enqueue event }
    end
```
The error can be seen in our tests on Jenkins here: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-downstream/detail/PR-525/39/pipeline/
```
[2019-09-12T20:36:19.421Z] NoMethodError:
[2019-09-12T20:36:19.421Z] undefined method `enqueue' for #<ElasticAPM::Agent:0xc9518ee>
[2019-09-12T20:36:19.421Z] # ./lib/elastic_apm/agent.rb:77:in `block in initialize'
```

We only ever get this error occasional when testing on JRuby.

I’m guessing there’s a race condition with defining the class and initializing the block and its binding. 
I would welcome any insight you’d have.

Thank you!

**Comment by headius** [comment] 2019-09-21 22:24
Very peculiar!

From looking at the code, it seems like the block passed in is turned into a proc and saved in the Instrumenter class and the Collector class that Metrics creates as an instance variable and subsequently called as a normal proc. By the time the block gets into those objects, it should already have a fully-initialized binding with a proper self. I don't see any possibility of a race here.

**Comment by headius** [comment] 2019-09-23 19:14
Still pondering this one. It might be possible if the Agent was getting constructed by another thread at the same time it's being defined. Does that seem plausible?

**Comment by headius** [comment] 2019-09-23 19:22
Oh I should clarify something also...

Your error indicates that the `self` for the block is correctly initialized to an instance of `Agent`. So the mystery we are investigating is how it has an instance of `Agent` with no `enqueue` method. I think I see what you meant by "race" now...there could indeed be a race between constructing `Agent` and finishing the definition of its methods...but don't see how yet.

**Comment by mikker** [comment] 2019-09-23 20:34
Chiming in, working on this with @estolfo 😊

Our current theory is that because we've been stubbing out the method in other places in the spec suite and the `Agent` is used as a singleton that RSpec's unstubbing of the method after a previous spec example might've removed the method altogether.

We're testing out stubbing on step further down the call chain instead, eg: https://github.com/elastic/apm-agent-ruby/pull/535/files#diff-4de0a8fadb6d9e1b9b931caca4c8c22cL17

**Comment by headius** [comment] 2019-09-23 20:38
@mikker Ah that would make a lot of sense!

FWIW I have been running this spec in a loop for the past hour (`rspec ...`) and have managed to see just one error. Maybe this gives us more clues?

```
  1) ElasticAPM::Middleware attaches a new trace_context
     Failure/Error: trace_context = @intercepted.transactions.first.trace_context
     
     NoMethodError:
       undefined method `trace_context' for nil:NilClass
     # java/lang/Thread.java:1559:in `getStackTrace'
     # ./spec/elastic_apm/middleware_spec.rb:61:in `block in ElasticAPM'
     # java/lang/invoke/MethodHandle.java:627:in `invokeWithArguments'
```

I have not been able to reproduce the `enqueue` error.

**Comment by mikker** [comment] 2019-09-23 21:03
My guess is that that is caused by the transaction expected to be in `@intercepted.transactions` didn't show up due to some other edge-case bug.

**Comment by mikker** [comment] 2019-09-23 21:04
Or it _is_ `nil` as in the collection was `[nil]`. Either way I don't suspect it to be directly related.

**Comment by estolfo** [comment] 2019-09-26 11:32
Closing this as the error was most likely due to Rspec not completing a cleanup before the next test started. I don't think it's indicative of any kind of issue with JRuby itself. Thanks for your response, @headius

**Comment by headius** [comment] 2019-09-26 19:32
@estolfo Ok thanks! Let us know if you come across any evidence that something should be fixed in JRuby.

**Closed by headius** 2019-09-26 19:32 UTC
