### ISSUE TITLE
IRB: arrow keys to move along cmd line and up/down in history not working on Windows

### ISSUE THREAD

**Issue by ssteidte** [jruby/jruby#4141] opened 2016-09-07 07:46 UTC
### Environment

Provide at least:
- JRuby from 9.1.3 on, including .4 and .5
- Windows
### Expected Behavior
- in IRB, arrow keys move the cursor along the cmd line or get previous/next line in history
### Actual Behavior
- while working on Linux, this has ceased working on Windows
- there is just no action when one of the arrow keys is pressed

**Comment by headius** [comment] 2016-09-07 14:41
This must be due to the ^C fix we did in 9.1.3 for https://github.com/jruby/jruby/issues/3721.

I don't know why it would cause this, though :-(

**Comment by headius** [comment] 2016-09-07 14:43
A workaround for you: I believe if you install the 1.0 jruby-readline gem from [here](http://repo1.maven.org/maven2/rubygems/jruby-readline/1.0/) you'll restore the old behavior.

@mkristian Perhaps it's time we made jruby-readline a real rubygems.org gem, so it's easier for folks to up/downgrade it as we make fixes.

**Comment by headius** [comment] 2016-09-07 14:49
Drat...installing the 1.0 gem does not seem to fix the problem. I'll look into this today.

**Comment by headius** [comment] 2016-09-07 15:33
Ok, here's a working workaround:

1. gem install that 1.0 jruby-readline gem
2. delete readline.jar from <jruby home>/lib/ruby/stdlib

**Comment by cmichon** [comment] 2016-09-08 07:17
The jar replacement fixes the issue. I agree the jruby-readline should become a real gem as otherwise this will remain a dirty fix.

**Comment by tobymurray-nanometrics** [comment] 2016-09-16 15:13
Would this also impact pasting content? I'm seeing some extremely weird behavior there, although I haven't tried to isolate JRuby from all the other tools which might be impacting it.

**Comment by headius** [comment] 2016-09-21 20:56
@tobymurray-nanometrics On Windows? It certainly could.

**Comment by headius** [comment] 2016-09-21 21:41
@mkristian I tried to release a 1.1.1 gem with the regression reverted, but I'm not sure it's building the gem appropriately for rubygems.org. I can install the gem, but attempting to activate it produces the following error:

```
[] ~/projects/jruby-readline $ gem install jruby-readline
Successfully installed jruby-readline-1.1.1-java
1 gem installed

[] ~/projects/jruby-readline $ jruby -v -e 'gem "readline"; require "readline"'
jruby 9.1.4.0 (2.3.1) 2016-09-01 2e1327f Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]
Gem::MissingSpecError: Gem::MissingSpecError
  to_specs at /Users/headius/.rvm/rubies/jruby-9.1.4.0/lib/ruby/stdlib/rubygems/dependency.rb:308
   to_spec at /Users/headius/.rvm/rubies/jruby-9.1.4.0/lib/ruby/stdlib/rubygems/dependency.rb:320
       gem at /Users/headius/.rvm/rubies/jruby-9.1.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:65
    <main> at -e:1
```

I believe it should be possible to put out a release of the gem, and get existing JRuby versions to load it by using `gem install --default jruby-readline` combined with `gem install jruby-readline` in some order, but this indicates it's simply not loading right.

**Comment by headius** [comment] 2016-09-21 21:58
jruby-readline 1.1.1 released to rubygems and maven. The current workaround is

1. gem install jruby-readline
2. delete readline.jar from <jruby home>/lib/ruby/stdlib

**Comment by headius** [comment] 2016-11-08 06:09
This is still outstanding. @enebo: Should we revert the change to jruby-readline and release 9.1.6.0 with the reverted version?

**Comment by enebo** [comment] 2016-11-08 14:37
@headius I feel this is more annoying than what happened in #3721 so yeah reverting feels like the lesser of two evils.  I also hate second-classing windows users so perhaps this is a nice gesture :)

**Comment by headius** [comment] 2016-11-08 17:41
This is fixed with the release of jruby-readline-1.1.1, and jruby-9.1.6.0 release today will ship that.

**Closed by headius** 2016-11-08 17:41 UTC
Labels: JRuby 9000, regression, stdlib

**Comment by hathawad** [comment] 2016-11-11 21:19
I can confirm this is fixed on Windows w/ `jruby-9.1.6.0`

**Comment by hathawad** [comment] 2018-03-22 16:14
This issue seems to be back w/ `jruby-9.1.16.0`

**Comment by hathawad** [comment] 2018-04-05 16:39
This is broken again on Windows w/ `jruby-9.1.16.0`
@headius do we need new issue, or should we reopen this one?

**Comment by hathawad** [comment] 2018-04-09 15:24
FYI this work around seems to be working (taken in part from above in this thread):

1. gem install  jruby-readline
2. copy `readline.jar` from gem installation to `lib\ruby\stdlib`

**Comment by mkristian** [comment] 2018-04-10 06:06
@hathawad may I ask which version of jruby-readline you are using ? as the version from jruby-9.1.16 should be the same (binary compatible) as jruby-readline-1.1.1

**Comment by rob99** [comment] 2018-05-25 05:55
> @hathawad may I ask which version of jruby-readline you are using ?

I had the same problem as @hathawad  - it's the jruby-9.1.16.0\lib\ruby\stdlib\readline.jar "version" i.e. the standard lib not the gem.  Replacing this jar with the one from the gem install fixes it.

**Comment by cmichon** [comment] 2018-05-25 11:49
Hi,

The #4141 is back on Windows with jruby 9.2.0.0 :-(

I confirm using all files (not just the jar) from
jruby-readline-1.1.1-java.gem and including them in
jruby-9.2.0.0/lib/ruby/stdlib fixes the arrow keys issue on Windows.

After verifications/tests, arrow keys are working, tab completion is
working, double escape and CTRL-A/CTRL-E/CTRL-R/CTRL-U are working too.

Good catch! I can upgrade now to jruby 9.2.0.0 with this temporary fix
until it gets merged in 9.2.x

Thanks a bunch.
Christian

**Comment by headius** [comment] 2018-06-02 15:54
@hathawad Could you open a new issue please? We want to keep the lineage of what was "fixed" when, even if it regresses.

**Comment by toliman7** [comment] 2019-04-10 21:13
Opened #5687 for 9.2.x

**Comment by cmichon** [comment] 2019-04-16 12:00
New re-re-regression. Reverting back to jline-2.11 and readline-1.1.1 did
the trick, again...

**Comment by F2Andy** [comment] 2019-05-29 07:57
Just to note that I am using JRuby 9.2.5.0, and also have this problem. The trick of using the  jruby-readline, and copying either the one file or all the files failed to solve it; I just got an error:

```
no such file to load -- jline/jline/2.11/jline-2.11 (LoadError)
do_require at C:/jruby-9.2.5.0/lib/ruby/stdlib/jar_dependencies.rb:356
...
