### ISSUE TITLE
Local jump behaviour varies

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#7136] opened 2022-03-13 17:14 UTC
```ruby
puts RUBY_DESCRIPTION

class XSafeTaskExecutor

  def initialize(task)
    @task = task
    @lock = Mutex.new
  end

  def execute(*args)
    success = true
    value   = reason = nil

    @lock.synchronize do
      begin
        value   = @task.call(*args)
        success = true
      rescue StandardError => ex
        reason  = ex
        success = false
      end
    end

    [success, value, reason]
  end

end

def execute
  Thread.new do
    executor = XSafeTaskExecutor.new(-> { yield 42 })
    @result = executor.execute
  end.join
end

to_enum(:execute).first
p @result

# ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21] => [true, nil, nil]
# jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 OpenJDK 64-Bit Server VM 17.0.2+8-86 on 17.0.2+8-86 +jit [darwin-aarch64] => [false, nil, #<ThreadError: Enumerable#first cannot be parallelized>]
# jruby 9.4.0.0-SNAPSHOT (3.1.0) 2022-03-12 d206b0cc49 OpenJDK 64-Bit Server VM 17.0.2+8-86 on 17.0.2+8-86 +jit [arm64-darwin] => [false, nil, #<ThreadError: Enumerable#first cannot be parallelized>]
```

@eregon

**Comment by headius** [comment] 2022-03-14 16:06
Some years ago we decided to disallow enumerators that span threads, which is why this fails in `first`. This case may be safe enough when threads are present, but it is a peculiar example. Because the thread calling into `first` and the thread that responds are different, we raise an error.

Removing the thread allows `first` to execute until it has one value, at which point it terminates the iteration and returns `42`. This behavior matches CRuby (I print the result of `first` here).

```
[] ~/projects/jruby $ rvm ruby-3.1 do ruby blah.rb
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin20]
42
nil

[] ~/projects/jruby $ jruby blah.rb
jruby 9.4.0.0-SNAPSHOT (3.1.0) 2022-03-12 fa5e9149ed OpenJDK 64-Bit Server VM 11.0.4+11 on 11.0.4+11 +jit [x86_64-darwin]
42
nil
```

I am a little confused by the CRuby behavior with the thread present. In the single-thread case, the `execute` method terminates prematurely and `@result` is never set to the array. In the threaded case, the result array is constructed and returned by execute. My first thought is that the threaded version is not terminating the enum iteration early, as it does for the unthreaded version. I do not have an explanation for this behavior.

**Comment by headius** [comment] 2022-03-17 07:05
Agreed, the behavior of the threaded version does not seem to make sense given the expected behavior of `first`. That we reject the thread-spanning Enumerator is beside the point; CRuby does not work like we think it should work, so there's no spec to follow.

**Comment by headius** [comment] 2022-03-31 23:19
Given your comment at https://github.com/ruby-concurrency/concurrent-ruby/issues/931#issuecomment-1072579667 and the related CRuby bugs, I'm closing this as invalid since we behave more reasonably than CRuby and this is undefined behavior.

**Closed by headius** 2022-03-31 23:19 UTC
