### ISSUE TITLE
BigDecimal#to_r produces grossly incorrect results

### ISSUE THREAD

**Issue by felixvf** [jruby/jruby#3728] opened 2016-03-13 02:24 UTC
### Environment

```
# jruby -v
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-b15 +jit [linux-amd64]
```

### Expected Behavior

```
# irb
2.3.0 :001 > require 'bigdecimal'
 => true 
2.3.0 :002 > BigDecimal.new("5").to_f
 => 5.0 
2.3.0 :003 > BigDecimal.new("5").to_r.to_f
 => 5.0 
2.3.0 :004 > BigDecimal.new("5").to_r
 => (5/1) 
2.3.0 :005 > BigDecimal.new("1234.56789").to_r
 => (123456789/100000) 
```

### Actual Behavior

```
# irb
jruby-9.0.5.0 :001 > require 'bigdecimal'
 => true 
jruby-9.0.5.0 :002 > BigDecimal.new("5").to_f
 => 5.0 
jruby-9.0.5.0 :003 > BigDecimal.new("5").to_r.to_f
 => 1.0 
jruby-9.0.5.0 :004 > BigDecimal.new("5").to_r
 => (1/1) 
jruby-9.0.5.0 :005 > BigDecimal.new("1234.56789").to_r
 => (123456789/50) 
```

**Comment by lucasallan** [comment] 2016-03-13 20:30
I'm not able to reproduce it in `master`. cc @kares @felixvf 
```
# irb
>>  require 'bigdecimal'
=> true
>>  BigDecimal.new("5").to_f
=> 5.0
>> BigDecimal.new("5").to_r.to_f
=> 5.0
>> BigDecimal.new("5").to_r
=> (5/1)
>>  BigDecimal.new("1234.56789").to_r
=> (123456789/100000)
>> JRUBY_VERSION
=> "9.1.0.0-SNAPSHOT"
```

**Comment by Lan5432** [comment] 2016-03-14 01:43
I also tried reproducing the bug and had the same output as lucasallan, BigDecimal appears to be fine in 9.1

(I can edit with code snippet showing the version, but I'm having some troubles currently)

**Comment by kares** [comment] 2016-03-14 06:36
thanks, it seems to be a duplicate of #3616 which has been fixed with https://github.com/jruby/jruby/commit/16b13e1cca6d74c5d09bf9ad9a5d6f7686c95b0d

**Closed by kares** 2016-03-14 06:36 UTC
Labels: beginner, core
