### ISSUE TITLE
TypeError: illegal access on 'put': class org.jruby.javasupport.JavaMethod (in module org.jruby.dist) cannot access a member of class java.lang.ProcessEnvironment (in module java.base) with modifiers "public"

### ISSUE THREAD

**Issue by afischer-opentext-com** [jruby/jruby#6059] opened 2020-02-14 15:27 UTC
**Environment Information**

```
C:>jruby -v
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 12.0.1+12 on 12.0.1+12 +jit [mswin32-x86_64]
```

Running on any Windows server OS

The jruby installation has a file `%JRUBY_HOME%/bin/.jruby.java_opts`with content

```
--add-opens java.xml/com.sun.org.apache.xerces.internal.dom=org.jruby.dist
--add-opens java.xml/com.sun.org.apache.xerces.internal.impl=org.jruby.dist
--add-opens java.xml/com.sun.org.apache.xerces.internal.parsers=org.jruby.dist
--add-opens java.xml/com.sun.org.apache.xml.internal.dtm.ref=org.jruby.dist
--add-opens java.xml/com.sun.org.apache.xpath.internal.jaxp=org.jruby.dist
--add-opens java.base/sun.nio.ch=org.jruby.dist
```

**Actual Behavior**

* When running the following snippet 

```
command = ['C:\Windows\System32\calc.exe']
processBuilder = Java::JavaLang::ProcessBuilder.new(command.to_java(:string))
processBuilder.redirectErrorStream(true)
environment = processBuilder.environment
environment.clear
custom = {}
custom['FOO'] = 'FOO'
custom.each do |name, value|
  environment.put(name, value)
end
```

This fails with

```
2020-02-14T15:18:22.454Z [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.
TypeError: illegal access on 'put': class org.jruby.javasupport.JavaMethod (in module org.jruby.dist) cannot access a member of class java.lang.ProcessEnvironment (in module java.base) with modifiers "public"
  play.rb at play.rb:9
     each at org/jruby/RubyHash.java:1428
   <main> at play.rb:8
```

**Expected Behavior**

* There is no TypeError or other warning

Can someone please let me know what is going wrong here and if there are any workarounds?

**Comment by afischer-opentext-com** [comment] 2020-02-14 15:51
Can someone confirm that the new and shiny `.jruby.java_opts` and `.jruby.module_opts` files are supported by the jruby.exe JRuby Launcher as well and not only by `jruby.bash`?

**Comment by headius** [comment] 2020-02-16 17:27
@afischer-opentext-com I can confirm that the `.java_opts` files are NOT yet supported by jruby.exe. That's our fault... we hate C++. We will get this remedied soon.

As for your original error, I believe it will be fixed by JRuby 9.2.10, which has fixes for `java_method` style dispatch (see #5841). Could you confirm that based on a [nightly dist of JRuby](https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/9.2.10.0-SNAPSHOT/) please?

**Comment by headius** [comment] 2020-02-16 17:27
I believe this is a duplicate of #5841.

**Closed by headius** 2020-02-16 17:27 UTC

**Comment by afischer-opentext-com** [comment] 2020-02-17 08:14
Testing/Using the [yesterdays snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/9.2.10.0-SNAPSHOT/jruby-dist-9.2.10.0-20200216.151341-81-bin.zip), I confirm that this issue is not anymore. 

What's the ETA for 9.2.10.0? Thank you!
