### ISSUE TITLE
Missing Zlib gzip bad stream exceptions

### ISSUE THREAD

**Issue by drbrain** [jruby/jruby#369] opened 2012-11-01 23:41 UTC
When running the sparklemotion/mechanize tests I get the following errors when testing handling of bad gzip streams.  Zlib::Error subclasses should be raised:

```
$ jruby -Ilib test/test_mechanize_http_agent.rb -n /test_response_content_encoding_gzip/
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
Run options: -n /test_response_content_encoding_gzip/ --seed 64057

# Running tests:

..EFE..EE

Finished tests in 0.060000s, 150.0000 tests/s, 116.6667 assertions/s.

  1) Error:
test_response_content_encoding_gzip_checksum_truncated(TestMechanizeHttpAgent):
IOError: footer is not found
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:506:in `eof'
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:512:in `eof?'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:1124:in `auto_io'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:417:in `content_encoding_gunzip'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:788:in `response_content_encoding'
    test/test_mechanize_http_agent.rb:948:in `test_response_content_encoding_gzip_checksum_truncated'
    org/jruby/RubyBasicObject.java:1667:in `__send__'

  2) Failure:
test_response_content_encoding_gzip_corrupt(TestMechanizeHttpAgent) [test/test_mechanize_http_agent.rb:890]:
[Mechanize::Error] exception expected, not
Class: <IOError>
Message: <"Unexpected end of ZLIB input stream">
---Backtrace---
org/jruby/ext/zlib/JZlibRubyGzipReader.java:506:in `eof'
org/jruby/ext/zlib/JZlibRubyGzipReader.java:512:in `eof?'
/Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:1124:in `auto_io'
/Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:417:in `content_encoding_gunzip'
/Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:788:in `response_content_encoding'
test/test_mechanize_http_agent.rb:891:in `test_response_content_encoding_gzip_corrupt'
---------------

  3) Error:
test_response_content_encoding_gzip_no_footer(TestMechanizeHttpAgent):
IOError: footer is not found
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:506:in `eof'
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:512:in `eof?'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:1124:in `auto_io'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:417:in `content_encoding_gunzip'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:788:in `response_content_encoding'
    test/test_mechanize_http_agent.rb:987:in `test_response_content_encoding_gzip_no_footer'
    org/jruby/RubyBasicObject.java:1667:in `__send__'

  4) Error:
test_response_content_encoding_gzip_checksum_corrupt_crc(TestMechanizeHttpAgent):
IOError: incorrect data check
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:506:in `eof'
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:512:in `eof?'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:1124:in `auto_io'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:417:in `content_encoding_gunzip'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:788:in `response_content_encoding'
    test/test_mechanize_http_agent.rb:914:in `test_response_content_encoding_gzip_checksum_corrupt_crc'
    org/jruby/RubyBasicObject.java:1667:in `__send__'

  5) Error:
test_response_content_encoding_gzip_checksum_corrupt_length(TestMechanizeHttpAgent):
IOError: incorrect length check
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:506:in `eof'
    org/jruby/ext/zlib/JZlibRubyGzipReader.java:512:in `eof?'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:1124:in `auto_io'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:417:in `content_encoding_gunzip'
    /Users/drbrain/Work/git/mechanize/lib/mechanize/http/agent.rb:788:in `response_content_encoding'
    test/test_mechanize_http_agent.rb:932:in `test_response_content_encoding_gzip_checksum_corrupt_length'
    org/jruby/RubyBasicObject.java:1667:in `__send__'

9 tests, 7 assertions, 1 failures, 4 errors, 0 skips
```

**Comment by knu** [comment] 2016-09-08 02:54
I've made the test suite skip some error tests for JRuby, but there are still problems with JRuby 9000.  JRuby 9.1.5.0 seems to raise `IOError: footer is not found` for a valid stream that JRuby 1.7 can read fine: https://travis-ci.org/sparklemotion/mechanize/jobs/158341977#L394

Any idea?

**Comment by headius** [comment] 2016-09-08 05:41
Well, this rises from the history books! I'm not sure what would cause that error. You can pass -Xbacktrace.style=full to get a mixed Ruby/Java backtrace that will pinpoint where it's coming from.

JRuby 9k uses native (FFI-based) IO for most file and stdio streams now, so it's certainly possible they're interacting badly with jzlib. Let's figure it out!

**Comment by knu** [comment] 2016-09-09 11:09
OK, I'll kick a test build shortly!

**Comment by knu** [comment] 2016-09-12 07:59
@headius Here you are!  https://travis-ci.org/sparklemotion/mechanize/jobs/158705201

**Comment by knu** [comment] 2016-09-12 08:00
Somehow build with JRuby 1.7.26 got broken by adding the option: https://travis-ci.org/sparklemotion/mechanize/jobs/158705200

**Comment by headius** [comment] 2016-09-13 21:26
@knu Strange that 1.7 broke, but the result on 9k looks good. We should be able to sort out why we're raising an IOError now and compare it with MRI.

**Comment by headius** [comment] 2016-09-13 21:37
I am able to reproduce locally but I do not know why we're raising these errors just yet.

**Comment by headius** [comment] 2016-09-13 21:46
@ymnk You still out there? :-)

I'm not sure why we get these errors. In both cases, `JZlibRubyGzipReader.read` and `eof` just try to read from a buffered stream around a jzlib gzip stream. Why would we be seeing these "footer" errors?

**Comment by headius** [comment] 2018-05-15 19:14
Still an issue. Unclear what needs to be done, so I'm detargeting.

**Comment by headius** [comment] 2020-07-18 07:12
The errors in question have been masked out for many years, and it's unlikely we'll ever fix this without digging under the covers of jzlib. Since it seems @ymnk is no longer maintaining that library, I'm going to mark this as "won't fix" since it's unlikely to affect anyone (we still error, it's just a different error).

**Closed by headius** 2020-07-18 07:12 UTC
Labels: stdlib
