### ISSUE TITLE
Unix sockets raise exception on long writes

### ISSUE THREAD

**Issue by evanphx** [jruby/jruby#3799] opened 2016-04-12 22:27 UTC
### Environment
- `jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.72-b15 on 1.8.0_72-b15 +jit [darwin-x86_64]`
- `Darwin veritas.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`
- Rails app running puma: `https://github.com/cdonadeo/puma_big_response_test`
### Expected Behavior

Long strings passed to `UNIXSocket#write` writes the data and returns the number of bytes written.

### Actual Behavior

`#write` writes a subset of the data and raises an exception: `#<SystemCallError: Unknown error - >}`. The amount of data varies but I've seen 8192 show up not-randomly, almost like there was a 8k buffer somewhere.

The git repo linked to above shows the behavior. The exception in question is raise inside `#fast_write`. Changing the code to use `#write` instead of `#syswrite` does not change the behavior.

**Comment by headius** [comment] 2016-04-12 22:29
Nice, haven't had a good UNIXSocket bug in a while. What are UNIX sockets used for in a puma set up?

I've got some long flights today so I may have time to look into this.

**Comment by TheKidCoder** [comment] 2016-04-12 22:30
Puma can use a UNIX socket to listen/respond to HTTP requests. For example, you can proxy requests from Nginx to Puma over a UNIX socket.

**Comment by evanphx** [comment] 2016-04-12 22:30
@headius What @TheKidCoder said.

**Comment by headius** [comment] 2016-04-12 22:31
Ok that makes sense.

**Comment by ericqweinstein** [comment] 2016-04-13 02:47
Does this issue correspond to [this constant](https://github.com/jruby/jruby/blob/915993886ae6663586d893b7d237f750068aceb5/lib/ruby/stdlib/ffi/platform/i386-darwin/socket.rb#L118)?

**Comment by headius** [comment] 2016-04-20 19:28
@ericqweinstein Seems plausible...I'm not familiar with that value.

**Comment by headius** [comment] 2016-08-22 17:02
We may be able to make progress on this with @etehtsea helping work on sockets. Sadly it won't be in 9.1.3.0.

**Comment by etehtsea** [comment] 2016-08-31 13:05
Hopefully, I have a fix for this.

**Comment by headius** [comment] 2016-11-08 06:15
@etehtsea Got that fix in a releasable state? We're hoping to push 9.1.6.0 tomorrow.

**Comment by etehtsea** [comment] 2016-11-08 10:55
@headius no, I don't have better solution for now.

**Comment by headius** [comment] 2016-11-08 17:38
@etehtsea I guess what I was asking is if the commit above is a "good enough" fix. If so, do you want to throw it in a PR for testing?

Status of testing is unclear and this is a key core API. Punting.

**Comment by etehtsea** [comment] 2016-11-09 05:49
@headius [you said earlier](https://github.com/jruby/jruby/pull/4123#issuecomment-245011489) that this fix couldn't be "good enough" because possibly it masks real issue.

As far as I remember I tested this issue using [this app](https://github.com/puma/puma/issues/929#issuecomment-209109850) so if needed I could try to convert it to regression spec.

**Closed** 2016-11-22 05:32 UTC

**Comment by sumitmah** [comment] 2017-01-12 07:02
@headius I'm still not getting consistent behaviour with 9.1.7.0 for the puma_big_response_test example app created by @evanphx.

**Comment by sumitmah** [comment] 2017-01-13 02:04
@headius we never merged following commit to master. https://github.com/etehtsea/jruby/commit/613c99f14314cbf0de3fffd44d2b3f3cac36d2f4

**Comment by mavenik** [comment] 2017-01-30 02:42
@headius This is still happening on 9.1.7.0 for long writes and Unix sockets with Puma. Switching to TCP port configuration for Puma has resolved it temporarily, but that's not a viable solution IMO.

Any ETA on the fix?

**Comment by etehtsea** [comment] 2017-01-30 12:52
@mavenik @sumitmah on what OS you caught this?

**Comment by sumitmah** [comment] 2017-01-30 13:31
@etehtsea I can reproduce on linux. This commit https://github.com/etehtsea/jruby/commit/613c99f14314cbf0de3fffd44d2b3f3cac36d2f4 I've tested, supposed to fix it but it never got merged to master. Only next commit after this was merged.

**Comment by etehtsea** [comment] 2017-01-30 15:03
@sumitmah  @mavenik At some point I decided that I had gone crazy, but actually this issue *was* fixed after updating to jnr-enxio 0.14 and appeared again after updating to jnr-unixsocket 0.15.
I'm looking for the fix now.

cc: @enebo @headius

**Comment by etehtsea** [comment] 2017-01-30 17:03
@sumitmah @mavenik should be fixed when https://github.com/jruby/jruby/pull/4466 will be merged.

**Comment by etehtsea** [comment] 2017-02-12 15:46
@sumitmah @mavenik please check again on master

**Comment by mavenik** [comment] 2017-02-13 10:33
@etehtsea Thanks! Will fetch master and verify this.
