### ISSUE TITLE
jRuby 9050 and 9100 behave differently for case / when with Array from MRI

### ISSUE THREAD

**Issue by yoshidajun** [jruby/jruby#3897] opened 2016-05-17 20:41 UTC
Environment:

jruby-9.0.5.0
jruby-9.1.0.0
ruby-2.2.4 ( MRI )
- Mac OS X ( 10.11.4 El Capitan )
- RVM 1.26.11
- irb to run the code

Problem:

The following code returns different results between jRuby and MRI.

``` ruby
ALL = ['v0', 'v1']
vs = ['v0', 'v1']

case vs
when ALL then 1234
else
  raise 'Undefined'
end
```
- MRI ( 2.2.4 ) returns 1234 ( good )
- jRuby ( 9.0.5.0, 9.1.5.0 ) raises RuntimeError: 'Undefined' ( why? )

Stacktrace:

``` ruby
RuntimeError: Undefined
    from (irb):7:in `<eval>'
    from org/jruby/RubyKernel.java:983:in `eval'
    from org/jruby/RubyKernel.java:1290:in `loop'
    from org/jruby/RubyKernel.java:1103:in `catch'
    from org/jruby/RubyKernel.java:1103:in `catch'
    from /Users/yjun/.rvm/rubies/jruby-9.1.0.0/bin/irb:13:in `<top>'
```

Another code using if / else:

``` ruby
ALL = ['v0', 'v1']
vs = ['v0', 'v1']

if ALL === vs
  1234
else
  raise 'Undefined'
end
```

=> This code returns the same result ( 1234: good ).

I thought `case a when b then c else d end` is equivalent to `if b === a then c else d end`.
But it doesn't look like so.

Is this a known issue?

**Comment by headius** [comment] 2016-05-17 20:48
Ah-ha...you may have found the source of pesky "Undefined" errors we have not been able to reproduce. Apparently this form is not particularly common?

This definitely needs to be fixed.

**Comment by headius** [comment] 2016-05-17 20:50
Oops...nevermind...the "Undefined" errors I've seen are unrelated to your script.

But yes, this is still a bug.

**Comment by yoshidajun** [comment] 2016-05-17 20:53
Thank you for your confirmation!

I'll fix my application's code to avoid that for now.
Looking forward to the bug fixed. :-)

**Comment by headius** [comment] 2016-05-17 21:06
cc @enebo and @subbuss since this is obviously a behavior issue in IR (JIT and interp both behave the same).

**Comment by subbuss** [comment] 2016-05-18 04:06
The case-when construct uses IRRuntimeHelpers.isEQQ (via EQQInstr) and the if-then-else construct uses the Array.=== call. So, maybe the isEQQ implementation has a bug in some corner-case.

**Comment by headius** [comment] 2016-05-18 22:20
@subbuss I think the problem is that the IR does not distinguish between these two whens:


```ruby
ary = [1,2,3]
case x
when 1,2,3
  # 1, 2, 3 should each be used to === in turn
when ary
  # Array#== should be called once
end
```

Both cases fall into `isEQQ` with a RubyArray, but the second case isn't supposed to === over the elements.

rescue may have a similar bug.

**Comment by enebo** [comment] 2017-03-14 15:00
I just tested the original case and we seem to be passing it now.  I am guessing this got fixed via another issue at some point in the past.

**Closed by enebo** 2017-03-14 15:00 UTC
Labels: core, ir, JRuby 9000
