### ISSUE TITLE
Rescue clause yielding TypeError hits %undefined

### ISSUE THREAD

**Issue by gregspurrier** [jruby/jruby#2417] opened 2015-01-03 17:36 UTC
[This may be a duplicate of Issue #2267, but it references jruby-head and I am able to give more detail about the failure mode.]

With the JRuby 1.7.18 release I started seeing the following error when running the [Klam](https://github.com/gregspurrier/klam) specs under Travis CI:

```
TypeError: class or module required for rescue clause. Found: %undefined
```
If I down-rev to JRuby 1.7.17, the tests pass. Here are examples of [failing](https://travis-ci.org/gregspurrier/klam/jobs/45751133) and [passing](https://travis-ci.org/gregspurrier/klam/jobs/45783485) builds differing only in the version of JRuby.

The code snippet that triggers the first of the failures is:
```ruby
(begin; (false ? false : __send__(:"simple-error",'cond failure')); rescue => __KLAM_001; __send__(:"error-to-string",__KLAM_001); end)
```
This string is generated by the Klam compiler and is being executed via `instance_eval` within an instance of a subclass of `BasicObject`.

NOTE: I am not able to reproduce this failure locally under OS X with Java 1.7.0_67.

**Comment by headius** [comment] 2015-01-07 00:36
Very weird.

**Comment by deepj** [comment] 2015-01-16 23:44
The same problem is on JRuby 9k too. I met with this issue in case of trying to pass tests of [lotus-router](https://github.com/lotus/router) on JRuby 9k.

```
git clone git@github.com:lotus/router.git lotus-router
cd lotus-router
bundle
rake test
```

Tested on
```
jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2015-01-15 4142c8d Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 +jit [darwin-x86_64]
```

**Comment by ntl** [comment] 2015-01-18 16:37
Just stumbled on this one with jruby-9000-dev built yesterday. Inheriting from `Object` is fine, but any object that raises an error within a `BasicObject` subclass dies.

**Comment by enebo** [comment] 2015-01-18 16:49
Ah yeah this is not an issue with 1.7.18 and is a problem with master/9k.  #2267 is causing people to run specs against the wrong version of JRuby.  I will update this issue and mark it against 9k.

**Comment by enebo** [comment] 2015-01-18 16:54
@ntl do you happen to have a reduces snippet for this?  My repros of making an object inherited from BasicObject so far have not been blowing up.

**Comment by ntl** [comment] 2015-01-18 19:32
This will do it for me. I think you have to rescue an error within `BasicObject`.

```ruby
class ExposesJRuby2417 < BasicObject                                               
  def blow_up                                                                      
    begin                                                                          
      ::Kernel.raise "error"                                                       
    rescue                                                                         
    end                                                                            
  end                                                                              
end                                                                                
ExposesJRuby2417.new.blow_up                                                       
```

**Comment by enebo** [comment] 2015-01-18 20:41
@ntl Excellent!  About as minimal as it probably gets...

**Comment by ntl** [comment] 2015-01-18 21:00
@enebo glad it's helpful. I strongly resisted the urge to golf it down further.

**Comment by subbuss** [comment] 2015-01-19 02:50
The problem is that 'StandardError' is not being found in the inheritance hierarchy when the class inherits BasicObject. So, maybe the bug is that in IR mode, we shouldn't be generating a lookup for StandardError but have it around. See the related FIXME in IRBuilder which talks of a different issue with having the class looked up. I think dealing with the FIXME will fix the issue. But, before I go ahead, it would be good to get some other eyes on it ( @enebo  @headius  ).

--------------------------------------------------------------------------

            // SSS FIXME:
            // rescue => e AND rescue implicitly EQQ the exception object with StandardError
            // We generate explicit IR for this test here.  But, this can lead to inconsistent
            // behavior (when compared to MRI) in certain scenarios.  See example:
            //
            //   self.class.const_set(:StandardError, 1)
            //   begin; raise TypeError.new; rescue; puts "AHA"; end
            //
            // MRI rescues the error, but we will raise an exception because of reassignment
            // of StandardError.  I am ignoring this for now and treating this as undefined behavior.
            //
            // Solution: Create a 'StandardError' operand type to eliminate this.
            Variable v = addResultInstr(s, new InheritanceSearchConstInstr(s.createTemporaryVariable(), s.getCurrentModuleVariable(), "StandardError", false));

**Comment by enebo** [comment] 2015-01-19 15:17
I think shortest near term fix would be to change module<0> to <Class:Object> right?  I guess we should figure out it overriding this particular constant will change rescue behavior or not too since manipulating StandardErrror to something else at runtime seems like a horrible idea :)  Having an operand for either behavior would probably be the thing to do once we figure out which way it is supposed to work.

```text
BB [6:LBL_2:10]
	%v_3 = recv_ruby_exc
	%v_4 = inheritance_search_const(module<0>)(module<0>, StandardError)
	%v_5 = rescue_eqq(%v_4, %v_3)
	b_true(LBL_5:16, %v_5)
```

**Closed** 2015-01-19 15:46 UTC
Labels: ir, JRuby 9000

**Comment by enebo** [comment] 2015-01-19 15:50
Ok so I looked into @subbuss question:

```ruby
Object.const_set :StandardError, 1

class ExposesJRuby2417 < BasicObject                                               
  def blow_up                                                                      
    begin                                                                          
      ::Kernel.raise "error"                                                       
    rescue 
       puts "rescued"                                                                        
    end                                                                            
  end                                                                              
end                                                                                
ExposesJRuby2417.new.blow_up   
```

In MRI this prints "rescued" and in JRuby we complain about StandardError being '1'.
