### ISSUE TITLE
`rails new app -O` failing

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#7737] opened 2023-03-28 17:50 UTC
`rails new app -O` is failing on jruby-9.4.2.0 and rails 7.0.4.3 with the following error:
```
...
M-GH4FQWVXGF:tmp Heinrich_Klobuczek$ rails new app -O
...
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
LoadError: no such file to load -- active_model/railtie
/Users/Heinrich_Klobuczek/mck/tmp/app/config/application.rb:5:in `<main>'
/Users/Heinrich_Klobuczek/mck/tmp/app/Rakefile:4:in `<main>'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/command.rb:51:in `invoke'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
rails aborted!
LoadError: no such file to load -- active_model/railtie
/Users/Heinrich_Klobuczek/mck/tmp/app/config/application.rb:5:in `<main>'
/Users/Heinrich_Klobuczek/mck/tmp/app/Rakefile:4:in `<main>'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/command.rb:51:in `invoke'
/Users/Heinrich_Klobuczek/.rvm/gems/jruby-9.4.2.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

It succeeds on MRI rubies 3.x

**Environment Information**
  
Provide at least:
* JRuby version: 9.4.2.0
* Operating system and platform (e.g. `uname -a`): Darwin M-GH4FQWVXGF 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

Other relevant info you may wish to add:
* Application/framework version (e.g. Rails, Sinatra): rails 7.0.4.3

**Expected Behavior**

* Completes without error

**Actual Behavior**

* Exits with errors

**Comment by enebo** [comment] 2023-03-28 19:45
Odd.  It appears something is requiring activemodel but you do not have it.  This would mean:

  1. it is not in the lock file but should be
  2. it is required when it shouldn't be

Rails new has some special jruby-specific initialization in it so perhaps something is out of date for Rails 7.  It could be a much more esoteric problem in JRuby itself but I would bet on new putting the wrong combo of stuff into initializers or Gemfile or both.

**Comment by klobuczek** [comment] 2023-03-29 21:16
I think it is a timing issue. In the generation process, there is something missing. After the generation, if you run the 2 commands
```
rails  importmap:install
rails  turbo:install stimulus:install
```
manually they succeed.

**Comment by headius** [comment] 2024-02-13 19:20
Any more clues on this? I cannot reproduce.

**Comment by headius** [comment] 2024-06-27 19:46
No followup since early 2023 so I think we need to close this. @klobuczek If you can still reproduce I'm keen to fix whatever's broken!

**Closed** 2024-06-27 19:47 UTC
