### ISSUE TITLE
Fix: Failing references to libc.so on FreeBSD 10

### ISSUE THREAD

**Issue by iamasmith** [jruby/jruby#1659] opened 2014-04-25 13:10 UTC
In FreeBSD 10 the first occurrence of libc.so on the path happens to be a linker script that unfortunately isn't handled by even the ports provided by the JDK.
This results in various errors when trying to use FFI functions or anything Unix Domain Socket based.
On the face of it this could be interpreted as a port issue requiring a patch to the JDK to handle the linker script, however, correctly specifying a real library IS handled correctly by the JDK so it brings an area of uncertainty as to where the fix should go.
The effected areas seem to be jffi and jnr.unixsocket with independent selection of libc.so by name. In a project like jruby one understands that it is necessary to overlook DRY principle sometimes in favour of taking a straight copy of the component to include in the project.
jffi has some platform specific selections for libc which default out for FREEBSD as libc.so, I don't see any way of observing the OS revision and the os.name simply says 'freebsd' so it doesn't seem pragmatic to approach the jffi folks with a way to go for libc.so.7 instead of libc.so on a FreeBSD 10 platform when earlier revisions will still have os.name = freebsd but their libc.so will be a binary.
jnr.unixsocket has independent code to load libc.so which falls straight into a simple loadLibrary call and similarly fails.
Fix submitted to jnr-ffi mentioned below.

**Comment by rtyler** [comment] 2015-08-07 22:32
We've had a number of jnr-ffi updates since this ticket was filed, and I saw this work on 1.7.16.1 last year. I'm going to close it out.

If the issue isn't properly fixed, please re-open @iamasmith

**Closed by rtyler** 2015-08-07 22:32 UTC

**Comment by iamasmith** [comment] 2015-08-18 12:00
Confirmed this is fixed by building from source 1.17.21. Our port on FreeBSD needs some updating I think as it's back at 1.7.15 :p

**Comment by iamasmith** [comment] 2015-08-20 14:19
Submitted a patch to the current port (1.7.15) here, hopefully it will be merged soon.
