### ISSUE TITLE
Fake prefix for canonicalizing classpaths slightly off on Windows

### ISSUE THREAD

**Issue by presidentbeef** [jruby/jruby#4645] opened 2017-06-03 01:46 UTC
The path generated on Windows by the fix in #4543 is off by two characters (the drive letter).

To reproduce, use [this repo](https://github.com/presidentbeef/jruby-realpath-error) and follow the README.

The output on Windows will be:

```
$ java -jar myapp.jar
Errno::ENOENT: No such file or directory - classpath:BY\jar-bootstrap.rb
          realpath at org/jruby/RubyFile.java:864
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:11
            <main> at classpath:/jar-bootstrap.rb:1
```

As noted [here](https://github.com/jruby/jruby/pull/4543#discussion_r118606731), this is because the path is expanded to include the drive. The fake prefix `/THIS_IS_A_FAKE_PATH_FOR_JRUBY` becomes something like `C:/THIS_IS_A_FAKE_PATH_FOR_JRUBY`. When it's supposed to be removed from the resulting path the `BY` is left over.

**Comment by kares** [comment] 2017-06-05 21:01
will mark this as a duplicate of https://github.com/jruby/jruby/issues/4645 (same issue)

**Closed by kares** 2017-06-05 21:01 UTC

**Comment by presidentbeef** [comment] 2017-06-05 21:17
Thank you @kares! 🚀
