### ISSUE TITLE
Error in File.stat

### ISSUE THREAD

**Issue by n-nishizawa** [jruby/jruby#2424] opened 2015-01-05 01:38 UTC
I'm using jruby 1.7.17
```
$ jruby -v
jruby 1.7.17 (1.9.3p392) 2014-12-09 fafd1a7 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_07-b10 +jit [Windows 7-amd64]
```

I tested this code on windows 7.

```
# coding: utf-8

path = 'てすと.txt'
puts "FileTest.readable?: #{FileTest.readable?(path)}"
puts File.stat(path)
```
And I got an error when I set java default encoding utf-8.

```
>jruby -J-Dfile.encoding=utf-8 stat.rb
FileTest.readable?: true
Errno::ENOENT: No such file or directory - 縺ｦ縺吶→.txt
    stat at org/jruby/RubyFile.java:848
  (root) at stat.rb:5
```

The file specified by the variable path exists. 
In fact, FileTest.readable? returns true.
And I can also read data from the file.
But File.stat throws an exception.

**Comment by n-nishizawa** [comment] 2015-01-07 02:21
This is an additional information.
Methods that access file attributes(stat) raise the same error.
For example File.ctime and File.ftype.

- File.ctime

```
# coding: utf-8

path = './てすと.txt'
puts "FileTest.readable?: #{FileTest.readable?(path)}"
puts File.ctime(path)
```

```
> jruby -J-Dfile.encoding=utf-8 .\stat.rb
FileTest.readable?: true
Errno::ENOENT: No such file or directory - ./縺ｦ縺吶→.txt
   ctime at org/jruby/RubyFile.java:860
  (root) at .\stat.rb:5
```

- File.ftype

```
> jruby -J-Dfile.encoding=utf-8 .\stat.rb
FileTest.readable?: true
Errno::ENOENT: No such file or directory - ./縺ｦ縺吶→.txt
   ftype at org/jruby/RubyFile.java:827
  (root) at .\stat.rb:5
```

I think handling of the path encoding when accessing the file attributes may be a cause.

**Comment by headius** [comment] 2015-02-23 19:03
Confirmed in JRuby 9k as well. This should be really be fixed for 9k.pre2.

**Comment by headius** [comment] 2015-02-23 19:49
Ok, I think I see the problem. We are using _stat64 as our win32 stat call, but we probably should be using _wstat which supports wide characters. There may be a way to make stat64 work properly if we transcode the characters to some appropriate encoding (we we may not be doing by just letting default Java transcoding convert the char[] back to byte[].

I'll see if I can get a jnr-posix change made to add _wstat.

**Comment by headius** [comment] 2015-02-23 20:17
Yup, that appears to fix it. We will need to patch and release jnr-posix for this. I will make the change there, but we need a release of it and pom.xml bump for 9k.pre2.

This *may* also fix it in 1.7, but I did not test that. 1.7 would need the same jnr-posix upgrade treatment.

Tagging @enebo re: jnr-posix lifecycle.

**Comment by headius** [comment] 2015-02-23 20:20
Reopening since it still needs release, and @enebo may want us to explore fixing it in 1.7.20 as well.

**Comment by enebo** [comment] 2015-02-23 20:23
Yeah definitely.  We just need to understand more about our last deployment attempt of jffi or possibly just back off that to get these fixes in under the guise of least risk perhaps.

**Comment by headius** [comment] 2015-04-28 14:52
I've got the commit to update 1.7 in my local repo and will push shortly, so let's call this fixed.

**Comment by headius** [comment] 2015-04-28 14:53
Oh all right, let's actually just leave it open until @enebo or I can confirm it on Windows.

**Comment by enebo** [comment] 2015-04-29 16:18
Works on windows with jruby-1_7.  Closing.

**Closed by enebo** 2015-04-29 16:18 UTC
Labels: core, JRuby 1.7.x, windows
