### ISSUE TITLE
Segmentation fault executing `Kernel.system("ls -lha")` inside Logstash

### ISSUE THREAD

**Issue by andsel** [jruby/jruby#6948] opened 2021-11-29 13:39 UTC
A user of Logstash, implementing a simple pipeline with some Ruby code to execute external process, reaches a segmentation fault.

**Environment Information**
  
- JRuby version:
```
bin $ ruby -version
jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +jit [linux-x86_64]
```
- JVM: 
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
- glibc:
```
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
- OS and Kernel:
```
Linux version 4.18.0-240.1.1.el8_3.x86_64 (mockbuild@x86-vm-09.build.eng.bos.redhat.com) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Fri Oct 16 13:36:46 EDT 2020
```
- CPU:
```
vendor_id : GenuineIntel
cpu family : 6
model name : Intel(R) Xeon(R) Gold 6246 CPU @ 3.30GHz
```

**Expected Behavior**
The execution shouldn't make the JVM to segfault

**Actual Behavior**

Executing the pipeline:
```
input {generator{}}
filter {ruby {code => 'status = Kernel.system("ls -lha")'} }
output { stdout {} }
```
the JVM crashes with:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbca5474344, pid=1167683, tid=1168059
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.10+9, mixed mode, tiered, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0xeb344]  __spawnix+0x64 
```

happening during jffi call:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 18876  com.kenai.jffi.Foreign.invokeN6O2(JJJJJJJJLjava/lang/Object;IIILjava/lang/Object;III)J (0 bytes) @ 0x00007fbc8cc1b110 [0x00007fbc8cc1b040+0x00000000000000d0]
J 21131 c2 com.kenai.jffi.Invoker.invokeN6(Lcom/kenai/jffi/CallContext;JJJJJJJILjava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;Ljava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;Ljava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;Ljava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;Ljava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;Ljava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;)J (1392 bytes) @ 0x00007fbc8d0a76cc [0x00007fbc8d0a74e0+0x00000000000001ec]
J 21130 c2 jnr.posix.LinuxLibC$jnr$ffi$0.posix_spawnp(Ljnr/ffi/byref/ByReference;Ljava/lang/CharSequence;Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;[Ljava/lang/CharSequence;[Ljava/lang/CharSequence;)I (356 bytes) @ 0x00007fbc8d0a96f8 [0x00007fbc8d0a8b60+0x0000000000000b98]
J 26944 c2 org.jruby.RubyKernel.system(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;[Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject; (239 bytes) @ 0x00007fbc8e06e750 [0x00007fbc8e06d6e0+0x0000000000001070]
```

I tried to reproduce on my local host without being successful.

**Comment by headius** [comment] 2021-11-29 16:18
Ok, so recapping a bit from the jffi issue...

* This `Kernel.system` line is *very* basic, and similar commands work fine outside of Logstash, so something is specific to the Logstash environment.
* One possible crash trigger might be due to missing the tweaks in https://github.com/jnr/jnr-posix/pull/171, but that should only affect process launches that redirect a stream to a file.
* We really need a way to reproduce this to investigate further, since the crash frame is within libc itself. Something about this setup is apparently causing us to use `posix_spawn` incorrectly.

**Comment by andsel** [comment] 2021-12-02 08:04
Hi @headius 
I tried in Virtualbox with [Centos 8.3](https://archive.kernel.org/centos-vault/8.3.2011/isos/x86_64/), which is binary equivalent to RHEL 8.3, running the offending pipeline for almost 10 hours without a crash. Sadly, it seems really difficult to reproduce outside of the environment where it was noticed first.

**Comment by headius** [comment] 2021-12-02 15:01
@andsel Ok, let's close this for now and hopefully you will get more information. Perhaps something was corrupt about the user's environment and it will not happen again. Reopen if you are able to come up with a reproduction, or if it happens again and we learn something new.

**Closed by headius** 2021-12-02 15:01 UTC
