### ISSUE TITLE
isutf8 exception Jruby 9.0.00

### ISSUE THREAD

**Issue by ggongaware** [jruby/jruby#3261] opened 2015-08-18 15:14 UTC
>> "text".isutf8
TypeError: no implicit conversion of Fixnum into String
	from org/jruby/RubyString.java:5300:in `force_encoding'
	from /xxx/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/kconv.rb:193:in `isutf8'
	from /xxx/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/kconv.rb:281:in `isutf8'
	from (irb):7:in `<eval>'
	from org/jruby/RubyKernel.java:979:in `eval'
	from org/jruby/RubyKernel.java:1292:in `loop'
	from org/jruby/RubyKernel.java:1099:in `catch'
	from org/jruby/RubyKernel.java:1099:in `catch'
	from /xxx/.rvm/rubies/jruby-9.0.0.0/bin/irb:13:in `<top>'

**Comment by rtyler** [comment] 2015-08-18 16:13
Here's a sample script that reproduces this, since it wasn't immediately obvious from the report:

```ruby
require 'kconv'

"test".isutf8
```

**Comment by headius** [comment] 2015-08-18 18:01
This appears to be the same issue as jruby/jruby#338.

**Comment by rtyler** [comment] 2015-08-18 20:03
@headius the same issue as a three year old bug? :crying_cat_face:

**Comment by headius** [comment] 2015-08-18 20:54
Yeah...we need to fix NKF to define those constants as Encoding instances and do the mapping back and forth to NKF encoding ints.

**Comment by k77ch7** [comment] 2016-01-22 14:52
@headius the above sample script doesn't reproduce. Works for me.

my env
```
$ ruby -v
jruby 9.0.5.0-SNAPSHOT (2.2.3) 2016-01-22 1761e2e Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [darwin-x86_64]
```

**Comment by headius** [comment] 2016-02-14 11:28
@k77ch7 Hmm, you're right. I'll poke around a bit and see if there's any reason not to close this.

**Comment by headius** [comment] 2016-02-14 11:33
Ah-ha, our good friend @kares is responsible for fixing this in cfdccd7e8ee239ca9a1ea19a22740c1ea0a15ce2.

I'm removing the 1.8 paths for JRuby 9.1.0.0 but otherwise we'll call this fixed. I'll also investigate whether we've got some tests to untag/unexclude.

**Comment by headius** [comment] 2016-02-14 11:37
I removed the 1.8 paths in ecae248e893167b82dde9af755ff80108717d330.

There does not appear to be any tests for the kconv.rb functionality right now.

**Comment by headius** [comment] 2016-02-14 11:39
Ok scratch that...there's nkf/test_kconv.rb. I'll fiddle with it for a bit and see if I can get it passing.

**Comment by headius** [comment] 2016-02-14 11:57
So it appears most of the remaining failures in `test_kconv.rb` are due to our NKF library still using Charset transcoding rather than jcodings. I'm going to resolve this and file another issue to get those fixed. That should give us the test coverage we want for this issue.

**Closed by headius** 2016-02-14 11:57 UTC
Labels: JRuby 9000, stdlib
