### ISSUE TITLE
With invokedynamic I get ArgumentError

### ISSUE THREAD

**Issue by thehappycoder** [jruby/jruby#3441] opened 2015-11-01 05:37 UTC
JRUBY_OPTS="--server -J-Xmx1200m -J-Xms32m -J-XX:MaxMetaspaceSize=228m -Xcompile.invokedynamic=true"

ActiveRecord::StatementInvalid (ArgumentError: wrong number of arguments (1 for 2): SELECT  "profile_generals".\* FROM "profile_generals" WHERE "profile_generals"."profile_id" = 30271 AND "profile_generals"."state_code" = 'ACTIVE' LIMIT 1):

Who's fault is it?

**Comment by kares** [comment] 2017-01-18 06:58
closing as duplicate of https://github.com/jruby/jruby/issues/3441

**Closed by kares** 2017-01-18 06:58 UTC
