### ISSUE TITLE
NullPointerException in Helpers.invokedynamic

### ISSUE THREAD

**Issue by jmiettinen** [jruby/jruby#3608] opened 2016-01-20 11:01 UTC
We have a Rails application running on Tomcat. From time to time, after a restart, loading some views will always fail with the following error:

```
Java::JavaLang::NullPointerException ():
  org.jruby.runtime.Helpers.invokedynamic(Helpers.java:2805)
  org.jruby.RubyObject.equalInternal(RubyObject.java:477)
  org.jruby.RubyArray.includes(RubyArray.java:655)
  org.jruby.RubyArray.include_p(RubyArray.java:1303)
  org.jruby.RubyArray$INVOKER$i$1$0$include_p.call(RubyArray$INVOKER$i$1$0$include_p.gen)
  org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
  org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
```

As restarting usually helps and I haven't been able to reproduce this, I am guessing this is some kind of concurrency problem. Can `RubyArray` have `null`s in it as a result of concurrent access to it from the application code?

The line numbers are for version 1.7.23.

**Comment by kares** [comment] 2016-01-20 18:00
would be interesting to know some context (if you have) around the piece of .rb code this comes from.

**Comment by headius** [comment] 2016-01-21 20:57
Recapping a bit from the actual code...

The line in question is here:

```java
    public static IRubyObject invokedynamic(ThreadContext context, IRubyObject self, MethodNames method, IRubyObject arg0) {
        RubyClass metaclass = self.getMetaClass(); <<<<<
        String name = method.realName();
        return getMethodCached(context, metaclass, method.ordinal(), name).call(context, self, metaclass, name, arg0);
    }
```

The only way we'd have a NPE at this point would be if self were null, which is a serious bug somewhere.

As you have seen, the self value here ultimately is coming out of an array during an `Array#includes` call:

```java
    public boolean includes(ThreadContext context, IRubyObject item) {
        int myBegin = this.begin;
        int end = myBegin + realLength;
        IRubyObject[] values = this.values;
        for (int i = myBegin; i < end; i++) {
            final IRubyObject value = safeArrayRef(values, i);
            if (equalInternal(context, value, item)) return true; <<<<<
        }

        return false;
    }
```

In order for there to be a loose null in an Array, one of two things would have to happen:

* A bug elsewhere that inserted a null or cleared an entry without replacing it with nil.
* Two thread concurrently accessing the array.

I agree with your assessment, and my guess is that there's a concurrency problem here. Unfortunately it's hard to find these issues when there's a bunch of interpreter frames mixed in.

If you have a system where this shows up, you might add some exception handling around that line and re-raise a Ruby exception like this:

```java
try {
    // that line that NPEs
} catch (NullPointerException npe) {
    throw context.runtime.newRuntimeError("NPE!!!");
}
```

Throwing a Ruby error will propagate out better and include a Ruby backtrace that should help figure out where this is happening.

Sorry we can't be more help, but we really need to know where the concurrent access is happening. Without that information, and since this seems likely to be a concurrency issue within your application (or the libraries it uses) I'm going to close this for now.

Please, please reopen if you are able to provide more information, or if the error becomes easily reproducible. We want to help!

**Closed by headius** 2016-01-21 20:57 UTC
Labels: core, JRuby 1.7.x

**Comment by jmiettinen** [comment] 2016-01-26 15:46
I went through the same code as headius noted, to no avail.

But, luckily later on when this problem happened again, we got a nice error in the form `Detected invalid array contents due to unsynchronized modifications with concurrent users`. So someone was structurally modifying a global array :unamused:.

So this is probably solved and thanks.

**Comment by headius** [comment] 2016-02-14 10:41
@jmiettinen In the future we will hopefully be able to explore an Array impl that's more robust under concurrency, but for now I'm glad you got a proper error instead of an NPE. Good to see you again at Jfokus!
