### ISSUE TITLE
cannot link Java class com.util (java.lang.NoClassDefFoundError: com/util (wrong name: com/Util))

### ISSUE THREAD

**Issue by javalovercn** [jruby/jruby#4861] opened 2017-11-21 03:24 UTC
1. new Eclipse Java project, and add a class named 'SecondUtil.java' in package 'com.util'
```Java
package com.util;

public class SecondUtil {
	public SecondUtil(){
		System.out.println("SecondUtil");
	}
}
```
2. add a class named 'TestMain.java' in package 'com'
```Java
package com;

import org.jruby.embed.ScriptingContainer;

public class TestMain {
	public static void main(final String[] args) {
		final ScriptingContainer sc = new ScriptingContainer();
		sc.runScriptlet("Java::com.util.SecondUtil::new()");
	}
}
```
3. import lib jruby-complete-9.1.14.0.jar
4. run TestMain, console prints 'SecondUtil', all is OK.
5. add a class 'Util.java' in package 'com' to current project
```Java
package com;

public class Util {
	public Util(){
		System.out.println("this is Util.");
	}
}
```
6. run TestMain, console prints following error:
```
NameError: cannot link Java class com.util (java.lang.NoClassDefFoundError: com/util (wrong name: com/Util))
  method_missing at org/jruby/javasupport/JavaPackage.java:259
          <main> at <script>:1
Exception in thread "main" org.jruby.embed.EvalFailedException: (NameError) cannot link Java class com.util (java.lang.NoClassDefFoundError: com/util (wrong name: com/Util))
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1300)
	at com.TestMain.main(TestMain.java:8)
Caused by: org.jruby.exceptions.RaiseException: (NameError) cannot link Java class com.util (java.lang.NoClassDefFoundError: com/util (wrong name: com/Util))
	at org.jruby.javasupport.JavaPackage.method_missing(org/jruby/javasupport/JavaPackage.java:259)
	at RUBY.<main>(<script>:1)
```
7. change jruby-complete-9.1.14.0.jar to jruby-complete-1.7.3.jar
8. run TestMain, it works well.

**Comment by headius** [comment] 2017-11-21 03:33
So we are having problems locating a class when there's a package of the same-but-lowercase name.

@kares You've done a lot of tweaking and optimizing of Java integration...perhaps some search order got reversed, or we're using the package name to try to load the class?

**Comment by headius** [comment] 2017-11-21 04:07
@javalovercn Is there a reason you closed this? I was able to reproduce locally, so I do believe this is a bug.

**Comment by headius** [comment] 2017-11-21 04:11
@kares The following fixes the problem for me and does not cause any regressions. Please review. Needs a test, obviously.

```diff
diff --git a/core/src/main/java/org/jruby/javasupport/Java.java b/core/src/main/java/org/jruby/javasupport/Java.java
index e481b7d113..73e8e7326b 100644
--- a/core/src/main/java/org/jruby/javasupport/Java.java
+++ b/core/src/main/java/org/jruby/javasupport/Java.java
@@ -961,13 +961,16 @@ public class Java implements Library {
             // cannot link Java class com.sample.FooBar needs Java 8 (java.lang.UnsupportedClassVersionError: com/sample/FooBar : Unsupported major.minor version 52.0)
             throw runtime.newNameError("cannot link Java class " + className + ' ' + msg, className, ex, false);
         }
+        catch (NoClassDefFoundError | ClassNotFoundException ncdfe) {
+            // let caller try other names
+            return null;
+        }
         catch (LinkageError ex) {
             throw runtime.newNameError("cannot link Java class " + className + ' ' + '(' + ex + ')', className, ex, false);
         }
         catch (SecurityException ex) {
             throw runtime.newSecurityError(ex.getLocalizedMessage());
         }
-        catch (ClassNotFoundException ex) { return null; }
 
         if ( initJavaClass ) {
             return getProxyClass(runtime, JavaClass.get(runtime, clazz));
```

**Comment by headius** [comment] 2017-11-21 05:26
@kares I went ahead with it because everything JI-related looked ok.

I also figured out this was probably introduced when you cleaned up the RaiseException nonsense in `getProxyClassOrNull` in 77ef13e8c9e. Took over 2.5 years for someone to run into this case!

**Closed** 2017-11-21 05:33 UTC
Labels: java integration, JRuby 9000, regression

**Comment by kares** [comment] 2017-11-21 06:04
heh, time sure flies and bugs prevail. makes sense - thanks for the fix :purple_heart:

**Comment by izayaaaaaaa** [comment] 2022-11-13 02:15
> So we are having problems locating a class when there's a package of the same-but-lowercase name.
> 
> @kares You've done a lot of tweaking and optimizing of Java integration...perhaps some search order got reversed, or we're using the package name to try to load the class?

This also happens in a java project in vs code when the package name 'addIt' and the class name 'AddIt' are the same but with different character cases.

_java.lang.NoClassDefFoundError: addIt/AddIt (wrong name: AddIt)_

**Comment by kares** [comment] 2022-11-15 09:21
@izayaaaaaaa that sounds like a similar bug - might be worth opening a clean new issue as the cause seems to be different.
BONUS points if you have a clean reproducer with latest JRuby 9.3.
