### ISSUE TITLE
jar-dependencies cannot be updated out-of-band from jruby

### ISSUE THREAD

**Issue by ccutrer** [jruby/jruby#7262] opened 2022-06-30 15:45 UTC
I want to make feature improvements to jar-dependencies, but when I install the updated gem into my system, bundler will refuse to load it because the default gem has already been installed. I've determined that the problem is that the rubygems/defaults/jruby.rb requires a file from jar-dependencies extremely early in the boot process of _any_ jruby process in order to hook into the rubygems install process. I plan on resolving this and sending PRs for both jruby and jar-dependencies, but want a tracking ticket first since it spans both projects.

**Environment Information**
  
* `jruby 9.3.1.0 (2.6.8) 2021-10-13 2e01e7199d OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.22.04.1 on 11.0.15+10-Ubuntu-0ubuntu0.22.04.1 [linux-x86_64]`
* `Linux opennuc 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Expected Behavior**

`Gemfile`:

```
gem "jar-dependencies", "~> 1.0" # installed manually locally; no actual code changes required other than the change in version number
```

Running `bundle console` should boot without error.

**Actual Behavior**

```
cody@opennuc:~/test$ bundle console
[DEPRECATED] bundle console will be replaced by `bin/console` generated by `bundle gem <name>`
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
Resolving dependencies...
Gem::LoadError: You have already activated jar-dependencies 0.4.1, but your Gemfile requires jar-dependencies 1.0.0. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports jar-dependencies as a default gem.
  check_for_activated_spec! at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/runtime.rb:309
                      setup at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/runtime.rb:25
                       each at org/jruby/RubyArray.java:1865
                       each at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/spec_set.rb:140
                        map at org/jruby/RubyEnumerable.java:799
                      setup at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/runtime.rb:24
                      setup at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler.rb:162
                    require at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler.rb:187
                        run at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/cli/console.rb:15
                    console at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/cli.rb:513
                        run at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27
             invoke_command at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127
                   dispatch at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392
                   dispatch at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/cli.rb:31
                      start at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485
                      start at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/cli.rb:25
                     <main> at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/exe/bundle:48
       with_friendly_errors at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120
                     <main> at /home/cody/.gem/jruby/2.6.8/gems/bundler-2.3.17/exe/bundle:36
                       load at org/jruby/RubyKernel.java:1052
                     <main> at /home/cody/.gem/jruby/2.6.8/bin/bundle:25
```

**Comment by headius** [comment] 2022-07-02 08:42
Good find! Yes, we should defer loading jruby-jars until RubyGems/Bundler can be activated.

**Comment by headius** [comment] 2022-08-04 20:58
I merged #7264 but it seems to have broken some things. We'll need to revert it or fix those issues before we can release 9.3.7.0.

**Comment by AndyObtiva** [comment] 2022-08-05 17:06
I don't know if this is the right place to report this, but I received an issue report yesterday in the [glimmer-dsl-swt] project, which depends on `jar-dependencies`, that it suddenly started giving this error upon scaffolding brand new projects:

```
Gem::LoadError: You have already activated jar-dependencies 0.4.1, but your Gemfile requires jar-dependencies 0.4.2. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports jar-dependencies as a default gem.
  check_for_activated_spec! at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/runtime.rb:308
                      setup at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/runtime.rb:25
                       each at org/jruby/RubyArray.java:1865
                       each at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/spec_set.rb:148
                        map at org/jruby/RubyEnumerable.java:799
                      setup at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/runtime.rb:24
                      setup at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler.rb:163
                     <main> at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/setup.rb:10
                 with_level at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:136
                    silence at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:88
                     <main> at /Users/jordancech/.rvm/gems/jruby-9.3.6.0@dads_converter_ruby/gems/bundler-2.3.19/lib/bundler/setup.rb:10
                    require at org/jruby/RubyKernel.java:1017
                    require at /Users/jordancech/.rvm/rubies/jruby-9.3.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
```

When I tried to enter the scaffolded project and run `bundle update jar-dependencies`, I got this error towards the end:

```
Bundler attempted to update jar-dependencies but its version stayed the same
```

There are other weird issues that were encountered, but they all were caused by the `jar-dependencies` gem update.

I was able to resolve all these issues by fixing the `jar-dependencies` gem version dependency in `glimmer-dsl-swt` to 0.4.1

In any case, I can help out by testing any future updates when you make a new release (coupled with jruby 9.3.7.0).

**Comment by ccutrer** [comment] 2022-08-05 17:44
Ugh, you didn't have `jar-dependencies` in the Gemfile at all, so yanking 0.4.2 and publishing as 1.0.0 wouldn't even help :(. That means for this transition it's going to be required that users either pin to 0.4.1, or update jruby :(.

**Comment by AndyObtiva** [comment] 2022-08-05 18:25
> Ugh, you didn't have jar-dependencies in the Gemfile at all, so yanking 0.4.2 and publishing as 1.0.0 wouldn't even help :(. That means for this transition it's going to be required that users either pin to 0.4.1, or update jruby :(.

Actually, I just updated my previous comment to include details about the `Gemfile` and `Gemfile.lock` of the scaffolded application.

Apparently, what brings in `jar-dependencies` is `psych` `4.0.4` because it has a dependency on `jar-dependencies` `(>= 0.1.7`. If `psych` was updated to a newer version that has a cap on the max version of `jar-dependencies` (e.g. `'>= 0.1.7', '<= 0.4.1'`), then that might perhaps resolve the issue for users without forcing them to pin `jar-dependencies` manually to 0.4.1 or update jruby.

**Comment by headius** [comment] 2022-08-09 15:28
We've been forced to revert this effort and take another look.

The problems were manifold:

* Existing JRuby installations cannot load the new jar-dependencies exactly because of this bug; 0.4.1 gets activated too early and errors result.
* At least one library, Psych, has jar-dependencies in its deps (to retrieve and load SnakeYAML) but its only version specified is `> 0.1.7` which means all new versions are eligible and anyone updating Psych will run into the version mismatch above.
* At the same time, portions of JRuby's own build are run using older versions of JRuby, which of course have this same bug and are incompatible with the 0.4.2 that gets installed during the build.

There's a path forward but we don't know all the twists yet.

It seems to me the primary issue is that 0.4.2 is not compatible with (and breaks) JRuby versions 9.3.6 and earlier, and 0.4.1 is not compatible with (and breaks) any JRuby version that depends on the 0.4.2 gem hooks. So we end up needing a hard break in compatibility that causes problems across the board.

**Comment by jsvd** [comment] 2024-12-03 16:13
As jar-dependencies 0.5.0 was released yesterday I'm guessing more folks will land here looking for answers. I'm also seeing the usual "already activated" in our CI today because of this.
A simple reproducer:

```
/tmp/jar_dep_test ❯ jruby -v
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 21.0.2+13-LTS on 21.0.2+13-LTS +jit [arm64-darwin]
```

```
/tmp/jar_dep_test ❯ cat Gemfile 
source "https://rubygems.org"
gemspec
```

```
/tmp/jar_dep_test ❯ cat jar_dep_test.gemspec 
Gem::Specification.new do |s|
  s.name        = 'example'
  s.version     = '0.1.0'
  s.licenses    = ['MIT']
  s.summary     = "This is an example!"
  s.description = "Much longer explanation of the example!"
  s.authors     = ["Ruby Coder"]
  s.email       = 'rubycoder@example.com'
  s.files       = ["lib/example.rb"]
  s.homepage    = 'https://rubygems.org/gems/example'

  s.add_dependency 'jar-dependencies', '~> 0.3'
end
```

Run bundle install
```
/tmp/jar_dep_test ❯ bundle install --path=vendor/bundle           
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.......
Fetching jar-dependencies 0.5.0
Installing jar-dependencies 0.5.0
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into `./vendor/bundle`
Post-install message from jar-dependencies:
[...]
```
Then require jar-dependencies within a bundle exec:

```
/tmp/jar_dep_test
❯ bundle exec ruby -e "require 'jars/installer'"
Gem::LoadError: You have already activated jar-dependencies 0.4.1, but your Gemfile requires jar-dependencies 0.5.0. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports jar-dependencies as a default gem.
  check_for_activated_spec! at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/runtime.rb:299
                      setup at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/runtime.rb:25
                       each at org/jruby/RubyArray.java:1981
                       each at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/spec_set.rb:191
                        map at org/jruby/RubyEnumerable.java:818
                      setup at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/runtime.rb:24
                      setup at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler.rb:164
                     <main> at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/setup.rb:16
                 with_level at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/ui/shell.rb:173
                    silence at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/ui/shell.rb:119
                     <main> at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/gems/shared/gems/bundler-2.5.22/lib/bundler/setup.rb:16
                    require at org/jruby/RubyKernel.java:1187
                    require at /Users/joaoduarte/.rvm/rubies/jruby-9.4.9.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
```

**Comment by headius** [comment] 2024-12-03 18:44
Also see https://github.com/mkristian/jar-dependencies/pull/83 for tracking the issue on the jar-dependencies side.

**Comment by headius** [comment] 2024-12-03 18:45
This was reverted in 9.4.9.0 because it broke stuff so reopening.

**Comment by headius** [comment] 2024-12-03 20:09
@malcolm-pro Ugh... that is an issue. And there's no version number we could give it that would not be picked up by that specification.

**Comment by malcolm-pro** [comment] 2024-12-03 20:31
> I believe if you pin your Gemfile to 0.4.1 it will get around the conflict for gems like Psych that specify an open-ended version. It's not great but it is a workaround until we find a better solution.

I did confirm that this works, thank you for the tip!

**Comment by headius** [comment] 2024-12-10 07:57
New possible fix for this in #8502. Basically I just moved the hook into our RubyGems defaults file, so it doesn't try to load jar-dependencies before RubyGems itself is ready to activate a gem.

I could use some help testing that in various scenarios, @ccutrer @malcolm-pro @AndyObtiva @jsvd!

**Closed** 2024-12-10 21:38 UTC

**Comment by headius** [comment] 2024-12-10 21:40
The fix has been confirmed by at least @flavorjones and @floehopper in #8488 so I've merged it in for 9.4.10.0. We'll have to figure out something for older JRuby versions and may need to spin 9.4.9.1 and 9.3.x releases so people have an upgrade path.

**Comment by flavorjones** [comment] 2024-12-20 18:22
@headius An issue with jar-dependencies has cropped up in the meantime for projects that have pinned the dependency: https://github.com/ruby/psych/issues/700

**Comment by headius** [comment] 2024-12-20 21:24
We will likely yank the jar-dependencies release until JRuby 9.4.10.0 is out with the activation fix. I don't think anyone currently can even use the 0.5.0 gem on a release because of this issue, so it should be a pretty safe yank.
