### ISSUE TITLE
Intermittent NPE w/ 9.0.3.0

### ISSUE THREAD

**Issue by r6p** [jruby/jruby#3407] opened 2015-10-22 00:40 UTC
When running our rspec suite we get the below NPE stacktrace (line 112) on every other run:

````
core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
104     public IRubyObject interpret(ThreadContext context, IRubyObject self,
105                                          InterpreterContext interpreterContext, RubyModule implClass,
106                                          String name, IRubyObject[] args, Block block, Block.Type blockType) {
107         Instr[]   instrs    = interpreterContext.getInstructions();
108         Object[]  temp      = interpreterContext.allocateTemporaryVariables();
109         double[]  floats    = interpreterContext.allocateTemporaryFloatVariables();
110         long[]    fixnums   = interpreterContext.allocateTemporaryFixnumVariables();
111         boolean[] booleans  = interpreterContext.allocateTemporaryBooleanVariables();
112         int       n         = instrs.length;
113         int       ipc       = 0;
114         Object    exception = null;
````

````
  Java::JavaLang::NullPointerException:
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:112)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:77)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:147)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:138)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:189)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:306)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:152)
     # org.jruby.runtime.BlockBody.yield(BlockBody.java:77)
     # org.jruby.runtime.Block.yield(Block.java:147)
     # org.jruby.RubyArray.each(RubyArray.java:1560)
     # org.jruby.RubyArray$INVOKER$i$0$0$each_DBG.call(RubyArray$INVOKER$i$0$0$each_DBG.gen)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:494)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:179)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:166)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:179)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:166)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:159)
     # org.jruby.runtime.BlockBody.yield(BlockBody.java:83)
     # org.jruby.runtime.Block.yieldNonArray(Block.java:151)
     # org.jruby.RubyBasicObject.yieldUnder(RubyBasicObject.java:1730)
     # org.jruby.RubyBasicObject.specificEval(RubyBasicObject.java:1753)
     # org.jruby.RubyBasicObject.instance_eval19(RubyBasicObject.java:1633)
     # org.jruby.RubyBasicObject$INVOKER$i$instance_eval19_DBG.call(RubyBasicObject$INVOKER$i$instance_eval19_DBG.gen)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrThreeBlock.call(JavaMethod.java:554)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:67)
     # org.jruby.runtime.Block.yieldSpecific(Block.java:116)
     # org.jruby.ir.runtime.IRRuntimeHelpers.yieldSpecific(IRRuntimeHelpers.java:457)
     # org.jruby.ir.instructions.YieldInstr.interpret(YieldInstr.java:72)
     # org.jruby.ir.interpreter.InterpreterEngine.processOtherOp(InterpreterEngine.java:506)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:177)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:118)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:109)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:155)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:118)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:109)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:152)
     # org.jruby.runtime.BlockBody.yield(BlockBody.java:77)
     # org.jruby.runtime.Block.yield(Block.java:147)
     # org.jruby.RubyArray.collect(RubyArray.java:2286)
     # org.jruby.RubyArray.map19(RubyArray.java:2300)
     # org.jruby.RubyArray$INVOKER$i$0$0$map19_DBG.call(RubyArray$INVOKER$i$0$0$map19_DBG.gen)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:494)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:155)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:175)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:166)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:155)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:175)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:166)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:152)
     # org.jruby.runtime.BlockBody.yield(BlockBody.java:77)
     # org.jruby.runtime.Block.yield(Block.java:147)
     # org.jruby.RubyArray.collect(RubyArray.java:2286)
     # org.jruby.RubyArray.map19(RubyArray.java:2300)
     # org.jruby.RubyArray$INVOKER$i$0$0$map19_DBG.call(RubyArray$INVOKER$i$0$0$map19_DBG.gen)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:494)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:155)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:175)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:166)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:152)
     # org.jruby.runtime.BlockBody.yield(BlockBody.java:77)
     # org.jruby.runtime.Block.yield(Block.java:147)
     # org.jruby.RubyArray.collect(RubyArray.java:2286)
     # org.jruby.RubyArray.map19(RubyArray.java:2300)
     # org.jruby.RubyArray$INVOKER$i$0$0$map19_DBG.call(RubyArray$INVOKER$i$0$0$map19_DBG.gen)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:494)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:155)
     # org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:175)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:166)
     # org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:152)
     # org.jruby.runtime.BlockBody.yield(BlockBody.java:77)
     # org.jruby.runtime.Block.yield(Block.java:147)
     # org.jruby.RubyArray.collect(RubyArray.java:2286)
     # org.jruby.RubyArray.map19(RubyArray.java:2300)
     # org.jruby.RubyArray$INVOKER$i$0$0$map19_DBG.call(RubyArray$INVOKER$i$0$0$map19_DBG.gen)
     # org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:494)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:152)
     # org.jruby.runtime.BlockBody.yield(BlockBody.java:77)
     # org.jruby.runtime.Block.yield(Block.java:147)
     # org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:450)
     # org.jruby.ir.instructions.YieldInstr.interpret(YieldInstr.java:75)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:191)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:115)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:122)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:109)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:122)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:109)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:122)
     # org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:109)
     # org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
     # org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
     # org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
     # org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
     # org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
     # org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
     # org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:122)
     # org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
     # org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:59)
     # org.jruby.runtime.Block.call(Block.java:106)
     # org.jruby.RubyProc.call(RubyProc.java:334)
     # org.jruby.RubyProc.call(RubyProc.java:240)
     # org.jruby.Ruby.tearDown(Ruby.java:3238)
     # org.jruby.Ruby.tearDown(Ruby.java:3211)
     # org.jruby.Main.internalRun(Main.java:308)
     # org.jruby.Main.run(Main.java:233)
     # org.jruby.Main.main(Main.java:200)
````

**Comment by headius** [comment] 2015-10-22 12:25
Ick, that's not good.

**Comment by headius** [comment] 2015-10-22 15:51
@r6p Do you get this if you run with --dev or JRUBY_OPTS=--dev?

**Comment by enebo** [comment] 2015-10-22 18:22
```java
        int       n         = instrs.length;
```
This must be run with -X-C.  I see no run through StartupInterpreter in last call so it is entering full interpreter run but it has no instructions which should be impossible.  If it is not -X-C then somehow the JIT is causing this (which is not apparent).  If it is enabled then something broke the replacement of startup to full interpretercontext.  If it is the latter case then changes to JITCompiler would be the culprit assuming this problem only started occurring since 9.0.1.0.

@r6p in addition to what options/mode you are running your tests can you say whether this is a regression since 9.0.1.0 as well?

**Comment by r6p** [comment] 2015-10-22 22:20
@headius @enebo here are the options at play during the offending rspec runs

````
JRUBY_OPTS=--debug -J-Xmx2048m -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF
````

I will try to see if it repros w/ --dev too.

**Comment by r6p** [comment] 2015-10-23 00:38
I can repro with the following options too (including --dev):

````
JRUBY_OPTS=--dev --debug -J-Xmx2048m -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF
````

**Comment by r6p** [comment] 2015-10-23 02:11
A debug build would be helpful as the Java stacktrace is abrupt during the rspec run and no context backtrace from Ruby is produced. But it happens in the context of running our MapReduce (M/R) job which is making use of "ScriptingContainer" to execute our Ruby code in a (M/R) harness during those test runs.

**Comment by headius** [comment] 2015-10-23 10:06
@r6p If you get a chance you could try running a build of JRuby with the following patch applied:

```diff
diff --git a/core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java b/core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
index a0e4827..cc8493e 100644
--- a/core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
+++ b/core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
@@ -105,6 +105,10 @@ public class InterpreterEngine {
                                          InterpreterContext interpreterContext, RubyModule implClass,
                                          String name, IRubyObject[] args, Block block, Block.Type blockType) {
         Instr[]   instrs    = interpreterContext.getInstructions();
+        if (instrs == null) {
+            System.out.println("null instrs detected in : " + interpreterContext.getScope());
+            throw context.runtime.newRuntimeError("null instrs");
+        }
         Object[]  temp      = interpreterContext.allocateTemporaryVariables();
         double[]  floats    = interpreterContext.allocateTemporaryFloatVariables();
         long[]    fixnums   = interpreterContext.allocateTemporaryFixnumVariables();
```

And you may want to pass -Xbacktrace.style=full so we get both Ruby frames and Java frames in the resulting exception trace. This should give us a better idea where it's happening in your code.

**Comment by r6p** [comment] 2015-10-23 16:44
@headius I'll give it a try later today. One other useful bit of information is that we force the JIT on programmatically. Maybe that has an impact on how you approach a diagnosis.

**Comment by r6p** [comment] 2015-10-23 17:02
@headius any chance I can get you to push a branch with that patch change? I'd like to be able to build and install it via:

````
$ rvm install --branch 9.0.3.0_issue_3407 jruby-head
````

Or maybe you can recommend a better way to do it using rvm?

**Comment by enebo** [comment] 2015-10-23 17:02
@r6p when you test could you also disable the progrmatic forcing of JIT.  Our runtime was not designed with the thought someone would do that.  I have no idea what issues that could cause.

**Comment by enebo** [comment] 2015-10-23 17:06
@r6p if you are progrmattically trying to toggle JIT on and off for test speed I recommend leaving the JIT enabled but changing JIT threshold to be much higher (-Xjit.threshold=10000).  I think it is set to 50 by default.

**Comment by r6p** [comment] 2015-10-23 17:12
@enebo I will toggle off the JIT, rebuild, and retest thanks.

**Comment by headius** [comment] 2015-10-23 17:58
@r6p Sure, I'll push a branch.

**Comment by headius** [comment] 2015-10-23 17:59
@r6p I have pushed a branch called `debug_3407` for you.

**Comment by r6p** [comment] 2015-10-24 08:59
@headius so I am getting output that looks like:

````
null instrs detected in : INSTANCE_METHOD some_method[/Users/me/blah.rb:85]
````

Line 85 is the line before the instance method named "some_method". Can you give me a little guidance on what else you'd like to see and I'll try to sanitize it and send it over?

We do something like this in that method that seems like it might be a source of trouble:

````
Marshal.dump([obj1, obj2]).to_java_bytes
````

**Comment by headius** [comment] 2015-10-25 21:31
Well to start, getting the content of that method at that line would be great :-)

**Comment by r6p** [comment] 2015-10-26 16:09
@headius, ok I'll see what I can do this morning. One thing to note, is when disabling the programmatic toggle of the JIT on as suggested by @enebo, I "think" the problem can't be reproduced. Hopefully that is helpful info.

**Comment by r6p** [comment] 2015-10-28 16:18
@headius and @enebo, I am going to work on creating a simple test case that reproduces the issue when the JIT is forced ON programmatically as that is the only circumstance under which I can reproduce the problem now. Please give me a sense of priority of this issue for the project, if it is an edge case I won't jump to it right away.

**Comment by headius** [comment] 2015-10-29 21:37
Given your unusual situation we don't currently consider this a high priority. We do, however, want to fix it for a release fairly soon.

Is there a reason you don't just run with default flags? Why are you starting up with jit OFF and then turning it on later?

**Comment by r6p** [comment] 2015-11-02 19:44
@headius ok I'll work on a case to reproduce it and send you the details as soon as I can. That being said there is no reason for us to force the JIT on anymore, we should use the default flags or tuned JVM options available when configuring our Map/Reduce jobs via the standard/non-programmtic path.

**Comment by r6p** [comment] 2015-11-04 18:54
@headius @enebo as a follow-up question are the standard JIT options propagated to any ScriptingContainer instances that we instantiate after start-up of the JVM? Or is there a programmatic need for the toggling on the launch of each container instance. Looking back at JRuby 1.7.x, we felt it was necessary for these toggles. But the JIT has changed much since then so maybe it is no longer necessary.

**Comment by enebo** [comment] 2015-11-12 23:40
@r6p I do not think you should be doing this.  I think upping jitthreshold will mostly do the same thing.  As a followup statement we once the profiler is in place our heuristics for when to JIT things should improve.   I am punting this a point release but I want to leave it open because we should probably raise an exception or give a clear message if someone tries to toggle between OFF and JIT mid-run.

**Comment by headius** [comment] 2015-11-19 16:47
@r6p Any status update? Things working better with you not twiddling the JIT settings after boot?

**Comment by headius** [comment] 2016-01-20 00:22
I'm going to close this as being a particularly unusual combination of startup flags and unusual use of JRuby at runtime.

@r6p If you still think there's something for us to fix here, we can revisit.

**Closed by headius** 2016-01-20 00:22 UTC
Labels: ir, JRuby 9000
