### ISSUE TITLE
jruby 1.7.20 - Java::JavaLang::IllegalArgumentException (the salt parameter must not be empty)

### ISSUE THREAD

**Issue by giosakti** [jruby/jruby#3025] opened 2015-06-08 13:15 UTC
Hi all,

Just upgraded jruby on our application from 1.7.19 to 1.7.20 and suddenly the server returned this long error message in almost all API call (previously everything is fine, test passed 100%)

https://gist.github.com/giosakti/03655ff24c7917c7d2ff

My application is on rails 4.1.10

**Comment by mkristian** [comment] 2015-06-08 13:26
this looks like a regression in jruby-openssl-0.9.7 which is bundled with
jruby-1.7.20 and 1.7.19 comes with jossl-0.9.6

unfortunately jruby-1.7.20 has a bug which prevents to downgrade to
jossl-0.9.6 :(

**Comment by kares** [comment] 2015-07-05 10:52
@giosakti any chance you can isolate this for us ? would help resolving the issue.

trace shows the `PKCS5.pbkdf2_hmac_sha1` call as problematic, would be useful to know your exact parameters it gets ... e.g. you may try monkey-patching the method to print what args its called with if you're not sure how to isolate.

**Closed** 2015-07-15 11:52 UTC
Labels: openssl
