### ISSUE TITLE
UnmodifiableRandomAccessList appears to be missing some Enumerable methods in 9.3.1.0

### ISSUE THREAD

**Issue by dwalinsq** [jruby/jruby#6914] opened 2021-10-27 22:00 UTC
Filing after discussion in the channel. Thanks for all you do in maintaining JRuby!

**Environment Information**
  
  JRuby 9.3.1.0 
  jdk1.8.0_272
  JRUBY_OPTS=-J-Xmx2048m -J-Dfile.encoding=UTF8 -J-Djava.security.egd=file:/dev/./urandom -J-Dclient.encoding.override=UTF8 -J-Duser.timezone=UTC -J-Djava.awt.headless=true
  
**Expected Behavior**

A `Java::JavaUtil::Collections::UnmodifiableRandomAccessList` should have all methods from Enumerable, even when there are other modules included.

**Actual Behavior**

From my app, the UnmodifiableRandomAccessList `class.instance_methods` returns the following, which is missing `map` and other Enumerable methods. I am getting a new `NoMethodError` when calling map on such a list in CI, on upgrading to 9.3.1.0 (this was not an issue on 9.2.19.0). UnmodifiableRandomAccessList.class.instance_methods:
```
       +[:contains?,
       + :retain_all,
       + :retain_all?,
       + :add_all,
       + :empty,
       + :to_array,
       + :removeAll,
       + :iterator,
       + :add?,
       + :toArray,
       + :remove_all,
       + :parallelStream,
       + :empty?,
       + :indexOf,
       + :add,
       + :==,
       + :spliterator,
       + :sort,
       + :remove?,
       + :removeIf,
       + :contains,
       + :size,
       + :sub_list,
       + :listIterator,
       + :replace_all,
       + :contains_all?,
       + :for_each,
       + :replaceAll,
       + :remove,
       + :index_of,
       + :add_all?,
       + :parallel_stream,
       + :stream,
       + :get,
       + :remove_if,
       + :is_empty,
       + :last_index_of,
       + :remove_all?,
       + :subList,
       + :contains_all,
       + :set,
       + :forEach,
       + :containsAll,
       + :list_iterator,
       + :clear,
       + :isEmpty,
       + :"__jcreate!",
       + :is_empty?,
       + :lastIndexOf,
       + :addAll,
       + :equals,
       + :remove_if?,
       + :retainAll,
       + :ruby_first,
       + :[],
       + :rindex,
       + :last,
       + :index,
       + :to_a,
       + :sort!,
       + :ruby_sort,
       + :ruby_last,
       + :[]=,
       + :first,
       + :to_ary,
       + :<<,
       + :length,
       + :+,
       + :member?,
       + :-,
       + :each,
       + :entries,
       + :include?,
       + :clone,
       + :inspect,
       + :join,
       + :each_with_index,
       + :dup,
       + :count,
       + :getClass,
       + :wait,
       + :notifyAll,
       + :equals?,
       + :notify,
       + :hash_code,
       + :hashCode,
       + :finalize,
       + :toString,
       + :get_class,
       + :notify_all,
       + :to_string,
       + :java_send,
       + :equal?,
       + :marshal_load,
       + :marshal_dump,
       + :java_method,
       + :java_object=,
       + :eql?,
       + :synchronized,
       + :to_java_object,
       + :to_s,
       + :java_class,
       + :hash,
       + :java_object,
       + :to_json,
       + :present?,
       + :to_yaml,
       + :to_proto_string,
       + :html_safe?,
       + :to_proto_primitive,
       + :instance_variable_names,
       + :acts_like?,
       + :deep_dup,
       + :to_param,
       + :presence,
       + :to_query,
       + :duplicable?,
       + :with_options,
       + :blank?,
       + :instance_values,
       + :as_json,
       + :in?,
       + :presence_in,
       + :pretty_print_instance_variables,
       + :pretty_print_cycle,
       + :pretty_print_inspect,
       + :pretty_print,
       + :try!,
       + :try,
       + :public_send,
       + :frozen?,
       + :protected_methods,
       + :java_implements,
       + :public_method,
       + :protos,
       + :freeze,
       + :java,
       + :singleton_methods,
       + :untaint,
       + :javafx,
       + :enum_for,
       + :private_methods,
       + :method,
       + :then,
       + :instance_variables,
       + :object_id,
       + :extend,
       + :itself,
       + :instance_variable_set,
       + :respond_to?,
       + :java_name,
       + :singleton_method,
       + :methods,
       + :gem,
       + :to_java,
       + :java_package,
       + :singleton_class,
       + :public_methods,
       + :to_enum,
       + :display,
       + :yield_self,
       + :tainted?,
       + :instance_variable_defined?,
       + :untrusted?,
       + :define_singleton_method,
       + :nil?,
       + :!~,
       + :com,
       + :instance_of?,
       + :java_require,
       + :javax,
       + :java_signature,
       + :===,
       + :tap,
       + :class_eval,
       + :java_annotation,
       + :send,
       + :pretty_inspect,
       + :trust,
       + :instance_variable_get,
       + :is_a?,
       + :java_field,
       + :remove_instance_variable,
       + :untrust,
       + :<=>,
       + :class,
       + :=~,
       + :org,
       + :taint,
       + :kind_of?,
       + :!,
       + :should_not_receive,
       + :should_receive,
       + :received_message?,
       + :instance_exec,
       + :unstub,
       + :null_object?,
       + :__id__,
       + :instance_eval,
       + :__send__,
       + :stub,
       + :should,
       + :should_not,
       + :!=,
       + :stub_chain,
       + :as_null_object]
```

This is the `class.ancestors` for this `UnmodifiableRandomAccessList`. It is the same in 9.3.1.0 as in 9.2.19.0, except that the version that is missing `map` and other `Enumerable` methods has `Enumerable` in it, while the 9.2.19.0 version (which *does* have map) does not list `Enumerable` in its ancestors.
```
       +[Java::JavaUtil::Collections::UnmodifiableRandomAccessList,
       + Java::JavaUtil::RandomAccess,
       + Java::JavaUtil::Collections::UnmodifiableList,
       + Java::JavaUtil::List,
       + Java::JavaUtil::Collections::UnmodifiableCollection,
       + Java::JavaUtil::Collection,
       + Java::JavaLang::Iterable,
       + Enumerable,
       + Java::JavaIo::Serializable,
       + Java::JavaLang::Object,
       + ConcreteJavaProxy,
       + JavaProxy,
       + JavaProxyMethods,
       + ActiveSupport::ToJsonWithActiveSupportEncoder,
       + Object,
       + PP::ObjectMixin,
       + JSON::Ext::Generator::GeneratorMethods::Object,
       + ActiveSupport::Tryable,
       + Kernel,
       + BasicObject
```

Note that this problem does not appear to occur with an UnmodifiableRandomAccessList that has no other modules included. This does not raise an error:
```
jruby -e 'x = java.util.Collections.unmodifiable_list(java.util.Collections::EMPTY_LIST); puts x.class.ancestors; x.map {p :ok}'
```

It therefore seems that some of the mixins in this section of the ancestors, which is different from the basic unmodifiable list, are somehow causing this problem. (None of these mixins should be removing Enumerable methods):

```
       + ActiveSupport::ToJsonWithActiveSupportEncoder,
       + Object,
       + PP::ObjectMixin,
       + JSON::Ext::Generator::GeneratorMethods::Object,
       + ActiveSupport::Tryable,
       + Kernel,
       + BasicObject
```

**Comment by klobuczek** [comment] 2021-10-30 23:41
This is likely related to https://github.com/jruby/jruby/issues/6924

**Comment by headius** [comment] 2021-11-22 17:55
@klobuczek Yeah this is probably a dupe but we'll leave it open until that is confirmed.

**Comment by enebo** [comment] 2021-12-01 19:31
Marking as duplicate of #6924 since it looks to have fixed this:

```text
system ~/work/jruby fix_6924 2344% jruby -e 'p Java::JavaUtil::Collections::UnmodifiableRandomAccessList.instance_methods'
[:contains?, :retain_all, :retain_all?, :add_all, :empty, :to_array, :removeAll, :iterator, :add?, :toArray, :remove_all, :parallelStream, :empty?, :indexOf, :add, :==, :spliterator, :sort, :remove?, :removeIf, :contains, :size, :sub_list, :listIterator, :replace_all, :contains_all?, :for_each, :replaceAll, :remove, :index_of, :add_all?, :parallel_stream, :stream, :get, :remove_if, :is_empty, :last_index_of, :remove_all?, :subList, :contains_all, :set, :forEach, :containsAll, :list_iterator, :clear, :isEmpty, :"__jcreate!", :is_empty?, :lastIndexOf, :addAll, :equals, :remove_if?, :retainAll, :ruby_first, :[], :rindex, :last, :index, :to_a, :sort!, :ruby_sort, :ruby_last, :[]=, :first, :to_ary, :<<, :length, :+, :member?, :-, :each, :entries, :include?, :clone, :inspect, :each_with_index, :join, :dup, :count, :drop_while, :select, :to_h, :find_all, :each_cons, :all?, :find, :reverse_each, :max_by, :minmax_by, :min_by, :zip, :reduce, :minmax, :one?, :take, :uniq, :group_by, :slice_after, :chunk_while, :collect, :drop, :none?, :lazy, :chunk, :detect, :sum, :sort_by, :slice_when, :cycle, :find_index, :partition, :min, :slice_before, :reject, :each_entry, :map, :chain, :collect_concat, :max, :grep, :each_with_object, :filter, :each_slice, :grep_v, :flat_map, :take_while, :inject, :any?, :getClass, :wait, :notifyAll, :equals?, :notify, :hash_code, :hashCode, :finalize, :toString, :get_class, :notify_all, :to_string, :java_send, :marshal_load, :equal?, :marshal_dump, :java_method, :eql?, :java_object=, :synchronized, :to_java_object, :to_s, :java_class, :hash, :java_object, :public_send, :frozen?, :protected_methods, :java_implements, :public_method, :freeze, :java, :singleton_methods, :untaint, :javafx, :enum_for, :private_methods, :method, :then, :object_id, :instance_variables, :extend, :itself, :instance_variable_set, :respond_to?, :java_name, :singleton_method, :methods, :to_java, :java_package, :singleton_class, :public_methods, :to_enum, :display, :yield_self, :tainted?, :instance_variable_defined?, :untrusted?, :define_singleton_method, :nil?, :!~, :com, :instance_of?, :java_require, :javax, :java_signature, :===, :tap, :java_annotation, :send, :trust, :instance_variable_get, :is_a?, :java_field, :remove_instance_variable, :untrust, :<=>, :class, :=~, :org, :taint, :kind_of?, :!, :instance_exec, :__id__, :instance_eval, :__send__, :!=]

```

**Closed by enebo** 2021-12-01 19:32 UTC
Labels: java integration
