### ISSUE TITLE
Test suite crashing with jruby 9.2.11 and rails 4.2

### ISSUE THREAD

**Issue by rpbaltazar** [jruby/jruby#6134] opened 2020-03-24 03:07 UTC
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
 jruby-9.2.11.0
Gemfile: gemfiles/rails_4_2.gemfile
* Operating system and platform (e.g. `uname -a`)
running on travis ci: https://travis-ci.com/github/rails-on-services/apartment/jobs/300904988

Other relevant info you may wish to add:

- Part of the test matrix for apartment gem

**Expected Behavior**

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.
* Provide an executable Ruby script or a link to an example repository.

**Actual Behavior**

```
loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
/home/travis/build/rails-on-services/apartment/gemfiles/vendor/bundle/jruby/2.5.0/gems/rake-0.9.6/lib/rake/task.rb:175: warning: singleton on non-persistent Java type Java::JavaLang::NullPointerException (http://wiki.jruby.org/Persistence)
rake aborted!
arjdbc.mysql.MySQLRubyJdbcConnection.doKillCancelTimer(MySQLRubyJdbcConnection.java:351)
arjdbc.mysql.MySQLRubyJdbcConnection.newConnection(MySQLRubyJdbcConnection.java:283)
arjdbc.jdbc.RubyJdbcConnection.initConnection(RubyJdbcConnection.java:468)
arjdbc.jdbc.RubyJdbcConnection.init_connection(RubyJdbcConnection.java:460)
arjdbc.jdbc.RubyJdbcConnection$INVOKER$i$0$0$init_connection.call(RubyJdbcConnection$INVOKER$i$0$0$init_connection.gen)
[ ... ] 
org.jruby.dist/org.jruby.runtime.load.LoadService.load(LoadService.java:343)
org.jruby.dist/org.jruby.RubyKernel.loadCommon(RubyKernel.java:1039)
org.jruby.dist/org.jruby.RubyKernel.load(RubyKernel.java:1009)
org.jruby.dist/org.jruby.RubyKernel$INVOKER$s$load.call(RubyKernel$INVOKER$s$load.gen)
org.jruby.dist/org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:417)
org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:375)
org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:174)
home.travis.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_11_dot_0.bin.bundle.invokeOther8:load(/home/travis/.rvm/gems/jruby-9.2.11.0/bin/bundle:23)
home.travis.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_11_dot_0.bin.bundle.RUBY$script(/home/travis/.rvm/gems/jruby-9.2.11.0/bin/bundle:23)
java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
org.jruby.dist/org.jruby.ir.Compiler$1.load(Compiler.java:89)
org.jruby.dist/org.jruby.Ruby.runScript(Ruby.java:1205)
org.jruby.dist/org.jruby.Ruby.runNormally(Ruby.java:1128)
org.jruby.dist/org.jruby.Ruby.runNormally(Ruby.java:1146)
org.jruby.dist/org.jruby.Ruby.runFromMain(Ruby.java:958)
org.jruby.dist/org.jruby.Main.doRunFromMain(Main.java:412)
org.jruby.dist/org.jruby.Main.internalRun(Main.java:304)
org.jruby.dist/org.jruby.Main.run(Main.java:234)
org.jruby.dist/org.jruby.Main.main(Main.java:206)
Tasks: TOP => default => spec => db:test:prepare => mysql:build_db
(See full trace by running task with --trace)
The command "bundle exec rake" exited with 1.
```

**Comment by rpbaltazar** [comment] 2020-03-24 03:10
@kares I've briefly spoken with @headius who told me you're the main person supporting older rails. This is a non blocking issue for me as I plan to deprecate rails 4.2 but I think worth for you to know.

**Comment by kares** [comment] 2020-03-24 06:23
Thanks, seems like older AR-JDBC has issues with the major MySQL driver [upgrade]( https://github.com/jruby/activerecord-jdbc-adapter/pull/1026)
This was pushed a month ago or so and since its a major upgrade might have breaking changes.
That being said we [limit the driver version](https://github.com/jruby/activerecord-jdbc-adapter/blob/1-3-stable/activerecord-jdbcmysql-adapter/activerecord-jdbcmysql-adapter.gemspec#L23) in AR-JDBC 1.3 but only if you use the shim actverecord-jdbcmysql-adapter gem, otherwise users might need to limit the driver themselves, e.g. : 
```ruby
gem 'activerecord-jdbc-adapter'
gem 'jdbc-mysql', '< 8', require: false
```

**Comment by kares** [comment] 2020-03-24 06:26
Anyhow, since the issue is AR-JDBC specific and not related to JRuby, I'm closing here.
Feel free to move it to the adapter repo. I do not think we have capacity to support a backport for the 1.3 line (esp. since the `< 8` specifier is in place). 
We sure did not test *jdbc_mysql* 8.x compatibility for Rails < 5

**Closed by kares** 2020-03-24 06:26 UTC
