### ISSUE TITLE
Jirb/Jirb-swing: Destructuring in #select block parameters not working properly

### ISSUE THREAD

**Issue by wrq** [jruby/jruby#7530] opened 2022-12-16 18:54 UTC
Using Jruby 9.4.0.0 in jirb/jirb-swing:

```(1..300).to_a.combination(3).select {|a,b,c| a + b == c}```

Gives instead:

```org.jruby.ir.IRScope.cloneInstrs(IRScope.java:588): Java::JavaLang::NullPointerException
	from org.jruby.ir.IRScope.prepareForCompilation(IRScope.java:655)
	from org.jruby.runtime.MixedModeIRBlockBody.promoteToFullBuild(MixedModeIRBlockBody.java:159)
	from org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:142)
	from org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:170)
	from org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
	from org.jruby.runtime.Block.yield(Block.java:188)
	from org.jruby.RubyEnumerable$17.call(RubyEnumerable.java:777)
	from org.jruby.RubyEnumerable$17.call(RubyEnumerable.java:773)
	from org.jruby.runtime.BlockCallback.call(BlockCallback.java:54)
	from org.jruby.runtime.CallBlock.doYield(CallBlock.java:102)
	from org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
	from org.jruby.runtime.Block.yieldValues(Block.java:234)
	from org.jruby.RubyEnumerator$1.call(RubyEnumerator.java:406)
	from org.jruby.runtime.BlockCallback.call(BlockCallback.java:58)
	from org.jruby.runtime.CallBlock.doYield(CallBlock.java:97)
	from org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
	... 155 levels...
```

I assume this has something to do with how |a,b,c| does an implicit destructuring into the 3-length arrays from the #combination generator. 

Running the same code as above from a file by invoking ```jruby test.rb``` gives the expected output, so it would seem as though the bad behavior is relegated to the (j)irb components.

**Comment by enebo** [comment] 2022-12-16 19:57
I believe this is a duplicate of https://github.com/jruby/jruby/issues/7486.  This works for me with HEAD.

**Closed by enebo** 2022-12-16 19:57 UTC
