### ISSUE TITLE
Refinement bug affecting arbre

### ISSUE THREAD

**Issue by dorianmariefr** [jruby/jruby#6599] opened 2021-03-06 23:13 UTC
**Environment Information**
  
Provide at least:
* `jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 25.275-b01 on 1.8.0_275-b01 +jit [darwin-x86_64]`
* `Darwin macbook.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64`

Other relevant info you may wish to add:
* arbre master branch
* rails 6.1.3

**Expected Behavior**

- when running arbre with latest jruby I except none of the test to break, see: https://github.com/activeadmin/arbre/pull/282

**Actual Behavior**

```
     Failure/Error: text_node form_builder.send(method, *args, &block)
     
     NoMethodError:
       undefined method `deep_merge!' for {}:Concurrent::Hash
       Did you mean?  deep_merge
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/backend/simple.rb:45:in `store_translations'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/backend/base.rb:230:in `block in load_file'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/backend/base.rb:230:in `load_file'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/backend/base.rb:18:in `block in load_translations'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/backend/base.rb:18:in `load_translations'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/backend/simple.rb:80:in `init_translations'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/backend/simple.rb:50:in `available_locales'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/config.rb:45:in `available_locales'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n/config.rb:51:in `available_locales_set'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n.rb:337:in `locale_available?'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n.rb:343:in `enforce_available_locales!'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.9/lib/i18n.rb:199:in `translate'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/actionview-6.1.3/lib/action_view/helpers/tags/translator.rb:15:in `translate'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/actionview-6.1.3/lib/action_view/helpers/tags/label.rb:21:in `translation'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/actionview-6.1.3/lib/action_view/helpers/tags/label.rb:79:in `render_component'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/actionview-6.1.3/lib/action_view/helpers/tags/label.rb:71:in `render'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/actionview-6.1.3/lib/action_view/helpers/form_helper.rb:1123:in `label'
     # /Users/dorianmariefr/.rvm/gems/jruby-9.2.14.0/gems/actionview-6.1.3/lib/action_view/helpers/form_helper.rb:2275:in `label'
     # ./lib/arbre/rails/forms.rb:30:in `proxy_call_to_form'
     # ./lib/arbre/rails/forms.rb:12:in `label'
     # ./spec/rails/integration/forms_spec.rb:73:in `block in form'
```

`#deep_merge` is defined via a refinement in i18n

https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/simple.rb#L22

```
using I18n::HashRefinements
```

See https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/core_ext/hash.rb

i18n works fine with jruby and has the `deep_merge` method, but arbre (or maybe action view) probably loads the Concurrent::Hash differently and the refinement is not applied.

See: https://github.com/activeadmin/arbre/pull/282

(sorry I wish I had the time to make a smaller reproduction case)

**Comment by headius** [comment] 2021-03-08 14:53
This should be fixed in JRuby 9.2.16.0, released last week. Duplicate of #6547.

**Closed by headius** 2021-03-08 14:53 UTC
