### ISSUE TITLE
Error running bundler to install gems

### ISSUE THREAD

**Issue by lephyrius** [jruby/jruby#4311] opened 2016-11-17 09:07 UTC
### Environment

 VERSION:  jruby 9.1.6.0 (2.3.1) 2016-11-09 fffffff OpenJDK 64-Bit Server VM 25.102-b14 on 1.8.0_102-cedar14-b14 +jit [linux-x86_64]
Heroku

### Expected Behavior
I ran the command `vendor/bundle/jruby/2.3.0/bin/bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment --no-clean`
To install my bundled gems.

### Actual Behavior
I got this error:

```
        Java::JavaLang::LinkageError: loader (instance of  org/jruby/util/OneShotClassLoader): attempted  duplicate class definition for name: "org/jruby/runtime/scopes/DynamicScope15"
        java.lang.ClassLoader.defineClass1(Native Method)
        java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        org.jruby.util.OneShotClassLoader.defineClass(OneShotClassLoader.java:17)
        org.jruby.runtime.scope.DynamicScopeGenerator.defineClass(DynamicScopeGenerator.java:313)
        org.jruby.runtime.scope.DynamicScopeGenerator.generate(DynamicScopeGenerator.java:258)
        org.jruby.parser.StaticScope.acquireConstructor(StaticScope.java:197)
        org.jruby.parser.StaticScope.construct(StaticScope.java:180)
        org.jruby.runtime.DynamicScope.newDynamicScope(DynamicScope.java:53)
        org.jruby.runtime.DynamicScope.newDynamicScope(DynamicScope.java:96)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.pre(MixedModeIRMethod.java:62)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:178)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.RubyClass.finvoke(RubyClass.java:531)
        org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1668)
        org.jruby.RubyKernel.send19(RubyKernel.java:1991)
        org.jruby.RubyKernel$INVOKER$s$send19.call(RubyKernel$INVOKER$s$send19.gen)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:109)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:95)
        org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:970)
        org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:69)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.RubyClass.finvoke(RubyClass.java:531)
        org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1668)
        org.jruby.RubyKernel.send19(RubyKernel.java:1991)
        org.jruby.RubyKernel$INVOKER$s$send19.call(RubyKernel$INVOKER$s$send19.gen)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:109)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:95)
        org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:970)
        org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:69)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
        org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
        org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
        org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
        org.jruby.runtime.Block.yield(Block.java:167)
        org.jruby.ext.zlib.RubyGzipFile.wrapBlock(RubyGzipFile.java:70)
        org.jruby.ext.zlib.RubyGzipFile.wrap19(RubyGzipFile.java:96)
        org.jruby.ext.zlib.RubyGzipFile$INVOKER$s$0$1$wrap19.call(RubyGzipFile$INVOKER$s$0$1$wrap19.gen)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)
        org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:171)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:333)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
        org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
        org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
        org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
        org.jruby.runtime.Block.yield(Block.java:167)
        org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:450)
        org.jruby.ir.instructions.YieldInstr.interpret(YieldInstr.java:83)
        org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:187)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:111)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:348)
        org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:173)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:333)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
        org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
        org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
        org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
        org.jruby.runtime.Block.yield(Block.java:167)
        org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:450)
        org.jruby.ir.instructions.YieldInstr.interpret(YieldInstr.java:83)
        org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:187)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:111)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:171)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:333)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
        org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
        org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
        org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
        org.jruby.runtime.Block.yield(Block.java:167)
        org.jruby.RubyIO.ensureYieldClose(RubyIO.java:1148)
        org.jruby.RubyIO.open(RubyIO.java:1141)
        org.jruby.RubyKernel.open19(RubyKernel.java:306)
        org.jruby.RubyKernel$INVOKER$s$0$3$open19.call(RubyKernel$INVOKER$s$0$3$open19.gen)
        org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:101)
        org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
        org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:109)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:95)
        org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
        org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:109)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:95)
        org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
        org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
        org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
        org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
        org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
        org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:69)
        org.jruby.runtime.Block.call(Block.java:126)
        org.jruby.RubyProc.call(RubyProc.java:324)
        org.jruby.RubyProc.call19(RubyProc.java:308)
        org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.invokeOther4:call(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:65)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.RUBY$method$apply_func$0(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:65)
        org.jruby.internal.runtime.methods.CompiledIRMethod.invokeExact(CompiledIRMethod.java:249)
        org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:115)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:198)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.invokeOther12:apply_func(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:60)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.RUBY$block$process_queue$2(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:60)
        org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
        org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:76)
        org.jruby.runtime.Block.yieldSpecific(Block.java:136)
        org.jruby.RubyKernel.loop(RubyKernel.java:1299)
        org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
        org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:139)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:145)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.invokeOther15:loop(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.RUBY$method$process_queue$0(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57)
        org.jruby.internal.runtime.methods.CompiledIRMethod.invokeExact(CompiledIRMethod.java:236)
        org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:106)
        org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)
        org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.invokeOther0:process_queue(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:29)
        tmp.build_689b99c9082c0caad302ef773b09d3c7.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bundler_minus_1_dot_13_dot_6.lib.bundler.worker.RUBY$block$initialize$1(/tmp/build_689b99c9082c0caad302ef773b09d3c7/vendor/bundle/jruby/2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:29)
        org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
        org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:67)
        org.jruby.runtime.Block.call(Block.java:126)
        org.jruby.RubyProc.call(RubyProc.java:324)
        org.jruby.RubyProc.call(RubyProc.java:249)
        org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
        java.lang.Thread.run(Thread.java:745)
```

**Comment by willemave** [comment] 2016-11-17 22:29
Yup, same, filed with bundler as well - https://github.com/bundler/bundler/issues/5182

**Comment by kares** [comment] 2016-11-18 05:29
its a JRuby bug introduced in 9.1.6. a work-around is either to downgrade to 9.1.5 (until 9.1.7 is out) or make sure Bundler does not run concurrently. closing as duplicate of #4285 ... has been fixed with https://github.com/jruby/jruby/commit/330e5ee25917511e40fafe1ac3ca8bdcec2ffcd5

**Closed by kares** 2016-11-18 05:29 UTC
