### ISSUE TITLE
Open3.open2e returns `Errno::ENOENT` in jRuby but runs fine on Ruby

### ISSUE THREAD

**Issue by abelsromero** [jruby/jruby#4943] opened 2018-01-05 22:57 UTC
### Environment
JRuby v 9.1.15.0
Run from IDE, no additional configurations.
Windows 7
Java 1.8.0_152

### Expected Behavior

* A script that runs a external command ([kindlegen](https://www.amazon.com/gp/feature.html?docId=1000765211)) using Open3.open2e should work on normal Ruby and jRuby.

### Actual Behavior

* The script works fine on Ruby 2.3.3, but fails when run through jRuby 9.1.15.0 showing `(Errno::ENOENT)`. I assume the error is related to not being able to find some find. is that so?
* Here is is a example project I created to reproduce the issue: https://github.com/abelsromero/jruby-open3-issue.
0. Clone the project and create a KINDLEGEN environment var pointing to the kindlegen file in the `files` directory.
1. Open cmd with Ruby available in PATH and go to the "files" directory.
2. Run "ruby Open3Ruby.rb" --> Script should complete, generating a file called "spine.mobi" in the same directory. If you see the script code, several "puts" show how the actual files involved exist and are available.
3. Open the project in IntelliJ. Run the class "RubyRunner". --> Execution will fail with message
```
C:\home\asalgadr\temp\jruby-open3-issue\.\files\kindlegen.exe
true
C:/home/asalgadr/temp/jruby-open3-issue/files/spine-kf8.epub
true
Exception in thread "main" org.jruby.exceptions.RaiseException: (Errno::ENOENT) C:\\home\\\asalgadr\\temp\\jruby-open3-issue\\.\\files\\kindlegen.exe -dont_append_source -c0 -o spine.mobi C:/home/asalgadr/temp/jruby-open3-issue/files/spine-kf8.epub
	at org.jruby.RubyProcess.spawn(org/jruby/RubyProcess.java:1569)
	at org.jruby.RubyKernel.spawn(org/jruby/RubyKernel.java:1511)
	at RUBY.popen_run(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jruby/open3_windows.rb:204)
	at RUBY.popen2e(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jruby/open3_windows.rb:199)
	at RUBY.<main>(<script>:26)
```
The first four lines are the puts that check that files involved are available.

**Comment by abelsromero** [comment] 2018-01-06 17:09
I updated the test project to support MacOS.
In MacOS the issue does not appear and the script runs fine on both shell (Ruby 2.4.x) and jRuby.

**Comment by headius** [comment] 2018-01-10 21:03
This is more fallout from Windows not getting the same subprocess love that unix platforms have gotten.

**Comment by abelsromero** [comment] 2018-01-11 07:28
> This is more fallout from Windows
Windows...not surprised  (╯°□°）╯︵ ┻━┻. 
But the thing is, isn't there absolutely nothing that can be done?
Even if the implementation is not 100% compliant with the original Ruby implementation, but at least allows executing an external process and get the output.

**Comment by headius** [comment] 2018-01-11 16:35
The issue is that the default implementation of Open3 wants to use lower-level IO and process APIs that don't work properly on Windows right now. So we have had to special-case Open3 methods on some platforms.

I'll look and see if we're just not special-casing this right.

**Comment by headius** [comment] 2018-01-11 17:03
Ok, so we only special-case popen3, probably because that was the most likely one for people to use. However, we should be able to special-case the others, since they're mostly subsets of popen3.

I've started a PR to improve our Windows patches to open3.

**Comment by abelsromero** [comment] 2018-01-12 08:25
> I've started a PR to improve our Windows patches to open3.

Many thanks! Let me know when is ready to test.

**Comment by headius** [comment] 2018-01-29 18:54
Link with #5018.

**Comment by headius** [comment] 2018-02-13 17:59
The childprocess gem does indeed contain a pretty solid FFI implementation of process logic for Windows. I think that's the path forward, maybe for 9.2.

**Comment by headius** [comment] 2021-04-06 22:57
This should be significantly improved by #6649, which gets the open3 library nearly green on Windows even without native processes. The specific issue reported here was resolved by properly passing a "script-like" string to sh or cmd.

**Closed by headius** 2021-04-06 22:57 UTC
Labels: core, windows
