### ISSUE TITLE
Delegate class ArgumentError

### ISSUE THREAD

**Issue by segiddins** [jruby/jruby#8146] opened 2024-03-07 05:32 UTC
This looks like a redux of https://github.com/jruby/jruby/issues/1370

**Environment Information**
  
Provide at least:
* JRuby version: 9.4
* Operating system and platform: `Darwin sr-71 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64`

Repro script:

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/inline'
require 'delegate'

gemfile do
  source "https://rubygems.org"
  gem 'sigstore_protobuf_specs'
end

class D < DelegateClass(Sigstore::TrustRoot::V1::TrustedRoot)
  def self.something
    new Sigstore::TrustRoot::V1::TrustedRoot.decode_json('{}')
  end
end

D.something
```

**Expected Behavior**

No error, neither truffleruby nor mri raise

**Actual Behavior**

```
ArgumentError: not delegated
        __getobj__ at /Users/segiddins/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/delegate.rb:405
  delegating_block at /Users/segiddins/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/delegate.rb:348
               new at org/jruby/RubyClass.java:897
            <main> at Untitled.rb:18
```

**Comment by enebo** [comment] 2024-03-07 15:42
@segiddins I see the backtrace showing 9.4.3.0 is erroring.  Is this also broken in 9.4.6.0?

**Comment by enebo** [comment] 2024-03-07 15:49
@segiddins Actually I see this happening with 9.4.6.0 as well using the release bits.

**Comment by enebo** [comment] 2024-03-07 16:00
Just went back to 9.4.0.0 and this has never worked in the 9.4 series.  I tried latest 9.3 and we get unrelated problem.

**Comment by headius** [comment] 2024-04-24 19:22
This is a peculiar thing to fail.

Unlike back in #1370, we no longer have our own custom logic for delegate. We just use the gem as-is, currently the 0.2.0 version of it. So it's unclear why we would behave differently.

**Comment by headius** [comment] 2024-04-24 19:39
Ok, it looks like part of the cause is that `Sigstore::TrustRoot::V1::TrustedRoot#initialize` is getting defined as a public method instead of private, which causes `Delegator` to try to wrap it and all heck breaks loose. So the question is why it's getting flipped to public in JRuby but not in other impls.

**Comment by headius** [comment] 2024-04-24 20:01
Ok this is a bug in the JRuby implementation of protobuf. When defining `initialize` methods in a JRuby extension, users currently need to explicitly set `visibility = Visibility.PRIVATE` or the method will be public. Normally this doesn't matter, but clearly it impacts this case.

A workaround would be to go through any classes being delegated and make sure their `initialize` methods are set to private. Doing that for `Sigstore::TrustRoot::V1::TrustedRoot#initialize` allows the script to run correctly:

```diff
diff --git a/blah.rb b/blah.rb
--- a/blah.rb	
+++ b/blah.rb	(date 1713988253713)
@@ -9,6 +9,8 @@
   gem 'sigstore_protobuf_specs'
 end
 
+Sigstore::TrustRoot::V1::TrustedRoot.send(:private, :initialize)
+
 class D < DelegateClass(Sigstore::TrustRoot::V1::TrustedRoot)
   def self.something
     new Sigstore::TrustRoot::V1::TrustedRoot.decode_json('{}')
```

This needs to be fixed in protobuf, but I recognize this is obviously a little error-prone so I've opened #8146 to discuss other ways to mitigate this (including a patch to `DelegateClass` itself to always ignore `#initialize` when delegating).

**Closed by headius** 2024-04-24 20:01 UTC

**Comment by headius** [comment] 2024-04-24 20:15
FYI here is where the annotation should have visibility set to private:

https://github.com/protocolbuffers/protobuf/blob/main/ruby/src/main/java/com/google/protobuf/jruby/RubyMessage.java#L89

Someone should file a bug with them or create a PR to fix it.

**Comment by headius** [comment] 2024-05-29 20:46
I'll be merging #8213 into master for JRuby 9.4.8.0 which will fix this without protobuf having to change anything.

@segiddins If you get a chance to test this against a jruby-head build next week that would be super great!
