### ISSUE TITLE
"Invalid extended option" error for legit `-X` options

### ISSUE THREAD

**Issue by alaz** [jruby/jruby#5091] opened 2018-03-17 15:57 UTC
JRuby version:

```
$ docker run --rm -it jruby:9-alpine jruby -v
jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a OpenJDK 64-Bit Server VM 25.151-b12 on 1.8.0_151-b12 +jit [linux-x86_64]
```

The list of valid `-X` options:

```
$ docker run --rm -it jruby:9-alpine jruby '-Xjit?'
jit.threshold=50
jit.max=4096
jit.maxsize=2000
jit.logging=false
jit.logging.verbose=false
jit.dumping=false
jit.logEvery=0
jit.exclude=
jit.debug=false
jit.background=true
jit.kernel=false
ir.jit.passes=null
jit.cache=true
jit.codeCache=null
```

And here it is an error when specifying any option:

```
$ docker run --rm -it jruby:9-alpine jruby -Xjit.max=16384 | head
expr: syntax error
jruby: invalid extended option jit.max=16384 (-X will list valid options)

Usage: jruby [switches] [--] [programfile] [arguments]
  -0[octal]         specify record separator (\0, if no argument)
  -a                autosplit mode with -n or -p (splits $_ into $F)
  -c                check syntax only
  -Cdirectory       cd to directory, before executing your script
  -d                set debugging flags (set $DEBUG to true)
  -e 'command'      one line of script. Several -e's allowed. Omit [programfile]

$ docker run --rm -it jruby:9-alpine jruby -Xjit.logging=true | head
expr: syntax error
jruby: invalid extended option jit.logging=true (-X will list valid options)

Usage: jruby [switches] [--] [programfile] [arguments]
  -0[octal]         specify record separator (\0, if no argument)
  -a                autosplit mode with -n or -p (splits $_ into $F)
  -c                check syntax only
  -Cdirectory       cd to directory, before executing your script
  -d                set debugging flags (set $DEBUG to true)
  -e 'command'      one line of script. Several -e's allowed. Omit [programfile]
```

**Comment by alaz** [comment] 2018-03-17 19:48
Oops, I was under impression the image is official indeed. If it's not, but claims so – isn't it a problem?

Thank you.

**Comment by BanzaiMan** [comment] 2018-03-17 23:52
Well, if Alpine's `expr` does not behave the way expect, perhaps that should be fixed, whether or not this Docker image is "official."

**Comment by headius** [comment] 2018-03-17 23:59
I hate to say it but I am thinking we should start pushing an official image with our releases. Issues like this that we can't fix directly will impact people disproportionately.

**Comment by alaz** [comment] 2018-03-18 07:05
Both 9.1.15 and 9.1.16 images inherit from the same Alpine 3.7.0 and `jruby` script in the former works fine.

The only change to the shell scripts in `bin` between 9.1.15 and 9.1.16 is this one b617d558bf1ec84a71caad4e6db8e554cb12787b and it was exactly about how `expr` is being used.

Which basically means that anyone who would try to pack JRuby 9.1.16 into Alpine will face the same issue.

**Comment by headius** [comment] 2018-03-19 15:36
@alaz Are you saying it worked ok in 9.1.15?

A workaround may be to install the native launcher (`gem install jruby-launcher`) since it uses standard C/++ to parse out these properties.

We'll need a patch for the bash launcher that doesn't regress the FreeBSD fix.

**Comment by alaz** [comment] 2018-03-19 15:47
@headius yes, 9.1.15 accepts arguments w/o problems:

```
$ docker run --rm jruby:9.1.15-alpine jruby -Xjit.max=16384 --version 
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 OpenJDK 64-Bit Server VM 25.151-b12 on 1.8.0_151-b12 +jit [linux-x86_64]
```

**Comment by headius** [comment] 2018-03-19 16:08
Reproduced locally.

**Comment by headius** [comment] 2018-03-19 16:42
This patch appears to work on both Darwin and Alpine for me. I'll test Ubuntu shortly.

```diff
diff --git a/bin/jruby.bash b/bin/jruby.bash
index 5c841fedb6..3b6dc0d775 100755
--- a/bin/jruby.bash
+++ b/bin/jruby.bash
@@ -20,6 +20,11 @@ case "`uname`" in
   MINGW*) jruby.exe "$@"; exit $?;;
 esac
 
+# ----- Determine how to call expr (jruby/jruby#5091) -------------------------
+if $(expr -- 1 \< 2 2>/dev/null) ; then
+  alias expr = "expr --"
+fi
+
 # ----- Verify and Set Required Environment Variables -------------------------
 if [ -z "$JAVA_VM" ]; then
   JAVA_VM=-client
@@ -244,7 +249,7 @@ do
      # Match -Xa.b.c=d to translate to -Da.b.c=d as a java option
      -X*)
         val=${1:2}
-        if expr -- "$val" : '.*[.]' > /dev/null; then
+        if expr "$val" : '.*[.]' > /dev/null; then
           java_args=("${java_args[@]}" "-Djruby.${val}")
         else
           ruby_args=("${ruby_args[@]}" "-X${val}")
```

**Comment by headius** [comment] 2018-03-19 17:06
The fix appears to work on Darwin, Ubuntu, and Alpine. I have committed it and it will be in 9.1.17.

**Closed by headius** 2018-03-19 17:06 UTC
