### ISSUE TITLE
Rails 6.1.2.x dynamic finders cause Java::JavaLang::ClassCastException

### ISSUE THREAD

**Issue by ryanfb** [jruby/jruby#6563] opened 2021-02-16 18:35 UTC
**Environment Information**
  
* JRuby version (`jruby -v`): `jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]`
* Operating system and platform: initially discovered on MacOS 10.13.6, but replicated on Travis under Ubuntu 18.04.5 LTS (Bionic), see below
* Application/framework version: Rails 6.1.2.1
* Code available at: https://github.com/sosol/sosol/tree/rails-6.1.2.1

**Expected Behavior**

* Dynamic Rails finder methods e.g. `find_by_custom_model_attribute()` should continue to work

**Actual Behavior**

* Dynamic Rails finder methods result in `Java::JavaLang::ClassCastException: org.jruby.ir.operands.TemporaryClosureVariable cannot be cast to org.jruby.ir.operands.DepthCloneable` ([full backtrace from Travis](https://travis-ci.com/github/sosol/sosol/jobs/483537961) under OpenJDK 8 [attached here](https://github.com/jruby/jruby/files/5990744/classcastexception.txt))

I was able to isolate this down to dynamic finders by running a single test and adding debug logging until I could pin it down. With e.g. [this change to use `where` instead](https://github.com/sosol/sosol/commit/3e71cdc31c9a87a34d19fd764c5fce966eeaf5d6), the single test I chose passes instead of resulting in `Java::JavaLang::ClassCastException` (single test invoked with `rails test test/unit/publication_test.rb:91`).

Exception occurs on both Rails 6.1.2.1 and Rails 6.1.2.

Exception does **not** occur under Rails 6.1.1 with nothing else changed: https://travis-ci.com/github/sosol/sosol/builds/217275737

I also expanded tests from OpenJDK 8 up through OpenJDK 15 to verify that it's not related to the older JVM with Rails 6.1.2.1: https://travis-ci.com/github/sosol/sosol/builds/217273487

Only difference between the two is the Rails version (+ dependencies): https://github.com/sosol/sosol/compare/rails-6.1.2.1...rails-6.1.1

Please let me know if you think I should file a regression on Rails or whichever `action/active*` gem change is responsible instead of or in addition to here.

**Comment by ryanfb** [comment] 2021-02-16 20:56
One last note, for the [example workaround above](https://github.com/sosol/sosol/commit/3e71cdc31c9a87a34d19fd764c5fce966eeaf5d6): I just tried the non-dynamic `find_by` method for the same attribute, and to my surprise it also results in the same `Java::JavaLang::ClassCastException`. So in summary:

* Broken: `DDBIdentifier.find_by_publication_id(self.publication.id)`
* Broken: `DDBIdentifier.find_by(publication_id: self.publication.id)`
* Works: `DDBIdentifier.where(publication_id: self.publication.id).limit(1).first`

**Comment by headius** [comment] 2021-02-17 04:28
Woah, that's not good! I think you will want to see this one @enebo!

The exception here is being raised in our compiler while building instructions for our interpreter. This is probably some peculiar syntax or gap in behavior that is not being tested.

If you can narrow this down to a specific line it would be a great help to us. You may be able to get better Ruby line numbers by passing `-Xjit.threshold=0` to JRuby, which will force it to compile everything (or everything it is able to compile, anyway).

We will definitely look into fixing this for the next release. Thank you for the report!

**Comment by ryanfb** [comment] 2021-02-17 16:17
Thanks for the fast response! It looks like setting `-Xjit.threshold=0` pushes the backtrace back out from gems to the culprit `find_by` line in my app ([example backtrace attached here](https://github.com/jruby/jruby/files/5996940/xjitthreshold0.txt)). 

Without it set, the last Ruby line in the backtrace seems to be here in ActiveSupport: https://github.com/rails/rails/blob/v6.1.2.1/activesupport/lib/active_support/callbacks.rb#L427

Looking at the [blame alone](https://github.com/rails/rails/blame/v6.1.2.1/activesupport/lib/active_support/callbacks.rb#L427), it seems like that line is unlikely to be the sole culprit. And in fact, checking between Rails v6.1.1 and v6.1.2.1, the ActiveSupport `callbacks.rb` file hasn't changed at all. ActiveSupport's `instrumenter.rb` and `notifications.rb` are also in the original backtrace and are unchanged between the two releases.

For convenience, here's the diff for Rails v6.1.1 and v6.1.2: https://github.com/rails/rails/compare/v6.1.1...v6.1.2

I'll see if I can add some more debug output inside my local copy of the Rails gem(s) to try to pin down where it's happening more closely.

**Comment by ryanfb** [comment] 2021-02-17 17:15
Wasn't able to get any closer to figuring out what introduced the regression with debug statements alone, but here's a full set of test logs with `-Xjit.threshold=0` enabled since it seems like the amount and location of backtrace output for each exception varies: https://travis-ci.com/github/sosol/sosol/builds/217390816

**Comment by enebo** [comment] 2021-02-17 17:30
Ok this is pretty wild.  There are two possible kinds of code which could trigger this:

  1. define_method(:something) { |d| super }
  2. def something(d); proc { super }.call; end

I will try and see if I can make a simple case fail but the gist of what is happening...we see a zsuper (arg-less super) and then we try and figure out what variables should be passed to it (in both cases above it should be 'd').  In our code we think we found the proper parent scope and the we build an explicit super(d).  The 'd' itself internally needs to know the 'd' is n levels above so we adjust the depth to account for that.

The actual problem is that instead of finding a scoped variable (e.g. 'd') we find a temporary one.  Temporary variables are not visible between scopes.

Until we figure this out if you can find the zsuper in question you can maybe change to a super with args (via your code or monkey path).   Once we get a reproduction we can put a fix for this into 9.2.15.0.

**Comment by enebo** [comment] 2021-02-17 17:34
@ryanfb based on your backtrace I am wondering what:

```ruby
target.send(method, *arguments, &block)
```
target + method is.  I will make an educated guess the first time this send it performed it is to a method with a zsuper shown in my last comment.  We lazily build methods at the time they are first called.   This is probably that point.

**Comment by ryanfb** [comment] 2021-02-17 18:03
@enebo thanks for the lead! With that info, I was able to isolate it down to these lines:

* https://github.com/rails/rails/blob/v6.1.2.1/activerecord/lib/active_record/core.rb#L351
* https://github.com/rails/rails/blob/v6.1.2.1/activerecord/lib/active_record/core.rb#L364

If I change both of those two instances from arg-less supers to `super(*args)`, I don't get the exception and my test suite passes.

Here's the Rails/ActiveRecord commit which introduced the regression: https://github.com/rails/rails/commit/f1b923b5d83b229738d2cb944498db832818d29c

**Comment by enebo** [comment] 2021-02-17 18:59
@ryanfb ah neat.  So we expose a problem from a feature we have (and shouldn't have it).  Our zsuper code in JRuby goes beyond what MRI does.  Effectively, the code saves all closure scopes as possible boundaries for a define_method back to a hard scope (e.g. method/module scope).  If it turns out that one of those closures are the real method boundary (e.g. define_method case) it will jump to a section representing the parameters to that particular closure and we will use those variables for the zsuper.  MRI (C Ruby) does not allow us to use zsuper within define_method.  Although what we do is very clever it is not what Ruby does.

An illustration of part of the problems with supporting this feature:

```ruby
class A
  def foo(one, two)
    puts one, two
  end
end


class B < A
  define_method(:foo) do |(a, b), c|
    a = 1
    super
  end
end

B.new.foo([2,3], 4)

```

If we run this with JRuby we hit the destructuring code and expose a bug in our feature which causes the class cast.  In C Ruby:

```text
Traceback (most recent call last):
	1: from zsuper1.rb:17:in `<main>'
zsuper1.rb:13:in `block in <class:B>': implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly. (RuntimeError)
```

Although we figured out a clever way of making zsuper work within define_method you can also see how out of control this could get.  In the above example, A#foo requires 2 arguments which would be an array of (a, b) [2, 3] (or possibly some object doing to_ary. if first caller of foo was doing something weirder)  The snippet though changes the value of a.  That would mean the original parameter value which led to being destructured would need to realize it has been modified and then pass [1, 3].  To support this we would need to understand how to reverse this destructuring.

So the solution to this issue will be to match MRI in issuing an error for define_method case while and not building up this list of scope variables bindings (since we don't need them).

**Comment by headius** [comment] 2021-02-18 18:35
Filed again as #6566 so this is affecting multiple people now.

@enebo We may want to prioritize getting a 9.2.15 out soonish. Is there any way this failure can be worked around, perhaps a monkey patch to alter the structure of the offending code?

**Comment by enebo** [comment] 2021-02-18 20:42
@headius I agree early next week I think.  The monkey patch is to rewrite find_by.  The two references are above in @ryanfb comment.

**Comment by headius** [comment] 2021-02-18 21:04
@enebo After I land some work on master I will review open 9.2.15 issues and see what else can/should be included.

**Comment by enebo** [comment] 2021-02-19 22:25
I tested against AR unit tests using msql3 and saw no errors with that PR against tag  v6.1.2.1 of Rails.

**Closed** 2021-02-23 19:46 UTC

**Comment by redconfetti** [comment] 2021-05-05 18:32
I'm getting the following error with jRuby v9.2.17.0 with Rails v6.1.3.1

```
Java::JavaLang::ClassCastException (org.jruby.ir.operands.TemporaryClosureVariable cannot be cast to org.jruby.ir.operands.DepthCloneable):

org.jruby.ir.IRBuilder.adjustVariableDepth(IRBuilder.java:4069)
org.jruby.ir.IRBuilder.access$400(IRBuilder.java:87)
org.jruby.ir.IRBuilder$9.run(IRBuilder.java:4013)
org.jruby.ir.IRBuilder.receiveBreakException(IRBuilder.java:1035)
org.jruby.ir.IRBuilder.buildZSuperIfNest(IRBuilder.java:4040)
org.jruby.ir.IRBuilder.buildZSuper(IRBuilder.java:4053)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:510)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.build(IRBuilder.java:528)
org.jruby.ir.IRBuilder.buildReturn(IRBuilder.java:3702)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:490)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.buildIf(IRBuilder.java:2901)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:459)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.build(IRBuilder.java:528)
org.jruby.ir.IRBuilder.buildBlock(IRBuilder.java:959)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:425)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.build(IRBuilder.java:528)
org.jruby.ir.IRBuilder.buildIterInner(IRBuilder.java:2973)
org.jruby.ir.IRBuilder.buildIter(IRBuilder.java:2994)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:462)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.build(IRBuilder.java:528)
org.jruby.ir.IRBuilder.setupCallClosure(IRBuilder.java:2761)
org.jruby.ir.IRBuilder.buildCall(IRBuilder.java:1130)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:427)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.buildLocalAsgn(IRBuilder.java:3005)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:465)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.build(IRBuilder.java:528)
org.jruby.ir.IRBuilder.buildBlock(IRBuilder.java:959)
org.jruby.ir.IRBuilder.buildOperand(IRBuilder.java:425)
org.jruby.ir.IRBuilder.build(IRBuilder.java:540)
org.jruby.ir.IRBuilder.build(IRBuilder.java:528)
org.jruby.ir.IRBuilder.defineMethodInner(IRBuilder.java:2082)
org.jruby.ir.IRMethod.buildMethodImpl(IRMethod.java:101)
org.jruby.ir.IRMethod.lazilyAcquireInterpreterContext(IRMethod.java:92)
org.jruby.internal.runtime.AbstractIRMethod.retrieveInterpreterContext(AbstractIRMethod.java:98)
org.jruby.internal.runtime.AbstractIRMethod.ensureInstrsReady(AbstractIRMethod.java:90)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:143)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:121)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:108)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:141)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:121)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:108)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:141)
var.lib.tomcats.calcentral.webapps.ROOT.WEB_minus_INF.lib.cache.cached_feed.invokeOther1:get_feed_internal(/var/lib/tomcats/calcentral/webapps/ROOT/WEB-INF/lib/cache/cached_feed.rb:16)
```

I thought this was resolved in v9.2.15?

**Comment by enebo** [comment] 2021-05-05 19:05
@redconfetti Are you positive you are loading jruby 9.2.17.0 or perhaps the jar.  I am checked out on the 9.2.17.0 tag and the line numbers from buildZsuperIfNest is wrong and that method has no call to receiveBreakException anymore.

**Comment by redconfetti** [comment] 2021-05-05 19:06
It's unfortunately happening in our staging servers, not locally. Perhaps there is something wrong there. I'll continue to investigate. Just raising a yellow flag for now.

**Comment by enebo** [comment] 2021-05-05 19:11
@redconfetti sure thing.  Hopefully it is something simple and I never put it past myself to make a mistake :)
