### ISSUE TITLE
require "irb" broken under Windows 

### ISSUE THREAD

**Issue by rovf** [jruby/jruby#7587] opened 2023-01-20 09:16 UTC
Command to reproduce the error:

    java -Xmx4G -cp jruby-complete-9.4.0.0.jar org.jruby.Main  -e 'require "irb"'

This produces the output:

io/console not supported; tty will not be manipulated
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fiddle/jruby.rb:158: warning: assigned but unused variable - size
Ignoring binding_of_caller-0.8.0 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.8.0
Ignoring debug_inspector-0.0.3 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.3
**LoadError: no such file to load -- win32api**
Did you mean?  Win32API
          require at org/jruby/RubyKernel.java:1057
          require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
  <class:Windows> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/reline/windows.rb:56
           <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/reline/windows.rb:3
          require at org/jruby/RubyKernel.java:1057
          require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
           <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/reline.rb:567
          require at org/jruby/RubyKernel.java:1057
          require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
           <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:13
          require at org/jruby/RubyKernel.java:1057
          require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85
           <main> at -e:1
... 14 levels...

**Environment Information**
  
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f Java HotSpot(TM) 64-Bit Server VM 25.241-b07 on 1.8.0_241-b07 +jit
 [x86_64-mswin32]

Windows 10

**Comment by mohits** [comment] 2023-01-20 14:04
I think this is related?
https://github.com/jruby/jruby/issues/7547#issuecomment-1384517817

**Comment by enebo** [comment] 2023-01-20 15:04
Yeah duplicate of #7547.  9.4.1.0 will have a fix but I still have not figured out why an installation of JRuby works to start irb (require will fail for an install as well as jruby-complete so it is a mystery what is happening).

**Comment by ahorek** [comment] 2023-01-22 00:10
is there a conflict between https://github.com/ruby/reline/pull/484 and https://github.com/jruby/jruby/commit/e9d8a73bc2b58dbef52a0b81bbe6fd76fd8f91ee ?

**Comment by enebo** [comment] 2023-01-23 22:25
@ahorek  yeah. I added a comment recommending not applying the fix since we already picked the opposite naming :)

**Closed by enebo** 2023-01-23 22:25 UTC
