### ISSUE TITLE
File locks do not release while JRuby process open in 9k-pre2

### ISSUE THREAD

**Issue by florf** [jruby/jruby#2958] opened 2015-05-19 13:40 UTC
While using both JRuby and JIRB to test and develop code, I have found that the process holds file locks on all source files currently loaded via a `require` statement.  The file locks are not released until the process is terminated; both Windows itself and gEdit 2.30.1 report that the file cannot be written to until the process terminates.

For reference, the output from `jruby -v` produces (formatted for readability):

```
jruby 9.0.0.0.pre2 (2.2.2) 2015-04-28 2755ae0 Java HotSpot(TM) 
  64-Bit Server VM 25.31-b07 on 1.8.0_31-b13 +jit [Windows 7-amd64]
```

**Comment by headius** [comment] 2015-05-28 22:51
That is surprising...I don't think that we lock required files at all.

**Comment by chrisseaton** [comment] 2015-05-28 22:54
I remember looking at this for Truffle - I think that MRI at least locks files that have DATA in them. There is a spec for that https://github.com/jruby/jruby/blob/master/spec/ruby/language/predefined/data_spec.rb#L26-L42.

**Comment by headius** [comment] 2015-05-28 22:55
I just confirmed, from ExternalScript on down, that we don't actively lock any files on load.

We do, however, keep the file open for as long as we're in the process of executing it. If the file never reaches its end (i.e. if it starts up a long-running app and blocks)

`DATA` should only be loaded from the target script; if it's a required or loaded file, any `__END__`  sections are simply dropped.

**Comment by headius** [comment] 2015-06-02 16:43
@florf This is not currently a high priority, since we do not actively lock these files and we *should* be closing them after they're done loading. If you can confirm we're holding an actual filesystem-level lock, or keeping files open longer than we should, it would help us have a goal to work toward.

**Comment by florf** [comment] 2015-06-08 13:34
It could be that the required files being held open were causing the permission issues.  That does make more sense now that I think about it.  I'll have to do more testing to be sure.

Insofar, IRB seems to be the one causing issues.

**Comment by headius** [comment] 2015-07-03 15:12
I think @enebo is looking at this for RC2.

**Comment by enebo** [comment] 2015-07-03 15:18
I am nearly positive this is a dupe of #3055.  Closing as duplicate only because I already close the other as fixed.

**Closed by enebo** 2015-07-03 15:18 UTC
Labels: windows
