### ISSUE TITLE
YAML.load significant performance degradation when JSON string is included

### ISSUE THREAD

**Issue by vassilios** [jruby/jruby#5098] opened 2018-03-21 01:10 UTC
### Environment

* JRuby version
jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-internal-b15 +jit [linux-x86_64]
* Operating system and platform
Linux ip-172-30-3-223 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior

On jruby 9.1.5.0, 9.1.6.0 and 9.1.7.0, the following gist [test_yaml.rb](https://gist.github.com/vassilios/ddbbb499aaa0d4cdd241d6c7e06f08eb) completes in a few milliseconds.

```
$ jruby test_yaml.rb 
9.1.5.0
  0.240000   0.020000   0.260000 (  0.070586)

$ jruby test_yaml.rb 
9.1.6.0
  0.260000   0.010000   0.270000 (  0.075033)

$ jruby test_yaml.rb 
9.1.7.0
  0.280000   0.000000   0.280000 (  0.080087)
```

### Actual Behavior
The same gist executed with jruby 9.1.8.0 takes more than 10 seconds.
```
$ jruby test_yaml.rb 
9.1.8.0
 11.570000   0.010000  11.580000 ( 11.411209)
```
Same thing happens for jruby 9.1.16.0
```
$ jruby test_yaml.rb 
9.1.16.0
 11.830000   0.010000  11.840000 ( 11.437966)
```

**Comment by headius** [comment] 2018-03-26 16:38
Good find! Investigating.

**Comment by headius** [comment] 2018-03-26 16:47
SnakeYAML was updated in October, so if that's the culprit it would have first manifested in JRuby 9.1.14.

A quick sampled profile shows only one big hot spot, a method in SnakeYAML: `ScannerImpl.scanFlowScalarNonSpaces`. On this profile, 650 out of 867 ticks were during this method's execution.

**Comment by headius** [comment] 2018-03-26 16:57
Ah I see you mention it being slow in 9.1.8.0. I'll start looking there for a possible culprit.

**Comment by headius** [comment] 2018-03-26 17:25
I traced it to the Psych update in b0487b4b1088e33ecef1f8321b0a14729ffba268. Continuing.

**Comment by headius** [comment] 2018-03-26 17:30
The only substantive commit in Psych 2.2.3 was ruby/psych@fc55b92ed76836ded814149628828bc424bd3af1, which updated SnakeYAML from 1.17 to 1.18. So we're back to that theory again.

**Comment by headius** [comment] 2018-03-26 17:49
Manually downgrading SnakeYAML from 1.18 to 1.17 does not resolve the issue, so we're back to Psych being the culprit.

**Comment by vassilios** [comment] 2018-03-26 18:05
@headius thanks for looking into this and keeping me up-to-date. Hope it gets resolved.

**Comment by headius** [comment] 2018-03-26 18:07
Ok ignore what I said earlier...after changing all references to "1.18" and manually downgrading SnakeYAML, performance does return to normal. I will check if latest SnakeYAML fixes it and if not I'll file an issue with them.

**Comment by headius** [comment] 2018-03-26 19:07
The Psych update is on hold until we can get a fix for https://bitbucket.org/asomov/snakeyaml/issues/401/jrubys-psych-library-uses-markgetindex

Hopefully it won't take long.

**Comment by headius** [comment] 2018-03-26 19:36
Ok, so the bad news is that SnakeYAML 1.19 does not appear to fix the issue, so we'll have to wait for 1.21 that fixes the issue I filed so we can release a new Psych.

**Comment by headius** [comment] 2018-03-26 21:25
Short term workaround: you *may* be able to install an older Psych and use it. If you are using Bundler, adding an older Psych version to e.g. `Gemfile` may do the trick.

For a more permanent solution, you can replace lib/ruby/stdlib/psych* with the contents of the gem's lib dir. There may be some oddities matching versions with the gemspec, so that may need to be replaced under lib/ruby/gems/shared/specifications/default.

**Comment by vassilios** [comment] 2018-03-27 00:58
I can confirm that the workaround of downgrading the psych gem works. 
Here's what I did.

I added psych version 2.2.2 in my Gemfile.
```
source 'https://rubygems.org'
gem 'psych', '2.2.2'
```

And added those two lines at the top of the gist.
```
require 'rubygems'
require 'bundler/setup'
```
The output after those changes showed no degradation:
```
$ jruby -S test_yaml.rb 
9.1.16.0
  0.220000   0.010000   0.230000 (  0.062216)
```

**Comment by asomov** [comment] 2018-04-04 19:51
If you test SnakeYAML 1.21-SNAPSHOT and it is quick enough,  we can release it immediately, otherwise it will be released in August 2018.
The performance penalty is most probably caused by more complex Unicode processing. SnakeYAML now properly works with characters above 65536 (Java chars were designed for 2 bytes per char)

**Comment by vassilios** [comment] 2018-04-05 14:54
@asomov thank you. @headius would you be testing the SnakeYAML 1.21-SNAPSHOT ? thx

**Comment by headius** [comment] 2018-04-11 23:58
@asomov @vassilios Testing now!

**Comment by headius** [comment] 2018-04-12 00:07
@asomov @vassilios The 1.21 version of SnakeYAML does indeed fix the performance issue, and requires only minor tweaks to the Psych code. Ship it! 👍

**Comment by vassilios** [comment] 2018-04-12 00:10
@headius thank you for testing it!

**Comment by asomov** [comment] 2018-04-13 06:58
1.21 released.
Please be aware that now [plain scalars are allowed in the flow context.](https://bitbucket.org/asomov/snakeyaml/issues/397/plain-scalars-with-colons-in-flow)
`{foo:bar}` -> `foo:bar -> null`

**Comment by headius** [comment] 2018-04-16 15:06
@asomov Thank you!

**Comment by asomov** [comment] 2018-04-16 15:31
Is not yet solved ?

**Comment by headius** [comment] 2018-04-16 16:29
@asomov This issue should not be closed until we have an updated Psych pushed for JRuby 9.1.17. It closed automatically (incorrectly) when I made my commit to Psych.

**Comment by headius** [comment] 2018-04-16 16:30
This is going to get pushed post-9.1.17 unless we can address the failures from updating Psych and its tests. I got both Psych test failures and YAML failures in the existing ruby specs.

**Comment by headius** [comment] 2018-04-16 16:36
@asomov Your comment about plain scalars...that may be the cause of some failures. I'm pushing a JRuby branch shortly for #5142 that should show all the new failures. Some appear to be related to scalars.

**Comment by headius** [comment] 2018-04-16 16:47
I have pushed branch [`psych_3_update`](https://github.com/jruby/jruby/tree/psych_3_update) which updates to Psych 3.0.3 that includes the above fixes. We'll need to address the failures before we commit this to a release.

**Comment by headius** [comment] 2018-09-19 16:30
#365 is merged and I believe everything is in place for a Psych release. Waiting to hear from @hsbt about that.

**Comment by hsbt** [comment] 2018-09-27 09:53
I will release it in this weekend.

**Closed** 2018-10-22 19:12 UTC
Labels: performance, regression
