### ISSUE TITLE
Puma incompatible after JRuby 9.1.14.0

### ISSUE THREAD

**Issue by yeryer** [jruby/jruby#5133] opened 2018-04-10 14:35 UTC
### Environment
jruby 9.1.14.0 (2.3.3) 2017-11-08 2176f24 Java HotSpot(TM) 64-Bit Server VM 25.152-b16 on 1.8.0_152-b16 +jit [mswin32-x86_64]
Windows 10
Rails 4.2.9
Puma 3.11.3-java
Rubymine 2018.1
Ruby arguments:  -J-Xmx4096m -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift)

### Actual Behavior
Puma runs fine on the above platform but whenever we try upgrading to 9.1.15 or 9.1.16 we are only able to get a couple successful file downloads before getting very frequent
net::ERR_INVALID_CHUNKED_ENCODING
and
net::ERR_CONTENT_LENGTH_MISMATCH
errors.

I've tried various puma versions and it doesn't matter--only JRuby   build 9.1.14 and earlier seem to work on windows.  I've also tried 5 different windows machines and various Java versions but the JRuby version is the only variable that seems to change things.

**Comment by enebo** [comment] 2018-04-10 16:06
@yeryer Interesting.  I just did scp from windows bash shell this morning and got corrupted mac errors (win10).  I was weirded out that a winbuntu -> fedora ssh connection would complain.  I wonder if MS has any info on this.  We really need to isolate what is wrong here since we changed since 9.1.14 because of other changes by other OSes.  Quite the sticky web.

If you have time perhaps you can make a simpler net/http script using https.  I would think you would see similar errors.  The smaller the better for us for debugging.

**Comment by headius** [comment] 2018-04-16 15:06
@yeryer Without a way to reproduce this I think we need your help. Since it regressed between 9.1.14 and 9.1.15, it should be possible to bisect those versions and pinpoint a single responsible commit.

I'm going to bump this to 9.2, since we'd like to get 9.1.17 out very soon, and 9.2 will follow closely after.

**Comment by headius** [comment] 2018-09-19 16:31
No follow-up, and people have been using Puma on JRuby versions higher than 9.1.14. Closing.

**Closed by headius** 2018-09-19 16:31 UTC
Labels: regression, windows
