### ISSUE TITLE
Incorrect binding.source_location line with -Xcompile.mode=JIT (confuses pry)

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby#8445] opened 2024-11-22 08:44 UTC
Hey!

I randomly bumped into this one while testing a new release of [pry-debugger-jruby](https://rubygems.org/gems/pry-debugger-jruby).

It seems `binding.source_location` is off by a few lines when `-Xcompile.mode=JIT` is being used, which confuses [pry](https://rubygems.org/gems/pry) since it uses that to display source code.

Example used below:

```ruby
puts RUBY_DESCRIPTION

# require 'bundler/inline'

# gemfile do
#   source 'https://rubygems.org'

#   gem 'pry'
# end

# require 'pry'

def some_method
  puts binding.source_location
  # binding.pry
  Hello.new.potato
  puts 'Hello, World!'
end

class Hello
  def potato
    puts "potato1"
    puts "potato2"
  end
end

some_method
```

(You can comment out the pry parts to see how pry misbehaves)

**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

`jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 23.0.1+8-FR on 23.0.1+8-FR +jit [x86_64-linux]`
`jruby -Xcompile.mode=JIT --debug test/test.rb`

* Operating system and platform (e.g. `uname -a`)

`Linux 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Expected Behavior**

```
$ jruby -Xcompile.mode=OFF --debug test/test.rb
jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 23.0.1+8-FR on 23.0.1+8-FR [x86_64-linux]
test/test.rb
14
potato1
potato2
Hello, World!
```

Correct line is shown (14)

**Actual Behavior**

```
$ jruby -Xcompile.mode=JIT --debug test/test.rb
jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 23.0.1+8-FR on 23.0.1+8-FR +jit [x86_64-linux]
test/test.rb
21
potato1
potato2
Hello, World!
```

Incorrect line is shown (21)

---

As always, thanks for the amazing work on JRuby, and very looking forward to the next release :pray: 

(Also, this doesn't block me at all -- just a see something, say something kinda report! :D )

**Comment by headius** [comment] 2024-12-04 04:59
This is not surprising. The JIT code that JRuby outputs does not maintain a Ruby stack trace, so when bindings are captured in a given scope (as Pry does) the file and line numbers will be off for those frames. This, and the use of `Binding.of_caller` type tricks, means you must run JRuby in the interpreter only, and probably in a debug mode that enables more tracing. It's very difficult to support the set of features that Pry needs in a JVM bytecode JIT like ours.

The --debug flag normally turns off JIT for this reason, but it can be turned back on by other flags.

This isn't really a bug but a known limitation.

**Comment by ivoanjo** [comment] 2024-12-04 09:44
> The --debug flag normally turns off JIT for this reason, but it can be turned back on by other flags.
>
> This isn't really a bug but a known limitation.

Got it! I got tripped here since I got JRuby one a docker image that had this on by default (I don't remember which... oops) and that's what sent me a bit in circles, because I was running `jruby --debug test/test.rb` but seeing the buggy behavior.

It took me a while to spot that the description mentioned JIT, and then be able to reproduce outside that docker image.

I guess I'll try asking the pry folks if they want to add a warning when pry is used with JIT enabled, since it's going to be confusing/misleading.

**Comment by headius** [comment] 2024-12-04 13:27
A warning is a good idea... perhaps they could have some test code they run to determine capabilities in general, rather than just checking our JIT mode (because what it can support may change over time).

I'm going to close this because there's no plans to support full introspection without debug flags on.

**Closed by headius** 2024-12-04 13:27 UTC

**Comment by ivoanjo** [comment] 2024-12-08 05:39
As an update on this one, I was trying to add a check for this to pry-debugger-jruby, and then suggest to upstream pry that they did something like it as well.

But I'm having trouble detecting when the "may not give correct results" config is running. I was hoping to create a check for it by looking at the JRuby config, rather than a more brittle "hey, check the source_location for some random code and see if it matches an expected result".

In particular, I'm getting a somewhat surprising result that combining `--dev` with `-Xcompile.mode=JIT` seems to make the issue go away + JRuby still claims to be in jit mode.

Thus just testing for "hey if you're in JIT mode you can expect incorrect results" doesn't seem to be enough :eyes: 

```
$ jruby -Xcompile.mode=JIT test/test.rb 
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 23.0.1+8-FR on 23.0.1+8-FR +jit [x86_64-linux]
JIT
["test/test.rb", 9]

$ JRUBY_OPTS=--dev jruby -Xcompile.mode=JIT test/test.rb 
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 23.0.1+8-FR on 23.0.1+8-FR +jit [x86_64-linux]
JIT
["test/test.rb", 5]

$ cat test/test.rb 
puts RUBY_DESCRIPTION
puts org.jruby.util.cli.Options::COMPILE_MODE.load

def some_method
  pp binding.source_location
end

class Hello
  def potato = nil
end

some_method
```

**Comment by headius** [comment] 2024-12-11 00:06
> --dev with -Xcompile.mode=JIT seems to make the issue go away + JRuby still claims to be in jit mode

I can't reproduce this, with any order of arguments and env:

```
[] jruby $ jruby blah.rb                                       
jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-12-11 963f994cde OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
JIT
["blah.rb", 9]
[] jruby $ jruby --dev blah.rb                                 
jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-12-11 963f994cde OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 [arm64-darwin]
OFF
["blah.rb", 5]
[] jruby $ jruby --dev -Xcompile.mode=JIT blah.rb              
jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-12-11 963f994cde OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
JIT
["blah.rb", 9]
[] jruby $ jruby -Xcompile.mode=JIT --dev blah.rb
jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-12-11 963f994cde OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
JIT
["blah.rb", 9]
[] jruby $ JRUBY_OPTS=-Xcompile.mode=JIT jruby --dev blah.rb
jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-12-11 963f994cde OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
JIT
["blah.rb", 9]
[] jruby $ JRUBY_OPTS=--dev jruby -Xcompile.mode=JIT blah.rb
jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-12-11 963f994cde OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
JIT
["blah.rb", 9]
```

It is interesting that your output does claim it is in JIT mode, but then runs correctly like it is not. Could you pass `-Xjit.logging` to see if it's actually compiling the script?

**Comment by ivoanjo** [comment] 2024-12-27 11:42
Happy holidays! Sorry for the late response.

I think I've spotted what I believe may be the difference here! I'm using the native jruby launcher, and I'm betting you're using the shell script version.

```
$ ldd /home/ivo.anjo/.rvm/rubies/jruby-9.4.9.0/bin/jruby
	linux-vdso.so.1 (0x00007ffc3dbea000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007492c3a00000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007492c3dc2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007492c3600000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007492c3cdb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007492c3e15000)
$ md5sum /home/ivo.anjo/.rvm/rubies/jruby-9.4.9.0/bin/jruby
7cee5d38a4d544edef86d7ad034aea36  /home/ivo.anjo/.rvm/rubies/jruby-9.4.9.0/bin/jruby
```

If I copy my own native launcher into the latest jruby docker image (which seems to use the shell launcher) here's what I see:

```
$ docker run --network=host -ti -v `pwd`:/working jruby:9.4.9.0-jre21 /bin/bash
Unable to find image 'jruby:9.4.9.0-jre21' locally
9.4.9.0-jre21: Pulling from library/jruby
Digest: sha256:3c57a4c2ec52728f89113540bdf35d94d7171e35cb4332ebe69c5ed0d887f381
Status: Downloaded newer image for jruby:9.4.9.0-jre21

root@rubyshade:/# jruby working/blah.rb 
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 21.0.5+11-LTS on 21.0.5+11-LTS +jit [x86_64-linux]
JIT
["working/blah.rb", 9]

root@rubyshade:/# jruby -Xjit.logging --dev -Xcompile.mode=JIT  working/blah.rb
2024-12-27T11:32:10.067Z [main] INFO Ruby : done compiling target script: working/blah.rb
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 21.0.5+11-LTS on 21.0.5+11-LTS +jit [x86_64-linux]
JIT
2024-12-27T11:32:10.222Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: Gem::Version canonical_segments at /opt/jruby/lib/ruby/stdlib/rubygems/version.rb:381
2024-12-27T11:32:10.313Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: #<Class:0x4c3c3d33> find_type at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:75
2024-12-27T11:32:10.317Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: #<Class:0x4c3c3d33> custom_typedefs at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:38
2024-12-27T11:32:10.320Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: #<Class:0x4c3c3d33> __typedef at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:61
2024-12-27T11:32:10.324Z [Ruby-0-JIT-1] INFO JITCompiler : block done jitting: FFI each_line &|line|2 at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:207
2024-12-27T11:32:10.345Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: Gem::Platform to_a at /opt/jruby/lib/ruby/stdlib/rubygems/platform.rb:129
2024-12-27T11:32:10.354Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: Gem::Specification platform at /opt/jruby/lib/ruby/stdlib/rubygems/specification.rb:2227
["working/blah.rb", 9]

root@rubyshade:/# which jruby
/opt/jruby/bin/jruby

root@rubyshade:/# cat /opt/jruby/bin/jruby
#!/bin/sh
# shellcheck disable=1007
# -----------------------------------------------------------------------------
# jruby.bash - Start Script for the JRuby interpreter
# -----------------------------------------------------------------------------
...

# ... here I copy my own jruby binary launcher into the docker image...

root@rubyshade:/working# cp ./jruby /opt/jruby/bin/binjruby

root@rubyshade:/# binjruby -Xjit.logging --dev -Xcompile.mode=JIT  working/blah.rb
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 21.0.5+11-LTS on 21.0.5+11-LTS +jit [x86_64-linux]
JIT
2024-12-27T11:33:58.593Z [Ruby-0-JIT-1] INFO JITCompiler : done building: Gem::Version canonical_segments at /opt/jruby/lib/ruby/stdlib/rubygems/version.rb:381
2024-12-27T11:33:58.703Z [Ruby-0-JIT-1] INFO JITCompiler : done building: #<Class:0x8c7d598> find_type at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:75
2024-12-27T11:33:58.704Z [Ruby-0-JIT-1] INFO JITCompiler : done building: #<Class:0x8c7d598> custom_typedefs at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:38
2024-12-27T11:33:58.704Z [Ruby-0-JIT-1] INFO JITCompiler : done building: #<Class:0x8c7d598> __typedef at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:61
2024-12-27T11:33:58.709Z [Ruby-0-JIT-1] INFO JITCompiler : done building: FFI at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:207
2024-12-27T11:33:58.719Z [Ruby-0-JIT-1] INFO JITCompiler : done building: Gem::Platform to_a at /opt/jruby/lib/ruby/stdlib/rubygems/platform.rb:129
2024-12-27T11:33:58.726Z [Ruby-0-JIT-1] INFO JITCompiler : done building: Gem::Specification platform at /opt/jruby/lib/ruby/stdlib/rubygems/specification.rb:2227
["working/blah.rb", 5]

root@rubyshade:/# jruby -Xjit.logging --dev -Xcompile.mode=JIT  working/blah.rb
2024-12-27T11:34:06.061Z [main] INFO Ruby : done compiling target script: working/blah.rb
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 21.0.5+11-LTS on 21.0.5+11-LTS +jit [x86_64-linux]
JIT
2024-12-27T11:34:06.239Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: Gem::Version canonical_segments at /opt/jruby/lib/ruby/stdlib/rubygems/version.rb:381
2024-12-27T11:34:06.338Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: #<Class:0x4c3c3d33> find_type at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:75
2024-12-27T11:34:06.342Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: #<Class:0x4c3c3d33> custom_typedefs at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:38
2024-12-27T11:34:06.345Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: #<Class:0x4c3c3d33> __typedef at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:61
2024-12-27T11:34:06.351Z [Ruby-0-JIT-1] INFO JITCompiler : block done jitting: FFI each_line &|line|2 at /opt/jruby/lib/ruby/stdlib/ffi/types.rb:207
2024-12-27T11:34:06.380Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: Gem::Platform to_a at /opt/jruby/lib/ruby/stdlib/rubygems/platform.rb:129
2024-12-27T11:34:06.388Z [Ruby-0-JIT-1] INFO JITCompiler : method done jitting: Gem::Specification platform at /opt/jruby/lib/ruby/stdlib/rubygems/specification.rb:2227
["working/blah.rb", 9]
```

So it looks like when using the binary launcher, you can get into this "jruby claims jit but doesn't actually jit" mode. 

I guess this may warrant a reopen since it looks like a bug in the launcher? I'll update the topic as well.
