### ISSUE TITLE
Include bundler in JRuby distribution

### ISSUE THREAD

**Issue by mdekstrand** [jruby/jruby#1146] opened 2013-10-21 21:51 UTC
The JRuby distribution includes a few tools already, such as rake. It'd be very useful for at least some use cases for JRuby to also include bundler.

I'm using JRuby to bootstrap some projects (generally nanoc website builds) so that they can be fully run with nothing but a JDK. Right now, that bootstrap is:
1. Download jruby (either from jruby.org, or via Maven)
2. Use JRuby's `gem` to install bundler somewhere in the local directory
3. Use the freshly-installed `bundle` to install the rest of the project's dependencies from the `Gemfile`

If JRuby's binary distribution and `jruby-complete` contained Bundler, I could entirely eliminate step 2.

**Comment by kares** [comment] 2016-10-10 10:42
@Asmod4n except what would be the point if there's no internet access and thus now way to install gems :) ?

**Comment by Asmod4n** [comment] 2016-10-10 16:30
@kares you could have a local repository of gems in your intranet.

**Comment by kares** [comment] 2016-10-10 21:06
... including Bundler since its for the best using the very same version the bundle was installed with.

**Comment by headius** [comment] 2016-10-11 09:33
From @drbrain's assessment in late 2013:

> Remember, there is not yet a RubyGems version that contains all the Bundler features, and won't be for at least two years.

Well, we're closing in on three years now and RG still does not include all of (or even most of) Bundler's features, right @indirect @drbrain?

I'd like to see what MRI folks think about including Bundler as a default gem. It has become nearly as indispensable as RubyGems itself, and yet it isn't shipped in the box.

**Comment by kares** [comment] 2016-10-11 10:30
even if MRI folks think its fine I still feel like its not that definite for JRuby - most of the times its fine but : 

- even lately Bundler (1.13.1) was released with a JRuby specific bug (they only test against MRI?)
- JRuby does some RGs extensions, Bundler patches RGs heavily - potential conflict is always near
- there has been problems (on JRuby) working around default gems - believe there's still left overs

... if Bundler is included JRuby should strongly consider running their suite (at the given release tag)

**Comment by enebo** [comment] 2016-10-11 17:24
@kares I think your points are true but regardless whether we ship bundler or not we have to deal with these issues now.  We cannot live for too long without working bundler support and retain users.  I definitely agree we need to do something about having CI for bundler to know when something breaks sooner than later.

I am still somewhat for this idea since RG still does not subsume the important bits of bundler yet and we will end up shipping a version of bundler we are confident in rather than letting people install the latest (and possibly have an immediate negative response).

**Comment by kares** [comment] 2016-10-12 04:03
I am all for it, just that I do have concerns with the current state of RG/Bundler. default gem issues might be most critical - recall there has been an issue where it prohibited using an explicitly installed gem version (of jossl) and always loaded the default - packed version.

**Comment by mkristian** [comment] 2016-10-12 08:26
@kares isn't there even a test for the case which you just mentioned about the default gem. maybe not in the main test suite but should rather easy to add, that an downgraded version of bundler is really picked.

**Comment by kares** [comment] 2016-10-12 11:26
@mkristian unsure but I know @etehtsea has been struggling lately with some default gem behavior.

**Comment by mkristian** [comment] 2016-10-12 11:45
@kares is there more than https://github.com/jruby/jruby/pull/4083 which is clearly a problem

**Comment by etehtsea** [comment] 2016-10-12 15:13
@kares @mkristian to be honest I can't reproduce [this](https://github.com/jruby/jruby/pull/4198#issuecomment-250897321) anymore. Maybe there was some local issue.

**Comment by kares** [comment] 2016-10-12 16:13
@mkristian @etehtsea that was the one on my mind - thank you both for pointing me into directions...
guess my concerns are no longer relevant than ... :children_crossing: looking forward for anyone attempting the Bundler packaging setup ... maybe for 9.2? I will check (or add) 4 a gem default test case @mkristian mentioned.

**Comment by enebo** [comment] 2017-02-17 17:33
I was going to resolve this based on not everyone agreeing we should include it but most people seem to support including it.  

I guess our main issue is operationally knowing whether a particular version of bundler is working well enough for us to include it in the distribution?  This obviously is an issue whether we include it or not but we have more pressure to make sure the particular version we include is working if we plan on endorsing it by putting in the distro...

**Comment by kares** [comment] 2017-02-18 06:34
still resisting a bit ... just hit a regression in their point release (1.14.4) that only seemingly broke in a .war
... to be fair its JRuby 1.7 but they claim support for 1.9.3 the work-around is not that straight-forward as you can not really gem manage bundler itself (chicken-egg problem). having it in would mean a small disaster :stuck_out_tongue_winking_eye:

**Comment by enebo** [comment] 2018-12-03 21:15
Closing this as C Ruby 2.6 will actually include this...so this will be part of ordinary updates for 2.6 support.  I could leave this issue open as that work but it has a lot of discussion about whether this should happen vs knowing we need to just do it.

**Closed by enebo** 2018-12-03 21:15 UTC
Labels: packaging
