### ISSUE TITLE
Pattern matching not working

### ISSUE THREAD

**Issue by stoivo** [jruby/jruby#8283] opened 2024-06-05 10:37 UTC
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`)  `jruby 9.4.7.0 (3.1.4) 2024-04-29 597ff08ac1 OpenJDK 64-Bit Server VM 25.412-b08 on 1.8.0_412-b08 +jit [aarch64-linux]`
* Operating system and platform (e.g. `uname -a`) `Linux d0135f341f7e 6.4.16-linuxkit #1 SMP PREEMPT Sat Sep 23 13:36:48 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

**Expected Behavior**

The following script should print `it works {:node=>:delim}`. 
```rb
token = {:node=>:delim}

case token
in node: :comma
  if token[:node] != :comma
    raise "token is not comma token #{token.inspect}"
  end
  puts "it works #{token}"
else
  puts "it works #{token}"
end
```

**Actual Behavior**

script crashed with error
```
RuntimeError: token is not comma token {:node=>:delim}
   <main> at lib/lol.rb:6
```

**Comment by headius** [comment] 2024-06-05 17:39
Also confirmed broken on our 3.4 branch.

**Comment by headius** [comment] 2024-06-05 19:34
This was broken due to a JIT optimization to avoid storing the intermediate `===` result for a `case...when` because that form immediately tests if that result is true and then throws it away. Pattern matching, however, saves that value to be used for later tests and error output, so omitting the load/store caused those tests to pick up the wrong value (a previous value set into the same temporary variable). The fix is to mark such `===` instructions as being used for pattern matching, to preserve all load/store operations.

Fixed by #8284.

**Closed** 2024-06-05 22:05 UTC

**Comment by stoivo** [comment] 2024-06-06 06:48
Impressive how quickly this was sorted out 👏 👏 👏 👏

**Comment by headius** [comment] 2024-06-06 17:53
It will be in 9.4.8.0 and should be in jruby-head snapshots today or tomorrow.
