### ISSUE TITLE
Java::JavaLang::ClassCastException with ActiveRecord `find_by`

### ISSUE THREAD

**Issue by estolfo** [jruby/jruby#6566] opened 2021-02-18 11:15 UTC
Hi JRuby team,

I work on the [Elastic APM ruby agent](https://github.com/elastic/apm-agent-ruby) and I’ve encountered an obscure error running our test suite on JRuby.

When we run our [graphql_spec](https://github.com/elastic/apm-agent-ruby/blob/v3.13.0/spec/integration/graphql_spec.rb) that runs a [`find_by`](https://github.com/elastic/apm-agent-ruby/blob/v3.13.0/spec/integration/graphql_spec.rb#L92) on an ActiveRecord model, this is the error:

> Java::JavaLang::ClassCastException (class org.jruby.ir.operands.TemporaryClosureVariable cannot be cast to class org.jruby.ir.operands.DepthCloneable (org.jruby.ir.operands.TemporaryClosureVariable and org.jruby.ir.operands.DepthCloneable are in unnamed module of loader 'bootstrap')):	

I’ve determined that we started getting the error with this commit of Rails: https://github.com/rails/rails/commit/acb6631cd99cdfe7db356773ef74cad7cbb570ed#

I’ve tried to reproduce it by running the ActiveRecord test suite itself on JRuby and by running a `find_by` in a new rails app but I don’t get the error. So perhaps it has something to do with the combination of gems we are using in our test suite (?)

The only way I know to reproduce the error is to run the `graphql_spec` in our repo:

> \> git clone https://github.com/elastic/apm-agent-ruby.git
> \> cd apm-agent-ruby
> \> git checkout v3.13.0
> (using JRuby 9.2.14.0)
> \> FRAMEWORK=rails-6.1 bundle
> \> FRAMEWORK=rails-6.1 rspec spec/integration/graphql_spec.rb:229

You'll see the error in the dumped log:

> E, [2021-02-18T12:07:14.118989 #43959] ERROR -- : class org.jruby.ir.operands.TemporaryClosureVariable cannot be cast to class org.jruby.ir.operands.DepthCloneable (org.jruby.ir.operands.TemporaryClosureVariable and org.jruby.ir.operands.DepthCloneable are in unnamed module of loader 'bootstrap')
I, [2021-02-18T12:07:14.122875 #43959]  INFO -- : Completed 500 Internal Server Error in 365ms (Views: 2.5ms | Allocations: 0)

We've been able to work around the error by using a `where` query instead, but I thought you might like to know about this.

Thanks!
Emily

**Comment by headius** [comment] 2021-02-18 18:34
I believe this is a duplicate of #6563 filed a few days ago. I will ask @enebo to prioritize a fix and see if there is any possible workaround.

**Closed** 2021-02-18 18:34 UTC

**Comment by estolfo** [comment] 2021-02-18 19:51
Thank you!
