### ISSUE TITLE
__callee__ uses real method and not aliased method name

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#7091] opened 2022-02-11 17:13 UTC
I am not sure if this will end up on 9.2 or not but this is broken for all supported versions:

```ruby
def foo
  p __callee__
end

alias :bar :foo

bar
```

I noticed while examining 3.1 ripper which aliases all events to the same method name (and hilarity ensues).

**Comment by enebo** [comment] 2022-06-21 16:54
Moving off of 9.2 since this has only been observed in one place and I worked around it (e.g. default ripper impl).

**Comment by joeldrapper** [comment] 2023-01-25 20:59
@headius using `alias_method` with `__callee__` is an important Ruby meta-programming technique that allows you to define methods that behave differently depending on which method was called.

**Comment by headius** [comment] 2023-03-02 05:24
This is actually a dupe of a very old bug, #2305, so I'm going to close it as a dupe.

But good news... I have a possible fix I'll push as a PR shortly.

**Closed by headius** 2023-03-02 05:24 UTC

**Comment by headius** [comment] 2023-03-02 12:57
See #7702.
