### ISSUE TITLE
JDK9 + 1.7.x produces io/console warnings

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3611] opened 2016-01-21 21:24 UTC
Not sure why these warnings are coming up.

```
$ jruby -v -e 1
jruby 1.7.25-SNAPSHOT (1.9.3p551) 2016-01-21 592384a on Java HotSpot(TM) 64-Bit Server VM 9-ea+100-2016-01-06-200131.javare.4235.nc +jit [darwin-x86_64]
failed to load native console support: Unsupported platform: x86_64-darwin
io/console not supported; tty will not be manipulated
...
```

We need to make fixes to 1.7 to support JDK9's new platform/version strings, I assume. We already made these changes on master.

**Comment by perlun** [comment] 2017-10-05 13:15
JRuby 1.7 has reached EOL (#4112). Can we close this?

**Comment by mprins** [comment] 2017-10-05 13:35
this may be a duplicate of #3700

**Comment by enebo** [comment] 2017-10-05 13:40
Yeah we will not support Java 9 for 1.7.x and this issue was fixed on 9.x before this issue was even opened.  So I will close this.

**Closed by enebo** 2017-10-05 13:40 UTC
