### ISSUE TITLE
Uninitialized constant -- already exists

### ISSUE THREAD

**Issue by fzakaria** [jruby/jruby#6139] opened 2020-03-25 21:24 UTC
Running into an interesting exception when running our code packaged in a JAR
```
Did you mean?  ActiveSupport::SafeBuffer
Did you mean?  ActiveSupport::SafeBuffer
  org/jruby/RubyModule.java:3370:in `const_missing'
  uri:classloader:/gems/activesupport-4.2.11.1/lib/active_support/core_ext/string/output_safety.rb:260:in `html_safe'
  uri:classloader:/gems/activesupport-4.2.11.1/lib/active_support/core_ext/string/output_safety.rb:22:in `html_escape'
  uri:classloader:/bundler/gems/diffy-de8b86845039/lib/diffy/html_formatter.rb:88:in `block in highlighted_words'
  org/jruby/RubyArray.java:1735:in `each'
  org/jruby/RubyEnumerable.java:1067:in `each_with_index'
  org/jruby/RubyEnumerator.java:323:in `each'
  org/jruby/RubyEnumerable.java:830:in `map'
  uri:classloader:/bundler/gems/diffy-de8b86845039/lib/diffy/html_formatter.rb:56:in `highlighted_words'
  uri:classloader:/bundler/gems/diffy-de8b86845039/lib/diffy/html_formatter.rb:11:in `to_s'
  uri:classloader:/bundler/gems/diffy-de8b86845039/lib/diffy/format.rb:34:in `html'
```

The fact that the constant seems present for the `did you mean?` leads me to believe some race condition. 
I know that ActiveSupport likes to make heavy use of _autoload_ which @headius has reported as unsafe via https://bugs.ruby-lang.org/issues/921
However I believe the codebase is mitigating this issue by explicitly requiring the file during our single-threaded startup phase.

```ruby
# bunch of requires
require "active_support/core_ext/string/output_safety"

# start up the Puma server
```

**Information**
  
Provide at least:
* jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-8u232-b09-1~deb9u1-b09 +jit [linux-x86_64]
* Linux fmzakari-glaptop 5.2.17-1rodete3-amd64 #1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018) x86_64 GNU/Linux

The bug is being experienced specifically when packaged up into a JAR with Warbler; however that's when we really push the concurrency through testing

**Comment by headius** [comment] 2020-03-25 21:33
Interesting. The constant in question is actually defined in the same file where the error is raised, and well before the actual usage at line 260 in output_safety.rb. So there doesn't appear to be either threading or autoload at play here.

**Comment by fzakaria** [comment] 2020-03-25 23:33
It is odd.
For posterity we are using 4.2.11.1 of ActiveSupport but its the same.
```ruby
class String
  # Marks a string as trusted safe. It will be inserted into HTML with no
  # additional escaping performed. It is your responsibilty to ensure that the
  # string contains no malicious content. This method is equivalent to the
  # `raw` helper in views. It is recommended that you use `sanitize` instead of
  # this method. It should never be called on user input.
  def html_safe
    ActiveSupport::SafeBuffer.new(self)
  end
end
```

How can `SafeBuffer` be unset there.

**Comment by kares** [comment] 2020-03-26 07:54
@fzakaria you seem to be on JRuby 9.1.17.0, if that is correct than
I am not sure its worth for the team revisiting issues for the old release. 
could you instead try reproducing with JRuby 9.2.11?

we understand it might be pain to upgrade a Rails app to a new major version but the transition from Ruby 2.3 -> 2.5 is expected to be smooth. there aren't any 9.1 releases planned so it would make sense to test against latest JRuby 9.2

**Comment by headius** [comment] 2020-03-27 19:58
At this point I have no theories. Without a way to reproduce this I'm not sure how to investigate. @fzakaria Are you able to reproduce this in a smaller app that you can share?

**Comment by kares** [comment] 2020-03-28 06:19
not finding the details, but it sure looks familiar - an old known issue with auto-loading on JRuby 9.1

**Comment by headius** [comment] 2020-03-29 04:32
@kares But it looks very much like this particular constant is not autoloaded and defined in the same file where it's accessed. It's very confusing!

**Comment by fzakaria** [comment] 2020-04-06 21:24
Thanks -- I will do that.
Would logging https://ruby-doc.org/core-2.7.1/Module.html#method-c-constants be
sufficient for that point in the stack ?


Cheers,
Farid Zakaria

**Comment by headius** [comment] 2020-04-07 19:23
@fzakaria That would be a good start; at least we might see if the constant table actually is missing the constant.

**Comment by reidmorrison** [comment] 2020-04-07 20:12
In our batch processing environment we often get `uninitialized constant` errors when multiple threads all try to load the same code at the same time. We just upgraded to JRuby 9.2.11.1 and decided to try `global.require.lock=true` along with increasing the number of worker threads.

We don't see this issue in our online / web system since we prime each JRuby instance with a single threaded client that exercises most of the code before putting it into rotation.

When running just 10 threads the number of `uninitialized constant` errors is very low, and always works on retry. Ideally we want to run 100 worker threads or more per process, instead of being capped at 10 due to this error.

These are our JAVA_OPTS when the container is started:
```
-server -Dfile.encoding=UTF-8 -Xms8g -Xmx8g -Xss2m 
-XX:G1HeapRegionSize=8m -XX:ReservedCodeCacheSize=512m 
-XX:+UseG1GC -XX:MaxGCPauseMillis=5000 -XX:+UseCodeCacheFlushing 
-XX:+ParallelRefProcEnabled 
-Djruby.compile.invokedynamic=true -Djruby.global.require.lock=true 
-XX:+PrintCommandLineFlags
```

It is based off of the "official" JRuby 9.2 docker image, which still uses Open JDK 1.8.0_242.

The problem is worse when a lot of the same jobs are already queued for processing and all worker threads try to process them at the same time upon startup. Once the system has been running for a while we do not see these `uninitialized constant` errors again.

We also added the following code to try and preload as much code as possible, prior to loading bundler which allowed us to get up to 10 threads:
```ruby
    def Kernel
      def autoload(module_, filename)
        require filename
      end
    end

    def Module
      def autoload(module_, filename)
        require filename
      end
    end
```

Is it possible that one thread starts to load a constant and then another comes along, "sees" that the class is loaded and then moves onto loading the next constant causing the missing constant errors?

**Comment by headius** [comment] 2020-04-08 05:51
@reidmorrison That scenario is definitely possible for autoloaded constants, though I believe JRuby master usually will not have that problem (autoloads should usually wait for an in-progresse autoload to finish before returning) and #5764 should when landed fix all remaining holes in that logic.

Unfortunately this case seems to be different. The constant that apparently is not present is defined in the same file as the method that reports the error. There's no way, even with concurrent threads loading the same file in parallel (which shouldn't be possible) for the method to be defined before the constant is assigned. That's what makes this truly baffling.

**Comment by fzakaria** [comment] 2020-04-13 16:55
I'm going to pepper in `global.require.lock=true` for out tests int he mean time; 
see what it does.

**Comment by headius** [comment] 2020-04-13 17:02
FWIW my project this week is to land a large rewrite of our load/require/autoload subsystem for JRuby 9.3. It may help this issue.

**Comment by fzakaria** [comment] 2020-04-13 17:28
We're still on 9.17.0 :(

We have a large project to try to get us to JDK11 & latest JRuby; 
we are slowly working to upgrade a lot of gems.

I have a personal goal to look back again at Warbler/Bundler to make some improvements;
(maybe even jlink)

**Comment by headius** [comment] 2020-05-15 23:32
@fzakaria Any updates here?

**Comment by fzakaria** [comment] 2020-05-19 03:48
No :(
I did the suggestions above and still see the failure.

We are working through finally upgrading to 9.2.X so maybe that will help.
Feel free to close since I don't have any updates; the original bug report
is odd though given the constant is declared in same file.


Farid Zakaria

**Comment by headius** [comment] 2021-08-19 18:21
This predates the load/require/autoload work from #5764 and I expect that 9.3 will fix this issue. Please confirm, and I will optimistically mark this one fixed.

**Closed by headius** 2021-08-19 18:21 UTC

**Comment by fzakaria** [comment] 2021-08-22 17:41
I hope to try 9.3 soon.

**Comment by sdlin** [comment] 2021-09-01 23:01
Hi @headius, thanks for your investigations into this issue. Is there any way that the loading work you mentioned (https://github.com/jruby/jruby/pull/5764) could be backported to version `9.2`?
