### ISSUE TITLE
Running specific regex with Regexp::IGNORECASE flag on text starting with specific pipe character results in java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mrckzgl** [jruby/jruby#7730] opened 2023-03-20 12:52 UTC
**Environment Information**
- JRuby: jruby 9.4.1.0 (3.1.0) 2023-02-07 237d5fa5f4 Java HotSpot(TM) 64-Bit Server VM 15.0.2+7-27 on 15.0.2+7-27 +jit [x86_64-linux] no command line flags

**Description**

Try running this simple code in JRuby
```
str1 = "asdas│dsfsd"
str2 = "│dsfsd"

regex1 = Regexp.new(Regexp.escape("abc"), Regexp::IGNORECASE)
puts "regex1 on str1 result: " + str1.match?(regex1).to_s
puts "regex1 on str2 result: " + str2.match?(regex1).to_s

regex2 = Regexp.new(Regexp.escape("test"), Regexp::IGNORECASE)
puts "regex2 on str1 result: " + str1.match?(regex2).to_s
puts "regex2 on str2 result: " + str2.match?(regex2).to_s
```

**Expected Behavior**
Output:
```
regex1 on str1 result: false
regex1 on str2 result: false
regex2 on str1 result: false
regex2 on str2 result: false
```

**Actual Behavior**

```
regex1 on str1 result: false
regex1 on str2 result: false
regex2 on str1 result: false
Unhandled Java exception: java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 8
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 8
           mbcCaseFold at org/jcodings/specific/BaseUTF8Encoding.java:154
           mbcCaseFold at org/jcodings/specific/UTF8Encoding.java:22
        lowerCaseMatch at org/joni/Search.java:42
            access$000 at org/joni/Search.java:27
                search at org/joni/Search.java:439
    forwardSearchRange at org/joni/Matcher.java:139
          searchCommon at org/joni/Matcher.java:447
   searchInterruptible at org/joni/Matcher.java:318
                   run at org/jruby/RubyRegexp.java:285
                   run at org/jruby/RubyRegexp.java:266
           executeTask at org/jruby/RubyThread.java:1751
           executeTask at org/jruby/RubyThread.java:1729
         matcherSearch at org/jruby/RubyRegexp.java:230
                matchP at org/jruby/RubyRegexp.java:1247
               match_p at org/jruby/RubyRegexp.java:1171
               match_p at org/jruby/RubyString.java:1729
                  call at org/jruby/RubyString$INVOKER$i$match_p.gen:-1
          cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:495
                  call at org/jruby/runtime/callsite/CachingCallSite.java:244
  invokeOther18:match? at regex_test.rb:10
           RUBY$script at regex_test.rb:10
                   run at regex_test.rb:-1
   invokeWithArguments at java/lang/invoke/MethodHandle.java:729
                  load at org/jruby/ir/Compiler.java:114
             runScript at org/jruby/Ruby.java:1277
           runNormally at org/jruby/Ruby.java:1194
           runNormally at org/jruby/Ruby.java:1176
           runNormally at org/jruby/Ruby.java:1212
           runFromMain at org/jruby/Ruby.java:991
         doRunFromMain at org/jruby/Main.java:398
           internalRun at org/jruby/Main.java:282
                   run at org/jruby/Main.java:227
                  main at org/jruby/Main.java:199
```

So when a string starts with a "|" character some regex on it will bail. The example works fine on standard `ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]`. The problem only appears on JRuby when the `Regexp::IGNORECASE` flag is set on the second regex.

**Comment by mrckzgl** [comment] 2023-03-21 11:46
happens to us also when the text is starting with other special characters. I guess a (rather not so common) portion of the UTF-8 range is affected.

**Comment by ahorek** [comment] 2023-05-02 17:16
does it work without https://github.com/jruby/joni/commit/2f859a47d70b17885457c1a43e7c13ec6c269705 ? it seems to be the same issue as https://github.com/jruby/jcodings/issues/26

**Comment by mrckzgl** [comment] 2023-05-02 19:46
how to test this (i.e. compile jruby) with the changed dependency?

**Comment by kares** [comment] 2023-05-03 08:59
I think it's simpler to just work on the JONI side, here's a test case: https://github.com/jruby/joni/pull/65

> does it work without https://github.com/jruby/joni/commit/2f859a47d70b17885457c1a43e7c13ec6c269705 ? it seems to be the same issue as https://github.com/jruby/jcodings/issues/26

correct, when https://github.com/jruby/joni/commit/2f859a47d70b17885457c1a43e7c13ec6c269705 is reverted the test-case mentioned above passes, but I am not 100% it's entirely the same issue (might be the same cause though).

**Comment by headius** [comment] 2023-05-03 22:16
I quickly read over most of the methods involved and did not see any obvious differences from the CRuby logic. So I assume I missed something.

**Comment by enebo** [comment] 2023-05-04 14:10
I think we can reduce this to something being wrong with BM_IC_FORWARD.  Also, I don't think it is #26 because this is not a broken string.

**Comment by headius** [comment] 2023-06-06 21:25
I'm going ahead with a release of joni that does not have a fix for this yet. Still needs to be addressed.

**Comment by headius** [comment] 2023-09-05 11:46
Revisiting this because I know it is holding up some users from upgrading...

The original case appears to work as expected now with JRuby 9.3 HEAD:

```
$ jruby -v blah.rb             
jruby 9.3.11.0-SNAPSHOT (2.6.8) 2023-09-05 8ccff43f1c OpenJDK 64-Bit Server VM 25.362-b09 on 1.8.0_362-b09 +jit [arm64-darwin]
regex1 on str1 result: false
regex1 on str2 result: false
regex2 on str1 result: false
regex2 on str2 result: false
```

The small case by @kares also appears to work:

```
$ jruby -v -e 'p "𝑍 " =~ /ab/i'
jruby 9.3.11.0-SNAPSHOT (2.6.8) 2023-09-05 8ccff43f1c OpenJDK 64-Bit Server VM 25.362-b09 on 1.8.0_362-b09 +jit [arm64-darwin]
nil
```

So it seems that fixes up to joni 2.2.1 may have fixed this issue? Do we have any other cases that can be used to test this?

**Comment by enebo** [comment] 2023-09-05 14:50
@headius we stopped using BM_IC_FORWARD (there is something wrong with it which still needs to be figured out).  The fix was to use the less efficient forward algo.

**Closed** 2023-09-05 14:50 UTC

**Comment by ikaronen-relex** [comment] 2023-09-06 08:15
Did we ever add any of these test cases into the test suite on the JRuby side (to make sure we don't get a regression if someone helpfully undoes the de-optimization and re-enables BM_IC_FORWARD before the underlying bug has been fixed)?

**Comment by kares** [comment] 2023-09-06 09:47
think it might make sense to have the test at the JONI side: https://github.com/jruby/joni/pull/65 (used to fail miserably, rebased and it's now :green_circle: )

**Comment by enebo** [comment] 2023-09-06 15:24
@ikaronen-relex thanks for bringing it up and @kares for making a unit test in joni.  This will be really helpful when we reexamine why BM_IC_FORWARD is broken.
