### ISSUE TITLE
FD leak with orphan Unix Socket

### ISSUE THREAD

**Issue by peacand** [jruby/jruby#6529] opened 2021-01-13 12:43 UTC
**JRuby version**
jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 OpenJDK 64-Bit Server VM 25.275-b01 on 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01 +jit [linux-x86_64]

**Env**
Linux hostname01 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Expected behavior**

When trying to connect to a Unix Socket (UNIXSocket.new) on which no process is listening, an exception is raised and no file descriptor is left at the end of the connection attempt

**Actual behavior**

When trying to connect to a Unix Socket on which no process is listening, an IOError is raised and the socket file descriptor is not closed. Therefore, if a client keeps trying to connect to a crashed daemon supposed to listen on the Unix Socket, the JRuby client will also crashed due to file descriptors exhaustion because of the sockets not closed. 

**Example**

```
require 'socket'

for i in 0..20
    begin
        a = UNIXSocket.new("uds.sock")
    rescue => e
        puts(e)
    end
end

gets

```

If the socket file uds.sock exists but no process it listening on it, the test script above will produce 20 IOError and at the end, if you look at the file descriptors you will see ~20 sockets. 

**Workaround**

I did not find any way to workaround this issue. I had a look at the abstract namespace sockets also, which could be a way, but they don't seem to be implemented in JRuby 2.5.0 at least. 

Could you help please ?

Thank you in advance

**Comment by headius** [comment] 2021-01-13 16:29
Seems like a clear bug and a good reproduction! Agreed, when a UNIXSocket fails to connect there should be no open fd leftover.

**Comment by headius** [comment] 2021-01-13 16:56
I have a simple fix that closes the socket when connecting or binding fails. I am not sure about a workaround, unfortunately; once the exception is raised the UNIXSocket object is no longer referenced and there's no way to close it. If you can determine the bad fd number you could use possibly use `IO.for_fd(fd).close` to shut it down.

**Comment by headius** [comment] 2021-01-13 17:26
Fixed by #6531.

@peacand Could you look into the socket specs at https://github.com/ruby/spec/tree/master/library/socket and see if you can come up with a test for this? I am not exactly sure how to test for open file descriptors, so you may want to open an issue there to discuss it.

**Closed by headius** 2021-01-13 17:26 UTC

**Comment by peacand** [comment] 2021-01-15 15:04
Wow I have never seen an issue being handled and fixed that fast ! Thank you very much @headius ! 
For the tests sorry but I will not be the right guy, since I'm not really an intensive Ruby or Java dev. Just an advanced Logstash user 😉 .

**Comment by headius** [comment] 2021-01-15 15:37
@peacand No problem, and honestly I am not sure how to test for this since there's no standard way to find leaked file descriptors.
