### ISSUE TITLE
Enumerable#chunk behaves in jruby-9.4.0.0 differently than in ruby 3.1.2 and jruby-9.3.9.0

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#7528] opened 2022-12-15 22:23 UTC
**Expected Behavior**

```
3.1.2 :003 > [0].chunk{0}.map(&:first)
 => [0]
 ```
 ```
 jruby-9.3.9.0 :001 > [0].chunk{0}.map(&:first)
 => [0]
 ```
**Actual Behavior**

```
jruby-9.4.0.0 :041 > [0].chunk{0}.map(&:first)
org/jruby/RubyYielder.java:115:in `yield': undefined method `first' for 0:Integer (NoMethodError)
	from org/jruby/RubyYielder.java:120:in `<<'
	from org/jruby/RubyGenerator.java:98:in `each'
	from org/jruby/RubyEnumerator.java:397:in `each'
	from org/jruby/RubyEnumerable.java:835:in `map'
	from (irb):41:in `evaluate'
	from org/jruby/RubyKernel.java:1143:in `eval'
	from org/jruby/RubyKernel.java:1586:in `loop'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from /Users/heinrich/.rvm/rubies/jruby-9.4.0.0/lib/ruby/gems/shared/gems/irb-1.4.1/exe/irb:11:in `<main>'
	from org/jruby/RubyKernel.java:1091:in `load'
	from /Users/heinrich/.rvm/rubies/jruby-9.4.0.0/bin/irb:23:in `<main>'
	from org/jruby/RubyKernel.java:1143:in `eval'
	from /Users/heinrich/.rvm/gems/jruby-9.4.0.0/bin/jruby_executable_hooks:22:in `<main>'
```

**Comment by enebo** [comment] 2022-12-16 20:48
This is a duplicate of https://github.com/jruby/jruby/issues/7486. This works for me with HEAD.

**Closed by enebo** 2022-12-16 20:48 UTC
