### ISSUE TITLE
Parser needs to handle encoding error properly

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2151] opened 2014-11-08 19:39 UTC
Failing test:

```
TestException#test_errinfo_encoding_in_debug:
Java::OrgJcodingsException::EncodingException: invalid code point value
    org.jcodings.specific.BaseEUCJPEncoding.codeToMbcLength(BaseEUCJPEncoding.java:55)
    org.jcodings.specific.EUCJPEncoding.codeToMbcLength(EUCJPEncoding.java:24)
    org.jruby.lexer.yacc.RubyLexer.isMultiByteChar(RubyLexer.java:618)
    org.jruby.lexer.yacc.RubyLexer.getIdentifier(RubyLexer.java:1329)
    org.jruby.lexer.yacc.RubyLexer.identifier(RubyLexer.java:1736)
    org.jruby.lexer.yacc.RubyLexer.yylex(RubyLexer.java:1305)
    org.jruby.lexer.yacc.RubyLexer.nextToken(RubyLexer.java:396)
    org.jruby.parser.RubyParser.yyparse(RubyParser.java:1583)
    org.jruby.parser.RubyParser.yyparse(RubyParser.java:1534)
    org.jruby.parser.RubyParser.parse(RubyParser.java:5216)
    org.jruby.parser.Parser.parse(Parser.java:108)
    org.jruby.parser.Parser.parse(Parser.java:78)
    org.jruby.parser.Parser.parse(Parser.java:70)
    org.jruby.Ruby.parseEval(Ruby.java:2716)
```

I'm marking this beginner as well, since it may simply be a matter of capturing the exception and re-raising it appropriately.

Run with `jruby test/mri/runner.rb ruby/test_exception.rb -n test_errinfo_encoding_in_debug`.

**Comment by enebo** [comment] 2016-02-19 16:59
Marking as duplicate of #3679.  The crash here is now what should be happening.  We are failing to make the error class before the actual test is executed.

**Closed by enebo** 2016-02-19 16:59 UTC
Labels: parser
