### ISSUE TITLE
No Method Error

### ISSUE THREAD

**Issue by pandar1** [jruby/jruby#1352] opened 2013-12-19 10:40 UTC
The following code in accounts.rb

``` ruby
def newpassword
end

  def newpassword=(newval)
    self.password = newval
  end
```

raise this error

NoMethodError (undefined method `newpassword=' for #<Account:0x15fffa6>):
  app/controllers/accounts_controller.rb:140:in`update'
  app/controllers/accounts_controller.rb:139:in `update'

The same code runs ok in Yarv

**Comment by rtyler** [comment] 2015-08-07 22:16
@pandar1 it appears you're working with Rails here, I'm not sure how to reproduce this in order to see if it has been fixed in newer versions of JRuby.

Would you please provide a reproduction case or at least validate whether the issue is still present for you on newer versions of JRuby?

**Comment by kares** [comment] 2017-01-17 15:31
no response - probably no longer valid. please let us know if issue persist on latest of JRuby 1.7

**Closed by kares** 2017-01-17 15:31 UTC
Labels: feedback needed
