### ISSUE TITLE
Mysterious core dump / segfault with 9.0.0.0-pre.

### ISSUE THREAD

**Issue by digitalextremist** [jruby/jruby#2506] opened 2015-01-23 04:17 UTC
Not sure where to even begin describing this issue. I have 2.8+ megabytes of error output and am afraid to post it all here in case it has something compromising in it. Let me know where to privately post a secret gist and the trainwreck is _all yours_ free of charge.

The fatal error completely took out all fault-tolerance for my otherwise impossible to kill process, down to crashing the Java VM itself. In other words, major show-stopper.

Using: `jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-22 e038fe1 Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 +jit [linux-amd64]`

I am 90% sure this is related to extremely heavy use of `Celluloid` but am not certain.

**Comment by digitalextremist** [comment] 2015-01-24 10:19
@headius this seems safe to post: https://gist.github.com/digitalextremist/6e79ecc443d7d1632e3e

Be advised @tarcieri / @halorgium, I do not believe Celluloid is not stable on `jRuby 9000` yet and I'm trying to figure out why. I've also gotten segfaults at start up before anything really happens in a server instance, which I'll post later.
 
/cc: @atambo, @enebo

**Comment by digitalextremist** [comment] 2015-01-24 10:22
Here was another piece of output I got right at start up one time. This time I had an actual core dump too, but it's stupid large. Too large for a gist.... over 3 gigs!

https://gist.github.com/digitalextremist/7f3c30f0dd3b6ef189dd

Once there's some semi-vague verdict even on what's up, I'll go back to testing `9000`, otherwise I downgraded for a while. Hope something in those messes help?

**Comment by subbuss** [comment] 2015-01-24 15:45
I think https://github.com/jruby/jruby/commit/0aef21d6cb0c62d9869d6d0fb4ea9b8909e4be0a will fix your problem. This was a known issue and we meant to figure out a way to disable it before pre, but forgot about it.

**Comment by subbuss** [comment] 2015-01-24 15:48
To clarify, this is a JVM bug that @chrisseaton first ran into a few months back and introduced a workaround, but it still crashes the JVM in some scenarios. AFAIK, @headius has brought this up with the JVM team, but since this piece of code is going to be disabled, we may not trigger the JVM bug in that scenario.

**Comment by digitalextremist** [comment] 2015-01-24 15:54
I'm impressed that this crystal-ball-territory mess drew any response at all, much less a possible line of code. Wish I could reliably trigger the crash. When that commit gets into `-head` please ping me and I'll re-up & resume trying to crash it. The issue sounds inter-lingual so I'll just get popcorn and watch it resolve itself. Feel free to close this once the commit is merged and pushed into the bloodstream.

**Comment by subbuss** [comment] 2015-01-24 15:57
That commit is merged (since I am a core committer) and is on the master repo. So, pull the latest version of master and get some popcorn.

**Comment by digitalextremist** [comment] 2015-01-24 16:11
Sweet @subbuss! Thanks!

`jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2015-01-24 0aef21d Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 +jit [linux-amd64]`

**Comment by digitalextremist** [comment] 2015-01-24 17:39
@subbuss I've core dumped again with the new build of jruby:

* https://gist.github.com/edad37c1a5ab685ea399

Is that the same fault occurring? Are you still thinking it's the issue you first thought?

**Comment by digitalextremist** [comment] 2015-01-24 17:46
Another only a few minutes later: https://gist.github.com/abb4f94d30926661fe72

Switching back to `1.7.*` for now until I get further instructions.

**Comment by subbuss** [comment] 2015-01-26 06:15
Hmm .. we'll see what our luck is in getting the JVM address this. In any case, we might try to play around some more with the interpreter loop to make the JVM not crash. To be continued ...

**Comment by digitalextremist** [comment] 2015-01-26 07:57
@headius asked if I was using `InvokeDynamic` and I am, if that matters. Has it degraded any since `1.17.18`? I'm still experiencing #1658 also, if that helps at all. Neither issue is reproducible for me, and I'm not at all sure they are connected or even related.

**Comment by lexs** [comment] 2015-04-20 06:31
Hi! I'm seeing what I think is the same JVM crash in a similar heavy MH/invokedynamic application (not JRuby). Do you have a JVM bug report @headius?

**Comment by headius** [comment] 2015-07-02 20:03
@lexs Can you post your crash?

This still appears to be a JVM bug, and I can now file such a bug, but without a way to reproduce it they generally just close them. So what we really need here is some way to reproduce this reliably.

**Comment by headius** [comment] 2020-07-08 21:52
Long defunct, please refile if this issue exists on a supported version of JRuby.

**Closed by headius** 2020-07-08 21:52 UTC
Labels: JRuby 9000
