### ISSUE TITLE
JRuby can Not load JFFI library under IBM Power 64 with PLinux platform 

### ISSUE THREAD

**Issue by xialixl** [jruby/jruby#1389] opened 2014-01-09 07:56 UTC
Environments:
IBM Power ppc 64 bit , POWER7 architecture, 
Red Hat Enterprise Linux Server release 6.3 (Santiago)
JRuby ver 1.6.8， jar file: jruby-complete-1.6.8.jar
Apache Hbase  0.95.2

In case of running Command from Hbase : 
.../hbase-0.95.2/bin/hbase shell  

We got Errors like following:
```
INFO  [main] Configuration.deprecation: hadoop.native.lib is deprecated. Instead, use io.native.lib.available
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Could not locate stub library in jar file.  Tried [jni/ppc64-Linux/libjffi-1.0.so, /jni/ppc64-Linux/libjffi-1.0.so]
        at com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:90)
```

My Analysis:
It looks like JRuby was going to load Java JFFI lib: libjffi-1.0.so which is supposed to exist under location jni/ppc64-Linux/libjffi-1.0.so inside the Jar 'ruby-complete-1.6.8.jar'.
for 1.6.8 version currently Jruby only has following kinds of JFFI lib for choices : 
```
jni/Darwin/
jni/Darwin/libjffi-1.0.jnilib
jni/i386-FreeBSD/
jni/i386-FreeBSD/libjffi-1.0.so
jni/i386-Linux/
jni/i386-Linux/libjffi-1.0.so
jni/i386-OpenBSD/
jni/i386-OpenBSD/libjffi-1.0.so
jni/i386-SunOS/
jni/i386-SunOS/libjffi-1.0.so
jni/i386-Windows/
jni/i386-Windows/jffi-1.0.dll
jni/ppc-AIX/
jni/ppc-AIX/libjffi-1.0.a
jni/ppc-Linux/
jni/ppc-Linux/libjffi-1.0.so
jni/sparc-SunOS/
jni/sparc-SunOS/libjffi-1.0.so
jni/sparcv9-SunOS/
jni/sparcv9-SunOS/libjffi-1.0.so
jni/x86_64-FreeBSD/
jni/x86_64-FreeBSD/libjffi-1.0.so
jni/x86_64-Linux/
jni/x86_64-Linux/libjffi-1.0.so
jni/x86_64-OpenBSD/
jni/x86_64-OpenBSD/libjffi-1.0.so
jni/x86_64-SunOS/
jni/x86_64-SunOS/libjffi-1.0.so
jni/x86_64-Windows/
jni/x86_64-Windows/jffi-1.0.dll
```

Fix:
Since '/jni/ppc64-Linux/libjffi-1.0.so' is missed inside jar , I downloaded the right version of JFFI sources (https://github.com/jnr/jffi) and built them by IBM XL C Compiler instead of default GCC at IBM ppc64 platform , Added the output libjffi-1.0.so into the right place of the  jruby-complete-1.6.8.jar.  Now it works well at my ppc64 env.

Advice:
 To support IBM ppc64 with Linux env , Could Jruby add JFFI library for ppc64 version into released Jruby jar files.

Thanks

**Comment by ayappanec** [comment] 2015-01-23 11:24
Can any maintainers look into this issue ( https://github.com/jnr/jffi/pull/12 )

**Comment by headius** [comment] 2015-01-23 14:33
Wow, apologies for missing this one for so long. The PR has been merged and we'll try to get releases of the whole JNR chain out for JRuby 1.7.x and 9k.pre2.

**Comment by headius** [comment] 2015-01-23 14:38
Oops...don't close until we have updated JNR-* in a JRuby release.

**Comment by ayappanec** [comment] 2015-01-28 06:34
Can this be added to upcoming JRuby 1.7.x release also ?

**Comment by ayappanec** [comment] 2015-02-04 15:34
Any update for the above comment?

**Comment by gustavotemple** [comment] 2015-02-25 18:51
@ayappanec, did you see this issue?

https://github.com/jnr/jffi/issues/15

**Comment by headius** [comment] 2015-02-25 23:12
I don't see why we couldn't update this in 1.7.x as well. @enebo and I know we need to update everything for next releases, which will involve fixing some regressions in the jnr-* chain of projects. Marking for 1.7.20.

**Comment by headius** [comment] 2015-02-26 06:06
jnr/jffi#16 details the now-mitigated showstopper preventing us from releaseing jffi 1.2.8. Should be able to get the family released this week.

**Comment by ayappanec** [comment] 2015-03-02 06:54
I came to know about the problem you guys facing for releasing jffi 1.2.8. I hope this one will get into Jruby 1.7.20 &  9000. Thank you.

**Comment by enebo** [comment] 2015-03-03 15:29
@headius was able to release jffi and dependent artifacts yesterday so the plan is to update master and jruby-1_7 before our next releases.

**Comment by headius** [comment] 2015-03-03 17:24
1.7 and master have both been updated for latest jnr-* projects.

If it's possible for someone on PLinux/ppc64 to do a build of jruby-1_7 branch and confirm it works properly, we'd appreciate it :-)

**Closed by headius** 2015-03-03 17:24 UTC
Labels: ffi, JRuby 1.7.x, JRuby 9000

**Comment by ayappanec** [comment] 2015-03-04 07:25
Building jruby-1_7 branch fails in PLinux/ppc64 & PLinux/ppc64le due to unknown compilation issue.
"Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jruby-core: Compilation failure"

But the main problem here is we are not able to build jruby-complete jar individually due to missing artfifacts.
"Failed to execute goal on project jruby-complete: Could not resolve dependencies for project org.jruby:jruby-complete:bundle:1.7.20-SNAPSHOT: The following artifacts could not be resolved: org.jruby:jruby-core:jar:noasm:1.7.20-SNAPSHOT, org.jruby:jruby-stdlib:jar:1.7.20-SNAPSHOT: Could not find artifact org.jruby:jruby-core:jar:noasm:1.7.20-SNAPSHOT in sonatype (https://oss.sonatype.org/content/repositories/snapshots/)"

It seems like the artifacts are not yet available in sonatype repository.

**Comment by mkristian** [comment] 2015-03-04 10:41
to build jruby-complete you need to run from the basedir of jruby
mvn -Pcomplete
or mvn clean install -Pcomplete
if this is not passing beyond jruby-core then nothing furtehr down the road
will work since all those missing artifacts will be build on the way

**Comment by ayappanec** [comment] 2015-03-04 11:27
I tried both the options but they failed to get beyond jruby-core. Finally i went into the maven/jruby-complete directory and tried to build jruby-complete jar by issuing "mvn clean install" and there i faced this missing artifacts issue..

**Comment by mkristian** [comment] 2015-03-04 13:32
I built the snapshot for you:
https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-complete/1.7.20-SNAPSHOT/

**Comment by headius** [comment] 2015-03-04 14:03
@ayappanec Please open a separate issue for your problems building JRuby on PLinux and we'll work through them separately. I suspect it's some oddity in how our build interacts with the JVM on that platform.

**Comment by ayappanec** [comment] 2015-03-04 14:45
@mkristian It requires jruby-core,jruby-stdlib and other such jars also.Can you please place those jars  also in sonatype?
@headius Sure. I will open a separate issue for building JRuby on PLinux

**Comment by mkristian** [comment] 2015-03-04 14:59
https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-core/
https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-stdlib/

BUT I do not understand since jruby-complete contains both the other
artifacts. and you do not need to build anything anymore, just download
what you need. if you need them as maven artifacts somehow you should be
able to build everything after the core with

mvn clean install -Pcomplete -rf :jruby-lib

let me know if you need something else.

**Comment by ayappanec** [comment] 2015-03-04 15:19
I tried with the command mentioned above. its trying to download the jruby-core jar from sonatype but failed since the jar uploaded there has some number associated with the filename "jruby-stdlib-1.7.20-20150304.132127-1.jar"

**Comment by headius** [comment] 2015-03-04 16:17
@ayappanec Thank you...please let us know when you've opened the other issue. For confirming this issue right now, just download the 1.7.20 build that @mkristian provided above.

**Comment by ayappanec** [comment] 2015-03-05 06:29
@headius I could see the jffi binaries for ppc64 & ppc64le in the jruby-complete jar. Thank you

**Comment by ayappanec** [comment] 2015-03-05 07:33
@headius I opened a new issue for Jruby build failure (https://github.com/jruby/jruby/issues/2648)

**Comment by ayappanec** [comment] 2015-03-31 13:54
It seems like we need ppc64le jnr-ffi TypeAliases and ruby ffi ppc64le platform specific types.conf as well to get the latest jruby working ppc64le. I could see the changes already went into the master branch of jnr-ffi & jruby. I don't know when the jnr-ffi next release is going to happen. If it happens before jruby release, then we need to change the jnr-ffi version to 2.0.3 in jruby to make use of it. Otherwise we have wait till further releases of jruby.

**Comment by gustavotemple** [comment] 2015-03-31 14:15
@lbianc @caioso

**Comment by headius** [comment] 2015-04-06 18:34
@ayappanec I'm largely paralyzed from improving ppc64le support right now without your help, so if there are additional issues we need to fix, I'm hoping to see PRs from you :-)

**Comment by ayappanec** [comment] 2015-04-07 09:02
@headius Sure.. Right now #2790 & #1897 seems to be the major hurdle. #2647 is yet another one but we have openjdk as an option here.
