### ISSUE TITLE
STDIN.gets under jirb doesn't work

### ISSUE THREAD

**Issue by pintubigfoot** [jruby/jruby#1372] opened 2013-12-31 06:16 UTC
#### Maybe related to issue at http://jira.codehaus.org/browse/JRUBY-5902

Under bash shell, this works as expected:

```
$ jruby -e "puts 'echo ' + STDIN.gets"
foo
echo foo
```

But under jirb prompt, it will hang forever until we kill the java process:

```
$ jirb
irb(main):001:0> puts 'echo ' + STDIN.gets
foo^M^M^M^M^M
--hang (whenever we press enter key, it will display ^M)--
```

Verified with jruby 1.7.9, linux, jvm 1.6, 64-bit:

```
$ java -version
java version "1.6.0_23"
Java(TM) SE Runtime Environment (build 1.6.0_23-b05)
Java HotSpot(TM) 64-Bit Server VM (build 19.0-b09, mixed mode)
```

Thank you.

**Comment by Saganesque** [comment] 2015-11-21 19:55
I am having the same problem under JRuby 1.7.9. It is only at the jirb command line that any gets command will hang, and only ctrl-z allows me to exit the program. irb does not have this problem.

**Comment by Saganesque** [comment] 2016-08-01 09:18
I am still having this problem under jruby-9.1.1.0. The simple statement:
`
print "The Farenheit equivalent is ", gets.to_i * 9 / 5 + 32, ".\n"`

causes the prompt to repeat ^M when the enter key is pressed (until a ctl-C followed by striking the enter key breaks you out with the message 

:Abort: abort then interrupt!
	from org/jruby/RubyIO.java:2203:in `gets'
	from org/jruby/RubyArgsFile.java:328:in `gets'
	from org/jruby/RubyKernel.java:323:in `gets'
	from (irb):3:in `<eval>'
	from org/jruby/RubyKernel.java:983:in `eval'
	from org/jruby/RubyKernel.java:1290:in `loop'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from /home/somedirector/.rvm/rubies/jruby-9.1.1.0/bin/irb:13:in `<top>'

**Comment by enebo** [comment] 2017-02-17 21:00
I can confirm this with Terminal on MacOS as well.  If I use shell-mode in Emacs I do not see this so it seems something weird with terminal mode within irb since I can -e a gets and it works ok.

**Comment by madrob** [comment] 2017-10-10 18:53
One of my colleagues suggested that it is due to jline2's use of UnixTerminal at https://github.com/jline/jline2/blob/cd8284800520f91b99936ae3e99c32c5a5f8e876/src/main/java/jline/UnixTerminal.java#L92

@enebo suggested a workaround by executing `` `stty icrnl` `` (the backticks are important) in your jirb and then Enter key works for STDIN.gets again.

Unsure if this will show up as regressions elsewhere...

**Comment by headius** [comment] 2017-10-31 20:58
We really need to get off of jline.

**Comment by headius** [comment] 2017-10-31 21:03
Related to getting off jline, you may find that using the pure-Ruby rb-readline library. I believe it has had some JRuby issues in the past, but it appears to work for me.

```
$ jruby -rrb-readline -S jirb
irb(main):001:0> $stdin.gets
asdf
=> "asdf\n"
irb(main):002:0> 
```

**Comment by headius** [comment] 2017-10-31 21:26
I have opened ConnorAtherton/rb-readline#145 to discuss official JRuby support in rb-readline. If we can work that out I see no reason to not ship rb-readline as our built-in readline, falling back to the jline version on platforms where rb-readline+jruby doesn't work well.

**Comment by madrob** [comment] 2017-11-06 21:14
any traction on this, @headius

**Comment by headius** [comment] 2017-11-08 17:23
@madrob If you mean on getting formal JRuby support in rb-readline, then no, not a lot of action there :-)

If you mean on putting rb-readline into JRuby as our readline, then also no. It would likely need to happen for a 9.2 release rather than a stable 9.1.x update.

If you follow my example above you can use rb-readline with JRuby. We will try to get a better readline in place for 9.2.

**Comment by headius** [comment] 2018-09-19 19:05
I had not noticed that @ConnorAtherton had expressed interest in us moving to rb_readline, but we're too close to 9.2.1 to move on it right now. Next release?

**Comment by headius** [comment] 2019-08-02 20:43
This is improved on by #5803 but doesn't wait for input for some reason:

```
$ irb
irb(main):001:0> STDIN.gets
=> nil
irb(main):002:0> STDIN.gets
=> nil
irb(main):003:0> STDIN.gets
=> nil
```

It doesn't hang though...that's something.

**Comment by headius** [comment] 2019-08-06 20:49
We will look into this with the move to reline in JRuby 9.3. We're stuck on jline at the moment, which doesn't interact well with normal IO.

**Comment by headius** [comment] 2021-03-16 07:47
I checked this with the latest irb and reline and it still seems to be an issue. There are also other issues with that update as discussed in ruby/irb#196.

**Comment by headius** [comment] 2022-11-16 21:41
This appears to be working fine with latest master on reline and new IRB.

```
$ jirb
irb(main):001:0> puts $stdin.gets
asdf
asdf                                                         
=> nil                                                       
irb(main):002:0> 
```

**Closed by headius** 2022-11-16 21:41 UTC
