### ISSUE TITLE
Parallel value assignment broken in IR builder (multi-value literals, calls, attr-assign, etc.)

### ISSUE THREAD

**Issue by jowl** [jruby/jruby#2574] opened 2015-02-06 23:29 UTC
It appears as if variables in expressions are evaluated at a later stage in jruby-head than in MRI and JRuby 1.7.19, as shown in the example below.

```
$ rvm jruby-head,jruby-1.7.19,2.2.0 do ruby -e 'a=0;b=[a,a=1];p(b)'
[1, 1]
[0, 1]
[0, 1]
```

Or more readable

```ruby
a = 0
[a, (a = 1)] # => [1, 1]
```

This is as minimal an example as I've been able to produce, and I don't really know where to continue the investigation.

**Comment by subbuss** [comment] 2015-02-06 23:34
Interesting bug :-) .. Looks like our IR builder is not respecting ordering here .. Generated instrs:
```
        a(0:0) = copy(Fixnum:0)
        a(0:0) = copy(Fixnum:1)
        %v_3 = copy(Array:[a(0:0), Fixnum:1])
```
So, clearly broken.

**Comment by subbuss** [comment] 2015-02-07 17:03
This was a "2 bugs for the price of 1" issue :-). See https://github.com/jruby/jruby/commit/eb3740c6fddf6c7e49cb4640a42a979aaa51deed

**Comment by jowl** [comment] 2015-02-07 22:22
Good job in finding the problem and fixing it so fast. I've confirmed that your fix indeed solves the array construction issue, but it seems that the rabbit hole is even deeper; the same behavior is observed in hash construction as well, for both keys and values.

```ruby
a = 0
{ a => a, (a = 1) => a } # => { 1 => 1 } (MRI: {0=>0, 1=>1})
{ a => a, a => (a = 2) } # => { 2 => 2 } (MRI: {1=>2})
```

This has been observed on cc00fd4024b908536018411e4bd47856f85bf95b.

**Comment by subbuss** [comment] 2015-02-07 22:43
Yes, I was going to audit the other literals and fix them. But, good to get confirmation that others might be broken similarly.

**Comment by subbuss** [comment] 2015-02-07 22:44
The fix is fairly trivial .. just have to systematically go through all literals fix the ones that need fixing.

**Comment by subbuss** [comment] 2015-02-08 15:06
I don't see any other multi-valued literal besides arrays and hashes. If I missed any, please update this issue.

**Comment by subbuss** [comment] 2015-02-08 15:09
Will check call args and masgns next.

**Comment by subbuss** [comment] 2015-02-08 15:27
You unearthed a gold mine of a bug here! :) A lot of parallel value construction in many call scenarios are broken. Interesting that this kind of bug never surface in mri tests or rubyspec.

a = 10
b = a / (a=10)
p b # prints 1

OR

a = "xyz"
p (a =~ (a = /[x]/)); # throws an exception

@enebo @headius fyi .. so, the real brain dead fix would be to just force all build values to go through 'copyAndReturnValue' and let OptimizeTempVarsPass, LocalOptPass, etc. propagate useless copies (which there will be lots of now). Otherwise, we'll have to look at all parallel value construction in calls, attr assign, etc. and fix up where required (even so, there will be lots of copies).

For the array and hash literal construction cases, after those passes and DCE runs, the output is:
```
        %t_b_4 = copy({Fixnum:0=>Fixnum:0, Fixnum:1=>Fixnum:1})
        %t_c_5 = copy({Fixnum:1=>Fixnum:1, Fixnum:1=>Fixnum:2})
....
        %t_b_3 = copy(Array:[Fixnum:0, Fixnum:1])
```

So, those passes will take care of killing useless instrs. but will defer fixing this till we've had a chance to chat about this.

**Comment by enebo** [comment] 2015-02-12 17:36
I am resolving this.  I covered the cases apparent where we have a list of arguments which must be processed.  It is possible some cases were missed (regression spec should cover broad cases known), but if any new cases are found a new issue should be opened.

**Closed by enebo** 2015-02-12 17:36 UTC
Labels: ir
