### ISSUE TITLE
Hash#take_while wrong behavior in 1.7.19

### ISSUE THREAD

**Issue by dzjuck** [jruby/jruby#2907] opened 2015-05-05 11:50 UTC
```ruby
passed = []
hash = {a: 1}
hash.take_while { |pair| passed << pair; true }
passed
# [:a] # jruby-1.7.19
# [[:a, 1]] # jruby-head
# [[:a, 1]] # mri-1.9.3
# [[:a, 1]] # mri-2.2.1
```

Thank you.

**Comment by nirvdrum** [comment] 2015-05-05 12:38
This appears to be problematic in 1.7.19 as well.

**Comment by dzjuck** [comment] 2015-05-05 12:46
@nirvdrum Thank you, it's typo, i meant 1.7.19

**Comment by nirvdrum** [comment] 2015-05-05 13:09
No worries.  We often get bug reports against older versions of JRuby.  So I like to verify that the problem is still present in the most recently released version.

**Comment by kares** [comment] 2015-05-26 14:27
can confirm this on 1.7.20 and that it also happens a couple of more methods from `Enumerable` :
```
irb(main):001:0> passed = []; hash = {a: 1}; hash.take_while { |pair| passed << pair; true }; passed
=> [:a]
irb(main):002:0> passed = []; hash = {a: 1}; hash.reject { |pair| passed << pair; true }; passed
=> [:a]
irb(main):003:0> passed = []; hash = {a: 1}; hash.collect { |pair| passed << pair; true }; passed
=> [[:a, 1]]
irb(main):004:0> passed = []; hash = {a: 1}; hash.select { |pair| passed << pair; true }; passed
=> [:a]
```

**Comment by kares** [comment] 2015-05-29 08:36
closing on **jruby-1_7** with https://github.com/jruby/jruby/commit/d8aa8afb15abb77a8fb894950810c0e95c7cf7a0

**Closed by kares** 2015-05-29 08:36 UTC
Labels: core, JRuby 1.7.x
