### ISSUE TITLE
Multicast Test Disabled for Linux and Windows

### ISSUE THREAD

**Issue by j2man** [jruby/jruby#5658] opened 2019-03-19 19:40 UTC
### Environment
Linux and Windows all releases

### Expected Behavior
Unit test multicast

### Actual Behavior
Unit test for multicast has been disabled and not "fixed".
https://github.com/jruby/jruby/issues/620

Disabling unit test has lead to the community that relies on JRuby into releasing broken multicast code. Unit test should have never been disabled and should be fixed to test local or at least warning level failure.

**Comment by headius** [comment] 2019-04-09 17:34
Closing as a dupe of 5656...we will deal with this one way or another in 9.2.8.

**Closed by headius** 2019-04-09 17:34 UTC
