### ISSUE TITLE
Possible ChannelFD leak in FilenoUtil?

### ISSUE THREAD

**Issue by seanguo** [jruby/jruby#4796] opened 2017-09-25 06:26 UTC
### Environment
JRuby 9.1.13.0
Linux
Using as embedded JSR223 engine

We upgraded from 1.7.21 to 9.1.13.0 to try to address the issue in https://github.com/jruby/jruby/issues/4446. But after a simple load test we found that the map in FilenoUtil is accumulating during the test. So I wrote the following simple script to try to reproduce:

### Sample Code Snippet
```
public class Test {
  public static void main(String[] args) throws InterruptedException, ScriptException, ClassNotFoundException, IOException {
    ScriptEngineManager scriptEngineManager = new ScriptEngineManager();
    final ScriptEngine engine = scriptEngineManager.getEngineByName("jruby");
    final ScriptContext scriptContext = new SimpleScriptContext();
    scriptContext.setAttribute("org.jruby.embed.termination", true, ScriptContext.ENGINE_SCOPE);

    engine.eval("print 'test\n'", scriptContext);

    System.gc();
    Thread.sleep(5000);

    System.out.println(Ruby.getGlobalRuntime().getFilenoUtil().getNumberOfWrappers());

  }
}
```

### Unexpected Behavior
I got the following output:
test
3
Shouldn't the number be 0?

Is this an issue of the new code or my usage is incorrect for the new update?
Thanks.

**Comment by seanguo** [comment] 2017-09-25 06:29
I also tried to dump the thread stack in the register method and unregister method, but it seems no unregister is invoked.
```
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:38)
	at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:190)
	at org.jruby.RubyIO.prepIO(RubyIO.java:255)
	at org.jruby.RubyIO.prepStdio(RubyIO.java:184)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:274)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:202)
	at org.jruby.Ruby.init(Ruby.java:1195)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.jsr223.Utils.setWriter(Utils.java:149)
	at org.jruby.embed.jsr223.Utils.preEval(Utils.java:113)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:88)
	at org.jruby.Test.main(Test.java:21)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:38)
	at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:190)
	at org.jruby.RubyIO.prepIO(RubyIO.java:255)
	at org.jruby.RubyIO.prepStdio(RubyIO.java:206)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:276)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:202)
	at org.jruby.Ruby.init(Ruby.java:1195)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.jsr223.Utils.setWriter(Utils.java:149)
	at org.jruby.embed.jsr223.Utils.preEval(Utils.java:113)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:88)
	at org.jruby.Test.main(Test.java:21)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:38)
	at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:190)
	at org.jruby.RubyIO.prepIO(RubyIO.java:255)
	at org.jruby.RubyIO.prepStdio(RubyIO.java:206)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:278)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:202)
	at org.jruby.Ruby.init(Ruby.java:1195)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.jsr223.Utils.setWriter(Utils.java:149)
	at org.jruby.embed.jsr223.Utils.preEval(Utils.java:113)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:88)
	at org.jruby.Test.main(Test.java:21)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:39)
	at org.jruby.RubyIO.<init>(RubyIO.java:138)
	at org.jruby.embed.jsr223.Utils.getRubyIO(Utils.java:179)
	at org.jruby.embed.jsr223.Utils.setWriter(Utils.java:150)
	at org.jruby.embed.jsr223.Utils.preEval(Utils.java:113)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:88)
	at org.jruby.Test.main(Test.java:21)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:39)
	at org.jruby.RubyIO.<init>(RubyIO.java:138)
	at org.jruby.embed.jsr223.Utils.getRubyIO(Utils.java:179)
	at org.jruby.embed.jsr223.Utils.setErrorWriter(Utils.java:171)
	at org.jruby.embed.jsr223.Utils.preEval(Utils.java:114)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:88)
	at org.jruby.Test.main(Test.java:21)
test
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:38)
	at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:190)
	at org.jruby.RubyIO.prepIO(RubyIO.java:255)
	at org.jruby.RubyIO.prepStdio(RubyIO.java:184)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:274)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:202)
	at org.jruby.Ruby.init(Ruby.java:1195)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.ScriptingContainer.terminate(ScriptingContainer.java:1858)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:98)
	at org.jruby.Test.main(Test.java:21)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:38)
	at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:190)
	at org.jruby.RubyIO.prepIO(RubyIO.java:255)
	at org.jruby.RubyIO.prepStdio(RubyIO.java:206)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:276)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:202)
	at org.jruby.Ruby.init(Ruby.java:1195)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.ScriptingContainer.terminate(ScriptingContainer.java:1858)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:98)
	at org.jruby.Test.main(Test.java:21)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at org.jruby.util.io.FilenoUtil.registerWrapper(FilenoUtil.java:82)
	at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:38)
	at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:190)
	at org.jruby.RubyIO.prepIO(RubyIO.java:255)
	at org.jruby.RubyIO.prepStdio(RubyIO.java:206)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:278)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:202)
	at org.jruby.Ruby.init(Ruby.java:1195)
	at org.jruby.Ruby.newInstance(Ruby.java:339)
	at org.jruby.embed.internal.AbstractLocalContextProvider.getGlobalRuntime(AbstractLocalContextProvider.java:82)
	at org.jruby.embed.internal.SingletonLocalContextProvider.getRuntime(SingletonLocalContextProvider.java:99)
	at org.jruby.embed.ScriptingContainer.terminate(ScriptingContainer.java:1858)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:98)
	at org.jruby.Test.main(Test.java:21)
3
```

**Comment by snood1205** [comment] 2017-09-25 08:32
If it helps at all, running jruby-9.1.13.0 on my mac gives me the following related warning message on all runs

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil to method sun.nio.ch.SelChImpl.getFD()
> WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by petrvalkoun-gooddata** [comment] 2017-10-24 10:05
jruby 9.1.13.0 on windows 8.1 x64 with jdk-9.0.2 x64 gives me following error:

gem update
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR:  Loading command: update (LoadError)
        Unsupported platform: x86_64-windows
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

**Comment by headius** [comment] 2017-10-30 15:05
@seanquo There certainly could be a leak, but your test may not quite rigorous enough to prove it. The fake filenos acquired by the container would likely be attached to IO objects that need to finalize. Assuming the container and everything it references goes away, there may be a couple GC cycles needed to fully unregister those filenos.

If, however, you can show that the fake filenos continue to pile up under heavy load with multiple GC cycles, then we may have a problem. We have (or used to have) tests for fileno leaks, but I'm not sure if they're running.

**Comment by seanguo** [comment] 2017-10-31 13:34
@headius Actually we found this issue during our load test. The heap continues grow and full GC won't help on reclaiming the memory. So we made a heap dump which shows the leak points of the file descriptor. That's why I created this issue and attached the small program for you to reproduce.

**Comment by headius** [comment] 2017-10-31 20:04
Complete test app with imports:

```java
import org.jruby.Ruby;

import javax.script.ScriptContext;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.script.SimpleScriptContext;
import java.io.IOException;

public class Test {
  public static void main(String[] args) throws InterruptedException, ScriptException, ClassNotFoundException, IOException {
    ScriptEngineManager scriptEngineManager = new ScriptEngineManager();
    final ScriptEngine engine = scriptEngineManager.getEngineByName("jruby");
    final ScriptContext scriptContext = new SimpleScriptContext();
    scriptContext.setAttribute("org.jruby.embed.termination", true, ScriptContext.ENGINE_SCOPE);

    engine.eval("print 'test\n'", scriptContext);

    System.gc();
    Thread.sleep(5000);

    System.out.println(Ruby.getGlobalRuntime().getFilenoUtil().getNumberOfWrappers());

  }
}
```

**Comment by headius** [comment] 2017-10-31 20:31
Ok, so there's a few problems here.

First off, the engine never goes out of scope, so I wouldn't expect it to go away. If the engine doesn't go away, the fake filenos registered by JRuby to serve that engine won't go away either.

Second, because the JSR-232 scripting logic in JRuby uses the "global" runtime, that runtime never goes out of scope and remains referenced. As a result, the IO objects that wrap those fake filenos (in this case, for in/out/err) never get collected.

I modified your script to loop 100 times over the script engine logic, creating and executing 100 engines. The count of fileno does not go beyond 3, regardless of how many engines execute.

I also made a Ruby script that generates hundreds of fake filenos. It does not appear to leak, and the filenos do get unregistered.

```ruby
loop do
  100.times do
    java.io.ByteArrayOutputStream.new.to_io
  end
  JRuby.gc
  p JRuby.runtime.fileno_util.number_of_wrappers
```

If you would like finer-grained control over scripting JRuby from Java, including the ability to use multiple, nonglobal runtimes and to shut down the instance when you're done, I would recommend you look at our [embedding API](http://jruby.org/apidocs/org/jruby/embed/ScriptingContainer.html) in org.jruby.embed.

**Comment by headius** [comment] 2017-10-31 20:33
I'm closing this because there's no evidence that we're leaking fake fileno. If you are seeing leaks in your application, I suspect it's because you're using JSR-223 engines, registering a bunch of new IO objects, and then never cleaning them up.

Your workarounds are:

* Clean up IOs created during each engine's lifespan before walking away from the engine.
* Use the JRuby embedding API to isolate the engines and shut them down when done (or make it possible for them to GC), so their resources will be reclaimed.

**Comment by seanguo** [comment] 2017-11-03 02:47
This is used to be fine with 1.7.27. So the implementation changes in 9.x. @headius Can you share more details on your first workaround:

> Clean up IOs created during each engine's lifespan before walking away from the engine.

Thanks.

**Comment by seanguo** [comment] 2017-12-20 10:03
@headius This become a blocking issue for us now. I understood what you said that JSR-223 engines are sharing the same global runtime and which makes the IO objects failed to be garbage collected.
For your first workaround suggestion, I do not think it's easy for us as your API consumer to remember and clean up those IOs before walking away from the engine. In the 1.7.x days we used to use 
`scriptContext.setAttribute("org.jruby.embed.termination", true, ScriptContext.ENGINE_SCOPE);`
to tell the engine to do the clean up after each script execution. Is that possible for you to do the IO objects clean up in the same manner.

And for your second suggestions. It's also not an easy solution for us. We use the JSR223 API as an abstract layer to invoke multiple script engines. Using JRuby's embedding API will make the code much more complicated. Also as you are the guys who understand that part much better, is that possible for you to provider a solution on the JSR223 level and let us isolate the engines/runtime?

Please suggest.

Thanks.

**Comment by oozzal** [comment] 2018-01-09 02:20
@headius This happened to us as well when upgrading to 9.1.15.0. We had to downgrade to 9.1.12.0  to run without any issue. Here's a snapshot of a heap dump:
<img width="1469" alt="screen shot 2018-01-09 at 8 01 24 am" src="https://user-images.githubusercontent.com/1573910/34702010-8451fe66-f513-11e7-8368-89824cb2cddc.png">

**Comment by oozzal** [comment] 2018-01-11 16:42
@seanguo were you able to find the issue / fix ?

**Comment by tcheng** [comment] 2018-01-18 11:01
@oozzal , I tried 9.1.12.0 but the memory leak issue still exists in our product. I assume it's because 9.1.12.0 doesn't include the fix for [#4446](https://github.com/jruby/jruby/issues/4446).

**Comment by fxposter** [comment] 2018-03-14 13:36
We are see leaks similar to @oozzal and downgrading to 9.1.12.0 actually fixes them for us.

**Comment by fxposter** [comment] 2018-03-14 14:31
Clarification - we downgraded from 9.1.16.0

**Comment by enebo** [comment] 2018-03-14 14:47
@fxposter so .13 might not be where the regression started.  If you have a chance to see when it started that will be helpful.

**Comment by headius** [comment] 2018-03-15 15:18
@fxposter If you can provide a heap dump of a badly-leaked application it would also help us sort out how the leak is happening.

At the moment we have no good way to reproduce this, since all reports are based on user applications we don't have access to.

@tcheng I did not notice your comment until now. This is good information, along with @seanguo's findings. I suspect the problem is due to reusing the same engine repeatedly but registering new Java streams for it to use (e.g. for stdio). I will investigate why we're not ever cleaning up abandoned streams.

**Comment by headius** [comment] 2018-03-15 18:02
Ok, after a bit more investigation I don't see anything obvious about fileno registration/unregistration. The fileno gets registered when we initialize an IO instance with a stream, and when the IO is closed or finalized it should be unregistering.

We really need a reproduction.

**Comment by mtjhax** [comment] 2018-03-28 02:35
I have created an app that recreates the problem. Unfortunately, the code causing the memory issue is buried in the AWS SDK v1 gem. I'm stepping into their code to try to get a cleaner repro but it's a little time-consuming so I thought I would share what I have including a zipped heap dump: https://gist.github.com/mtjhax/92df4b277e16adfca951bf3d180c4f1a

**Comment by headius** [comment] 2018-04-10 14:57
@mtjhax Thanks for the heap dump and efforts to simplify a reproduction! I'll have a look at the dump and see what it tells me.

**Comment by headius** [comment] 2018-04-10 17:43
I can definitely see the leaked ChannelFD but I do not see the reason for it yet.

**Comment by headius** [comment] 2018-04-10 17:56
I may have found a clue!

It seems that almost all of the leaked ChannelFD are associated with either IOReadableByteChannel or IOWritableByteChannel, which simply wrap an IO object and simulate a readable or writable channel. These objects are constructed in two places: in the Java extension to IO `to_channel`, which is used to get a Channel for a given IO, and in the following lines of code used by IO#copy_stream: [readable](https://github.com/jruby/jruby/blob/bc950eac653ce1593e020be9f824e783cd239c4f/core/src/main/java/org/jruby/RubyIO.java#L4213-L4214), [writable](https://github.com/jruby/jruby/blob/bc950eac653ce1593e020be9f824e783cd239c4f/core/src/main/java/org/jruby/RubyIO.java#L4229-L4230).

Notice that in the latter `copy_stream` cases, we construct the channel, wrap it in an IO, and then immediately set `autoclose` to `false`. To preserve the underlying stream, we do not want the wrapper to close it automatically; this causes the temporary IO to not "finish" the ChannelFD it contains, and as a result it never unregisters.

I will investigate this and try to come up with a better option.

**Comment by headius** [comment] 2018-04-10 18:09
Oh some clarification of this code, and a couple questions.

First off...the logic I pointed out is used if you are doing copy_stream with an object that is not an IO (`copy_stream` will use that IO's channel directly) or a String (`copy_stream` will open a file for you) but which defines "read" or "write" methods.

Does this seem like something your code or libraries you call might be doing? Perhaps somewhere in the AWS libraries?

**Comment by headius** [comment] 2018-04-10 18:25
I believe I've reproduced the issue with the following code, which gobbles up memory very quickly for all the registered ChannelFD:

```ruby
io1 = File.open("pom.xml")
io2 = Object.new
def io2.write(stuff); stuff.size; end
loop { IO.copy_stream(io1, io2) }
```

**Comment by mtjhax** [comment] 2018-04-10 19:16
> Does this seem like something your code or libraries you call might be doing? Perhaps somewhere in the AWS libraries?
In my case, whatever is going on is coming out of the AWS v1 SDK gem. Going to poke around the code paths I'm using -- should be possible to find something.

**Comment by headius** [comment] 2018-04-10 19:17
It looks like we have a winner. I will land a patch shortly that avoids the use of a temporary IO object for "IO-like" streams, and so avoids the nasty little autoclose/unregister dance altogether.

Given this patch, we can make the following comparison based on my script above.

Before:
![image](https://user-images.githubusercontent.com/10135/38578541-d8f27588-3cc9-11e8-8b77-82ad0c81e3ab.png)

After:
![image](https://user-images.githubusercontent.com/10135/38578525-c7a71194-3cc9-11e8-8d0a-e6f5e43bcae8.png)

The before case continues to grow and grow while the after case levels off. There are also huge pauses in the before case every time it has to copy a multi-gigabyte heap to make room for the leak.

**Comment by headius** [comment] 2018-04-10 20:49
Ok, I've pushed a fix to jruby-9.1 branch, which will show up as a stable nightly build here: http://jruby.org/nightly

Those of you having issues can check it out. I've just kicked it to generate a new build right now, so it should be there soon.

Still need to write a test that verifies that IO-like read/write streams passed to copy_stream do not get registered.

**Comment by mtjhax** [comment] 2018-04-10 22:08
I thank you sir! And I dearly wish that I had time to actually help out by tracking this down in the sources myself but as you might suspect, I am currently engaged in battle with AWS gems.

**Comment by headius** [comment] 2018-04-11 20:34
@mtjhax No worries, just let us know if you can confirm it is fixed.

@seanguo @tcheng @fxposter @oozzal Same goes for you if you still have access to the apps in question.

**Closed** 2018-04-11 20:49 UTC
Labels: regression
