### ISSUE TITLE
JRuby 9.2.17.0 fails to install sassc on Windows

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6648] opened 2021-04-02 09:41 UTC
On JRuby 9.2.16.0 it worked fine, so this sounds like a regression.

Reproduction:
```
gem install sassc -N
```

Expected and on 9.2.16.0: https://github.com/ruby/setup-ruby/runs/2212961109#step:20:9
```
Successfully installed ffi-1.15.0-java
Building native extensions. This could take a while...
Successfully installed sassc-2.4.0
2 gems installed
```

Actual on 9.2.17.0: https://github.com/ruby/setup-ruby/pull/165/checks?check_run_id=2227889407#step:20:10
```
Successfully installed ffi-1.15.0-java
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.

    current directory: D:/jruby-9.2.17.0/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
D:/jruby-9.2.17.0/bin/jruby.exe -I D:/jruby-9.2.17.0/lib/ruby/stdlib -r ./siteconf20210330-2584-1pgoh9i.rb extconf.rb
extconf failedNo such file or directory - {"SOURCE_DATE_EPOCH"=>"1617110021"}

Gem files will remain installed in D:/jruby-9.2.17.0/lib/ruby/gems/shared/gems/sassc-2.4.0 for inspection.
Results logged to D:/jruby-9.2.17.0/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.0/sassc-2.4.0/gem_make.out
Error: Process completed with exit code 1.
```

From https://github.com/ruby/setup-ruby/pull/165#issuecomment-810250236

Self-reminder: revert https://github.com/ruby/setup-ruby/commit/ad65390c0a7505ce47023b0555e762426132496b when this is fixed

**Comment by headius** [comment] 2021-04-02 17:33
Most likely this is something related to the RubyGems update.

**Comment by headius** [comment] 2021-04-02 17:41
JRuby 9.2 HEAD appears to install sassc fine on Darwin, and I expect it is fine on Linux as well. Will have to dig up a Windows env to investigate.

**Comment by headius** [comment] 2021-04-02 18:27
This is caused by a change in RubyGems to use open3 for launching extconf. Process launching on Windows is still a problem so this ends up in logic that does not support environment variables properly and the `SOURCE_DATE_EPOCH` variable ends up being treated as a filename to execute.

**Comment by headius** [comment] 2021-04-02 18:30
Reproduction of the error, at least. I believe this is the root cause of sassc failing to extconf properly.

```
C:\jruby>jruby -ropen3 -e "Open3.capture2e({'FOO' => 'BAR'}, 'cmd.exe')"
Errno::ENOENT: No such file or directory - {"FOO"=>"BAR"}
      spawn at org/jruby/RubyProcess.java:1674
      spawn at org/jruby/RubyKernel.java:1720
  popen_run at C:/jruby/lib/ruby/stdlib/jruby/open3_windows.rb:204
    popen2e at C:/jruby/lib/ruby/stdlib/jruby/open3_windows.rb:199
  capture2e at C:/jruby/lib/ruby/stdlib/jruby/open3_windows.rb:365
     <main> at -e:1
```

**Comment by headius** [comment] 2021-04-02 18:34
Actually appears that the use of open3 was further back. The change that broke on JRuby is here: https://github.com/rubygems/rubygems/commit/55472a333a8d0898758d40f0d6abd7aa97d2cbd3

The env vars were moved from being set globally to being set for just the command launch, uncovering the missing functionality in JRuby process launching on Windows.

**Comment by slonopotamus** [comment] 2021-04-28 20:09
I also hit this bug when trying to install [kindlegen on JRuby + Windows](https://github.com/slonopotamus/kindlegen/runs/2460612297?check_suite_focus=true#step:5:42).

**Comment by slonopotamus** [comment] 2021-04-28 20:10
BTW, is this a duplicate of #6291?

**Comment by headius** [comment] 2021-04-28 22:26
@slonopotamus You are correct, this is the same issue and the same fix. I will close that and this (probably did not close because it has now merged to master).

**Closed by headius** 2021-04-28 22:26 UTC
