### ISSUE TITLE
Report Builder not working with Jruby 9.2.7

### ISSUE THREAD

**Issue by snepal87** [jruby/jruby#5780] opened 2019-06-28 23:12 UTC
I was using Ruby 2.6.0 for my Test Automation before and used Report_Builder to print Html Report of my test results. But I have recently switched from Ruby to Jruby 9.2.7 due to certain things I needed. However, I am having issues with printing Test Report on JRuby. Below is the error I see on my Jenkins runs. 

Can anyone look into this?

Use `bundle info [gemname]` to see where a bundled gem is installed.
TypeError: no implicit conversion of nil into Array
             + at org/jruby/RubyArray.java:3274
  get_features at /My/Folder .rvm/gems/jruby-9.2.7.0/gems/report_builder-1.8/lib/report_builder/builder.rb:134
          step at org/jruby/RubyRange.java:577
  get_features at /My/Folder .rvm/gems/jruby-9.2.7.0/gems/report_builder-1.8/lib/report_builder/builder.rb:130
          each at org/jruby/RubyArray.java:1792
  get_features at /My/Folder .rvm/gems/jruby-9.2.7.0/gems/report_builder-1.8/lib/report_builder/builder.rb:112
    get_groups at /My/Folder .rvm/gems/jruby-9.2.7.0/gems/report_builder-1.8/lib/report_builder/builder.rb:82
  build_report at /My/Folder .rvm/gems/jruby-9.2.7.0/gems/report_builder-1.8/lib/report_builder/builder.rb:22
  build_report at /My/Folder .rvm/gems/jruby-9.2.7.0/gems/report_builder-1.8/lib/report_builder.rb:76
        <main> at /My/Folder .rvm/gems/jruby-9.2.7.0/gems/report_builder-1.8/bin/report_builder:82
          load at org/jruby/RubyKernel.java:1022
        (root) at /My/Folder .rvm/gems/jruby-9.2.7.0/bin/report_builder:1
          eval at org/jruby/RubyKernel.java:1061
        <main> at /My/Folder .rvm/gems/jruby-9.2.7.0/bin/jruby_executable_hooks:24

**Comment by enebo** [comment] 2019-07-02 20:07
I have never used this gem before and do not even know how to use it so this will be very hard for me to debug without some small reproduction.  I did check out the repository and I see that it fails on this line:

```ruby
(0..feature['elements'].size-1).step(2) do |i|
```

Printing out ```(0..feature['elements'].size-1)``` seems like it would be helpful since step2 seems to be confused here.

**Comment by headius** [comment] 2019-07-09 22:58
This is likely a duplicate of #5686 and related issues. JRuby 9.2.7.0 mistakenly shipped a copy of Bundler in the standard library, which interferes with updating it. That's already fixed for 9.2.8.0 (Bundler has been removed).

**Closed by headius** 2019-07-09 22:58 UTC
