### ISSUE TITLE
[Truffle] BigDecimal marshaling should include precision information

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#3860] opened 2016-05-06 20:42 UTC
The marshaled output and parsing logic for `BigDecimal` doesn't deal with precision in JRuby+Truffle. While the format is internally consistent, it doesn't work with other implementations. This is problematic when dealing with persistent serialized objects, where interop could become an issue.

**Comment by chrisseaton** [comment] 2016-10-30 22:24
I can't even find where the marshal code for `BigDecimal` is. How does it work?

**Comment by pitr-ch** [comment] 2016-10-31 07:33
I does not have proper implementation https://github.com/jruby/jruby/blob/b235ce7bd1315ec3203f4bd8254b8c262af72145/lib/ruby/truffle/truffle/bigdecimal.rb#L255

**Comment by chrisseaton** [comment] 2016-10-31 10:52
Ah so that's the cause of all this! Ok I can probably fill that in with the proper code.

**Comment by chrisseaton** [comment] 2016-11-01 23:48
Fixed in d2df6980a37de268c4d9150f1e2809772d9d4e01.

The marshal output still isn't exactly the same as the other implementations, but it seems to be compatible. We should aim to make all marshal output bit identical to MRI.

**Closed by chrisseaton** 2016-11-01 23:48 UTC
Labels: truffle
