### ISSUE TITLE
Intermittent exceptions with 'Java::JavaLang::NoClassDefFoundError : org/jruby/gen/RubyObject13'

### ISSUE THREAD

**Issue by kalenp** [jruby/jruby#8412] opened 2024-11-06 20:12 UTC
In our CI system, we're seeing intermittent test failures due to an exception
```
Java::JavaLang::NoClassDefFoundError : org/jruby/gen/RubyObject13

java.base/java.lang.ClassLoader.defineClass1(Native Method)
java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
org.jruby.dist/org.jruby.util.ClassDefiningJRubyClassLoader.defineClass(ClassDefiningJRubyClassLoader.java:53)
org.jruby.dist/org.jruby.java.codegen.RealClassGenerator.defineRealImplClass(RealClassGenerator.java:552)
org.jruby.dist/org.jruby.java.codegen.RealClassGenerator.createRealImplClass(RealClassGenerator.java:162)
org.jruby.dist/org.jruby.javasupport.Java.generateRealClass(Java.java:1607)
org.jruby.dist/org.jruby.java.proxies.JavaInterfaceTemplate$3.allocate(JavaInterfaceTemplate.java:299)
org.jruby.dist/org.jruby.RubyClass.allocate(RubyClass.java:234)
org.jruby.dist/org.jruby.RubyClass.newInstance(RubyClass.java:910)
org.jruby.RubyClass$INVOKER$i$newInstance_DBG.call(RubyClass$INVOKER$i$newInstance_DBG.gen)
org.jruby.dist/org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:75)
```

This arises when calling `new` on a Ruby class which includes a kotlin interface.  This occurs on ~10% of our CI runs, indicating there may be some sort of race condition in generating the generic RubyObjects.

**Environment Information**
  
```
$ jruby --version
jruby 9.3.15.0 (2.6.8) 2024-06-26 28bea01242 OpenJDK 64-Bit Server VM 11.0.15+0-adhoc..source on 11.0.15+0-adhoc..source +jit [x86_64-linux]
```

**Comment by headius** [comment] 2024-11-06 20:20
I notice `newInstance_DBG` in that trace, which would indicate that this is running with `--debug`. Can you confirm that is the case?

This is likely some kind of race when booting up. The thread in this stack trace is attempting to implement a Java interface on a class that contains 13 instance variables. It uses the `RubyObject13` class name for the appropriate specialized superclass, but can't find it. It may be that it has not been generated yet and this logic does not force it to be generated, or it may have been generating in parallel and the thread saw it before it was completely defined.

If it is a race, it can be fixed by pre-generating all the specialized `RubyObject` subtypes we plan to use at runtime and never defining any others, or by making this interface-implementation logic ensure that the supertype it references has been fully defined. Given that we would like to be able to generate new "shapes" in future versions, a hybrid approach may be needed.

**Comment by kalenp** [comment] 2024-11-06 20:26
We are indeed running with `--debug`.  This is in CI, and I believe that's being used to generate code coverage statistics.

**Comment by kalenp** [comment] 2024-11-06 20:38
When this fails, many tests using that same class will all fail, so the issue is persistent once it occurs.  The tests are run single threaded, but these are system tests, so there may be background threads executing code concurrently with the tests.

**Comment by headius** [comment] 2024-11-07 23:33
@kalenp I have made a PR to pre-generate all the specialized RubyObject classes, which means they'll be at the same classloader level as JRuby and that should fix this. But I'm still curious how it happened.

I tried to come up with a reproduction locally–not racing, mind you–and failed. My theory was that a superclass Foo had variables and generated its RubyObject1 class, and then a subclass Bar tried to implement an interface and failed to find RubyObject1. But that doesn't seem to fail, and the resulting Java class has the correct hierarchy.

I did notice, however, that the existing RubyObjectSpecializer, which creates these specialized subclasses, uses a static final reference to a classloader for creating all these types. That should be fine; any classloader that can see that static final variable should be able to use the same generated classes. However we use other classloaders for the generated interfaces, and they are not children of this classloader. At the very least we should not use this static classloader and use one that other generated classes will see and live within.

It's also possible that by being static final and used across multiple JRuby instances, this hits a thread-safety issue in the classloading chain. I doubt our dynamic class generation is using thread-safe classloaders.

So #8414 is the PR that avoids any runtime generation, and that should definitely fix the problem. However I'll also try to fix it without pre-generating the classes... would you be able to verify these changes and see if they eliminate the errors?

**Comment by kalenp** [comment] 2024-11-13 23:27
Managed to get a local reproduction, though it's still quite large.  Looks like it does not depend on running with `--debug`, as I have disabled that in the local version.  It currently appears to be an ordering issue of some sort, since it repros consistently when I run the test suite with a fixed test ordering, but not when the same tests run in differently sliced and ordered groups.  I'll continue to work on reducing the repro size (currently a suite of 900 tests) to something more manageable to see if that produces any insights.

**Comment by kalenp** [comment] 2024-11-14 22:24
Managed to get this down to a reasonable repro.  

```
class BaseRubyClass
end

class ExtendedRubyClass < BaseRubyClass
  include Java::ComGoogleCommonCache::Cache
end

BaseRubyClass.new
ExtendedRubyClass.new
```

Not all java interfaces seem to trigger this, and I have yet to find an instance from the SDK that will trigger it.  Still haven't figure out the pattern of what distinguishes the offending interfaces from those which work.

The order of instantiation is also important here.  If you swap them so that ExtendedRubyClass is instantiated before BaseRubyClass, then it runs correctly.

With this minimal repro, the backtrace is:
```
Unhandled Java exception: java.lang.NoClassDefFoundError: org/jruby/gen/RubyObject1
java.lang.NoClassDefFoundError: org/jruby/gen/RubyObject1
         defineClass1 at java/lang/ClassLoader.java:-2
          defineClass at java/lang/ClassLoader.java:1017
          defineClass at org/jruby/util/ClassDefiningJRubyClassLoader.java:53
  defineRealImplClass at org/jruby/java/codegen/RealClassGenerator.java:552
  createRealImplClass at org/jruby/java/codegen/RealClassGenerator.java:162
    generateRealClass at org/jruby/javasupport/Java.java:1607
             allocate at org/jruby/java/proxies/JavaInterfaceTemplate.java:299
             allocate at org/jruby/RubyClass.java:234
          newInstance at org/jruby/RubyClass.java:882
                 call at org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1
                 call at org/jruby/internal/runtime/methods/JavaMethod.java:332
         cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:351
                 call at org/jruby/runtime/callsite/CachingCallSite.java:144
     invokeOther4:new at test/test_jruby_classgen_error.rb:12
          RUBY$script at test/test_jruby_classgen_error.rb:12
                  run at test/test_jruby_classgen_error.rb:-1
  invokeWithArguments at java/lang/invoke/MethodHandle.java:710
                 load at org/jruby/ir/Compiler.java:114
            runScript at org/jruby/Ruby.java:1262
          runNormally at org/jruby/Ruby.java:1181
          runNormally at org/jruby/Ruby.java:1163
          runNormally at org/jruby/Ruby.java:1199
          runFromMain at org/jruby/Ruby.java:980
        doRunFromMain at org/jruby/Main.java:408
          internalRun at org/jruby/Main.java:292
                  run at org/jruby/Main.java:237
                 main at org/jruby/Main.java:209
```

Now that I have this reduced, I'm also able to confirm that it's still present in the latest 9.4 release.

**Comment by headius** [comment] 2024-11-15 20:42
This fits my expectations. When the base class gets instantiated first, it generates its specialized class into the classloader dedicated to that task. The interface implementation class then gets instantiated, which triggers generating its class, which needs to extend the generated class for the base. But the two generators use different classloaders so the bar class cannot be found. 

The simple fix would be to use the same classloader, but eliminating the specialized class generation at runtime (by pre-generating) also fixes it.

**Comment by headius** [comment] 2024-11-18 21:08
I believe it only fails when the interface to be implemented is loaded at runtime via `require`. The interface will be loaded into the JRubyClassLoader for the runtime, which is not related to the classloader used for generating the specialized object classes (RubyObject1 etc), so it is unable to resolve a classloader hierarchy that contains both the interface and the specialized superclass.

```
[] jruby $ cat tmp/foo/Foo.java 
package foo;

public interface Foo {}
[] jruby $ javac -d tmp tmp/foo/Foo.java      
[] jruby $ jar cf foo.jar -C tmp foo/Foo.class
[] jruby $ cat blah.rb  
require './foo.jar'

class BaseRubyClass
end

BaseRubyClass.new

class ExtendedRubyClass < BaseRubyClass
  include Java::foo.Foo
end

ExtendedRubyClass.new
[] jruby $ jruby blah.rb
Unhandled Java exception: java.lang.NoClassDefFoundError: org/jruby/gen/RubyObject0
java.lang.NoClassDefFoundError: org/jruby/gen/RubyObject0
         defineClass1 at java/lang/ClassLoader.java:-2
          defineClass at java/lang/ClassLoader.java:757
          defineClass at org/jruby/util/ClassDefiningJRubyClassLoader.java:58
  defineRealImplClass at org/jruby/java/codegen/RealClassGenerator.java:552
  createRealImplClass at org/jruby/java/codegen/RealClassGenerator.java:162
    generateRealClass at org/jruby/javasupport/Java.java:1607
             allocate at org/jruby/java/proxies/JavaInterfaceTemplate.java:296
             allocate at org/jruby/RubyClass.java:250
          newInstance at org/jruby/RubyClass.java:914
...
```

**Comment by headius** [comment] 2024-11-18 22:52
@kalenp Fixes are on the way but the next release has not yet been scheduled.

A workaround for you would be to disable the specialized classes using the `-Xreify.variables=false` flag to JRuby or the JVM property `jruby.reify.variables=false`. This will cause objects to use more memory, since they won't have access to the specialized classes, but with no specialized classes being generated you won't trigger the bug.

**Comment by kalenp** [comment] 2024-11-18 23:09
Just verified that we're only hitting this in CI, not production, and we've temporarily quarantined those tests.  Must just be that we're loading the classes in a different order in the testing environment.  I can try the extra options in CI to see if that allows us to reinstate those tests.

Thank you for the fix!

**Comment by headius** [comment] 2024-11-18 23:19
If all other settings are basically the same in production, it may just be a happy accident that you don't see the issue there. Tests may instantiate objects in a different (unusual) order than normal production usage, which would allow the interface implementations to be generated based on unspecialized superclasses. It is certainly possible that production could start to show the issue if other changes alter that order. 

Thank you for checking whether the suggested flag fixes the issue in CI. That would be a reasonable workaround for production environments as well, memory increase notwithstanding. The fix will definitely go out in the next JRuby in 9.4, whenever we get that released.

**Closed** 2024-11-20 14:15 UTC
