### ISSUE TITLE
Backtrace in ArgumentError is wrong sometimes

### ISSUE THREAD

**Issue by jensnockert** [jruby/jruby#3624] opened 2016-01-28 19:25 UTC
This is on `jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 24.79-b02 on 1.7.0_79-b15 +jit [darwin-x86_64]`

I can't say what exactly is wrong except that the last frame in the Ruby-only trace is wrong, or what is triggering it. My feeling is that the method name and arity message is correct, and that the last frame is just wrong filename/line number. But since it is inside ActiveRecord (which has internals I'm not confident with) I can't say for sure if anything else is wrong.

https://gist.github.com/jensnockert/078e74541c6d50989ce8

**Comment by kares** [comment] 2016-01-29 06:37
seems like another AR-JDBC incompatibility with Rails [master](https://github.com/rails/rails/tree/bb4c63c70368c6f0189bf1f380ef66c07d7de40d) ... the schema definition is passed wrong number of args?

**Comment by jensnockert** [comment] 2016-01-29 08:46
The incompatability isn't the jruby bug, that part I have fixed. The bug is that the backtrace points to a line that doesn't exist in AR.

**Comment by headius** [comment] 2016-03-04 18:22
This looks like it's running with `-Xbacktrace.style=full`, which prints all internal `.java` lines and sometimes confounds backtrace-processing libraries. Perhaps that's all that's going on here?

**Comment by jensnockert** [comment] 2016-03-04 19:25
There's one below without `-Xbacktrace.style=full`, it has the same issue.

**Comment by doudou** [comment] 2016-03-25 00:04
I experience the same problem with, in my case, a TypeError pointing to the wrong place. Not related to Rails or activerecord, it's purely my own code

```
/home/doudou/dev/rock/toolchain-devel/jruby/tools-roby/lib/roby/execution_engine.rb:247:in `process_events_synchronous'
/home/doudou/dev/rock/toolchain-devel/jruby/tools-roby/lib/roby/event_generator.rb:247:in `call'
```

The interesting bit is that the line reported in execution_engine.rb is the same than the line in event_generator.rb. The latter makes sense, the former is idiotic (the line points to a attr_reader definition, miles away from the process_events_synchronous method).

One can find the same pattern in the gist from @jensnockert: the next-to-last file/line is good, the last line makes no sense and reports the same line number than next-to-last.

Tested on jruby 9.0.5.0. I'm installing 9.0.3.0 to see if there's the same issue there.

**Comment by doudou** [comment] 2016-03-25 00:05
FYI, jruby 9.0.3.0 has the same issue

**Comment by doudou** [comment] 2016-03-25 00:06
More precisely,

```
jruby 9.0.3.0 (2.2.2) 2015-10-21 633c9aa Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 +jit [linux-amd64]
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 +jit [linux-amd64]
```

Both installed using rbenv

**Comment by doudou** [comment] 2016-03-27 18:06
Some more information: the exception in my case is caused by JRuby when calling the method itself (process_events_synchronous), while checking the keyword args. The call is IMO legit, i.e. the exception is probably raised within JRuby's own code, but we'll see about that [here](https://github.com/jruby/jruby/issues/3760)

From the point of view of this issue, it looks like the line number is not updated properly when resolving a call, while the file is (the file is the file of the called method, the line number the line number of the call site). This hunch comes from the full backtrace in my case:

```
    org/jruby/ir/runtime/IRRuntimeHelpers.java:589:in `checkForExtraUnwantedKeywordArgs'
    org/jruby/ir/runtime/IRRuntimeHelpers.java:543:in `checkArity'
    org/jruby/ir/instructions/CheckArityInstr.java:69:in `checkArity'
    org/jruby/ir/interpreter/InterpreterEngine.java:390:in `processBookKeepingOp'
    org/jruby/ir/interpreter/StartupInterpreterEngine.java:111:in `interpret'
    org/jruby/ir/interpreter/InterpreterEngine.java:86:in `interpret'
    org/jruby/internal/runtime/methods/InterpretedIRMethod.java:193:in `INTERPRET_METHOD'
    /home/doudou/dev/rock/toolchain-devel/jruby/tools-roby/lib/roby/execution_engine.rb:661:in `process_events_synchronous'
    org/jruby/internal/runtime/methods/InterpretedIRMethod.java:180:in `call'
    org/jruby/internal/runtime/methods/DynamicMethod.java:197:in `call'
    org/jruby/runtime/callsite/CachingCallSite.java:313:in `cacheAndCall'
    org/jruby/runtime/callsite/CachingCallSite.java:163:in `call'
    org/jruby/ir/interpreter/InterpreterEngine.java:316:in `processCall'
    org/jruby/ir/interpreter/StartupInterpreterEngine.java:77:in `interpret'
    org/jruby/ir/interpreter/InterpreterEngine.java:80:in `interpret'
    org/jruby/internal/runtime/methods/InterpretedIRMethod.java:165:in `INTERPRET_METHOD'
    /home/doudou/dev/rock/toolchain-devel/jruby/tools-roby/lib/roby/event_generator.rb:661:in `emit'
    org/jruby/internal/runtime/methods/InterpretedIRMethod.java:152:in `call'
    org/jruby/internal/runtime/methods/DynamicMethod.java:189:in `call'
    org/jruby/runtime/callsite/CachingCallSite.java:293:in `cacheAndCall'
    org/jruby/runtime/callsite/CachingCallSite.java:131:in `call'
    org/jruby/ir/interpreter/InterpreterEngine.java:332:in `processCall'
    org/jruby/ir/interpreter/StartupInterpreterEngine.java:77:in `interpret'
    org/jruby/ir/interpreter/Interpreter.java:132:in `INTERPRET_BLOCK'
    test/test_event_generator.rb:33:in `block in test_emit_without_propagation_raises'
```

**Comment by kares** [comment] 2017-01-18 11:12
there's no reproduction case here thus if smone is experiencing the issue (on latest 9.1) please include code

**Comment by enebo** [comment] 2017-05-17 16:36
Yeah I have personally fixed some line number issues since the last update but without something we can run to repro this issue is just languishing.  So if someone can make a repro we can sink our teeth into then re-open or create a new issue.

**Closed by enebo** 2017-05-17 16:36 UTC
Labels: feedback needed, JRuby 9000
