### ISSUE TITLE
gem install failure on Windows

### ISSUE THREAD

**Issue by djberg96** [jruby/jruby#2500] opened 2015-01-22 18:27 UTC
Windows 7
jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) Client VM 24.51-b03 on 1.7.0_51-b13 +jit [Windows 7-x86]
    
    C:\>jruby -S gem install test-unit
    ERROR:  Loading command: install (Win32::Registry::Error)
    The system cannot find the file specified.
    ERROR:  While executing gem ... (NoMethodError) undefined method `invoke_with_build_args' for nil:NilClass

**Comment by pandar1** [comment] 2015-01-26 14:39
same here on win server 2003

**Comment by djberg96** [comment] 2015-01-26 15:06
I've traced it to the 'load_and_instantiate' method in the command_manager.rb file. It looks right, but it's failing to load for some reason. Still digging.

**Comment by amistryGithub** [comment] 2015-01-26 19:53
Hi
I ran into same issue when trying to install cucumber gem.   Any luck @djberg96 ?

**Comment by djberg96** [comment] 2015-01-26 22:54
Not yet. I'm not even sure how win32-registry even enters into it.

**Comment by djberg96** [comment] 2015-01-26 23:08
Ok, it's trying to require rubygems/commands/install_command.rb. Which in turn makes several require calls. I tried calling them individually, until I found one that failed. Narrowed it down to rubygems/dependency_installer.rb:

    irb(main):003:0> require 'rubygems/dependency_installer'
    Win32::Registry::Error: The system cannot find the file specified.
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/registry.rb:319:in `QueryValue'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/registry.rb:642:in `read'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/registry.rb:702:in `read_s_expand'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/resolv.rb:129:in `get_hosts_dir'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/registry.rb:433:in `open'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/registry.rb:540:in `open'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/resolv.rb:128:in `get_hosts_dir'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/win32/resolv.rb:13:in `get_hosts_path'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/resolv.rb:174:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/remote_fetcher.rb:1:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/remote_fetcher.rb:6:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `__script__'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/spec_fetcher.rb:1:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `__script__'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/spec_fetcher.rb:1:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `__script__'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/dependency_installer.rb:1:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/dependency_installer.rb:5:in `require'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/dependency_installer.rb:5:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `eval'
        from C:/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from (irb):3:in `evaluate'
        from C:/jruby-9.0.0.0.pre1/bin/jirb:13:in `__script__'irb(main):004:0> quit

**Comment by djberg96** [comment] 2015-01-26 23:16
Ok, more tracing, it happens if you "require 'resolve'". Now digging into that.

**Comment by djberg96** [comment] 2015-01-26 23:20
Here's the troublesome call:

    require 'win32/resolv'
    Win32::Resolv.get_hosts_path

MRI returns "C:/Windows/System32/drivers/etc/hosts". JRuby is choking.

**Comment by djberg96** [comment] 2015-01-26 23:37
Alright, narrowed that down even more. Here's the code bringing down the whole shebang.

    require 'win32/registry'
    include Win32

    TCPIP_NT = 'SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'

    Registry::HKEY_LOCAL_MACHINE.open(TCPIP_NT) do |reg|
      reg.read_s_expand('DataBasePath')
    end

**Comment by djberg96** [comment] 2015-01-27 01:16
Alright, I think it's as simple as this:

    C:\jruby-9.0.0.0.pre1\lib\ruby\stdlib\win32>diff -u registry.bak registry.rb
    --- registry.bak        Tue Jan 20 14:43:28 2015
    +++ registry.rb Mon Jan 26 18:09:29 2015
    @@ -280,7 +280,7 @@
           end

           def make_wstr(str)
    -        str.encode(WCHAR)
    +        str.encode(WCHAR) + 0.chr.encode(WCHAR)
           end

           def OpenKey(hkey, name, opt, desired)

After I made that change, it's working for me.

**Comment by djberg96** [comment] 2015-01-27 02:38
I should also add that I commented out all the win9x code logic.

**Comment by headius** [comment] 2015-01-27 02:48
Hot damn, I love simple fixes. Wanna throw that and deleting the 9x logic (which I assume is gone from MRI as well) into a PR?

Anything else we can do to make our versions more similar to or exactly like MRI would be VERY welcome.

**Comment by djberg96** [comment] 2015-01-27 02:57
Just to clarify, the Windows 9x code I commented out was in resolv.rb. That's still in MRI.

**Comment by headius** [comment] 2015-01-27 03:17
Ahh, well the fix alone will be fine then :-) I doubt JRuby could run on 9x, but I hate maintaining stdlib diffs.

**Comment by michaelbuckner** [comment] 2015-01-29 13:22
I ran into a similar issue and made the same change as @djberg96 above. Unfortunately for me this did not resolve my issue.

>gem install rails
ERROR:  Loading command: install (LoadError)
        load error: jopenssl/load -- java.lang.NullPointerException: null
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

**Comment by djberg96** [comment] 2015-01-29 13:49
@michaelbuckner I realized after reading your post that I've had my gem source set to "http://rubygems.org" for a long time. I think I got fed up with openssl errors. But, even after setting it back to "https://rubygems.org" I don't see an error.

Does it go away if you change your source to not use https? Not an ideal solution perhaps, but helps us nail down the issue.

**Comment by michaelbuckner** [comment] 2015-01-29 14:04
Nope, it does not.

gem install rails --source http://rubygems.org
ERROR:  Loading command: install (LoadError)
        load error: jopenssl/load -- java.lang.NullPointerException: null
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

**Comment by djberg96** [comment] 2015-01-29 14:09
Well, it was worth a shot. An NPE is a Java issue, though. Can you tell us more about your environment? Version of Windows, Java, etc.

**Comment by michaelbuckner** [comment] 2015-01-29 18:18
Windows 7 Ultimate 64bit
JRE Bundled with latest jruby installer (tried 1.8 too)

**Comment by djberg96** [comment] 2015-01-29 18:22
@michaelbuckner I would file a separate issue.

**Comment by michaelbuckner** [comment] 2015-01-29 18:25
I did ; )

Thanks for your help.

**Comment by amistryGithub** [comment] 2015-01-30 04:13
Apparently, it seems the issue was with the jRuby 9 pre installation
missing some files.  I re-installed a new JRuby 9 pre and that resolved the
issue.

**Comment by headius** [comment] 2015-02-23 18:55
Closing the loop on this...

The original issue was caused by win32/registry.rb not constructing wstrings properly. FFI will append a null character to strings, but only when declared as :string, which is currently always just a byte string. This should be improved, but in the short term since we're working with plain pointers we need to manually append the null bytes.

I believe this is resolved by #2523, and we have a separate issue for the NPE that @michaelbuckner reported.

**Closed by headius** 2015-02-23 18:55 UTC
Labels: JRuby 9000, windows
