### ISSUE TITLE
Bundler won't use dependency API in 2.0 mode for JRuby 1.7.18

### ISSUE THREAD

**Issue by rosenfeld** [jruby/jruby#2457] opened 2015-01-13 19:16 UTC
It boils down to this according to my experiments:

```
irb -r net/http -r openssl
irb(main):001:0> Net::HTTP.get 'bundler.rubygems.org', '/api/v1/dependencies?gems=railties,actionmailer,sprockets-rails,sprockets,puma,foreman,jruby-openssl,rsolr,activesupport,rake,rspec,guard-rspec,nokogiri,tidy_ffi,fakefs,pry-byebug'
=> ""
```

The response is not empty as you can confirm by either downloading the URL or running this on MRI or on 1.9 mode.

**Comment by Who828** [comment] 2015-01-14 06:16
I can confirm that it's working on master (JRuby 9000) with 2.x mode. 
guess this will be fixed once its out.

**Comment by headius** [comment] 2015-01-14 13:53
One liner that reproduces this on 1.7:

```
jruby -rnet/http -ropenssl -e "p Net::HTTP.get 'bundler.rubygems.org', '/api/v1/dependencies?gems=railties,actionmailer,sprockets-rails,sprockets,puma,foreman,jruby-openssl,rsolr,activesupport,rake,rspec,guard-rspec,nokogiri,tidy_ffi,fakefs,pry-byebug'"
```

**Comment by mkristian** [comment] 2015-01-14 13:56
I needed to add ```--2.0```:

```
jruby --2.0 -rnet/http -ropenssl -e "p Net::HTTP.get 'bundler.rubygems.org', '/api/v1/dependencies?gems=railties,actionmailer,sprockets-rails,sprockets,puma,foreman,jruby-openssl,rsolr,activesupport,rake,rspec,guard-rspec,nokogiri,tidy_ffi,fakefs,pry-byebug'"
```

**Comment by headius** [comment] 2015-01-14 14:15
Oh, right, you need that too :-)

**Comment by perlun** [comment] 2015-01-14 15:31
Does this work properly on older JRuby 1.7 versions?

**Comment by rosenfeld** [comment] 2015-01-14 15:46
This is the only one I tried. I wanted to test one request in my app without the GVL in MRI, that is how I found out this issue...

**Comment by rosenfeld** [comment] 2015-02-02 18:12
This issue also prevents rbenv from installing JRuby if you have `compat.version=2.0` in your ~/.jrubyrc, which is my case:

https://github.com/sstephenson/ruby-build/issues/718

**Comment by hathawad** [comment] 2015-06-25 15:15
This works properly in JRuby 1.7.13

**Comment by rosenfeld** [comment] 2015-06-25 18:50
Weird... I just checked that one-liner with 1.7.19 and it worked... Maybe the guys in bundler.rubygems.org changed something that affected this somehow... Not sure how to proceed from here... Should we close this ticket and re-open if it happens again? I suspect there's still some hidden bug but now it's no longer reproducible...

**Comment by digitalextremist** [comment] 2015-07-18 21:09
This is occurring with `1.7.21`

**Comment by kares** [comment] 2017-05-23 10:26
closing since this was a JRuby 1.7.x issue ... seems fine by now (on JRuby 1.7.25+ using Bundler 1.13)

**Closed by kares** 2017-05-23 10:26 UTC
Labels: JRuby 1.7.x
