### ISSUE TITLE
Windows 10 Native subprocess control ... sun.nio.ch

### ISSUE THREAD

**Issue by linojon** [jruby/jruby#6461] opened 2020-11-11 17:50 UTC
Hello. Installed jRuby first time on Windows 10 and get this error 

```
[main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist' to enable.
```

I've seen other references to this message but they're mostly closed. If there's a fix how do i add it? Thanks.

Installed jruby-9.2.13.0 from https://www.jruby.org/download
"JRuby 9.2.13.0 Windows Executable (x64) (md5, sha1, sha256)"

![image](https://user-images.githubusercontent.com/68624/98845986-75dc7b00-241c-11eb-9f8d-9609d01c8586.png)

**Comment by headius** [comment] 2020-11-12 05:00
This is not an error... it is just a warning from the JDK that we are digging around in classes that are not open for such uses. Normally we open up the packages and classes in question, but I think the native .exe binary we ship with the Windows distribution has not been updated to have those JVM flags.

We have open issues for updating this binary, such as #6155.

Since you appear to be running this under the MinGW environment, you may be able to use the jruby.bash script provided in the bin/ dir along with jruby.exe. If it works, you could delete the .exe and copy bin/jruby.bash to bin/jruby.

If that is not an option, my recommendation would be to either ignore the warning (it won't break anything) or add the suggested flag to your JAVA_OPTS environment variable like this:

```
set JAVA_OPTS="--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist"
```
(adjusted as appropriate for whatever shell you are using in Windows)

**Comment by headius** [comment] 2020-11-12 05:00
Marking as a dupe of #6155.

**Closed by headius** 2020-11-12 05:00 UTC
