### ISSUE TITLE
AsciidoctorJ build fails on Windows 10 with JRuby 9.1.0.0

### ISSUE THREAD

**Issue by robertpanzer** [jruby/jruby#3862] opened 2016-05-08 18:13 UTC
### Environment

JRuby 9.1.0.0 on Windows 10.
No gems installed but using Asciidoctor installed with the jruby-gradle plugin.

### Expected Behavior

AsciidoctorJ runs with 9.1.0.0 :-)

### Actual Behavior

I just tried to build the current AsciidoctorJ 1.6.0 branch with JRuby 9.1.0.0.
Unfortunately the tests fail with this error:

```
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: C:/Users/foo/asciidoctorj/asciidoctorj-core/build/resources/test/documentwithnotexistingfile.adoc: Failed to load AsciiDoc document - can't modify frozen String
    at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1437)
    at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1409)
    at org.jruby.RubyKernel.warn(org/jruby/RubyKernel.java:1167)
    at RUBY.preprocess_include(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:868)
    at RUBY.process_line(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:632)
    at RUBY.peek_line(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:162)
    at RUBY.peek_line(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:665)
    at RUBY.skip_blank_lines(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:319)
    at RUBY.next_section(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:278)
    at RUBY.parse(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:67)
    at RUBY.parse(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:471)
    at RUBY.load(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1344)
    at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1462)
    at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
    at RUBY.convertFile(<script>:68
```

The last line of Asciidoctor in question is:
```ruby
          warn %(asciidoctor: WARNING: #{line_info}: include file not found: #{include_file})
```

I don't get these errors on OS X.

I filed the same issue as https://github.com/asciidoctor/asciidoctor/issues/1752 as I am not sure if it related to JRuby 9.1.0.0 or Asciidoctor.
At least the same code runs on JRuby < 9.1.0.0.

**Comment by mojavelinux** [comment] 2016-05-08 23:31
The same code also works on Linux.

**Comment by headius** [comment] 2016-05-09 21:23
Dupe of #3855.

**Closed by headius** 2016-05-09 21:23 UTC
