### ISSUE TITLE
Pre-epoch times are rounded up by #to_i 

### ISSUE THREAD

**Issue by p-mongo** [jruby/jruby#6104] opened 2020-03-03 01:03 UTC
When a pre-Unix epoch time is converted to the timestamp, JRuby rounds the value up rather than down.

MRI:

<pre>
speed% ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
speed% irb
irb(main):001:0> time = Time.utc(1960, 1, 1, 0, 0, 0, 999_999)
irb(main):002:0> time.to_f
=> -315619199.000001
irb(main):003:0> time.to_i
=> -315619200
</pre>

JRuby:

<pre>

speed% ruby -v                 
jruby 9.2.11.0 (2.5.7) 2020-03-02 612d7a05a6 OpenJDK 64-Bit Server VM 25.171-b11 on 1.8.0_171-8u171-b11-2-b11 +jit [linux-x86_64]
speed% irb
irb(main):001:0> time = Time.utc(1960, 1, 1, 0, 0, 0, 999_999)
=> 1960-01-01 00:00:00 UTC
irb(main):002:0> time.to_f
=> -315619199.000001
irb(main):003:0> time.to_i
=> -315619199
</pre>

The times should be rounded down so that comparisons like `foo <= upper_bound`, when upper_bound has a fractional second, [continue to exclude the following second](https://jira.mongodb.org/browse/RUBY-2145).

**Comment by headius** [comment] 2020-03-03 14:41
Looks like the specs are super weak here, maybe you could help fill them out? (Submitting to JRuby is good... they will get merged back to https://github.com/ruby/spec periodically.)

https://github.com/jruby/jruby/blob/0694db42019c06bce2ff0fff0ba45012b5950d9e/spec/ruby/core/time/shared/to_i.rb

So it seems the issue is that we're rounding toward zero rather than rounding down. Shouldn't be too hard to fix.

**Comment by headius** [comment] 2020-03-03 16:32
Looks like we're just truncating:

https://github.com/jruby/jruby/blob/cf4d39c354995a6c67fb86334b2cefe350d5938c/core/src/main/java/org/jruby/RubyTime.java#L835

**Comment by headius** [comment] 2020-03-03 16:44
Trivial patch:

```diff
diff --git a/core/src/main/java/org/jruby/RubyTime.java b/core/src/main/java/org/jruby/RubyTime.java
index e23732f482..de9a444db6 100644
--- a/core/src/main/java/org/jruby/RubyTime.java
+++ b/core/src/main/java/org/jruby/RubyTime.java
@@ -832,7 +832,7 @@ public class RubyTime extends RubyObject {
 
     @JRubyMethod(name = {"to_i", "tv_sec"})
     public RubyInteger to_i() {
-        return getRuntime().newFixnum(getTimeInMillis() / 1000);
+        return getRuntime().newFixnum(Math.floorDiv(getTimeInMillis(), (long) 1000));
     }
 
     /**
```

@p-mongo Care to write up a couple specs and I'll get this merged?

**Comment by p-mongo** [comment] 2020-03-04 00:44
I will work on it.

**Closed** 2020-04-07 13:05 UTC
