### ISSUE TITLE
Creating a new Rails project does not behave like CRuby/MRI

### ISSUE THREAD

**Issue by StaringSkyward** [jruby/jruby#6114] opened 2020-03-09 14:38 UTC
**Environment Information**

***Version***
```
root@6b47e212214f:/app# ruby --version
jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-b10 +jit [linux-x86_64]
```
(Verified with `jruby:latest` docker image running under docker on Mac and Linux)

***Environment***
```
root@6b47e212214f:/app/jruby_on_rails# env | sort
BUNDLE_APP_CONFIG=/usr/local/bundle
BUNDLE_BIN=/usr/local/bundle/bin
BUNDLE_PATH=/usr/local/bundle
BUNDLE_SILENCE_ROOT_WARNING=1
GEM_HOME=/usr/local/bundle
HOME=/root
HOSTNAME=6b47e212214f
JAVA_BASE_URL=https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jre_
JAVA_HOME=/usr/local/openjdk-8
JAVA_URL_VERSION=8u222b10
JAVA_VERSION=8u222
JRUBY_SHA256=b7c58688093f54acd89d732a8bf40e3ae0ac4c92488d6f5b424c33e4fb09c7bb
JRUBY_VERSION=9.2.8.0
LANG=C.UTF-8
OLDPWD=/app
PATH=/usr/local/bundle/bin:/opt/jruby/bin:/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app/jruby_on_rails
SHLVL=1
TERM=xterm
_=/usr/bin/env
```

***Gems***
```
rails --version
Rails 6.0.2.1
```

**Steps to Reproduce**
On a Mac or Linux host with docker, grab the latest JRuby image:

`docker run -it --rm -v `pwd`:/app -w /app jruby:latest bash`

Inside the image, install Rails:
`gem install rails`

Once Rails is installed, create a new Rails project:
`rails new jruby_on_rails_project --database=jdbcpostgresql`

**Expected Behavior**
JRuby should produce a skeleton Rails project as MRI Ruby does with the obvious exceptions of the JRuby specific gems and configuration differences.

**Actual Behavior**
Just a few files are present, no directories or rails app proper:

```
root@6b47e212214f:/app# cd jruby_on_rails/
root@6b47e212214f:/app/jruby_on_rails# find . -type f
./.ruby-version
./config.ru
./README.md
./Rakefile
./.gitignore
./Gemfile
```
JRuby exhibits the same behaviour for both a conventional Rails web app and an API app using the `--api` switch to `rails new`.

**Comment by headius** [comment] 2020-03-10 18:41
Hmm, I tried locally (not in a Docker container) and it generates correctly:

```
[] ~/projects/jruby $ rails new jruby_on_rails_project --database=jdbcpostgresql
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/headius/projects/jruby/jruby_on_rails_project/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
...
```

**Comment by headius** [comment] 2020-03-10 18:50
Reproduced following your instructions!

```
root@9380614df38a:/app# rails new jruby_on_rails_project --database=jdbcpostgresql
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
root@9380614df38a:/app# 
```

It looks like it bails out attempting to initialize the git repository in the new app. That's likely because git is not available in this image! It's a poor way to terminate, though...so that seems like a bug.

With git installed, it works as expected:

```
root@9380614df38a:/app# which git
/usr/bin/git
root@9380614df38a:/app# rails new jruby_on_rails_project --database=jdbcpostgresql
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /app/jruby_on_rails_project/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
...
```

**Comment by headius** [comment] 2020-03-10 18:57
Note also there's at least one library that attempts to run `make` even though it doesn't build anything for JRuby (the Makefile gets stubbed out):

```
Fetching bindex 0.8.1
Installing bindex 0.8.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/bundle/jruby/2.5.0/gems/bindex-0.8.1/ext/skiptrace
/opt/jruby/bin/jruby -I /opt/jruby/lib/ruby/stdlib -r
./siteconf20200310-669-1qxnhey.rb extconf.rb

current directory: /usr/local/bundle/jruby/2.5.0/gems/bindex-0.8.1/ext/skiptrace
make "DESTDIR=" clean
sh: 1: make: not found
```

The base jruby docker image needs a bit more stuff to generate a Rails app.

Perhaps should be added @lopex @enebo?

**Comment by headius** [comment] 2020-03-10 19:02
There may not be a bug here? It seems like `git` gets run via `thor`, which has this code:

```ruby
...
      if config[:capture]
        require "open3"
        result, status = Open3.capture2e(*env_splat, command.to_s)
        success = status.success?
      else
        result = system(*env_splat, command.to_s)
        success = result
      end

      abort if !success && config.fetch(:abort_on_failure, self.class.exit_on_failure?)
...
```

On JRuby and CRuby both, calling `system` with an non-existent command quietly just returns nil, and this `abort` call does not include a message to be displayed.

This probably should be filed as a bug (or enhancement) for thor.

**Comment by headius** [comment] 2020-03-10 19:06
I'm closing this since there doesn't appear to be a JRuby bug. It's up for debate whether the JRuby docker image should include `git` and `make`, since they appear to be needed for generating Rails 6+ apps, but I feel like most folks would rather make that decision themselves.

I would suggest refiling this with Rails first, since it should be easy to reproduce with CRuby when the `git` command is not present. Thor is working as written, but may need an enhancement to present an error when the requested command is not available. I'll leave that to you and Rails core to determine.

**Closed by headius** 2020-03-10 19:06 UTC

**Comment by enebo** [comment] 2020-03-10 19:25
I believe rails has an issue open (which may have already been resolved) on not giving a proper error message or working around git not being present.
