### ISSUE TITLE
ConditionVariable#wait causes thread to wait forever in 9.2.8.0

### ISSUE THREAD

**Issue by asppsa** [jruby/jruby#5863] opened 2019-09-09 06:33 UTC
### Environment

+ `jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 25.222-b05 on 1.8.0_222-b05 +jit [linux-x86_64]`
+ `Linux managua 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux`
+ This issue appears to affect only 9.2.8.0.  From my testing, the issue is not present in 9.2.7.0, or in 9.1.x.
+ It does not involve any gems - just core libraries.

### Expected Behaviour

Running [this file](https://gist.github.com/asppsa/c74b654a006475c44729cc57cd3fd86e#file-test-rb) should result in "ping" and "pong" being printed repeatedly to the screen.  This works on MRI and on older versions of JRuby.

### Actual Behaviour

"ping" and "pong" are printed some number of times (it varies), and then output stops.  [Output from Ctrl+\\](https://gist.github.com/asppsa/c74b654a006475c44729cc57cd3fd86e#file-output-from-ctrl) indicates that both the main thread and Thread-1 are in a waiting state.

### Additional info

This issue has been filed on advice from @headius, after a conversation on IRC. He has suggested that https://github.com/jruby/jruby/commit/bea9ad42f62e24a3963e135f2138c75a716f7790 is the source of the issue.

**Comment by headius** [comment] 2019-09-11 20:39
Thank you for filing this one! This definitely should be fixed for 9.2.9.

**Comment by headius** [comment] 2019-10-16 04:39
Likely the same general issue as #5875.

**Comment by headius** [comment] 2019-10-23 19:01
> Likely the same general issue as #5875.

This does not appear to be the case. That issue is caused by us giving up on the lock immediately upon interrupt and raising an error. The correct behavior is up for debate, but probably should be checking for thread events (raise, kill) and if none exist try to acquire the lock again.

**Comment by headius** [comment] 2019-10-24 05:03
I've pushed a fix for this that actually uses the Mutex's JDK Lock to do the sleeping, via a JDK Condition. Your script runs properly now!

I'm still debating the complexity of the patch, since it required us to start using the native JDK thread state rather than our tightly-controlled synthetic state. This may be fine for general use cases, but there's a few tests that have become unreliable as a result.

Anyway, you can check out #5942 for the current iteration of the fix.

**Closed** 2019-10-26 23:52 UTC
Labels: concurrency, regression
