### ISSUE TITLE
[ffi] ulong type looses precision in 64bit mode

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#6376] opened 2020-08-30 02:01 UTC
**Environment Information**
  
Provide at least:
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-08-29 34d51ab110 Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS on 11.0.2+9-LTS +jit [linux-x86_64]

it's represented as "long" https://github.com/jruby/jruby/blob/b267aa1e495670edcd0c919d92a4228fd3de7944/core/src/main/java/org/jruby/ext/ffi/AbstractMemory.java#L951

**Expected Behavior**
should pass tests

**Actual Behavior**
```
  1) Struct tests ulong field r/w (8000000000000000)
     Failure/Error: s[:v] = obj
   
     RangeError:
       bignum too big to convert into `long'
     # ./spec/ffi/struct_spec.rb:346:in `test_num_field'
     # ./spec/ffi/struct_spec.rb:357:in `block in int_field_test'

  2) Struct tests ulong field r/w (ffffffffffffffff)
     Failure/Error: s[:v] = obj

     RangeError:
       bignum too big to convert into `long'
     # ./spec/ffi/struct_spec.rb:346:in `test_num_field'
     # ./spec/ffi/struct_spec.rb:357:in `block in int_field_test'
```

refs https://github.com/jruby/jruby/pull/6375

**Comment by headius** [comment] 2020-09-16 19:32
Was this fixed by #6375?

**Comment by ahorek** [comment] 2020-09-16 20:28
nope, but it's not a regression. There's a new (commented) test that reveals this problem, see
https://github.com/ffi/ffi/blob/31b4eebdf9dfb7ebd182425b2b4f55b35e34a0cc/spec/ffi/struct_spec.rb#L375

**Comment by headius** [comment] 2020-09-21 22:13
I'll look into this and https://github.com/jnr/jffi/issues/87 a bit this evening.

**Comment by headius** [comment] 2020-09-21 22:50
I believe both tests are passing with #6406. Issue jnr/jffi#87 is a duplicate of this; the error is coming from JRuby, and if it allowed coercing a ulong value into long bits, I believe it passes through to the struct ok.

**Comment by headius** [comment] 2020-09-21 22:55
@ahorek I think I have added you to a team that allows issue triage, including code reviews. Accept that and please review #6406 if you get a chance!

**Closed** 2020-09-22 17:27 UTC
