### ISSUE TITLE
Cannot install latest "selenium-webdriver" gem

### ISSUE THREAD

**Issue by boris-petrov** [jruby/jruby#5708] opened 2019-04-24 12:07 UTC
### Environment

```
%  jruby -v
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 OpenJDK 64-Bit Server VM 11.0.3+4 on 11.0.3+4 +jit [linux-x86_64]
%  uname -a
Linux Boris-Desktop 5.0.8-arch1-1-ARCH #1 SMP PREEMPT Wed Apr 17 14:56:15 UTC 2019 x86_64 GNU/Linux
```

Trying to install `selenium-webdriver` gem after version `3.141.0` (which is the last one that works) fails with:

```
Building native extensions. This could take a while...
ERROR:  Error installing /home/boris/.gradle/caches/modules-2/files-2.1/rubygems/childprocess/1.0.1/2196a2de665622e2135ddfb46c653e4f3e3ede51/childprocess-1.0.1.gem:
        ERROR: Failed to build gem native extension.

    current directory: /home/boris/project/features/build/tmp/jrubyExec/gems/childprocess-1.0.1/ext
/usr/lib/jvm/java-11-openjdk/bin/java -cp :/home/boris/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.7.0/308120bca38f617e7b275af8ce0cbd9f0be66218/jruby-complete-9.2.7.0.jar org.jruby.Main mkrf_conf.rb
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/home/boris/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.
7.0/308120bca38f617e7b275af8ce0cbd9f0be66218/jruby-complete-9.2.7.0.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

current directory: /home/boris/project/features/build/tmp/jrubyExec/gems/childprocess-1.0.1/ext
jrake RUBYARCHDIR=/home/boris/project/features/build/tmp/jrubyExec/extensions/universal-java-11/2.5.0/childprocess-1.0.1 RUBYLIBDIR=/home/boris/projectr/features/build/tmp/jrubyExec/extensions/universal-java-11/2.5.0/childprocess-1.0.1
sh: jrake: command not found

rake failed, exit code 127

Gem files will remain installed in /home/boris/project/features/build/tmp/jrubyExec/gems/childprocess-1.0.1 for inspection.
Results logged to /home/boris/project/features/build/tmp/jrubyExec/extensions/universal-java-11/2.5.0/childprocess-1.0.1/gem_make.out
```

Any ideas?

**Comment by headius** [comment] 2019-04-25 11:57
This appears to be some problem installing the `childprocess` gem that's a downstream dependency of `selenium-webdriver`. Try installing `childprocess` directly, and if you get the same error post a comment pointing at the log file output.

It looks like it's trying to find the command `jrake` but it's not present. We do not normally ship a `jrake` in our bin directory, so I'm not sure why it's choosing this name instead of just `rake`.

**Comment by headius** [comment] 2019-04-25 12:02
I can simulate your error by setting the environment variable `rake` to point to `jrake`. Perhaps you or some tool in your environment is doing the same?

```
$ rake=jrake gem install childprocess
Fetching: childprocess-1.0.1.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing childprocess:
	ERROR: Failed to build gem native extension.

    current directory: /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/childprocess-1.0.1/ext
/Users/headius/projects/jruby/bin/jruby mkrf_conf.rb

current directory: /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/childprocess-1.0.1/ext
jrake RUBYARCHDIR=/Users/headius/projects/jruby/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.3/childprocess-1.0.1 RUBYLIBDIR=/Users/headius/projects/jruby/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.3/childprocess-1.0.1
sh: jrake: command not found

rake failed, exit code 127

Gem files will remain installed in /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/childprocess-1.0.1 for inspection.
Results logged to /Users/headius/projects/jruby/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.3/childprocess-1.0.1/gem_make.out
```

**Comment by boris-petrov** [comment] 2019-04-25 13:08
@headius - thanks for the support. You're right, `sudo jruby -S gem install selenium-webdriver` as well as `sudo jruby -S gem install childprocess` work fine. We're using Gradle and the `com.github.jruby-gradle.base` plugin. I'm not sure how to debug this. I grepped for any `jrake` occurrences in my gems directory but there are none... we don't set anything concerning `rake`/`jrake` at all. There are no mentions of these strings at all in our codebase. How do I approach this?

**Comment by headius** [comment] 2019-04-25 13:24
Ah perhaps this is a problem with the jruby-gradle plugin? I don't believe this a bug in JRuby, since it appears to install just fine directly. I'm guessing the `rake` functionality in jruby-gradle (or some downstream dependency of it) is running the antiquated `jrake` command when these days we generally just prefer `rake` and don't install or ship the `j` versions anymore.

You could try setting the same `rake` environment variable as in my snippit above...otherwise I'm also not sure what we can do to help in JRuby itself. This seems to be a jruby-gradle or environment-specific issue.

**Comment by headius** [comment] 2019-04-25 13:26
Potentially related: https://github.com/robfletcher/gradle-compass/issues/17

**Comment by boris-petrov** [comment] 2019-04-25 14:30
[Searching](https://github.com/jruby-gradle/jruby-gradle-plugin/search?q=jrake&unscoped_q=jrake) for `jrake` doesn't match anything in their repo... very strange. Is there some printing I could put somewhere to figure out who tries to call this command?

**Comment by headius** [comment] 2019-04-25 15:58
@mkristian @rtyler You have any thoughts here? I really don't know enough about the jruby-gradle internals to know how to sort this out.

**Comment by rtyler** [comment] 2019-04-25 16:06
@boris-petrov it would be helpful for me to see some of the `build.gradle` that's expressing these dependencies.

**Comment by boris-petrov** [comment] 2019-04-25 20:46
@headius, @rtyler - thank you for the support!

Create a new directory, put the following in `build.gradle`:

```gradle
plugins {
	id 'com.github.jruby-gradle.base' version '1.6.0'
}

dependencies {
	jrubyExec 'org.jruby:jruby-complete:9.2.7.0'

	jrubyExec 'rubygems:selenium-webdriver:3.142.0'
}

import com.github.jrubygradle.JRubyExec

task foobar(type: JRubyExec) {
	script 'rspec'
}
```

And run `gradle foobar` in it. It fails with the error in my first post. I'm on Gradle 5.2.1.

**Comment by headius** [comment] 2019-04-26 15:23
@boris-petrov Does forcing env var "rake" to be "rake" help? Maybe it will still pick up that environment when run from Gradle?

**Comment by boris-petrov** [comment] 2019-04-26 20:57
If you mean running `rake=rake gradle foobar` - then the error changes to `rake: command not found`... which is actually true, I don't have that command. Should I have it?

**Comment by mkristian** [comment] 2019-04-26 21:11
@boris-petrov not external install of `rake` is not needed. just trying to figure out where things are going wrong. just building your sample project - but taking time with a slow internet connection

have you ever tried to install gem with jruby-complete itself ?
`GEM_HOME=. java -jar jruby-complete.jar -S gem install selenium-webdriver -v 3.142.0`
(hope I got this command right)

**Comment by boris-petrov** [comment] 2019-04-26 21:21
@mkristian - well, I haven't tried your specific command (I'll try it tomorrow) but for me `sudo jruby -S gem install selenium-webdriver` works fine so the problem is somewhere in jruby-gradle I guess. The sample project I gave shouldn't download almost anything... only the plugin and the gem. So it should be fast enough. But please tell me if it doesn't break on your side.

**Comment by mkristian** [comment] 2019-04-26 22:38
@boris-petrov jruby-complete.jar is working so as you said it is something in jruby-gradle-plugin.

**Comment by rtyler** [comment] 2019-04-27 16:20
@boris-petrov Thanks for the reproduction case, I've reproduced this with an older version of Gradle. I'm going to close this ticket and would you mind re-opening something here: https://github.com/jruby-gradle/jruby-gradle-plugin

**Closed by rtyler** 2019-04-27 16:20 UTC
