### ISSUE TITLE
Could JRuby provide a static nightly/latest build URL for easier tooling support?

### ISSUE THREAD

**Issue by PragTob** [jruby/jruby#6092] opened 2020-02-22 22:58 UTC
Hello JRuby friends,

just wanted to report an issue and figured out I lost a good way to easily run current JRuby master.

I know there are [nightly builds](https://www.jruby.org/nightly) but the URL seems to change which makes them somewhat inconvenient for tools.

I'd like to be able to add `jruby-dev` or similar to `ruby-build` similar to what our TruffleRuby friends did recentl: https://github.com/rbenv/ruby-build/pull/1405

but right now I don't see how without advanced trickery :)

Thank you! :green_heart:

**Comment by headius** [comment] 2020-02-22 23:24
@PragTob Yeah this has been requested before and we are interested in setting up a dev build like TruffleRuby has. It's not difficult; `mvn -Prelease` will create the release artifacts. The work to be done is basically just hooking up the appropriate Github actions. I believe @eregon was willing to help us reproduce what TruffleRuby does, but any help you can provide is welcome too!

**Comment by PragTob** [comment] 2020-02-23 12:13
@headius not sure me and my grand maven knowledge would be of much help - I'd love to obviously. Right now it's rather unlikely I'll have time to but maybe smething happens. One thing or another, thank you!

**Comment by eregon** [comment] 2020-02-23 12:16
For now I worked around for supporting `jruby-head` in https://github.com/ruby/setup-ruby by having this little script parse the XML from Maven to find the correct URLs: https://github.com/ruby/jruby-dev-builder/blob/a415a0911c66901939648c622a057f3918f6bd06/find-jruby-head-url.rb

Which actually means https://github.com/ruby/jruby-dev-builder has stable download URLs, but I am unsure we'd want to expose those as official JRuby nightlies, instead we'd probably want a similar repository in the jruby organization?
Obviously the platforms there are a bit GitHub Actions-specific and all 3 non-Windows downloads are probably extremely similar.
Those downloads also ship Bundler 1 + a `ruby` symlink, which might or not be desirable for JRuby nightlies.

@headius If such an approach sounds fine to you, could you create a `jruby-nightly`/`jruby-dev-builds` or so repository in the GitHub jruby organization?
Then we could have a stable URL like
https://github.com/jruby/repo-name/releases/latest/download/jruby-nightly.tar.gz

**Comment by eregon** [comment] 2020-03-31 20:41
Builds on https://github.com/ruby/jruby-dev-builder no longer include Bundler.
They just download the latest snapshot, unpack it, add a `bin/ruby` alias, repack it:
https://github.com/ruby/jruby-dev-builder/blob/master/.github/workflows/build.yml

So maybe they're good enough for JRuby nightlies as-is.
@headius Thoughts?

Stable URLs for those are:
https://github.com/ruby/jruby-dev-builder/releases/latest/download/jruby-head-macos-latest.tar.gz
https://github.com/ruby/jruby-dev-builder/releases/latest/download/jruby-head-ubuntu-16.04.tar.gz
https://github.com/ruby/jruby-dev-builder/releases/latest/download/jruby-head-ubuntu-18.04.tar.gz
https://github.com/ruby/jruby-dev-builder/releases/latest/download/jruby-head-windows-latest.tar.gz

**Comment by headius** [comment] 2020-03-31 22:52
@eregon Yeah that sounds just fine. Would it still be better to move it under the jruby organization? Given that this is used by ruby/setup-ruby it almost seems more appropriate for it to be a sibling project, but maybe there are future changes we need to make that would be better under our org.

**Comment by eregon** [comment] 2020-04-02 18:53
I'd prefer to keep it where it is so all repos related to ruby/setup-ruby are in the same organization. (Sorry, I kind of changed my mind on this)

I would avoid 2 different repositories unless we want some differences in the builds, to make maintenance easier. We can always create a second repository later if some difference is needed.

If you're OK with that I think the next step would be to make a PR to ruby-build like https://github.com/rbenv/ruby-build/pull/1405. I'll let you (or someone else) do that.

**Comment by eregon** [comment] 2020-04-06 20:53
It's for simplicity to mirror how other builds are done for CRuby and TruffleRuby, e.g., at https://github.com/ruby/ruby-builder/releases

We could do without (jruby-dev-builder just adds a `bin/ruby` symlink on those platforms, https://github.com/jruby/jruby/issues/6092#issuecomment-606863041), but it would be extra logic just for JRuby in `setup-ruby` and `ruby-builder`, and we would still need a separate archive for Windows (`bin/ruby` is not a symlink there and we need `bin/ruby.bat`).

If we were to have a single archive for Linux & macOS, how should we name it? (given the existing `jruby-head-windows-latest.tar.gz`)

**Comment by headius** [comment] 2020-05-15 23:08
@PragTob The main part of this has been resolved since @eregon set up https://github.com/ruby/jruby-dev-builder/releases/latest to grab our latest snapshot build each night.

I believe the remaining work for this issue would be to get ruby-build using the same source, and we'd be all set. I do not know where this change needs to be made... could you put together a PR for ruby-build?

**Comment by headius** [comment] 2020-05-15 23:08
Rest of work is in ruby-build, so closing this.

**Closed by headius** 2020-05-15 23:08 UTC

**Comment by eregon** [comment] 2021-06-11 09:38
`jruby-dev` added to ruby-build in https://github.com/rbenv/ruby-build/pull/1773

**Comment by eregon** [comment] 2021-11-07 14:43
> It occurs to me now that you have Linux (two flavors of Ubuntu) and MacOS packages separately. Why is that? We should not build any differently on those platforms.

On this topic, I realized for JRuby release builds at https://github.com/ruby/ruby-builder/releases/tag/toolcache which were done using `ruby-build`, jruby launcher is installed, and so these archives are platform-specific.

For jruby-dev builds at https://github.com/ruby/jruby-dev-builder/releases, jruby-launcher is not included (except maybe on Windows if that's already there?), so the archives are probably not platform-specific currently.

For ruby-build users, this doesn't matter because in either ruby-build installs `jruby-launcher`.

For setup-ruby users, it means when they use `jruby-head` it doesn't have `jruby-launcher` installed.
Is this something we should fix? cc @headius 

Is it always OK to build jruby-launcher on some machine and reuse it on another machine, as long as the OS (so linux/macos/windows, not OS version) and the architecture match?

If we included jruby-launcher in https://github.com/ruby/jruby-dev-builder/releases, and since that's used by `ruby-build`, it means we'd have a amd64 executable in it, even when installing on non-amd64, e.g. darwin-aarch64. ruby-build would still install the gem and probably override some things, but the jruby-launcher gem might have a newer version and then there are probably some amd64-specific files left in that case.
