### ISSUE TITLE
Decreased coverage with 9.1.7.0 snapshot

### ISSUE THREAD

**Issue by donv** [jruby/jruby#4404] opened 2016-12-21 14:06 UTC
jruby 9.1.7.0-SNAPSHOT (2.3.1) 2016-12-21 946befd Java HotSpot(TM) 64-Bit Server VM 25.112-b16 on 1.8.0_112-b16 +jit [darwin-x86_64]

When testing https://travis-ci.org/donv/capybara-screenshot-diff I get a very low coverage percentage using simplecov and JRuby 9.1.7.0-SNAPSHOT.

I get the expected coverage percentage of 86% when using any MRI version since 2.1 and JRuby 9.1.2.0, 9.1.5.0, and 9.1.6.0.

To reproduce:

```
git clone git@github.com:donv/capybara-screenshot-diff.git
cd capybara-screenshot-diff
rake test
```

**Comment by enebo** [comment] 2016-12-21 14:47
@donv Not seeing this on macos at least:

```text
11 files inspected, no offenses detected
Started with run options --seed 42427

  11/11: [=================================] 100% Time: 00:00:02, Time: 00:00:02

Finished in 2.32263s
11 tests, 25 assertions, 0 failures, 0 errors, 0 skips
```

Java was:

```text
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

**Comment by PragTob** [comment] 2016-12-25 09:40
Ha! Fun thing... I just talked to @colszowka (creator of simplecov) a while back about JRuby support etc. and he asked if I'd be willing to join the team and be the JRuby support person and officially support JRuby. We both agreed that chances of this requiring any work/of any regressions would be super low :smile: 

Anyhow, the simplecov specs also [fail on jruby-head now](https://travis-ci.org/colszowka/simplecov/jobs/186604999) and it seems to be exactly the integration tests with different reported coverage values.

I can also confirm the decreased coverage on the repo @donv mentioned:

```
tobi@comfy ~/github/capybara-screenshot-diff $ GEM_HOME=vendor JRUBY_OPTS=--debug ../jruby/bin/jruby -S vendor/bin/bundle exec rake test
Started with run options --seed 61202

  11/11: [=================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.77429s
11 tests, 25 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /home/tobi/github/capybara-screenshot-diff/coverage. 11333 / 26516 LOC (42.74%) covered.
Coverage (42.74%) is below the expected minimum coverage (86.00%).
rake aborted!
Command failed with status (2)
/home/tobi/github/capybara-screenshot-diff/vendor/gems/rake-12.0.0/exe/rake:27:in `<main>'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:1:in `(root)'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `block in start'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/exe/bundle:34:in `<main>'
/home/tobi/github/capybara-screenshot-diff/vendor/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

@enebo there is a switch in the repo that checks if JRuby has `--debug` enabled and doesn't run them unless the switch is set --> with it it runs fine :)

Happy to help in any way to debug this and get it back working for 9.1.7.0 as this is a critical bug/regression for me personally :D

Anyhow, happy holidays to all of you and thanks for all you do :star2:

**Comment by enebo** [comment] 2016-12-27 19:26
@PragTob ah heh...I definitely did not run with --debug so that is why I did not see the issue.  Thanks for pointing that out.

**Comment by enebo** [comment] 2017-01-03 20:18
Bisected this to f9d704c86d51d1a5b0f226aec2299ee4fb887abf ...

**Comment by kares** [comment] 2017-01-04 07:00
so JRuby must potentially dead-locks in a debugging session so that simplecov reports correct coverage ...
maybe there's a remedy of having simplecov improved or not - imagine it relies on an `at_axit` handler

**Comment by PragTob** [comment] 2017-01-04 08:44
[at_exit seems to be used her](https://github.com/colszowka/simplecov/blob/16911081b282c521ee24f65f305bcc8b0a344d79/lib/simplecov/defaults.rb#L52-L90) - I'm not in the simplecov code base that much yet and time is somewhat limited, if you gave me general directions of what'd be the problem/potential fix I could try fixing that :)

also @enebo thanks for bisecting and all the work :) :green_heart:

**Comment by kares** [comment] 2017-01-05 05:54
@PragTob @enebo think its fine to revert and deal with the dead-lock later (might be fixed in ruby-debug)

**Comment by kares** [comment] 2017-01-05 05:57
@enebo see you already reverted on master at https://github.com/jruby/jruby/commit/57ba4fd2034fa70c46f31e216e026b44ee693457 ... thanks, closing

**Closed by kares** 2017-01-05 05:57 UTC
Labels: regression
