### ISSUE TITLE
Multicast Receive Broken On all Unixy machines.

### ISSUE THREAD

**Issue by j2man** [jruby/jruby#5657] opened 2019-03-19 19:29 UTC
### Environment
Logstash 6.6.2 Bundled JRuby
jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 Java HotSpot(TM) 64-Bit Server VM 25.162-b12 on 1.8.0_162-b12 +jit [mswin32-x86_64]

Running on:
Red Hat Enterprise Linux Workstation 7.5 (Maipo)

### Expected Behavior
Call to recvfrom should not generate a socket error.

### Actual Behavior
SocketError: No message available
  block in ./udprcv.rb at ./udprcv.rb:14
                  loop at org/jruby/RubyKernel.java:1292
                <main> at ./udprcv.rb:17

Broken in:
jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 OpenJDK 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [linux-x86_64]

Verified that it works in this release just fine:
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on OpenJDK 64-Bit Server VM 1.8.0_181-b13 +jit [linux-amd64]

Something is broken.

################## Rx Code
require 'socket'
require 'ipaddr'

MCAST_GROUP = {
  :addr => '225.4.5.6',
  :port => 12345,
  :bindaddr => '0.0.0.0'
}

ip =  IPAddr.new(MCAST_GROUP[:addr]).hton + IPAddr.new(MCAST_GROUP[:bindaddr]).h
ton
sock = UDPSocket.new
sock.setsockopt(Socket::IPPROTO_IP, Socket::IP_ADD_MEMBERSHIP, ip)
sock.setsockopt(Socket::SOL_SOCKET, Socket::SO_REUSEPORT, 1)
sock.setsockopt(Socket::SOL_SOCKET, Socket::SO_REUSEADDR, 1)
sock.bind(Socket::INADDR_ANY, MCAST_GROUP[:port])
loop do
  msg, info = sock.recvfrom(1024)
  puts "MSG: #{msg} from #{info[2]} (#{info[3]})/#{info[1]} len #{msg.size}"
end

################## Tx Code
require 'socket'
MCAST_GROUP = {
:addr => '225.4.5.6',
:port => 12345,
}
s = UDPSocket.new
s.setsockopt(Socket::IPPROTO_IP, Socket::IP_MULTICAST_TTL, 1)
s.send("hello", 0, MCAST_GROUP[:addr], MCAST_GROUP[:port])

**Comment by enebo** [comment] 2019-04-08 21:14
This is fixed via #5678.

**Comment by enebo** [comment] 2019-04-08 21:25
It is very unclear what changed here.  I don't see how the implementation before #5678 could have ever worked unless the multicastsocket was something else altogether (since that classes channel is literally return null).  Checked Linux (FC/Ubuntu) and MacOS.  So I have not technically tried RHEL but I would be surprised if it is not fixed since it is pretty plain Java networking code.  The wrinkle is that Win10 (or more specifically my win10 env) is not passing with that code so it is possible some other envs still don't work but I am optimistically resolving for all but windows.

The test in our jruby test suite is reenabled so we should not see any regressions.

**Closed by enebo** 2019-04-08 21:25 UTC

**Comment by j2man** [comment] 2019-04-08 23:32
For Windows 10:

Logstash 5.5.1 ships with:
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on OpenJDK 64-Bit Server VM 1.8.0_181-b13 +jit [linux-amd64]

I have verified that it works in the 1.7.25 release just fine on windows 10 using Logstash 5.5.1

**Comment by j2man** [comment] 2019-04-08 23:37
"...it is possible some other envs still don't work but I am optimistically resolving for all but windows."

There is another issue for the Windows side:
[https://github.com/jruby/jruby/pull/5678]#5678 (wow nice number)
Maybe we can close that on if this fix works on Windows?
