### ISSUE TITLE
[Truffle] Array#at CreateCast not working

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2839] opened 2015-04-16 14:36 UTC
Expected
```
ruby -e '2147483647-(-5);puts ["test_from_sjis","test_to_utf8","test_to_softbank","test_to_kddi","test_to_sjis","test_docomo","test_encoding_name","test_comparison","test_to_eucjp","test_from_utf8"].sort.to_s'
["test_comparison", "test_docomo", "test_encoding_name", "test_from_sjis", "test_from_utf8", "test_to_eucjp", "test_to_kddi", "test_to_sjis", "test_to_softbank", "test_to_utf8"]
```
Actual
```
$ ./bin/jruby -Xtruffle.exceptions.print_java=true -X+T -e '2147483647-(-5);puts ["test_from_sjis","test_to_utf8","test_to_softbank","test_to_kddi","test_to_sjis","test_docomo","test_encoding_name","test_comparison","test_to_eucjp","test_from_utf8"].sort.to_s'
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at org.jruby.truffle.nodes.RubyTypesGen.asLong(RubyTypesGen.java:160)
	at org.jruby.truffle.nodes.coerce.ToIntNodeFactory$ToIntLongNode.executeLongFixnum(ToIntNodeFactory.java:362)
	at org.jruby.truffle.nodes.coerce.ToIntNodeFactory$ToIntLongNode.execute(ToIntNodeFactory.java:343)
	at org.jruby.truffle.nodes.core.FixnumLowerNode.execute(FixnumLowerNode.java:47)
	at org.jruby.truffle.nodes.RubyNode.executeIntegerFixnum(RubyNode.java:85)
	at org.jruby.truffle.nodes.core.FixnumLowerNode.executeIntegerFixnum(FixnumLowerNode.java:127)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$AtNodeFactory$AtRubyArrayNode.execute(ArrayNodesFactory.java:3844)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:65)
	at org.jruby.truffle.nodes.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:145)
	at org.jruby.truffle.nodes.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:108)
	at org.jruby.truffle.nodes.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:53)
	at org.jruby.truffle.nodes.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:35)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:150)
	at org.jruby.truffle.nodes.methods.locals.WriteLocalVariableNodeFactory$WriteLocalVariableUninitializedNode.execute(WriteLocalVariableNodeFactory.java:205)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.control.TryNode.execute(TryNode.java:60)
	at org.jruby.truffle.nodes.RubyNode.executeVoid(RubyNode.java:204)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:80)
	at org.jruby.truffle.nodes.control.WhileNode$WhileRepeatingNode.executeRepeating(WhileNode.java:92)
	at com.oracle.truffle.api.nodes.LoopNode.executeRepeatingNode(LoopNode.java:46)
	at com.oracle.truffle.api.impl.DefaultLoopNode.executeLoop(DefaultLoopNode.java:38)
	at org.jruby.truffle.nodes.control.WhileNode.execute(WhileNode.java:51)
	at org.jruby.truffle.nodes.RubyNode.executeVoid(RubyNode.java:204)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:80)
	at org.jruby.truffle.nodes.control.WhileNode$WhileRepeatingNode.executeRepeating(WhileNode.java:92)
	at com.oracle.truffle.api.nodes.LoopNode.executeRepeatingNode(LoopNode.java:46)
	at com.oracle.truffle.api.impl.DefaultLoopNode.executeLoop(DefaultLoopNode.java:38)
	at org.jruby.truffle.nodes.control.WhileNode.execute(WhileNode.java:51)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.CatchBreakAsReturnNode.execute(CatchBreakAsReturnNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchReturnNode.execute(CatchReturnNode.java:39)
	at org.jruby.truffle.nodes.methods.CatchNextNode.execute(CatchNextNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:65)
	at org.jruby.truffle.nodes.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:145)
	at org.jruby.truffle.nodes.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:108)
	at org.jruby.truffle.nodes.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:53)
	at org.jruby.truffle.nodes.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:35)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:150)
	at org.jruby.truffle.nodes.RubyNode.executeVoid(RubyNode.java:204)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:80)
	at org.jruby.truffle.nodes.methods.CatchNextNode.execute(CatchNextNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchReturnAsErrorNode.execute(CatchReturnAsErrorNode.java:37)
	at org.jruby.truffle.nodes.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:254)
	at org.jruby.truffle.runtime.RubyContext.eval(RubyContext.java:235)
	at org.jruby.truffle.nodes.RubyNode.ruby(RubyNode.java:484)
	at org.jruby.truffle.nodes.core.ArrayNodes$SortNode.sortUsingRubinius(ArrayNodes.java:4683)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$SortNodeFactory$SortObjectNode.executeChained0(ArrayNodesFactory.java:23327)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$SortNodeFactory$SortUninitializedNode.executeUninitialized0(ArrayNodesFactory.java:22977)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$SortNodeFactory$SortUninitializedNode.execute(ArrayNodesFactory.java:22954)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:65)
	at org.jruby.truffle.nodes.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:145)
	at org.jruby.truffle.nodes.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:108)
	at org.jruby.truffle.nodes.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:53)
	at org.jruby.truffle.nodes.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:35)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:150)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:112)
	at org.jruby.truffle.nodes.RubyCallNode.executeArguments(RubyCallNode.java:166)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:145)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.CatchNextNode.execute(CatchNextNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchReturnAsErrorNode.execute(CatchReturnAsErrorNode.java:37)
	at org.jruby.truffle.nodes.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	at org.jruby.truffle.nodes.methods.SetMethodDeclarationContext.execute(SetMethodDeclarationContext.java:46)
	at org.jruby.truffle.nodes.TopLevelRaiseHandler.execute(TopLevelRaiseHandler.java:32)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:254)
	at org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:243)
	at org.jruby.truffle.runtime.RubyContext.load(RubyContext.java:194)
	at org.jruby.truffle.TruffleBridgeImpl.execute(TruffleBridgeImpl.java:191)
	at org.jruby.truffle.TruffleBridgeImpl.execute(TruffleBridgeImpl.java:168)
	at org.jruby.Ruby.runInterpreter(Ruby.java:867)
	at org.jruby.Ruby.runInterpreter(Ruby.java:881)
	at org.jruby.Ruby.runNormally(Ruby.java:756)
	at org.jruby.Ruby.runFromMain(Ruby.java:573)
	at org.jruby.Main.doRunFromMain(Main.java:404)
	at org.jruby.Main.internalRun(Main.java:299)
	at org.jruby.Main.run(Main.java:226)
	at org.jruby.Main.main(Main.java:198)
"test_from_sjis","test_to_utf8","test_to_softbank","test_to_kddi","test_to_sjis","test_docomo","test_encoding_name","test_comparison","test_to_eucjp","test_from_utf8",internal implementation error - ClassCastException java.lang.Integer cannot be cast to java.lang.Long org.jruby.truffle.nodes.RubyTypesGen.asLong(RubyTypesGen.java:160)
core:/core/rubinius/common/array.rb:1167:in `at': internal implementation error - ClassCastException java.lang.Integer cannot be cast to java.lang.Long org.jruby.truffle.nodes.RubyTypesGen.asLong(RubyTypesGen.java:160) (RubyTruffleError)
	from core:/core/rubinius/common/array.rb:1167:in `isort!'
	from inline-ruby:1:in `<main>'
	from -e:1:in `<main>'
```

**Comment by eregon** [comment] 2015-04-16 15:37
I cannot reproduce, did you commit the CreateCast?

**Comment by bjfish** [comment] 2015-04-16 15:44
@eregon without the CreateCast it's a different exception below. I think @nirvdrum has a handle on this issue and is planning to look at it shortly.

```
./bin/jruby -Xtruffle.exceptions.print_java=true -X+T -e '2147483647-(-5);puts ["test_from_sjis","test_to_utf8","test_to_softbank","test_to_kddi","test_to_sjis","test_docomo","test_encoding_name","test_comparison","test_to_eucjp","test_from_utf8"].sort.to_s'
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for AtUninitializedNode@7ebc0d3a: [org.jruby.truffle.runtime.core.RubyArray@6c089bd6, 0]
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$AtNodeFactory$AtUninitializedNode.executeUninitialized0(ArrayNodesFactory.java:3806)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$AtNodeFactory$AtUninitializedNode.execute(ArrayNodesFactory.java:3787)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:65)
	at org.jruby.truffle.nodes.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:145)
	at org.jruby.truffle.nodes.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:108)
	at org.jruby.truffle.nodes.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:53)
	at org.jruby.truffle.nodes.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:35)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:150)
	at org.jruby.truffle.nodes.methods.locals.WriteLocalVariableNodeFactory$WriteLocalVariableUninitializedNode.execute(WriteLocalVariableNodeFactory.java:205)
	at org.jruby.truffle.nodes.RubyNode.executeVoid(RubyNode.java:204)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:80)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.control.TryNode.execute(TryNode.java:60)
	at org.jruby.truffle.nodes.RubyNode.executeVoid(RubyNode.java:204)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:80)
	at org.jruby.truffle.nodes.control.WhileNode$WhileRepeatingNode.executeRepeating(WhileNode.java:92)
	at com.oracle.truffle.api.nodes.LoopNode.executeRepeatingNode(LoopNode.java:46)
	at com.oracle.truffle.api.impl.DefaultLoopNode.executeLoop(DefaultLoopNode.java:38)
	at org.jruby.truffle.nodes.control.WhileNode.execute(WhileNode.java:51)
	at org.jruby.truffle.nodes.RubyNode.executeVoid(RubyNode.java:204)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:80)
	at org.jruby.truffle.nodes.control.WhileNode$WhileRepeatingNode.executeRepeating(WhileNode.java:92)
	at com.oracle.truffle.api.nodes.LoopNode.executeRepeatingNode(LoopNode.java:46)
	at com.oracle.truffle.api.impl.DefaultLoopNode.executeLoop(DefaultLoopNode.java:38)
	at org.jruby.truffle.nodes.control.WhileNode.execute(WhileNode.java:51)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.CatchBreakAsReturnNode.execute(CatchBreakAsReturnNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchReturnNode.execute(CatchReturnNode.java:39)
	at org.jruby.truffle.nodes.methods.CatchNextNode.execute(CatchNextNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:65)
	at org.jruby.truffle.nodes.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:145)
	at org.jruby.truffle.nodes.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:108)
	at org.jruby.truffle.nodes.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:53)
	at org.jruby.truffle.nodes.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:35)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:150)
	at org.jruby.truffle.nodes.RubyNode.executeVoid(RubyNode.java:204)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:80)
	at org.jruby.truffle.nodes.methods.CatchNextNode.execute(CatchNextNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchReturnAsErrorNode.execute(CatchReturnAsErrorNode.java:37)
	at org.jruby.truffle.nodes.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:254)
	at org.jruby.truffle.runtime.RubyContext.eval(RubyContext.java:235)
	at org.jruby.truffle.nodes.RubyNode.ruby(RubyNode.java:484)
	at org.jruby.truffle.nodes.core.ArrayNodes$SortNode.sortUsingRubinius(ArrayNodes.java:4683)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$SortNodeFactory$SortObjectNode.executeChained0(ArrayNodesFactory.java:23327)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$SortNodeFactory$SortUninitializedNode.executeUninitialized0(ArrayNodesFactory.java:22977)
	at org.jruby.truffle.nodes.core.ArrayNodesFactory$SortNodeFactory$SortUninitializedNode.execute(ArrayNodesFactory.java:22954)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:52)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:65)
	at org.jruby.truffle.nodes.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:145)
	at org.jruby.truffle.nodes.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:108)
	at org.jruby.truffle.nodes.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:53)
	at org.jruby.truffle.nodes.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:35)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:150)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:112)
	at org.jruby.truffle.nodes.RubyCallNode.executeArguments(RubyCallNode.java:166)
	at org.jruby.truffle.nodes.RubyCallNode.execute(RubyCallNode.java:145)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.methods.CatchNextNode.execute(CatchNextNode.java:36)
	at org.jruby.truffle.nodes.methods.CatchReturnAsErrorNode.execute(CatchReturnAsErrorNode.java:37)
	at org.jruby.truffle.nodes.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	at org.jruby.truffle.nodes.methods.SetMethodDeclarationContext.execute(SetMethodDeclarationContext.java:46)
	at org.jruby.truffle.nodes.TopLevelRaiseHandler.execute(TopLevelRaiseHandler.java:32)
	at org.jruby.truffle.nodes.control.SequenceNode.execute(SequenceNode.java:83)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:54)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:77)
	at org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:254)
	at org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:243)
	at org.jruby.truffle.runtime.RubyContext.load(RubyContext.java:194)
	at org.jruby.truffle.TruffleBridgeImpl.execute(TruffleBridgeImpl.java:191)
	at org.jruby.truffle.TruffleBridgeImpl.execute(TruffleBridgeImpl.java:168)
	at org.jruby.Ruby.runInterpreter(Ruby.java:867)
	at org.jruby.Ruby.runInterpreter(Ruby.java:881)
	at org.jruby.Ruby.runNormally(Ruby.java:756)
	at org.jruby.Ruby.runFromMain(Ruby.java:573)
	at org.jruby.Main.doRunFromMain(Main.java:404)
	at org.jruby.Main.internalRun(Main.java:299)
	at org.jruby.Main.run(Main.java:226)
	at org.jruby.Main.main(Main.java:198)
"test_from_sjis","test_to_utf8","test_to_softbank","test_to_kddi","test_to_sjis","test_docomo","test_encoding_name","test_comparison","test_to_eucjp","test_from_utf8",Truffle doesn't have a case for the org.jruby.truffle.nodes.core.ArrayNodesFactory$AtNodeFactory$AtUninitializedNode node with values of type  Array(org.jruby.truffle.runtime.core.RubyArray)[[Ljava.lang.Object;,10] java.lang.Long=0
core:/core/rubinius/common/array.rb:1166:in `at': Truffle doesn't have a case for the org.jruby.truffle.nodes.core.ArrayNodesFactory$AtNodeFactory$AtUninitializedNode node with values of type  Array(org.jruby.truffle.runtime.core.RubyArray)[[Ljava.lang.Object;,10] java.lang.Long=0 (TypeError)
	from core:/core/rubinius/common/array.rb:1166:in `isort!'
	from inline-ruby:1:in `<main>'
	from -e:1:in `<main>'
```

**Comment by nirvdrum** [comment] 2015-04-17 01:30
I accidentally committed everything in 9ad70d51c0bc71df7531c61c32f8e6343d156ba2, but that should fix both the long lowering to int issue in `Array#at` as well as the `ClassCastException` in `ToIntNode`.

**Closed by nirvdrum** 2015-04-17 01:30 UTC

**Comment by eregon** [comment] 2015-04-17 09:50
Should be fixed now.
