### ISSUE TITLE
define_method doesn't work with empty blocks

### ISSUE THREAD

**Issue by adaedra** [jruby/jruby#3606] opened 2016-01-19 22:10 UTC
When running the following code:

```ruby
define_method(:test) {}
test
```

I obtain:

```
RuntimeError: BUG: interpreter fell through to end unexpectedly
   test at test.rb:1
  <top> at test.rb:4
```

It seems that jruby can't call empty methods defined through `define_method`.

Tested with:

* `jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]` (Installed through chruby/ruby-install on OS X 10.11.2)
* `jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa OpenJDK 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [linux-amd64]` (Installed through pacman on Arch Linux)

**Comment by headius** [comment] 2016-01-19 22:11
This is a dupe...have to find the issue.

**Comment by headius** [comment] 2016-01-19 22:12
Dupe of #3483.

**Closed by headius** 2016-01-19 22:12 UTC
