### ISSUE TITLE
Can't run Chrome webdriver

### ISSUE THREAD

**Issue by pmontrasio** [jruby/jruby#3170] opened 2015-07-23 20:33 UTC
This is the error I get when running Selenium with chrome

```
 Selenium::WebDriver::Error::WebDriverError:
   unable to connect to chromedriver http://127.0.0.1:9515
 # /home/me/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/chrome/service.rb:50:in `__script__'
 # /home/me/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/chrome/bridge.rb:15:in `__script__'
 # /home/me/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:37:in `__script__'
 # /home/me/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver.rb:67:in `__script__'
 # /home/me/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:13:in `__script__'
 # /home/me/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:45:in `visit'
 # /home/me/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
 # /home/montra/.rvm/gems/jruby-9.0.0.0.pre1@myproject/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `visit'
```

The driver has been set up with 

```
Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end
```

This could be a bug of the Chrome webdriver not supporting JRuby but I'm starting from here because it could be caused by some peculiarity of the Java environment.

**Comment by nirvdrum** [comment] 2015-07-23 20:43
Just to be clear, you were able to verify this works with MRI?  The reason I ask is chromedriver requires a separate download and installation.  The selenium-webdriver gem then uses this downloaded binary.

**Comment by pmontrasio** [comment] 2015-07-23 20:47
Yes, it works with MRI. This is a Rails 4.2 / Ruby 2.2.2 project that I'm trying to run with JRuby 9.0.0.0
I rerun the tests with MRI right now to be sure everything is OK.

**Comment by clonezone** [comment] 2015-07-29 21:14
I'm running into a similar issue with JRuby v9.0.0.0 final. No Capybara, but direct use of selenium-webdriver v2.46.2. Works fine with Rubinius v2.5.7.

**Comment by rtyler** [comment] 2015-08-02 07:32
@pmontrasio @clonezone would either of you have a simple reproduction case that we could use to verify a fix for this? My experience with Capybara/Selenium is about three years old at this point, but I have a hunch that this might have to do with process spawning

**Comment by clonezone** [comment] 2015-08-03 15:32
```ruby
require 'selenium-webdriver'

webdriver = Selenium::WebDriver.for :chrome
webdriver.quit
```

On Ubuntu v14.04.2 LTS, with Chrome v40, Chromedriver v2.10.267518, selenium-webdriver v2.46.2, and Rubinius v2.5.7, this works: the browser gets launched and shuts down. (You need to have Chrome and Chromedriver in your `PATH`.)

With everything else the same, switching to JRuby v9.0.0.0 results in

```
Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515
  connect_until_stable at /install/path/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/chrome/service.rb:109
        block in start at /install/path/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/chrome/service.rb:69
                locked at /install/path/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/socket_lock.rb:38
                 start at /install/path/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/chrome/service.rb:66
            initialize at /install/path/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/chrome/bridge.rb:34
                   for at /install/path/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/driver.rb:56
                   for at /install/path/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver.rb:84
                 <top> at selenium-test:3
```

**Comment by reach2jeyan** [comment] 2017-02-14 18:11
@clonezone I am facing the same error currently in `travis CI`. Any idea how did you debug the issue? 

PFB the log generated. 

https://api.travis-ci.org/jobs/201592573/log.txt?deansi=true

**Comment by clonezone** [comment] 2017-02-14 20:46
I still have no solution.

**Comment by reach2jeyan** [comment] 2017-02-15 04:15
@clonezone: Okay! It was the issue with 2.7 version of chrome driver. I downgraded to 2.27, it works now.

Thanks

**Comment by venu14feb** [comment] 2017-04-18 20:32
I have encountered the same issue, but downgrading the chrome driver to 2.27 did not resolve it.

**Comment by reach2jeyan** [comment] 2017-04-19 06:07
@venu14feb What is the error you are getting, can you please paste the logs

**Comment by venu14feb** [comment] 2017-04-19 13:51
@reach2jeyan, I am getting the below error:
unable to connect to chromedriver 127.0.0.1:9515 (Selenium::WebDriver::Error::WebDriverError)

**Comment by headius** [comment] 2017-04-19 14:52
This appears to be working fine on JRuby master on my system...

```
~/projects/jruby $ gem install selenium-webdriver
Fetching: rubyzip-1.2.1.gem (100%)
Successfully installed rubyzip-1.2.1
Fetching: ffi-1.9.18-java.gem (100%)
Successfully installed ffi-1.9.18-java
Fetching: childprocess-0.6.3.gem (100%)
Successfully installed childprocess-0.6.3
Fetching: websocket-1.2.4.gem (100%)
Successfully installed websocket-1.2.4
Fetching: selenium-webdriver-3.3.0.gem (100%)
Successfully installed selenium-webdriver-3.3.0
5 gems installed

~/projects/jruby $ sudo dnf install chromedriver
[sudo] password for headius: 
Last metadata expiration check: 0:51:25 ago on Wed Apr 19 08:59:03 2017.
Dependencies resolved.
...
Installed:
  chromedriver.x86_64 57.0.2987.133-1.fc25                           chromium-libs.x86_64 57.0.2987.133-1.fc25                           chromium-libs-media.x86_64 57.0.2987.133-1.fc25                          

Complete!

~/projects/jruby $ jruby blah.rb

~/projects/jruby $ cat blah.rb
require 'selenium-webdriver'

webdriver = Selenium::WebDriver.for :chrome
webdriver.quit
```

**Comment by headius** [comment] 2017-04-19 14:58
As near as I can tell, the chromedriver installed on my Fedora appears to be in the 2.29 range, since it's for Chrome 57. All I did was `gem install selenium-webdriver` and `dnf install chromedriver` and it works, so I'm not sure what else to do here.

@venu14feb Can you give more details about your environment?

**Comment by venu14feb** [comment] 2017-04-19 15:30
@headius, I am trying to run the cucumber scripts and using Ruby. 
The environment: 
- ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
- chromedriver - have tried with 2.27 and 2.29

(The issue started after upgrading my machine to Windows 10. It asked to upgrade Ruby that supports 64 bit and I did)

May I know what '_dnf install chromedriver_' does? May be I couldn't find this command as I am using Ruby and not JRuby.

**Comment by headius** [comment] 2017-04-19 15:39
Well, we can't help with C Ruby issues. If you are having the trouble with a current JRuby release, let us know.

**Closed by headius** 2017-04-19 15:39 UTC
Labels: feedback needed, JRuby 9000

**Comment by reach2jeyan** [comment] 2017-04-20 05:33
@venu14feb If you are using ruby, could you please place the chromedriver in the lib file of the ruby and check?

**Comment by venu14feb** [comment] 2017-04-24 20:48
@headius .. Sorry if this was the wrong post. 

@reach2jeyan .. Yes I did place the chromedriver.exe file in the bin folder and the same was defined in the path to be launched. Seems like the issue is to do with Windows 10 being 64 bit. 
Will keep you posted after I find a resolution. Thanks for your assistance!

**Comment by venu14feb** [comment] 2017-04-28 20:45
@reach2jeyan ... The issue is, can't run the cucumber scripts from command prompt on windows 10 (which was fine on windows 7). Don't know why. But I found a solution, I installed the rubymine IDE and its running the scripts successfully now.

**Comment by reach2jeyan** [comment] 2017-05-02 06:23
@venu14feb Strange...! How could an IDE resolve the issue of chromedriver?

**Comment by sidh12** [comment] 2018-06-25 10:14
Hi all can anyone help me to resolve the issue
'ArgumentError: cannot interpret as DNS name: nil'
the error is coming when doing capybara selenium integration testing in rails 4
here iam using jruby-1.7.9 and ruby version inside jruby is  2.0.0.p195
already i had used the ruby version is 1.9.7 at that time i faced the error 
'cant connect to chrome driver error'
in pure ruby like without using jruby its the integration testing is working...bur my application is in jruby...so, anyone have any solution on this.. wat should i do to resolve this??
Thanks in advance

**Comment by headius** [comment] 2018-06-25 16:54
@sidh12 Unfortunately JRuby 1.7.x is not supported anymore. The error you get here appears to be trying to pass a nil value as DNS host when doing a lookup, but I don't know much more. If you stop by IRC or Gitter we may be able to help, but updating to JRuby 9.x is almost certainly your best path forward.
