### ISSUE TITLE
JRuby 9.4 appears to re-order array parallel assigns

### ISSUE THREAD

**Issue by luke-hill** [jruby/jruby#7988] opened 2023-10-27 10:47 UTC
**Environment Information**
  
Provide at least:
* JRuby 9.4 - no flags
* GitHub CI runs found here: https://github.com/cucumber/cucumber-ruby-core/actions/runs/6578797110/job/18114639421

**Actual Behavior**

* When running tests on ruby 2.5+ there is a scenario performing a long test. Said scenario will then do a parallel assign of iVars on initialize.

For ruby 2.5+ the following is observed
```
0> event
=> #<Cucumber::Core::Events::TestStepFinished:0x000055602c739358 @test_step=#<Cucumber::Core::Test::Step: features/test.feature:4>, @result=#<Cucumber::Core::Test::Result::Passed:0x000055602c739510 @duration=#<Cucumber::Core::Test::Result::Duration:0x000055602c739538 @nanoseconds=1016>>>

0> event.attributes
=> [#<Cucumber::Core::Test::Step: features/test.feature:4>, #<Cucumber::Core::Test::Result::Passed:0x000055602c739510 @duration=#<Cucumber::Core::Test::Result::Duration:0x000055602c739538 @nanoseconds=1016>>]
```

**However** these 2 values in the array are reversed in JRuby 9.4.4

```
0> event
=> #<Cucumber::Core::Events::TestStepFinished:0x7f426ddd @result=#<Cucumber::Core::Test::Result::Passed:0x3a209918 @duration=#<Cucumber::Core::Test::Result::Duration:0x2cae5fa7 @nanoseconds=45101>>, @test_step=#<Cucumber::Core::Test::Step: features/test.feature:4>>

0> event.attributes
=> [#<Cucumber::Core::Test::Result::Passed:0x3a209918 @duration=#<Cucumber::Core::Test::Result::Duration:0x2cae5fa7 @nanoseconds=45101>>, #<Cucumber::Core::Test::Step: features/test.feature:4>]
```

* Provide an executable Ruby script or a link to an example repository.

**Expected Behavior**

Should be identical

NB: The portion of the code that generates these is quite metaprogram heavy

```
Class.new(Event) do
          attr_reader(*events)

          define_method(:initialize) do |*attributes|
            events.zip(attributes) do |name, value|
              instance_variable_set("@#{name}".to_sym, value)
            end
          end

          def attributes
            instance_variables.map { |var| instance_variable_get(var) }
          end

.... # more stuff
```

**Comment by luke-hill** [comment] 2023-10-27 11:03
I think I've managed to narrow it down to a `#zip` and `instance_variable_set` call.

`events.zip(attributes)` returns the array in order. But then calling the variable set sets them in reverse order?

**Comment by headius** [comment] 2023-10-28 04:45
Wow, this is an interesting one!

I'm excited to see if you can come up with a good reproduction, because it's definitely one of the more exotic examples of metaprogramming I have seen. You are making some anonymous classes that dynamically assign whatever instance variables are passed in, while inside an `Enumerable#zip` – which I believe forces a Fiber to be used due to its invocation of `Enumerator#next` – so there's numerous places this could be going astray.

Please let us know how we can help reproduce this!

**Comment by luke-hill** [comment] 2023-10-30 09:41
You should be able to reproduce it by using the github action from the OSS repo. I appreciate it's quite obfuscated.

In terms of deriving an SSCCE I am not sure how much time I will have to do that. I will try to do bits and pieces where possible

**Comment by headius** [comment] 2023-10-30 16:53
I am wondering, are you just seeing them out of order in the inspect output for these objects? I don't think there's any specification or requirement that instance variables be printed in any particular order, and since we store them in a hash table, the order may vary.

If you are seeing out of order values in an array or other ordered structure, that's something we definitely would look into, but if this issue is simply about the display order of the instance variables, I don't think there's really a bug here.

**Comment by luke-hill** [comment] 2023-10-31 09:53
They are in the wrong order. The iVars have been assigned incorrectly.

**Comment by headius** [comment] 2023-10-31 17:22
In your output, it appears that the values have been assigned to the correct ivar names. The inspect output does not guarantee any particular order when printing out the values.

**Comment by headius** [comment] 2023-10-31 17:50
I poked around CRuby/MRI tests and commit history for a while, but could not find any formal specification that instance variables should be returned in insertion order. However, there are a few tests that appear to depend upon and confirm this behavior in support of other features.

In test/ruby/test_shape.rb, added for recent object-shaping improvements, there are tests to confirm that falling back on a table-based store will still return instance variables in order.

In rubyspec's instance_variables_spec.rb, a spec was added in 2021 that confirms variables are returned in insertion order. I do not know whether this was simply testing the behavior that already existed, or if that behavior was previously specified as official.

In any case, I think this is an easy change, so I'll look into making it anyway.

**Comment by headius** [comment] 2023-10-31 17:53
FWIW, it's not that we reverse the order or actively do anything to change the order. The issue is that we use an unordered HashMap in the implementation, which will return items in bucket order...unrelated to insertion order in any way. The fix is to use a LinkedHashMap which preserves order at the cost of more memory (but this is in a table maintained on a per-class basis).

**Comment by kares** [comment] 2023-11-01 08:16
what a weird thing to support and/or rely on! :1st_place_medal:

**Comment by luke-hill** [comment] 2023-11-01 09:40
@kares not really. If I do a parallel assign. I'd expect the first thing to be assigned first and the second thing to be assigned second. Same as any normal ruby implementation.

@headius I'm not familiar with the JRuby cadence or backporting. What version/s will this target in the 9.2/9.3/9.4 branches?

**Comment by headius** [comment] 2023-11-01 12:48
@luke-hill I feel it important to clarify something here: the variables were assigned in the correct order. What you see in the output of inspect is just the order in which the internal instance variable table returned the values for printing. With more variables, you would see they are in a seemingly random order, because the table used does not guarantee any particular order. It does not mean they were assigned in the order in which they were printed out.

The change I made just switched that internal table to a version that will always return the variables in assignment order.

**Comment by luke-hill** [comment] 2023-11-01 13:15
@headius but they weren't assigned in the correct order. The error in the CI run proves this.

We tried to call a method on the "correct" value, and because the value was incorrect it failed.

If there isn't a fix incoming for this, then this bug is still a bug.

**Comment by headius** [comment] 2023-11-01 14:28
They were assigned in the correct order, as shown by your output, meaning that the correct values were assigned to the correct instance variables. When you request all instance variables, they may not be returned in the order you originally assigned them because they may not be stored in that order internally. As far as I know there's no specification that requires they be returned in insertion order.

You can prove they were assigned correctly by printing out the variable names while you map them to their values. You will see that the names are **also** returned in a different order. You are just expecting them to be the same order as they were assigned.

Any case, it's moot, because the instance_variables method should also be fixed by my change.

**Comment by headius** [comment] 2023-11-01 14:43
@luke-hill An example might help illustrate this.

The following command lines show that the instance variable names may vary in order from insertion order. With names of the form `var#` we get insertion order for two and three variables, but then a different order with four variables.

```
$ (chruby jruby-9.4.3.0 ; ruby -e 'o = Object.new; 2.times {|i| o.instance_variable_set("@var#{i}", i)}; p o.instance_variables')
[:@var0, :@var1]
$ (chruby jruby-9.4.3.0 ; ruby -e 'o = Object.new; 3.times {|i| o.instance_variable_set("@var#{i}", i)}; p o.instance_variables')
[:@var0, :@var1, :@var2]
$ (chruby jruby-9.4.3.0 ; ruby -e 'o = Object.new; 4.times {|i| o.instance_variable_set("@var#{i}", i)}; p o.instance_variables')
[:@var3, :@var0, :@var1, :@var2]
```

The effect is even more pronounced with ten variables:

```
$ (chruby jruby-9.4.3.0 ; ruby -e 'o = Object.new; 10.times {|i| o.instance_variable_set("@var#{i}", i)}; p o.instance_variables')
[:@var3, :@var4, :@var5, :@var6, :@var0, :@var1, :@var2, :@var7, :@var8, :@var9]
```

But the values are absolutely being assigned to the correct variables:

```
$ (chruby jruby-9.4.3.0 ; ruby -e 'o = Object.new; 10.times {|i| o.instance_variable_set("@var#{i}", i)}; p o.instance_variables.map {|var| [var, o.instance_variable_get(var)]}')
[[:@var3, 3], [:@var4, 4], [:@var5, 5], [:@var6, 6], [:@var0, 0], [:@var1, 1], [:@var2, 2], [:@var7, 7], [:@var8, 8], [:@var9, 9]]
```

Under 9.4.5.0, this order will match the insertion order:

```
$ ruby -v -e 'o = Object.new; 10.times {|i| o.instance_variable_set("@var#{i}", i)}; p o.instance_variables.map {|var| [var, o.instance_variable_get(var)]}' 
jruby 9.4.5.0-SNAPSHOT (3.1.4) 2023-10-31 344511036e OpenJDK 64-Bit Server VM 25.362-b09 on 1.8.0_362-b09 +jit [arm64-darwin]
[[:@var0, 0], [:@var1, 1], [:@var2, 2], [:@var3, 3], [:@var4, 4], [:@var5, 5], [:@var6, 6], [:@var7, 7], [:@var8, 8], [:@var9, 9]]
```

However I strongly encourage you to avoid relying on this order, since it does not appear to be a specified behavior and it could change in the future. A better option would be for you to `sort` the `instance_variables` array before mapping it to values. This will avoid any fluctuations in the order and work across all versions of JRuby (and other Ruby implementations).

**Comment by enebo** [comment] 2023-11-01 14:59
"However I strongly encourage you to avoid relying on this order, since it does not appear to be a specified behavior and it could change in the future. A better option would be for you to sort the instance_variables array before mapping it to values. This will avoid any fluctuations in the order and work across all versions of JRuby (and other Ruby implementations)."

To speak to this you may also find it breaking in C Ruby itself over time not because the behavior in C Ruby changes but because you change your code in such a way to add environmental ambiguity:

```ruby
def initialize
   if something_sometimes
       @a = true
   end
   @b = 1
end
```

local_variables here will not only not be the expected order but may not even contain the same number of variables until after multiple initialize calls.  This is not likely to happen in your specific code based on how it works but it just points out that reflective methods semantics depending on order may be more complicated than they first appear.

**Comment by headius** [comment] 2023-11-01 15:28
I could not get the fixed version to run in your CI, but running locally I do still see the error you reported. I am investigating now.

I do see that the variables **are** being assigned the correct values. The names are just returned in an unexpected order.

The following output is from adding `p` to the Event class's metaprogramming. The first four are the instance variable names and values being assigned. The last two are the order the names are returned from `instance_variables`.

```
:test_step
#<Cucumber::Core::Test::Step: features/test.feature:4>
:result
#<Cucumber::Core::Test::Result::Passed:0x2d1dee39 @duration=#<Cucumber::Core::Test::Result::Duration:0x48d5f34e @nanoseconds=52500>>
:@result
:@test_step
```

**Comment by headius** [comment] 2023-11-01 16:35
I believe I've found the issue.

Your code uses a list of passed in `events` to set up a new class. That class contains:

1. a set of attribute accessors, one per event
2. a constructor that dynamically assigns those events as instance variables
3. an `attributes` method that returns an array of the events stored in instance variables

My fix was correct for 2 and 3, but the accessors from 1 screw up the order again.

The problem is that JRuby eagerly tries to figure out what variable names you are likely to use in a given class when you initialize it for the first time. We do that by walking all methods in the class's hierarchy, looking for reads and writes of literal instance variables (using e.g. `@foo`) or attribute accessors and using that discovered set of names to pre-shape the instance variable table.

Unfortunately, the order in which we encounter those methods is unpredictable, because the method table does not preserve any particular order. In this case, we encounter the `result` accessor first, so it is the first variable that goes into the instance variable name table. This effectively causes the order of `instance_variables` to be reversed from the original `events` ordering.

This could be fixed by not eagerly discovering instance variables. However, that would break a key optimization in JRuby that picks the best-guess shape immediately rather than picking a poor shape and having to evolve it as new variables come in.

It might be possible to fix by insertion-ordering the method table, but that is a nontrivial change and this is still a very fragile way to write code; a change in how we discover these variables might alter the order they are encountered again, and we reserve the right to do that to create better (i.e. more efficient) shapes for Ruby objects.

My proposal to you is that if the order of the event names is important, that order should be preserved in the event type. The patch below will ensure that the events are returned in the order in which they were provided, without relying on the ordering of the `instance_variables` array.

```diff
diff --git a/lib/cucumber/core/event.rb b/lib/cucumber/core/event.rb
index 80f30c3..81489af 100644
--- a/lib/cucumber/core/event.rb
+++ b/lib/cucumber/core/event.rb
@@ -18,8 +18,8 @@ module Cucumber
             end
           end
 
-          def attributes
-            instance_variables.map { |var| instance_variable_get(var) }
+          define_method(:attributes) do
+            events.map { |var| instance_variable_get(:"@#{var}") }
           end
 
           def to_h
```

You could also store the `events` array somewhere in the new class and access it from there rather than passing it along as a captured variable. This change allows your suite to run to completion on JRuby 9.4.4.0 and 9.4.5.0-SNAPSHOT.

**Comment by luke-hill** [comment] 2023-11-01 16:53
Yep. That is precisely the bit of code I un-did recently. In order to reduce complexity of the class itself. https://github.com/cucumber/cucumber-ruby-core/pull/268/files#diff-c7c8b4b1d4b4c6c28d0d04b138b4ac5f1eff33b9cca272ca5f404527fef07094L21

Ideally we should be able to not have to metaprogram in items in order to satisfy something. It's frustrating this is something that is clearly broken but if it's unfixable then it's unfixable :(

**Comment by headius** [comment] 2023-11-01 18:49
I understand it feels like it's broken, but I would contend that you're using the wrong tool for this job.

Nothing in the documentation of `instance_variables` dictates a particular order in which the variables will be returned. In CRuby, that order happens to be the order you want, with the names presented in the order in which they were first assigned. I say "first assigned" because this isn't really simple assignment ordering; you want the variables to be returned in the order that their initial declaration happened.

There are ways to make JRuby match for some of these scenarios, but you are still relying on a property of `instance_variables` that is neither promised nor specified in the CRuby tests.

I would suggest that the simplest option for you would be to use an associated collection that **does** promise to return values in first assignment order, like a Hash, or perhaps replace your class with a Struct or OpenStruct.

**Comment by headius** [comment] 2023-11-02 17:32
We're going to call this fixed, in that instance variables should now be printed and returned in declaration order... but declaration order is not always predictable due to our object shaping.

It is unclear whether ordered instance variables are part of the Ruby specification, or if it is incidental due to reuse of the CRuby `st_table` which gained ordering in the Ruby 1.9 timeframe. I would argue this is not something we want to specify, to allow implementers a free hand when optimizing variable access and memory layout. As an example, the JVM makes no guarantees as to the layout of fields in a given class, and reflective access should not be expected to return those fields in any particular order. This allows the GC to pack objects more efficiently, with reference values aligned at 32- and 64-bit boundaries and small numerics packed into available space. We are working toward similar optimizations.

**Closed by headius** 2023-11-02 17:32 UTC

**Comment by luke-hill** [comment] 2026-04-15 18:55
As a heads up. Whilst maybe not relevant I've been working on "unpicking" this metaprogram assignment as we're onto JRuby 10+ and Ruby 3.2+ as a minimum so I figured I'd revisit this. As such we can just use direct assignment for everything bar the initializer (And that will be tidied up later).

The solution (For all methods bar the initialize method), is as follows

```
      def to_h
        instance_variables.to_h do |variable_name|
          [variable_name[1..].to_sym, instance_variable_get(variable_name)]
        end
      end

      def attributes
        instance_variables.map { |var| instance_variable_get(var) }
      end
```

I plan on releasing this as a "first" refactor. And then for the initialize method I'm going to define them for each event. Because we inherit based on a procedural definition, whereas an initializer would use the variable name (Yes with an order, but we could even use keyword if we were worried). And given that we "have to define" said variables in at least one place, I'd rather define them in the initializer (And reader), than a pseudo-inheritance tree.

Maybe it's a tiny bit more code per event, but we then avoid all this hoo-ha.

Sorry if not relevant but figured I'd post for clarity.
