### ISSUE TITLE
Module#prepend + JRuby::Synchronized break refinements in inherited classes

### ISSUE THREAD

**Issue by p-mongo** [jruby/jruby#6573] opened 2021-02-23 03:33 UTC
When I have:

- A base class defining a method
- A subclass that inherits from the base class
- The base class uses Module#prepend to prepend a module (the prepended module can be empty)
- Either the base class or the subclass include JRuby::Synchronized
- There is a refinement for the base class

... the refinement isn't visible in the subclass.

Test code (https://github.com/p-mongo/tests/blob/master/jruby-deep-merge/test3.rb): 

```
require 'jruby/synchronized'

class Base
  def deep_merge
  end
end

module Foo
end

Base.prepend(Foo)

class Sub < Base
  include JRuby::Synchronized
end

module R
  refine Base do

    def deep_merge
      p 'called'
    end

  end
end

using R

Base.new.deep_merge
Sub.new.deep_merge
```

Result (9.2.14.0, deep_merge is accessible on the base class but not on the subclass):

```
serene%  ruby test3.rb
"called"
NoMethodError: undefined method `deep_merge' for #<Sub:0x702ed190>
  <main> at test3.rb:30
```

The error occurs if I move the JRuby::Synchronized include from the subclass to the base class.

The error goes away if I stop including JRuby::Synchronized or if I stop prepending Foo.

I tested on 9.2.11.1 and it also has this error so this isn't a recent regression as far as I can tell.

Since JRuby::Synchronized is a JRuby-specific feature, I wasn't able to execute this test under MRI as it's written.

This case comes up when using ActiveSupport + i18n 1.8.8 or newer, which started using Concurrent::Hash.

Test case (https://github.com/p-mongo/tests/blob/master/jruby-deep-merge/test1.rb):

```
gem 'i18n', '1.8.8'
gem 'activesupport'

require 'active_support'
require 'active_support/core_ext'
require 'i18n'

backend = I18n::Backend::Simple.new
backend.store_translations(:en, {})
```

Result:

```
serene% ruby test1.rb            
NoMethodError: undefined method `deep_merge!' for {}:Concurrent::Hash
Did you mean?  deep_merge
  store_translations at /home/w/.rbenv/versions/jruby-9.2.14.0/lib/ruby/gems/shared/gems/i18n-1.8.8/lib/i18n/backend/simple.rb:45
              <main> at test1.rb:9
```

This failure happens if I flip the order of activesupport and i18n includes, leading me to think that i18n 1.8.8 under Rails (or any application using ActiveSupport hash core extensions) would be broken under JRuby.

i18n 1.8.7 works because it doesn't use Concurrent::Hash.

For reference: https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent-ruby/concurrent/hash.rb (the first example was reduced from this code + i18n usage of it).

**Environment Information**
  
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 11.0.10+9-post-Debian-1 on 11.0.10+9-post-Debian-1 +jit [linux-x86_64]

jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11.0.10+9-post-Debian-1 on 11.0.10+9-post-Debian-1 +jit [linux-x86_64]

* Operating system and platform (e.g. `uname -a`)

Linux serene 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux

**Comment by headius** [comment] 2021-02-23 18:01
I believe this is a duplicate of #6547, which is partially fixed by #6549

The problem here is mostly due to the logic of refinements and the logic of Synchronized both using semi-transparent method wrappers to indicate refined or synchronized methods, respectively. The short term fix is to modify to the refinement logic to unwrap methods wrapped by Synchronized (or by instrumented profiling) before making refinement decisions about them. A further issue, #6559, will alter the way Synchronized works so there will be no future issues.

As mentioned in https://github.com/jruby/jruby/issues/6547#issuecomment-773071597, you can work around this in JRuby 9.2.14 and earlier by requiring `i18n/backend/simple` early in boot, which avoids the two types of method wrappers stepping on each other.

**Closed by headius** 2021-02-23 18:01 UTC
