### ISSUE TITLE
Unexpected frame in stack trace from `caller` method with create_method invocation

### ISSUE THREAD

**Issue by jonathanswenson** [jruby/jruby#6846] opened 2021-09-20 18:44 UTC
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
`jruby 9.3.0.0-SNAPSHOT (2.6.8) 2021-09-18 ffffffffff OpenJDK 64-Bit Server VM 25.272-b10 on 1.8.0_272-b10 +jit [linux-x86_64]`

(built from source from most recent commit on master: 4727fcb3b037537ceecc67d771aa338bd5188af4 using a simple nix derivation) 
* Operating system and platform (e.g. `uname -a`)
`Linux hostname 5.10.40-1rodete2-amd64 #1 SMP Debian 5.10.40-1rodete2 (2021-06-22) x86_64 GNU/Linux`

(glinux) 

**Expected Behavior**

we’re doing some dynamic validation detection of routes, and in doing so checking the call stack generated by the `caller` method. 

in 9.3.0.0 there appears to be an unexpected stack frame. 

This is not a repro, but a digestion of some code we hae. 

```
0  # file.rb
1  [:get, :patch].each do |verb| # we have some others here too
2    real_method = :"real_#{verb}"
3    alias_method real_method, verb
4    define_method(verb) do |path = nil, opts = {}, &block|
5      create_route(verb, real_method, path, opts, 1, &block)
6    end
7  end
8
9  def create_route(...)
10   # method call that calls caller
11 end
12
13 # caller_file.rb
14
15 get '/foo' do 
16   ...
17 end
18
19 patch '/bar' do 
20   ...
21 end
```

when patch is called, stack trace looks like
```
file.rb:10:in `create_route'
file.rb:9:in `create_route'
file.rb:5:in `block in patch'
caller_file.rb:38:in `<class:Engine>'
```

in this case, the frame that references file.rb:9 is unexpected. 

when get it called stack trace looks like: 
```
file.rb:10:in `create_route'
file.rb:5:in `block in get'
caller_file.rb:15:in `<class:Engine>'
```

and it doesn’t have this added frame (as expected).

**Comment by headius** [comment] 2021-09-20 18:49
This is probably due to work in #6771, which improved the printing of arity-mismatch ArgumentErrors when called through our bytecode-generated varargs wrappers.

The problem is illustrated in #6335 and was fixed by also considering the varargs frame for stack traces. It was supposed to be [eliminated if the actual method body frame makes it through the stack trace mining](https://github.com/jruby/jruby/pull/6771/commits/9b7afc5186e706c61b62521e0f66e99446442d54#diff-13d0be77817edcb3c08171f843430f522b2d681757bde35d625c7069b7b9946dR97-R105), to avoid doubling up, but it appears that logic is not working

**Comment by headius** [comment] 2021-09-20 18:50
Example showing it not working... there should not be two `foo` in this trace:

```
$ jruby -e 'def foo(a); raise; end; def bar; a = [1]; foo(*a); end; bar'
RuntimeError: No current exception
     foo at -e:1
     foo at -e:1
     bar at -e:1
  <main> at -e:1
```

**Closed** 2021-10-05 20:02 UTC
