### ISSUE TITLE
unable to get value of object's fields in RubyMine debugger

### ISSUE THREAD

**Issue by os97673** [jruby/jruby#2301] opened 2014-12-10 10:41 UTC
Originally filed agains RubyMine (https://youtrack.jetbrains.com/issue/RUBY-15864)
Users basically unable to see value of object's fields.
Here is a simple example which shows how we (ruby-debug-base) try to get value of fields.
It looks like a bug for me, but if it is not please suggest a way to implement similar functionality for jruby.

```ruby
class Foo
  attr_accessor :test
end

foo = Foo.new
foo.test = 'visible?'
puts foo.test

bindings = ["binding()", "Kernel::binding()", "Object.send(:binding)"].map {|b| foo.instance_eval(b)}
bindings.each do |b|
  puts "--#{eval("@test", b).nil?}--"
end
```

**Comment by mount986** [comment] 2015-01-02 21:34
@ninkibah: Can you please post a link to the follow-up issue if you raised one? I've been tracking this issue since #1758 and would like to know when it is fully up and working again.  Thanks.

**Comment by ninkibah** [comment] 2015-01-02 21:56
@mount986 I have added a comment here: https://youtrack.jetbrains.com/issue/RUBY-15864

I don't know if the current fix is enough for @os97673 and his colleagues to be able to fix the RubyMine debugger.

**Comment by os97673** [comment] 2015-01-03 07:06
@ninkibah @mount986 I'm not sure the problem has been fixed, at least both my test and the test provided by @headius still don't work :(
@headius @enebo what the changes you've committed were supposed to change?

**Comment by os97673** [comment] 2015-01-15 07:54
> @headius @enebo what the changes you've committed were supposed to change?

Guys, could you please answer the question.  It looks like I've misunderstood your comments in the issue and I'm not sure what behavior to expect now and should I change something in ruby-debug-ide or not.

**Comment by headius** [comment] 2015-01-26 20:42
Fix applied in b5b7305 does not appear to have been enough. Can you show the current failing test case? I'm not sure what we don't do at this point.

**Comment by os97673** [comment] 2015-01-27 04:23
@headius both the test you provided and my original tests still work the same way as before :(
Is it what you want or I need test in some special format?

**Comment by os97673** [comment] 2015-04-04 04:48
Any chance to get the problem fixed?

**Comment by headius** [comment] 2015-04-06 15:31
I think we have this working correctly in JRuby 9k, but 1.7.x still has the wrong output.

**Comment by headius** [comment] 2015-04-06 16:40
Hopefully it is now fixed to everyone's satisfaction. @os97673 Please try out a head or snapshot build with the latest fix and let us know if it's working properly.

**Comment by ninkibah** [comment] 2015-04-06 17:24
I'm trying out jruby-head, but from the install output, this branch is the new 9.0.0.0 branch. Is there a branch for the planned 1.7.20? The reason I ask is that when I use the 9.0.0.0.pre1 branch, I get errors in my tests, probably due to some difference in the postgresql adapter. It objects to doing inserts specifying nil values for columns with default values. This seems to work fine in 1.7.19, but not in 9.0.0.0.pre1.

I'll see if I can track down the cause a bit more. For now, I'm trying out jruby-head for the current bug.

**Comment by donv** [comment] 2015-04-07 07:12
Hi @ninkibah !

The branch for the upcoming 1.7.20 release is "jruby-1_7".

**Comment by os97673** [comment] 2015-04-07 11:27
@headius the original problem  is fixed.
Unfortunately now ruby-debug-ide doesn't work correctly due to the following exception.
Please let me know if you need more information.
```
org.jruby.runtime.DynamicScope.getNextCapturedScope()Lorg/jruby/runtime/DynamicScope;
 	org.jruby.debug.Context.contextCopyLocals(Context.java:448)
	org.jruby.debug.Context.frame_locals(Context.java:303)
	org.jruby.debug.Context$INVOKER$i$1$0$frame_locals_DBG.call(Context$INVOKER$i$1$0$frame_locals_DBG.gen)
	org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:364)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:288)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:77)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:152)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:139)
	org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:293)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:304)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:137)
	org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:109)
	org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:145)
	org.jruby.runtime.BlockBody.yield(BlockBody.java:82)
	org.jruby.runtime.Block.yield(Block.java:147)
	org.jruby.RubyArray.each(RubyArray.java:1570)
	org.jruby.RubyArray$INVOKER$i$0$0$each_DBG.call(RubyArray$INVOKER$i$0$0$each_DBG.gen)
	org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:472)
	org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	org.jruby.ir.instructions.CallBase.interpret(CallBase.java:416)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:320)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:137)
	org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:109)
	org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:145)
	org.jruby.runtime.BlockBody.yield(BlockBody.java:82)
	org.jruby.runtime.Block.yield(Block.java:147)
	org.jruby.RubyContinuation.enter(RubyContinuation.java:107)
	org.jruby.RubyKernel.rbCatch19Common(RubyKernel.java:1132)
	org.jruby.RubyKernel.rbCatch19(RubyKernel.java:1125)
	org.jruby.RubyKernel$INVOKER$s$rbCatch19_DBG.call(RubyKernel$INVOKER$s$rbCatch19_DBG.gen)
	org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:171)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:297)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:77)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:152)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:139)
	org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:293)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:304)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:123)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:110)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
	org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	org.jruby.ir.instructions.CallBase.interpret(CallBase.java:416)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:320)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:123)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:110)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
	org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	org.jruby.ir.instructions.CallBase.interpret(CallBase.java:416)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:320)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:123)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:110)
	org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:180)
	org.jruby.RubyClass.finvoke(RubyClass.java:716)
	org.jruby.runtime.Helpers.invoke(Helpers.java:604)
	org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:381)
	org.jruby.debug.DebugEventHook.callAtLine(DebugEventHook.java:585)
	org.jruby.debug.DebugEventHook.callAtLine(DebugEventHook.java:571)
	org.jruby.debug.DebugEventHook.processEvent(DebugEventHook.java:199)
	org.jruby.debug.DebugEventHook.eventHandler(DebugEventHook.java:97)
	org.jruby.runtime.EventHook.event(EventHook.java:30)
	org.jruby.Ruby.callEventHooks(Ruby.java:3131)
	org.jruby.runtime.ThreadContext.trace(ThreadContext.java:627)
	org.jruby.ir.interpreter.InterpreterEngine.processBookKeepingOp(InterpreterEngine.java:367)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:92)
	org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:117)
	org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:104)
	org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:33)
	org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	org.jruby.Ruby.runInterpreter(Ruby.java:855)
	org.jruby.Ruby.loadFile(Ruby.java:2911)
	org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.loadScript(LibrarySearcher.java:260)
	org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:248)
	org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	org.jruby.runtime.load.LoadService.load(LoadService.java:327)
	org.jruby.debug.Debugger.load(Debugger.java:145)
	org.jruby.debug.RubyDebugger.debug_load(RubyDebugger.java:204)
	org.jruby.debug.RubyDebugger$INVOKER$s$0$2$debug_load_DBG.call(RubyDebugger$INVOKER$s$0$2$debug_load_DBG.gen)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
	org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	org.jruby.ir.instructions.CallBase.interpret(CallBase.java:416)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:320)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:180)
	org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:167)
	org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:288)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:117)
	org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:104)
	org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:33)
	org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	org.jruby.Ruby.runInterpreter(Ruby.java:855)
	org.jruby.Ruby.loadFile(Ruby.java:2911)
	org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.loadScript(LibrarySearcher.java:260)
	org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:248)
	org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	org.jruby.runtime.load.LoadService.load(LoadService.java:327)
	org.jruby.RubyKernel.loadCommon(RubyKernel.java:992)
	org.jruby.RubyKernel.load19(RubyKernel.java:984)
	org.jruby.RubyKernel$INVOKER$s$0$1$load19_DBG.call(RubyKernel$INVOKER$s$0$1$load19_DBG.gen)
	org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
	org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:288)
	org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
	org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:117)
	org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:104)
	org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:33)
	org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	org.jruby.Ruby.runInterpreter(Ruby.java:873)
	org.jruby.Ruby.runInterpreter(Ruby.java:881)
	org.jruby.Ruby.runNormally(Ruby.java:756)
	org.jruby.Ruby.runFromMain(Ruby.java:573)
	org.jruby.Main.doRunFromMain(Main.java:404)
	org.jruby.Main.internalRun(Main.java:299)
	org.jruby.Main.run(Main.java:226)
	org.jruby.Main.main(Main.java:198)
```

**Comment by enebo** [comment] 2015-04-10 16:12
Re-added DynamicScope.getNextCapturedScope to not break ruby-debug-ide on master to address unrelated error @os97673 reported.  jruby-1_7 still reports wrong output so I am leaving this issue open since it is fixed on master but not on jruby-1_7.

**Comment by headius** [comment] 2015-04-30 15:43
@ninkibah Sorry to hear you had issues with your app on 9k.pre1. If you still have those issues on pre2 we REALLY want to know about them.

@os97673 I think this should be working correctly now in 1.7.20 and @enebo's fix for master should be in 9k.pre2. Can you please confirm things are working with 9k.pre2 and a head build of jruby-1_7 branch?

**Comment by headius** [comment] 2015-04-30 15:43
Optimistically closing this because the spec passes and the 9k fix was cherry-picked over to 1.7.

**Closed by headius** 2015-04-30 15:43 UTC
Labels: JRuby 1.7.x

**Comment by ninkibah** [comment] 2015-04-30 16:39
@headius I might try out 9k pre2 this weekend, as we have a bank holiday on Monday! When is 1.7.20 coming out?

**Comment by os97673** [comment] 2015-05-02 07:38
> @os97673 I think this should be working correctly now in 1.7.20 and @enebo's fix for master should be in 9k.pre2. Can you please confirm things are working with 9k.pre2 and a head build of jruby-1_7 branch?

I've tried 9k.pre2 and everything works ok there.
I will try to build jruby-1_7 but it make take a time since I've never done it before.

**Comment by os97673** [comment] 2015-05-02 16:51
tried jruby-1_7 and the test works correctly.

**Comment by headius** [comment] 2015-05-05 16:47
@os97673 Thanks for the confirmation :-)

**Comment by cprice404** [comment] 2015-05-25 19:12
@headius just FYI; this patch turned out to be a pretty huge improvement in memory usage for us :)  Prior to the patch the objects that were referenced by the Frame.self field included a lot of unnecessary scope, and thus if we had other code that held references to those, it meant that there was a huge amount of memory that could not be GC'd.  With this patch the retained size for each one of the objects we created via a call to instance_eval went down from 7MB to less than 1kb.  :)

Granted this probably has more to do with what our code is doing with these evals than what JRuby is, but thought you might be interested in that data point.
