### ISSUE TITLE
Socket.each loops after receiving RST pegging CPU at 100%

### ISSUE THREAD

**Issue by jsvd** [jruby/jruby#7961] opened 2023-10-11 10:47 UTC
**Environment Information**
  
JRuby versions tested:

* jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 OpenJDK 64-Bit Server VM 17.0.4.1+1 on 17.0.4.1+1 +jit [darwin-aarch64]
* jruby 9.3.11.0 (2.6.8) 2023-09-11 cf0bf1a786 OpenJDK 64-Bit Server VM 17.0.4.1+1 on 17.0.4.1+1 +jit [arm64-darwin]
* jruby 9.4.4.0-SNAPSHOT (3.1.4) 2023-10-11 1ae2b687b5 OpenJDK 64-Bit Server VM 17.0.4.1+1 on 17.0.4.1+1 +jit [arm64-darwin]

* Operating system and platform 

Darwin arkham.local 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64

**Expected Behavior**

* Describe your expectation of how JRuby should behave:

MRI will raise Errno::ECONNRESET for each connection that is closed. Cpu stays at ~0%.

* Provide an executable Ruby script: 

```ruby
require 'socket'

HOST = 'localhost'
PORT = 5555

def connect_and_close
  socket = TCPSocket.new(HOST, PORT)
  linger = [1,0].pack('ii')
  socket.setsockopt(Socket::SOL_SOCKET, Socket::SO_LINGER, linger)
  socket.close
end

def tcp_receiver(socket)
  socket.each { |line| puts line }
rescue Errno::ECONNRESET
  puts "connection reset"
end

server_thread = Thread.new do
  server_socket = TCPServer.new(HOST, PORT)
  loop do
    socket = server_socket.accept

    Thread.new(socket) do |socket|
      tcp_receiver(socket)
    end
  end
end

sleep 1
10.times { connect_and_close }

server_thread.join
```

**Actual Behavior**

* Describe or show the actual behavior

All JRuby versions that I tested will loop, raising CPU usage by about 8-10% per thread handling a connection. With 10 connections CPU stays pegged at nearly 100% on my machine.

I thought this would be related to https://github.com/jruby/jruby/issues/7805, but I've tested with a recent 9.4.4.0 snapshot and 9.3.11.0, and the issue still happens.

**Comment by headius** [comment] 2023-10-13 16:58
How peculiar. At least it is not something new, but I have no explanation for it right now.

**Comment by yamam** [comment] 2023-10-17 00:53
The cause of the problem may be the same as #6346

**Comment by headius** [comment] 2023-10-18 13:05
There's some weird behavior in this thing.

First off, if I replace the `loop` with `10.times` it runs to completion and the sockets return `connection reset` (I added some additional logging):

```
$ ruby socket_bug.rb
accept
socket: #<TCPSocket:fd 22>
accept
socket: #<TCPSocket:fd 23>
accept
socket: #<TCPSocket:fd 24>
accept
socket: #<TCPSocket:fd 34>
accept
socket: #<TCPSocket:fd 35>
accept
socket: #<TCPSocket:fd 18>
accept
socket: #<TCPSocket:fd 36>
accept
socket: #<TCPSocket:fd 43>
accept
socket: #<TCPSocket:fd 50>
accept
socket: #<TCPSocket:fd 54>
connection resetconnection resetconnection reset

connection reset
connection reset

connection reset
connection reset
connection reset
connection reset
```

After the first "accepted" there's a pause for a good couple of seconds, and then the rest all comes out.

If I leave the `loop` in place, and remove the `SO_LINGER` setting, it runs forever (as expected) with ten sockets connected but no unusual CPU use. The sockets do not return `connection reset`:

```
$ ruby socket_bug.rb
accept
socket: #<TCPSocket:fd 22>
accept
socket: #<TCPSocket:fd 23>
accept
socket: #<TCPSocket:fd 16>
accept
socket: #<TCPSocket:fd 25>
accept
socket: #<TCPSocket:fd 24>
accept
socket: #<TCPSocket:fd 30>
accept
socket: #<TCPSocket:fd 31>
accept
socket: #<TCPSocket:fd 29>
accept
socket: #<TCPSocket:fd 32>
accept
socket: #<TCPSocket:fd 33>
accept
```

I stepped through the script with `SO_LINGER` set, and it appears that JRuby gets stuck in a `select` loop on these sockets. They continually return readiness for `READ`, but even after closed by the client they still appear to be `isOpen` and the `select` operations continue to immediately return `READ`. So rather than returning `connection reset` the sockets appear open and readable and we keep trying to read.

So there seems to be two issues interacting here:

* Something about the loop prevents the ten open sockets from returning `connection reset` to the calling threads.
* SO_LINGER appears to cause some peculiar behavior on a closed socket being `select`ed, leading to endless `READ` results.

There may be some logical issues in JRuby's IO subsystem causing it to get into this `select` loop, but it doesn't seem to excuse the socket appearing to still be open after close. It's very strange.

**Comment by headius** [comment] 2023-10-18 13:37
More data: when running with `10.times` and no `SO_LINGER` the threads behave the same way as with `loop` and `SO_LINGER`: the `each` call returns without processing any lines and the threads terminate without error.

So we have the following:

* `loop` plus `SO_LINGER`: sockets do not raise any error and continue to be readable, leading to threads looping and high CPU.
* `10.times` plus `SO_LINGER`: sockets raise errors and all threads terminate
* `loop` without `SO_LINGER`: sockets do not raise errors and `each` returns having processed no lines
* `10.times` without `SO_LINGER: sockets do not raise errors and `each` returns having processed no lines, with all threads terminating

Behavior without `SO_LINGER` seems consistent: the client closes the socket, the server reads no lines, and the threads terminate normally.

**Comment by headius** [comment] 2023-10-18 13:44
On further inspection, the `10.times` and `loop` cases actually do behave the same; the errors raised are due to the main thread terminating in the former case, shutting down the runtime and interrupting the threads.

So the bottom line here is that `SO_LINGER` causes the sockets to appear forever readable.

**Comment by headius** [comment] 2023-10-18 15:38
There's a bit of risk here so this probably won't make it into the 9.4.4.0 release today.

**Closed** 2023-10-18 21:52 UTC
