### ISSUE TITLE
Graphenes are not matched correctly using \X

### ISSUE THREAD

**Issue by thallgren** [jruby/jruby#4870] opened 2017-11-28 10:58 UTC
### Environment
jruby-9.1.7.0 running on Linux 4.13.13-100.fc25.x86_64 #<nbsp>1 SMP Wed Nov 15 17:33:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior
\X should match the letter à in the form of a graphene encoded as U+0061 U+0300. The MRI shows the expected behavior:
```
$ irb
2.3.1 :001 > x = "h\u0061\u0300llo"
 => "hàllo" 
2.3.1 :002 > x =~ /h\Xllo/
 => 0 
```
### Actual Behavior
\X does not match the graphene using JRuby.
```
$ irb
jruby-9.1.7.0 :001 > x = "h\u0061\u0300llo"
 => "hàllo"
jruby-9.1.7.0 :002 > x =~ /h\Xllo/
 => nil 
```
Corresponding [issue for the jruby/joni](/jruby/joni/issues/30) package.

**Comment by olleolleolle** [comment] 2017-11-28 13:16
(Same in 9.1.14.0.)

**Comment by headius** [comment] 2017-11-28 14:00
Dupe of #4568.

**Closed by headius** 2017-11-28 14:00 UTC
