### ISSUE TITLE
`require_relative` does not work inside a jar on Windows

### ISSUE THREAD

**Issue by uemurm** [jruby/jruby#6254] opened 2020-06-01 04:29 UTC
This seems to be a recurrence of #4188.

**Environment Information**
jruby-complete-9.2.11.1.jar
Windows 10

**Pre-condition**
```
D:\work\DESK\core\functional-tests>cat foo.rb
class Foo
  def initialize
    puts 'This is a constructor.'
  end
end

D:\work\DESK\core\functional-tests>cat relative.rb
require_relative 'foo'
Foo.new

D:\work\DESK\core\functional-tests>cat require.rb
require './foo'
Foo.new

D:\work\DESK\core\functional-tests> jar cvf relative.jar relative.rb
D:\work\DESK\core\functional-tests> jar cvf require.jar require.rb
```

**Expected Behavior**
Behave in the same way as `require.rb`
```
D:\work\DESK\core\functional-tests>C:\work\dev-env\Tools\Java\jdk1.8.0_191\bin\java.exe -ea -cp D:\tmp\jruby-complete-9.2.11.1.jar;require.jar org.jruby.Main uri:classloader:/require.rb
This is a constructor.
```

**Actual Behavior**
```
D:\work\DESK\core\functional-tests>C:\work\dev-env\Tools\Java\jdk1.8.0_191\bin\java.exe -ea -cp D:\tmp\jruby-complete-9.2.11.1.jar;relative.jar org.jruby.Main uri:classloader:/relative.rb
LoadError: no such file to load -- uri:classloader:/foo
           require at org/jruby/RubyKernel.java:974
  require_relative at org/jruby/RubyKernel.java:1002
            <main> at uri:classloader:/relative.rb:1
```

**Comment by trejkaz** [comment] 2020-07-13 04:31
Can also reproduce on macOS but with a slightly different result:

```lang-none
% java -ea -cp '/Users/tester/test/jruby/space in path/jruby-complete-9.2.11.1.jar:relative.jar' org.jruby.Main uri:classloader:/relative.rb
LoadError: no such file to load -- uri:classloader://foo
```

Also the same result on latest release 9.2.12.0:

```lang-none
% java -ea -cp '/Users/dnoll01/test/jruby/space in path/jruby-complete-9.2.12.0.jar:relative.jar' org.jruby.Main uri:classloader:/relative.rb
LoadError: no such file to load -- uri:classloader://foo
```

In both cases using `require` worked instead, which would be the workaround but I find a lot of core tools are now using `require_relative` and it's difficult to convince them to switch back. :)

**Comment by trejkaz** [comment] 2020-07-13 04:39
Though, if I put foo.rb in the jar as well, then it works:

```lang-none
% jar cvf relative.jar relative.rb foo.rb                                                                                                  
added manifest
adding: relative.rb(in = 32) (out= 34)(deflated -6%)
adding: foo.rb(in = 71) (out= 67)(deflated 5%)

% java -ea -cp '/Users/tester/test/jruby/space in path/jruby-complete-9.2.12.0.jar:relative.jar' org.jruby.Main uri:classloader:/relative.rb
This is a constructor.
```

That _seems_ on the surface to make sense - relative.jar inside the jar, resolving foo.rb relatively, finds foo.rb inside the jar.

**Comment by trejkaz** [comment] 2020-07-13 06:08
Alright, the issue seen locally is similar looking but I can seemingly reproduce it on paths without a space, and but it does seem to have _something_ to do with the classpath, I just can't figure out what.

If I run with classpath set to jruby-complete.jar I don't get it now:

```lang-none
% java -cp "jruby-complete-9.2.12.0.jar" -ea org.jruby.Main -S gem
RubyGems is a sophisticated package manager for Ruby.  This is a
basic help message containing pointers to more information.
...
```

If I run with the individual jars I was getting on the classpath when run from a Maven/Gradle project, I get the error:

```lang-none
% java -cp "jcodings-1.0.44.jar:joda-time-2.9.9.jar:jnr-constants-0.9.12.jar:jnr-unixsocket-0.20.jar:jnr-posix-3.0.50.jar:jruby-core-9.2.7.0.jar:jruby-stdlib-9.2.7.0.jar:invokebinder-1.11.jar:options-1.4.jar:joni-2.1.26.jar:dirgra-0.3.jar:backport9-1.2.jar:jnr-enxio-0.19.jar" -ea org.jruby.Main -S gem
LoadError: load error: rubygems/gem_runner -- java.lang.AssertionError: Invalid start: 81
  require at org/jruby/RubyKernel.java:987
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
   <main> at uri:classloader:/META-INF/jruby.home/bin/jgem:9
     load at org/jruby/RubyKernel.java:1022
   <main> at uri:classloader:/META-INF/jruby.home/bin/gem:4
```

This happens even with all the jars in the current directory so it's a bit weird. It seems like maybe I'm missing something from the classpath, but to get that error in that situation seems odd to me.

**Comment by headius** [comment] 2020-07-13 08:00
I can reproduce the original error using the jruby.jar from the jruby dist (which shouldn't matter for this case):

```
$ java -cp lib/jruby.jar:relative.jar -Djruby.home=`pwd` org.jruby.Main uri:classloader:/relative.rb
LoadError: no such file to load -- uri:classloader:/foo
           require at org/jruby/RubyKernel.java:1043
  require_relative at org/jruby/RubyKernel.java:1071
            <main> at uri:classloader:/relative.rb:1
```

But I do not believe this is improper behavior. The relative path of the `relative.rb` inside the jar is `uri:classloader:/`, and so `require_relative` will not find a file in some other path like `./`.

Adding the current directory to the classpath makes it work the way you expect, since the current path is now in the `uri:classloader` namespace:

```
$ java -cp lib/jruby.jar:relative.jar:`pwd` -Djruby.home=`pwd` org.jruby.Main uri:classloader:/relative.rb
This is a constructor.
```

...as does adding `.` to the classpath:

```
$ java -cp lib/jruby.jar:relative.jar:. -Djruby.home=`pwd` org.jruby.Main uri:classloader:/relative.rb
This is a constructor.
```

The logic for `require_relative` works by using the reported path of the filename, which in this case will report that is is inside the `uri:classloader` namespace:

```
$ java -cp lib/jruby.jar:file.jar -Djruby.home=`pwd` org.jruby.Main uri:classloader:/file.rb
uri:classloader:/file.rb
```

@trejkaz It appears you may be running into the same issue. There's also an additional complexity here:

* If no classpath is provided, the `java` command includes the current directory.
* Passing the `-cp` or `-classpath` parameters to the `java` command causes the current directory to be excluded.

When running the `jruby` command from a normal JRuby distribution, if you do not specify a classpath we will emulate the behavior of the `java` command and include the current directory as the default classpath (in addition to the `lib/jruby.jar` we use to execute... but you shouldn't have to care about that). So running this example just using `jruby` works as expected, since the current directory is in the `uri:classloader` namespace:

```
$ jruby uri:classloader:/relative.rb
This is a constructor.
```

And finally, the example of `require "./foo"` works because "./" is always resolved relative to the user's current system directory, not against any path in the "virtual" `uri:classloader` namespace (unless you explicitly `chdir` into a `uri:classloader` path, which we do support).

All examples here appear to be working as expected, so I'm going to close this issue. If you run into a different issue, please open a new bug and we will try to help.

@enebo @mkristian @kares I guess this may not be covered well enough in the wiki?

**Closed by headius** 2020-07-13 08:00 UTC

**Comment by headius** [comment] 2020-07-13 16:43
I added a page to the wiki, linked from the [Integration With JVM Languages](https://github.com/jruby/jruby/wiki/Integration-With-JVM-Languages)

[Loading Scripts From Classpath](https://github.com/jruby/jruby/wiki/Loading-Scripts-From-Classpath)

Hopefully this clears up some confusion!

**Comment by trejkaz** [comment] 2020-07-13 23:52
I figured out my issue too I believe, backport9-1.2.jar seems to have been the culprit and forcibly updating it to a newer version fixed the issue. (Maybe I can just bump JRuby up to a newer version but I think we already tried that and the newest release hadn't worked either.)
