### ISSUE TITLE
warFile based on JRuby-9.2.7.0 fails to initialize when deployed to Tomcat, seems bundler related.

### ISSUE THREAD

**Issue by skoona** [jruby/jruby#5721] opened 2019-04-29 21:10 UTC
Deploying a warFile built on JRuby-9.2.7.0 ecosystem fails to initialize.  Error messages seem to suggest that the wrong version of Bundler is being used.  Changing to Bundler-1.16.3 during build then complain that gems can't be found or that gem-pristine needs to be run on random gems.  

I think it could be related to #5686 since the fail point has been removed with ruby-9.2.8.0.

### Environment

RVM-1.29.7
RAILS-5.2.3
JRUBY-9.2.7.0
JRUBY-JARS-9.2.7.0
JRUBY-RACK-1.1.21
WARBLER-2.0.5
TOMCAT-7.0.22
java version "1.8.0_60"
MacOS High Sierra

### Expected Behavior
normal initialization.

### Actual Behavior
produces the following in browser and tomcat log

Browser: 
```
Internal Server Error (500)
Request Method:    GET
Request URL:    http://localhost:8080/
You must use Bundler 2 or greater with this lockfile. 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/lockfile_parser.rb:95:in `initialize' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:84:in `initialize' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/dsl.rb:218:in `to_definition' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/dsl.rb:13:in `evaluate' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:35:in `build' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler.rb:135:in `definition' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler.rb:101:in `setup' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/setup.rb:20:in `<main>' 
from org/jruby/RubyKernel.java:987:in `require' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `<main>' 
from org/jruby/RubyKernel.java:987:in `require' 
from /Library/Tomcat/apache-tomcat-7.0.22/webapps/ROOT/WEB-INF/config/boot.rb:4:in `<main>' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require' 
from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `<main>'
You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.
```

Tomcat:
```
29-Apr-2019 13:48:17.687 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive ROOT.war
uri:classloader:/jruby/rack/response.rb:294: warning: constant ::Fixnum is deprecated
uri:classloader:/jruby/rack/core_ext.rb:26: warning: constant ::NativeException is deprecated
Exception `Bundler::LockfileError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/lockfile_parser.rb:108 - You must use Bundler 2 or greater with this lockfile.
Exception `Bundler::LockfileError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/lockfile_parser.rb:108 - You must use Bundler 2 or greater with this lockfile.
Exception `Bundler::LockfileError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/lockfile_parser.rb:108 - You must use Bundler 2 or greater with this lockfile.
Exception `Bundler::LockfileError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/lockfile_parser.rb:108 - You must use Bundler 2 or greater with this lockfile.
uri:classloader:/jruby/rack/response.rb:294: warning: constant ::Fixnum is deprecated
uri:classloader:/jruby/rack/core_ext.rb:26: warning: constant ::NativeException is deprecated
Ignoring childprocess-1.0.1 because its extensions are not built. Try: gem pristine childprocess --version 1.0.1
```

**Comment by skoona** [comment] 2019-04-29 21:16
Should say that running a rails server or console from the command line works normally.

**Comment by headius** [comment] 2019-04-29 22:21
Duplicate of #5686, which is now fixed. Thanks for the report!

**Closed by headius** 2019-04-29 22:21 UTC
