### ISSUE TITLE
Java::JavaLang::ClassCastException when initializing instance variable

### ISSUE THREAD

**Issue by rovf** [jruby/jruby#7596] opened 2023-01-25 12:01 UTC
**Environment Information**
  
Using jruby-complete-9.4.0.0.jar on Windows 10,  running under Java 1.8

I must admit upfront, that I was not able yet to create a simple reproducible example for the error. It occurs in our application  and somehow seems to depend on what had been executed before. I still report it in the hope that the error message perhaps gives you an idea where it goes wrong. I also describe a work-around to the bug.

We have a  module U and a class V, which simplified look like this:

```
module U
  extend self
  def f
    '067'
  end 
end

class V
  def w
    @wk ||= U.f # <--- exception here
  end
  def forget_w!
     @wk=nil
  end
end
```
The idea here is, that we do some meomoizing: On the first invocation of V#w, U.f is calculated. On each subsequent invocation for the same object, the memoized value is returned. Note that @wk is not defined in the constructor of the class. The instance variable springs into existence during the first invocation of V#w.

In our application, a large number of such V instances is created.  If V.w is executed on the first of them, it works fine. If it is executed on the second instance which had been created, I get an exception:

_Java::JavaLang::ClassCastException Exception: **java.lang.Long cannot be cast to org.jruby.runtime.builtin.IRubyObject**     [ 1] org.jruby.ir.runtime.IRRuntimeHelpers.getVariableWithAccessor(IRRuntimeHelpers.java:2047)_

I can make the error disappear, when I rewrite the method w in the following way:

```
  def w
     if ! defined?(@wk) || @wk.nil?
      @wk = U.f # <--- no exception here
    end
    @wk
  end
```
I conclude that the problem is related to using `@wk ||= ...` for creating an instance variable which has not existed before. I do not know why then the exception does not occur for every instance of V, because in this particular execution, each instance **does** invoke the method w at least once.. 

**Additional information**: 

Another oddity is related to catching this exception. In my original code, the exceptions are caught like this:

```
def some_method(v)
   x = v.w # <---- Produces exception from above
  ...
rescue Exception => e
  puts "Caught: #{e}..."
end
```

Running some_method displayed the aforementioned exception. In the process of debugging, I also had in between a version of my method w which looked like this:

```
  def w
    @wk ||= U.f # <--- exception here
  rescue Exception => e
     puts "Exception #{e} in w"
     exit
  end
```

In this variant, the exception was still reported from the calling method , some_method, but not by the `rescue` statement inside method w. Consequently, the `exit` statement was not executed either.

**Comment by headius** [comment] 2023-01-25 12:39
Thank you for the report!

It seems like this is getting an incorrect value, like it is looking for the instance variable slot but picking up the slot that is 
for `object_id` or similar.

Reproducing this might be easier if you force the JRuby JIT to run using `-Xjit.threshold=0`. Another flag that would help me diagnose this would be `-Xbacktrace.style=full` to show all Java/JVM and Ruby frames in the stack trace.

**Comment by rovf** [comment] 2023-01-25 12:52
**UPDATE** : 

When I explained above the work-around to the bug, I was a mis-observation: I get the impression that there is a basic problem in bringing instance variables to life in some objects of a class. To see better what is going on, I printed more diagnostics in the method w:

 ```
  def w
     puts ":::: calculating"
     puts ":::: #{defined?{@wk)}"
     if ! defined?(@wk)
       puts ":::: undefined"
       @wk = U.f # <--- no exception here
    end
    puts ":::: should be defined"
    puts ":::: #{@wk}"
    @wk
  end
```

Now again the first V instance in our application is running the method w several times without problem. The second instance however produces the output

:::: calculating
:::: instance-variable
:::: should be defined

and then an exception. Note that in the second V instance, `@wk` was already defined, even though the method had never been executed. I have the impression, that somehow the instance variable @wk had somehow been associated to the class, i.e. to all other instances. 

In the JRuby version we used previously (we were running JRuby 1.7 until now),  some of the V-objects had a @wk variable (those where V#w had been invoked) and some of them didn't (those where V#w had never been invoked yet). I'm not sure now whether this was a misconception of my side on how dynacmically defining instance variables works (and which just happened to work in the old JRuby), or whether this is a bug in the new JRuby.

**Comment by rovf** [comment] 2023-01-25 13:18
I just re-tested our application with jruby-complete-9.2.8.0.jar and the problem did not occur there. If you want me to test it with yet another version, let me know.

**Comment by headius** [comment] 2023-01-25 13:38
@rovf This is definitely not your bug. It appears to be a regression in JRuby, but a very unique and special regression I have not seen reported until now!

I am guessing it would be difficult for you to make the app available for me to test. Without a reproduction in hand, I will have to guide you to gather more information for me. Primarily, that would be reproducing the error with `-Xbacktrace.style=full` passed to JRuby (or JVM property "jruby.backtrace.style=full".

I still suspect that this object has an `object_id` being stored in the object's internal variables, which share a table with instance variables. Something is then causing your `@wk` lookup to try to use that state, which is a long and not castable to our Ruby object type IRubyObject.

Let me know if you can try to reproduce this with the flag above. I will also be available on our Matrix channel to work with you.

**Comment by rovf** [comment] 2023-01-25 13:50
This JRuby option is rejected. My call looks like this:

```
java -Xmx4G -cp 'C:\jruby\jruby-complete-9.4.0.0.jar;C:\\Cygwin64\\home\\FISRONA\\gitwrk\\vp5\\repository\\maven2\\com\\tsystems\\dialog\\lcr\\18.12.1\\lcr-18.12.1.jar' org.jruby.Main '-Xbacktrace.style=full' C:/Cygwin64/home/FISRONA/gitwrk/vp5/manualtest/perform_mt.rb
```

and this gave me the error message

_jruby: invalid extended option backtrace.style=full_

Are you sure that this option is supposed to go to JRuby?

**Comment by headius** [comment] 2023-01-25 13:52
When running from the jar, past the flag to Java as a JVM property like this: `-Djruby.backtrace.style=full`

**Comment by rovf** [comment] 2023-01-25 14:11
Here is the full backtrace:

   [ 1] org.jruby.ir.runtime.IRRuntimeHelpers.getVariableWithAccessor(IRRuntimeHelpers.java:2047)
    [ 2] C_3a_.Cygwin64.home.fisrona.gitwrk.vp5.src.main.scripts.data.vehicle.RUBY$method$werk$0(C:/Cygwin64/home/fisrona/gitwrk/vp5/src/main/scripts/data/vehicle.rb:130)
    [ 3] org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:152)
    [ 4] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:148)
    [ 5] org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
    [ 6] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351)
    [ 7] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144)
    [ 8] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:346)
    [ 9] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [10] org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
    [11] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
    [12] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
    [13] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
    [14] org.jruby.RubyClass.newInstance(RubyClass.java:931)
    [15] org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
    [16] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
    [17] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
    [18] org.jruby.ir.instructions.CallBase.interpret(CallBase.java:561)
    [19] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:363)
    [20] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [21] org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
    [22] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
    [23] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
    [24] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
    [25] org.jruby.ir.instructions.CallBase.interpret(CallBase.java:561)
    [26] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:363)
    [27] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [28] org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
    [29] org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201)
    [30] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188)
    [31] org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:220)
    [32] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372)
    [33] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175)
    [34] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
    [35] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [36] org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
    [37] org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
    [38] org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:170)
    [39] org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
    [40] org.jruby.runtime.Block.yield(Block.java:188)
    [41] org.jruby.RubyArray.each(RubyArray.java:1988)
    [42] org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
    [43] org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:560)
    [44] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
    [45] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
    [46] org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:94)
    [47] org.jruby.ir.instructions.CallBase.interpret(CallBase.java:558)
    [48] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:363)
    [49] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [50] org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
    [51] org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136
)
    [52] org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:177)
    [53] org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
    [54] org.jruby.runtime.Block.yieldArray(Block.java:230)
    [55] org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:492)
    [56] org.jruby.ir.instructions.YieldInstr.interpret(YieldInstr.java:92)
    [57] org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:166)
    [58] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:98)
    [59] org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
    [60] org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201)
    [61] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188)
    [62] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:383)
    [63] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:185)
    [64] org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:192)
    [65] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:337)
    [66] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [67] org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
    [68] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
    [69] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
    [70] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
    [71] org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:94)
    [72] org.jruby.ir.instructions.CallBase.interpret(CallBase.java:558)
    [73] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:363)
    [74] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [75] org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMet
hod.java:128)
    [76] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
    [77] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
    [78] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
    [79] org.jruby.ir.instructions.CallBase.interpret(CallBase.java:561)
    [80] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:363)
    [81] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [82] org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
    [83] org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
    [84] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
    [85] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
    [86] org.jruby.ir.instructions.CallBase.interpret(CallBase.java:561)
    [87] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:363)
    [88] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
    [89] org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:96)
    [90] org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:81)
    [91] org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:30)
    [92] org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
    [93] org.jruby.Ruby.runInterpreter(Ruby.java:1312)
    [94] org.jruby.Ruby.runInterpreter(Ruby.java:1316)
    [95] org.jruby.Ruby.runNormally(Ruby.java:1199)
    [96] org.jruby.Ruby.runNormally(Ruby.java:1176)
    [97] org.jruby.Ruby.runNormally(Ruby.java:1212)
    [98] org.jruby.Ruby.runFromMain(Ruby.java:991)
    [99] org.jruby.Main.doRunFromMain(Main.java:398)
    [100] org.jruby.Main.internalRun(Main.java:282)
    [101] org.jruby.Main.run(Main.java:227)
    [102] org.jruby.Main.main(Main.java:199)

**Comment by rovf** [comment] 2023-01-25 15:12
New information:

I could now make some comparision between two runs, one OK and one crashing. The main difference between wht two runs was in the use of the `Marshal` class. I didn't mention before that we are using `Marshal`, because I didn't consider it significant:

Run 1 (good):
   I read data from a file and create an array of 2 objects of class `V`. By this time, the method `w` has not been called yet. Then I use `Marshal.dump` to create a String representation of this array, write in on the disk, and then I process the array, doing plenty of invocations of `w` on the first array element, then plenty of invocations of `w` on the second element. No problem.

Run 2 (bad):
   I read the data from the file created in the first run, use `Marshal.load` to create the two element array, and then process as above. For the first array element everything is fine, but the second element crashes on the invocation of the `w` method.

It looks now that the error relates to the `Marshal` class: Data loaded via `Marshal` behave badly for my test situation.

**Comment by rovf** [comment] 2023-01-25 15:29
Indeed, this is it! The data is broken after the `Marshal.load`. I could create at least a somewhat reduced example, which reproduces the error. Sadly, even the reduced example consists still of about 280 lines of code.

**Comment by headius** [comment] 2023-01-25 19:49
Great investigation! That makes sense; Marshal is probably putting the fields back in the wrong place, or not coordinating properly with the instance variables table.

And the size of the reduced code is not too important if it fails consistently. Post that code and I can get this fixed.

**Comment by rovf** [comment] 2023-01-26 11:15
As I already said in my mail, I can provide the example code, but I would prefer to send it to you by mail, and not making it visible to every one, because it is based on code in our project. Although it does not contain real confidential information, I'm not supposed to make any of the code publicly visible. Can you give me an email address for this?

**Comment by rovf** [comment] 2023-01-30 13:30
>  Post that code and I can get this fixed.

Sorry, but I haven't got yet your contact mail address where I could send you the example code for reproducing the error....

**Comment by enebo** [comment] 2023-01-30 17:29
@rovf it is his name at his name .com (it is also in his github profile).

**Comment by headius** [comment] 2023-01-31 16:40
I received your example and can reproduce on 9.4. I can also confirm it does not happen on 9.3.

**Comment by headius** [comment] 2023-01-31 17:07
@rovf Ok, it does look like what I suspected: an object_id is somehow getting into the ivar slot for a regular Ruby ivar, so we blindly cast that value and it blow up.

But I'm confused by your example. Without knowing how the data is being marshaled in the first place, I can't be sure the stream isn't bad. If this is from an older JRuby, it may be that it was producing data that could not be marshaled by a newer JRuby. However, it does unmarshal on Ruby 3.1, so that theory is not strong.

Is it possible to see the code that produced this marshaled data file?

**Comment by headius** [comment] 2023-01-31 18:28
I found a fix for this and pushed #7606. The issue was that we were using the Ruby object_id as a key during object unmarshaling, which interfered with the instance variable table (and bloated up the size of any unmarshaled object). My fix uses a Java IdentityHashMap instead.

**Closed** 2023-01-31 18:38 UTC

**Comment by rovf** [comment] 2023-02-01 08:44
> @rovf Ok, it does look like what I suspected: an object_id is somehow getting into the ivar slot for a regular Ruby ivar, so we blindly cast that value and it blow up.
> 
> But I'm confused by your example. Without knowing how the data is being marshaled in the first place, I can't be sure the stream isn't bad. If this is from an older JRuby, it may be that it was producing data that could not be marshaled by a newer JRuby. However, it does unmarshal on Ruby 3.1, so that theory is not strong.
> 
> Is it possible to see the code that produced this marshaled data file?

It is produced with the exactly same JRuby version. The actual code was in our large application and difficult to extract, but if this it important for you, I can try to also create a small example. However, if you can somehow give me a link to a JRuby-complete-jar with the fix, I could try it with our application, which perhaps would be an even better test.

**Comment by headius** [comment] 2023-02-01 13:26
The nightly snapshot of the 9.4.1 complete jar is in here: https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-complete/9.4.1.0-SNAPSHOT/

I don't believe I need to see the marshalling code anymore since it was purely a problem in the unmarshalling logic.

**Comment by rovf** [comment] 2023-02-02 11:23
I can confirm that the error does not occur anymore in our application when running it with jruby-complete-9.4.1.0-20230201.063920-78.jar

**Comment by headius** [comment] 2023-02-02 15:57
> I can confirm that the error does not occur anymore in our application when running it with jruby-complete-9.4.1.0-20230201.063920-78.jar

Thank you!
