### ISSUE TITLE
Bundle install fails with jruby-head with a Java::JavaLang::ArrayIndexOutOfBoundsException on travis

### ISSUE THREAD

**Issue by pxlpnk** [jruby/jruby#3102] opened 2015-07-02 21:51 UTC
When trying to install the bundle for lograge we run into a weird exception:
https://travis-ci.org/roidrage/lograge/jobs/69340155#L190

I tried running bundle install with `--verbose` here https://travis-ci.org/pxlpnk/lograge/jobs/69359540 but it didn't yield any further pointers. 
Any idea where I can start with my investigation?

**Comment by pxlpnk** [comment] 2015-07-02 22:08
I disabled the logstash Gem and the installation works then. https://travis-ci.org/pxlpnk/lograge/jobs/69362086
Could the problem be in fetching the Gem or something in the gemspec?

**Comment by headius** [comment] 2015-07-03 02:48
Hmm...I'm trying to reproduce it by bundle installing from that PR and it's not blowing up for me. Are you able to reproduce the exception locally? We need more information.

**Comment by cheald** [comment] 2015-07-03 06:18
I had the same issue with a jruby-head build (via RVM) this afternoon.

https://gist.github.com/cheald/5417ab577218766c474f

**Comment by pxlpnk** [comment] 2015-07-03 09:10
@headius I am currently struggling with setting up a vm that is like the travis ci one.
What would you need on information and how do I get it?

**Comment by headius** [comment] 2015-07-03 14:32
@pxlpnk You can request SSH access to an instance for 24 hours by emailing Travis CI support. Once in there you can run the same sequence of commands, but for the bundle install we can try a few flags to get more information:

* `--verbose` or other bundle flags that would make it print out the exceptions
* with and without jruby flag `-Xbacktrace.style=full` which includes normally-omitted Java backtrace lines

I'll be on IRC today if you want to work together on this.

**Comment by headius** [comment] 2015-07-03 14:33
@cheald If that is indeed the same error, it may be related to a fix we made to *prevent* this error. What rev is that build?

**Comment by pxlpnk** [comment] 2015-07-03 16:01
Unfortunately I won't get to this today. I will ping their support and see if I can get SSH access and run it with `-Xbacktrace.style=full`

Using `--verbose` didn't yield any result as it can be seen here: https://travis-ci.org/pxlpnk/lograge/jobs/69359540#L181

**Comment by cheald** [comment] 2015-07-03 19:12
$ jruby -v
jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-07-02 10be3bb OpenJDK 64-Bit Server VM 25.25-b02 on 1.8.0_25-b18 +jit [linux-amd64]

**Comment by cheald** [comment] 2015-07-03 19:14
FWIW, this is failing when I try to run rake from my Manticore project - https://github.com/cheald/manticore - you can probably clone it and bundle install/rake to repro it. I'm working on rebuilding jruby-head right now to re-test.

**Comment by cheald** [comment] 2015-07-03 19:21
Full reproduction steps here: https://gist.github.com/cheald/81b0189bb64dabcff8aa

**Comment by headius** [comment] 2015-07-06 20:00
@cheald Great, thank you!

**Comment by headius** [comment] 2015-07-06 20:04
I was unable to reproduce with my working copy of JRuby, but I'll try against RVM now.

**Comment by headius** [comment] 2015-07-06 23:35
The fix is in! Please confirm with latest JRuby head.

**Closed** 2015-07-06 23:35 UTC
Labels: JRuby 9000

**Comment by pxlpnk** [comment] 2015-07-07 07:50
Still breaks on travis. Do you know how often the jruby head builds get updated from their side? /cc @rkh
https://travis-ci.org/roidrage/lograge/jobs/69846080#L153
