### ISSUE TITLE
`bundle exec racc` fails on jruby-head

### ISSUE THREAD

**Issue by marcandre** [jruby/jruby#6416] opened 2020-09-28 20:12 UTC
Gemfile states `gem 'racc'`, without any particular spec.

```sh
$ bundle
[...]
Using racc 1.5.0 (java)
[...]
$ bundle exec racc ...
bundler: command not found: racc
Install missing gem executables with `bundle install`
rake aborted!
```

Same config appears to run without an issue on jruby
See full CI spec (github actions): https://github.com/rubocop-hq/rubocop-ast/pull/128/checks?check_run_id=1178552900

Reproduced on my mac too.

**Comment by headius** [comment] 2020-09-29 16:45
I'm guessing this is due to the built-in racc being the one without the GPLed parser generator bits. I think @tenderlove managed to split this up, but manually installing racc might solve the problem.

**Comment by headius** [comment] 2020-09-29 16:51
Hmm so far I can't reproduce using JRuby master or JRuby 9.2.13.0 from RVM:

```
[] ~/projects/jruby/tmp $ rvm use system
Now using system ruby.

[] ~/projects/jruby/tmp $ bundle install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.1.4
Using racc 1.5.0 (java)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

[] ~/projects/jruby/tmp $ bundle exec racc
no input

[] ~/projects/jruby/tmp $ rvm use jruby-9.2.13.0
Using /Users/headius/.rvm/gems/jruby-9.2.13.0

[] ~/projects/jruby/tmp $ bundle install
Fetching gem metadata from https://rubygems.org/.
Using bundler 2.1.4
Fetching racc 1.5.0 (java)
Installing racc 1.5.0 (java)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

[] ~/projects/jruby/tmp $ bundle exec racc
no input
```

How did you install JRuby?

**Comment by marcandre** [comment] 2020-09-29 17:40
Oh, looks like github purges the logs quickly.

I can no longer reproduce it on my machine, but it still does it on github actions. I recreated a PR for you: https://github.com/rubocop-hq/rubocop-ast/pull/132/checks?check_run_id=1183594198
(ignore the "Coding style" failure)

I'm pretty much using the exact same setup as `parser`, so I was curious and checked but their CI does not run on JRuby-head...

**Comment by headius** [comment] 2021-02-24 21:31
This should be fixed by the restoration of the racc gem as a default gem in #6576. The racc bits themselves were updated to match latest in #6537.

**Closed by headius** 2021-02-24 21:31 UTC

**Comment by headius** [comment] 2021-03-09 04:21
I am a bit confused why this is still failing for you.

Here's 9.2.x HEAD for me locally:

```
[] ~/projects/rubocop-ast $ bundle install
Fetching gem metadata from https://rubygems.org/.........
Using rake 13.0.3
Using bundler 2.2.11
Using ast 2.4.2
Using diff-lcs 1.4.4
Using json 2.5.1 (java)
Using parallel 1.20.1
Using parser 3.0.0.0
Using rainbow 3.0.0
Using racc 1.5.2 (java)
...
Bundle complete! 11 Gemfile dependencies, 27 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

[] ~/projects/rubocop-ast $ bundle exec racc --version
racc version 1.5.2
```

I can give the exact sequence of commands you have in CI a try later but shouldn't this have failed if it is still broken?

**Comment by headius** [comment] 2021-03-09 04:22
FWIW this is the same on master. I did confirm both worked before restoring the racc gem.

**Comment by marcandre** [comment] 2021-03-09 04:33
I do not know why there's an issue on github actions. There's nothing unusual about the setup (copied from `parser`). 

I did not test on my machine, but the exact step would be to do `bundle exec rake spec` which should trigger `racc` because of [this rule](https://github.com/rubocop/rubocop-ast/blob/master/tasks/compile.rake#L43-L46). Maybe do a `rake clean` beforehand to be sure to trigger `racc`.

**Comment by marcandre** [comment] 2021-03-09 18:36
I can't test it easily locally, as `ruby-build` has not been updated but not released (cc @eregon)

@headius reminder: could you reopen this issue?

**Comment by eregon** [comment] 2021-03-09 20:42
Release of `ruby-build` done: https://github.com/rbenv/ruby-build/releases/tag/v20210309

**Comment by marcandre** [comment] 2021-03-09 20:47
Thanks @eregon ❤️

**Comment by headius** [comment] 2021-03-09 20:55
> I opened #6604 but I can not say it was without a feeling of frustration

We just want to keep the list of issues closed in a given release consistent.

Your title specified that `bundle exec racc` did not work. Your description provided an example showing that `bundle exec racc` did not work. I pointed out in https://github.com/jruby/jruby/issues/6416#issuecomment-793363653, that command, run against the project you specified, worked fine for us locally. So I would consider this issue to be resolved.

If there is a different or more complex issue during a different sequence of commands or in a specific environment, that would be new work to investigate. Ergo, we would want a new issue that we can attach to a new release.

FWIW I can reproduce the ongoing issue when running the full `bundle exec rake spec` build, but not when running the command line that you specified as the problem here. We will continue this in the new issue.

**Comment by headius** [comment] 2021-03-09 20:57
Also to clarify... the problem was not the title (although we would prefer not to rename issues that have been included in closed releases). The problem was that we do not reopen issues attached to closed releases. The new issue that you filed is just fine, since it references this one and elaborate on the remaining problem.

**Comment by marcandre** [comment] 2021-03-09 22:45
> We just want to keep the list of issues closed in a given release consistent.

This is your prerogative, but it is mine to point out that this rule offers only downsides to the contributors that report issues. I am unaware of other FOSS projects that have such a rule, so I hope you realize that it may be badly perceived and you should take for granted that episodic contributors like myself will be completely unaware of that and have no reason to suspect such a rule and act accordingly.

I will also point out that instead of asking me to open a new one, you did not even acknowledge my original request to reopen the issue. Your later reply also did not include "I'm sorry" or "Please".

**Comment by headius** [comment] 2021-03-09 23:06
I would be happy to discuss this further over a chat, but these comments have become counterproductive. As I see it, you let us know late last night that there were still issues (thank you!), and after I confirmed (seven minutes later) that the original problem appeared to be ok in 9.2.16.0, you clarified what we should run to reproduce (thank you!). I let you know that we would prefer a new issue, you opened one, and I am **at this moment** trying to fix it.

I should have asked you to open a new issue right away, but since `bundle exec racc` worked for me I wanted to confirm that there was not some environment or update issue on your end. I was hoping to avoid filing a new issue unnecessarily if it was just a temporary problem (like CI did not update JRuby, or something).

I don't feel like our policy is that unusual. Bugs cannot be reopened by the original reporter for a good reason: it is the project's prerogative whether they want to reopen a closed issue. You requested a reopen, and I did not make it clear that closed release issues should remain closed.

Please accept my most humble apologies for not communicating quickly and clearly enough how we would like to proceed with this ongoing issue.

**Comment by headius** [comment] 2021-03-09 23:58
Closing the loop: the ongoing issues with racc appear likely to be a packaging issue... we are not including all of the default gem bits in the distribution. See #6604 and I will try to figure out a reasonable workaround until we can address it properly.
