### ISSUE TITLE
class name wasn't set properly for some constant in 9.0.5.0?

### ISSUE THREAD

**Issue by godfat** [jruby/jruby#3641] opened 2016-02-04 12:03 UTC
Sorry I can't find a smaller code to reproduce this, but this happens only in jruby 9.0.5.0,
and 9.0.4.0 works fine. Here's the code:
https://github.com/godfat/rest-more/blob/rest-more-3.4.0/lib/rest-core/client/facebook.rb#L8
`Builder.client` would return a new class, and the name should be set to `RestCore::Facebook`.
Surprisingly, if you change the constant to `FAcebook`, it works, and so on so forth.
Interestingly, `Github` won't work either.

I suspect this was due to that the constant might be considered set somewhere else.

This bug caused this error:
https://travis-ci.org/godfat/rest-more/jobs/106942941#L310
Because we can't serialize anonymous class (which shouldn't be).

**Comment by kares** [comment] 2016-02-18 15:04
tested `bin/jruby -e "require 'rest-core/client/facebook'; p RestCore::Facebook"` and is now fine, printing : 
```
RestCore::Facebook
```
... the cause of the issue is explained at https://github.com/jruby/jruby/issues/3645#issuecomment-184641569 marking as duplicate

**Closed by kares** 2016-02-18 15:04 UTC

**Comment by godfat** [comment] 2016-02-18 15:17
Thank you!
