### ISSUE TITLE
alias method doesn't work as expected

### ISSUE THREAD

**Issue by jankowy** [jruby/jruby#5291] opened 2018-08-27 11:32 UTC
### Environment
* JRuby version
`jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 25.181-b13 on 1.8.0_181-8u181-b13-1~deb9u1-b13 +jit [linux-x86_64]`
* Operating system and platform
`Linux b8eda5147dd5 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 GNU/Linux`

I have two simple ruby scripts:

```
# alias.rb

class User

  def full_name
    puts "Johnnie Walker"
  end

  def self.add_rename
    alias name full_name
  end
end

class Developer < User
  def full_name
    puts "Geeky geek"
  end
  add_rename
end

Developer.new.name #=> Johnnie Walker"
```

and

```
# alias_method.rb

class User

  def full_name
    puts "Johnnie Walker"
  end

  def self.add_rename
    alias_method :name, :full_name
  end
end

class Developer < User
  def full_name
    puts "Geeky geek"
  end
  add_rename
end

Developer.new.name #=> "Geeky geek"
```

### Expected Behavior

On CRuby everything works as excpeted:

```
root@ed81cc48a8a7:/app# ruby alias.rb 
Johnnie Walker
root@ed81cc48a8a7:/app# ruby alias_method.rb 
Geeky geek
root@ed81cc48a8a7:/app# ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

### Actual Behavior

On JRuby `alias` and `alias_method` seem to work the same way:

```
root@b8eda5147dd5:/app# ruby --version
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 25.181-b13 on 1.8.0_181-8u181-b13-1~deb9u1-b13 +jit [linux-x86_64]
root@b8eda5147dd5:/app# ruby alias.rb 
Geeky geek
root@b8eda5147dd5:/app# ruby alias_method.rb 
Geeky geek
```

**Comment by ChrisBr** [comment] 2018-08-27 16:57
Confirmed on current master, first glance looks like we only have one method cache for alias and alias_method...

**Comment by headius** [comment] 2018-08-27 18:33
I'd guess that "alias" within a self.whatever (defs) style method is not getting the proper location to define its new target, or is otherwise just using the wrong target.

I do wonder if this behavioral difference between `alias` and `alias_method` is intentional though. Perhaps this should be raised with ruby-core for clarification?

**Comment by headius** [comment] 2018-10-26 20:39
Punting because there's some questions in my mind as to whether `alias` and `alias_method` should actually behave differently here.

**Comment by headius** [comment] 2018-12-18 18:58
I'm going to close this as Won't Fix because I don't believe the MRI behavior is correct. I don't see why `alias` and `alias_method` in this context should do anything differently, and the `alias` behavior there just seems broken to me.

For the record, I think I know how to fix it: alias should be passed the class of the current method, rather than the "self" object which will refer to the subclass. I just don't know why you'd want that, especially in this case where the alias is *clearly* running against the subclass.

**Comment by headius** [comment] 2018-12-18 18:58
If this is a problem for you I would recommend opening an issue with ruby-core (https://bugs.ruby-lang.org) and getting clarification about this strange behavior. We'll happily fix it if they make this behavior official, or we will match whatever they decide to do if it differs from what we do now.

**Closed by headius** 2018-12-18 18:58 UTC
