### ISSUE TITLE
LinkageError under load when reify.classes is used

### ISSUE THREAD

**Issue by sclasen** [jruby/jruby#1021] opened 2013-09-17 22:44 UTC
Getting these randomly during load testing. Get 12x of them at the same time, which also happens to be the level of concurrency of the load test.

* JRuby 1.7.4

```
Java::JavaLang::LinkageError 
message='loader (instance of  org/jruby/util/ClassCache$OneShotClassLoader):
attempted  duplicate class definition for name: "rubyobj/Redis/Future"' 
backtrace="java.lang.ClassLoader.defineClass1(Native Method)"
```

**Comment by kares** [comment] 2016-01-10 18:15
has been fixed for a while ... duplicate of #1229

**Closed by kares** 2016-01-10 18:15 UTC
Labels: java integration
