### ISSUE TITLE
Error calling `Array#flatten` on Enumerator elements via `Symbol#to_proc` in JRuby 9.4

### ISSUE THREAD

**Issue by janko** [jruby/jruby#7538] opened 2022-12-25 22:46 UTC
**Environment Information**
  
```sh
$ jruby -v
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.2+0 on 17.0.2+0 +jit [arm64-darwin]
``` 
```sh
$ uname -a
Darwin Jankos-MacBook-Air.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
```

**Expected Behavior**

The following script passes without errors on Ruby 3.1:

```rb
array = [
  [
    [128, 161, 196],
    [151, 184, 223],
    [167, 202, 244],
    [174, 207, 247],
    [184, 217, 252],
    [187, 219, 247],
    [188, 220, 246],
    [182, 213, 233],
  ]
]

array.to_enum.map(&:flatten)
```

**Actual Behavior**

However, on JRuby 9.4 it raises an error:

```
ArgumentError: `flatten': wrong number of arguments (given 7, expected 0..1)
    each at org/jruby/RubyArray.java:1988
    each at org/jruby/RubyEnumerator.java:397
     map at org/jruby/RubyEnumerable.java:835
  <main> at program.rb:14
... 5 levels...
```

A simpler form of this bug is:

```rb
array = [[[1], [2], [3]]]
array.to_enum.map(&:flatten)
```
```
ArgumentError: `flatten': wrong number of arguments (given 2, expected 0..1)
    each at org/jruby/RubyArray.java:1988
    each at org/jruby/RubyEnumerator.java:397
     map at org/jruby/RubyEnumerable.java:835
  <main> at program.rb:2
... 5 levels...
```

What's interesting is that the behavior is different depending on whether or not I use the `Symbol#to_proc` shorthand:

```rb
array = [[]]
array.to_enum.map { |a| a.flatten } # works without issues
array.to_enum.map(&:flatten) #~> NoMethodError: undefined method `flatten' for nil:NilClass
```

So, the issue seems to occur when mapping Enumerators with the `&:foo` shorthand.

This bug originally occurred in the [ImageProcessing test suite](https://github.com/janko/image_processing/actions/runs/3777675215/jobs/6421632269).

**Comment by enebo** [comment] 2022-12-26 17:04
This is a duplicate of https://github.com/jruby/jruby/issues/7486. This works for me with HEAD.  We will put out 9.4.1.0 right after new years.

**Closed by enebo** 2022-12-26 17:04 UTC
