### ISSUE TITLE
JRuby 9.4 `each_slice` chaining regression

### ISSUE THREAD

**Issue by cbeer** [jruby/jruby#7505] opened 2022-12-01 17:50 UTC
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc):
> jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 18.0.1.1+0 on 18.0.1.1+0 +jit [x86_64-darwin]
* Operating system and platform (e.g. `uname -a`)
> Darwin li-dl-7467-b893 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

**Expected Behavior**

In CRuby (and JRuby 9.3):

```
irb(main):001:0> [1,2,3,4,5,6,7].each_slice(3).map(&:join)
=> ["123", "456", "7"]
```

**Actual Behavior**

JRuby 9.4 throws an exception:

```
irb(main):001:0> [1,2,3,4,5,6,7].each_slice(3).map(&:join)
org/jruby/RubyArray.java:2030:in `each_slice': undefined method `join' for 1:Integer (NoMethodError)
	from org/jruby/RubyEnumerator.java:397:in `each'
	from org/jruby/RubyEnumerable.java:835:in `map'
```

**Comment by enebo** [comment] 2022-12-01 18:19
This is a duplicate of #7491 (different example of same error).

**Closed by enebo** 2022-12-01 18:19 UTC
