### ISSUE TITLE
Rack tests broken

### ISSUE THREAD

**Issue by raggi** [jruby/jruby#2428] opened 2015-01-05 18:57 UTC
We have two failing tests on jruby 9k: https://travis-ci.org/rack/rack/jobs/45815446

As yet, I haven't diagnosed myself. Associated Rack ticket: https://github.com/rack/rack/issues/778

Thanks!

**Comment by headius** [comment] 2015-01-06 17:14
This actually appears to work on 9k and not on 1.7. Notice in your log that the bacon.rb warning is coming from a 1.7.18-d19 install in rvm.

However, I can't reproduce it on either 9k or 1.7 on OS X. It may be specific to Linux.

@raggi Are you on Linux? If so, can you try running there with both versions and report back?

**Comment by raggi** [comment] 2015-01-06 17:18
I haven't replicated this locally (I'm keeping my rack time minimal these days, as I have absolutely no use for it (or ruby) anymore). It's occurring on travis.

**Comment by raggi** [comment] 2015-01-06 17:19
So it is. Eugh, travis.

**Comment by headius** [comment] 2015-01-06 17:28
It is specific to Linux or specific to Travis?

**Comment by raggi** [comment] 2015-01-06 17:46
Sorry, I'm shaving yaks right now (bundler, travis, optional dependencies, platforms). I'll have some better answers for you in maybe 20 minutes.

**Comment by raggi** [comment] 2015-01-06 18:16
Yes, it's 1.7.18 on linux that's failing. My apologies for the confusion.

**Comment by headius** [comment] 2015-01-06 21:05
@raggi Ok, thank you for confirming. I think we can take it from here.

**Comment by mkristian** [comment] 2015-04-09 20:13
@raggi I tried to reproduce the issue on current master - I could not reproduce it with jruby-1.7.19 or jruby-9.0.0.0-pre1 and rack on travis seems to be green now.

would like either to fix the problem or close this issue

**Comment by raggi** [comment] 2015-04-11 21:22
Feel free to close

**Closed** 2015-04-12 05:51 UTC
Labels: in progress, JRuby 1.7.x
