### ISSUE TITLE
File::Stat.new() issue in 1.7.23 on Windows 7

### ISSUE THREAD

**Issue by ph** [jruby/jruby#3525] opened 2015-12-08 18:01 UTC
I have been investigating a Logstash [issue](https://github.com/logstash-plugins/logstash-input-file/issues/82) with the file input on windows 7 x86.

Se this JVM error log at https://gist.github.com/ph/c0dcc55573337a8d2296

When we try to use the `File::Stat.new` on a file deleted by another process it 
throw an exception `EXCEPTION_PRIV_INSTRUCTION` by following the trace and the logic flow I have narrowed it down in our code to this line https://github.com/jordansissel/ruby-filewatch/blob/master/lib/filewatch/watch.rb#L102

**Few points that I know:**

- When I run the same code in a Windows 2012 Server or Windows 10, I don't have the problem.
- When I rollback to JRuby to 1.7.22 I don't see the issue anymore on windows 7.

I have tried to create a simple test case outside of Logstash without luck so far.
I have a reproducible way using logstash check the [issue](https://github.com/logstash-plugins/logstash-input-file/issues/82) for the full test case

**Comment by ph** [comment] 2015-12-08 18:03
@enebo Could this be related to the latest changes concerning `Stat` Handling under windows and could I provide anything else to help debug this issue?

**Comment by enebo** [comment] 2015-12-08 23:57
@ph hmmm this is pretty weird.  It sort of sounds like some race exists where FindFirstFileW thinks something is there and then it really isn't and it crashes.  I am wondering if there are any issues in MSDN (or however bugs are tracked in Windows) about FindFirstFileW.  It is a little odd to be seeing this problem since this is a very common API call in Windows.

**Comment by enebo** [comment] 2015-12-09 00:26
@ph Another suggestion (if possible) is to see if MRI will also crash in this way.  We are both calling the same methods (although we call through our jffi subsystem and they compile C code).  I am curious whether it also crashes on MRI.

**Comment by ph** [comment] 2015-12-09 14:15
@enebo Concerning the race this is what I though also from the error log. For reproducing under mri, we will check to come up with a easier test case to reproduce might take some times.

cc @jsvd

**Comment by enebo** [comment] 2015-12-09 22:25
@ph @jsvd I did some cursory searches for problems with FindFirstFileW and with the errno returned and it was not particularly useful.

**Comment by enebo** [comment] 2015-12-13 01:34
@ph @jsvd I did some cursory searches for problems with FindFirstFileW and with the errno returned and it was not particularly useful.

WOW --- this text area has had this sentence in it for days :|  I should remember to hit the comment button.

**Comment by enebo** [comment] 2016-01-11 21:14
Hmm I might have had a breakthrough!  https://msdn.microsoft.com/en-us/library/windows/desktop/aa364946%28v=vs.85%29.aspx

Check out this section on transactional support:

"Transacted Operations

If a file is open for modification in a transaction, no other thread can open the file for modification until the transaction is committed. So if a transacted thread opens the file first, any subsequent threads that try modifying the file before the transaction is committed receives a sharing violation. If a non-transacted thread modifies the file before the transacted thread does, and the file is still open when the transaction attempts to open it, the transaction receives the error ERROR_TRANSACTIONAL_CONFLICT.
"
This is not the exact same thing but it seems close in spirit.  I might look into the transactional version of these file.

@ph the logstash script you have that reproduces this that I can run locally on my win7 windows machine?

**Comment by enebo** [comment] 2016-01-11 21:45
Hmm on the next link to the transacted version is it not highly recommending I not use this...

**Comment by enebo** [comment] 2016-01-11 21:51
ignore my last two comments.  I had not looked at the actual crash dump since before I left for Japan and I realize I should have :)

jnr.posix.WindowsLibC$jnr$ffi$0.FindFirstFileW([BLjnr/posix/windows/WindowsFindData;)Ljnr/posix/HANDLE;+60

So, I was spending time this afternoon looking at GetFileAttributesExW when the crash is happening after that call in the failure branch in FindFirstFileW.  So this bug just got much different and hopefully will get some traction now that I am actually looking at the right method :|

**Comment by enebo** [comment] 2016-01-12 16:52
I can reproduce this problem entirely within jnr-posix now.  If I create a temp file via java.io.File then FindFirstFileW will crash the JVM.  If I access the parent directory of that file then the call passes.  I would expect some all or nothing behavior unless some fields are layed out wrong WindowsFindData and directories are not trying to write to those fields somehow???  Anyways this is good new since I have something local which is broken.

This particular bug was not occurring very often because it is only called on a failure from GetFileAttributesExW.  So, in other words, only in a weird case.

**Comment by ph** [comment] 2016-01-12 18:19
@enebo Wohoo! do you still need a reproducible Logstash script? There is more details on our side at https://github.com/logstash-plugins/logstash-input-file/issues/82

 I will gladly test it if you have fix!

**Comment by enebo** [comment] 2016-01-12 21:09
@ph I will be updating jruby-1_7 branch with new jnr-posix which has resolved the issue.  I would like to get some confirmation.  Perhaps I can ask you to test this tomorrow to make sure it is really fixed?

**Comment by ph** [comment] 2016-01-12 21:14
@enebo Sound like plan! point me to a binary and It will be easy to test.

**Comment by enebo** [comment] 2016-01-12 21:20
Whoops wrong issue description.  @ph can you build jruby-1_7 or do you need a nightly build made?

**Comment by ph** [comment] 2016-01-12 21:26
@enebo I would prefer a nightly build

**Comment by enebo** [comment] 2016-01-12 21:42
@ph http://ci.jruby.org/snapshots/jruby-1_7/jruby-bin-1.7.24-SNAPSHOT.tar.gz

**Comment by enebo** [comment] 2016-01-13 14:57
@ph If you got the snapshot yesterday then get another today since there are two more commits in it now.

**Comment by ph** [comment] 2016-01-14 14:33
Same kind of error with the newest build, (I used the .zip which should be the same as the tgz)

![screenshot 2016-01-14 09 30 32](https://cloud.githubusercontent.com/assets/640/12326916/942e3790-baa1-11e5-849b-453848cfc89b.png)

full trace in https://gist.github.com/ph/4384f48b0ffa580a595b

**Comment by enebo** [comment] 2016-01-14 15:36
Ok well I will see if I can repro with the linked issue from logstash locally on my win7 box.  Stay tuned...

**Comment by enebo** [comment] 2016-01-19 18:58
@jsvd @ph http://ci.jruby.org/snapshots/jruby-1_7/jruby-bin-1.7.24-SNAPSHOT.tar.gz

I think I got it for realsies this time.  I cannot reproduce on 32 bit JVM running the logstash example now but I would love to get confirmation this is good with logstash now.

**Comment by ph** [comment] 2016-01-19 21:13
@enebo With the latest snapshot that you posted, I cannot reproduce that issue with windows 7 :+1:

**Comment by enebo** [comment] 2016-01-19 22:27
@ph excellent.  Look forward to a JRuby release tomorrow then.

**Closed by enebo** 2016-01-19 22:27 UTC
