### ISSUE TITLE
Warnings in Rake's extension code to FileUtils under JRuby 9.4.0.0

### ISSUE THREAD

**Issue by deivid-rodriguez** [jruby/jruby#7499] opened 2022-11-30 10:22 UTC
**Environment Information**
  
I'm getting new warnings since JRuby 9.4.0.0 in Rake's extension code to FileUtils: https://github.com/ruby/rake/blob/1d387b0291a95d433e83963c0278c656841263c3/lib/rake/file_utils_ext.rb.

**Expected Behavior**

Clone ttps://github.com/rubygems/rubygems/.

Run `ruby -Ilib -S rake install` with JRuby 9.4.0.0. NOTE: this upgrades your JRuby installation to the the master version of RubyGems & Bundler. It can be reverted with `gem update --system <previous_version>`.

You'll get an output full of lines similar to the following:

```
/Users/deivid/.asdf/installs/ruby/jruby-9.4.0.0/lib/ruby/gems/shared/gems/rake-13.0.6/lib/rake/file_utils_ext.rb:36: warning: key :verbose is duplicated and overwritten on line 36
```

**Actual Behavior**

Clean output.

**Comment by enebo** [comment] 2022-11-30 14:29
Yeah I just noticed this myself yesterday but in another library.  The warn comes from something like this:

```ruby
options = {key: 1}

def foo(key: 2, **options)
end

foo(key: 3, **options)
```

**Comment by enebo** [comment] 2022-11-30 21:40
Ugh.  This will be an interesting issue.  If I do something like:

```ruby
foo(**{key: 1, **{key: 2}})
```

We will see the warning.  If we do:

```ruby
foo(**{key: 1}, **{key: 2})
```

We do not see the warning. 

This is all tied to multiple assignment:

```ruby
a = **{key: 1, **{key: 2}}
```
We have a warning.

So the rule here is that in the warnings we are hash splatting and not keyword resting.  The duplication on 
hash splatting should warn only.  We get this warning in the parser as well but only in the case of statically specified
keywords.

**Comment by enebo** [comment] 2022-11-30 23:01
Luckily kwrest and hashsplat is not done in the same place in IRBuilder.

**Comment by deivid-rodriguez** [comment] 2023-02-09 21:41
@enebo Just some heads up that I upgraded our CI to use JRuby 9.4.1.0 and I'm still seeing the issue. Was the fix to this supposed to be released with JRuby 9.4.1.0? Thanks!

**Comment by deivid-rodriguez** [comment] 2023-03-02 13:18
@enebo should I report a new issue or would you rather reopen this? Thanks!

**Comment by headius** [comment] 2023-03-02 22:29
If it's exactly the same we can just reopen this bug.

**Comment by headius** [comment] 2023-03-06 14:14
@enebo one more look at this before 9.4.2?

**Comment by enebo** [comment] 2023-03-06 17:50
This was opened as a new issue and it expanded the cause to the point I realized there was a very simple rule:  Only literal ```**{a: 1}``` sorts of kwrests issues the warning (which begs the question how often does that actually happen?).

The error you are seeing will be in 9.4.2.0 and was fixed in https://github.com/jruby/jruby/issues/7672

**Closed by enebo** 2023-03-06 17:50 UTC

**Comment by deivid-rodriguez** [comment] 2023-03-06 17:53
Thank you!
