### ISSUE TITLE
Can't access java member variables

### ISSUE THREAD

**Issue by yamam** [jruby/jruby#5684] opened 2019-04-09 22:38 UTC
### Environment

jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server VM 25.201-b09 on 1.8.0_201-b09 +jit [mswin32-x86_64]

### Expected Behavior

JavaTest.java
```java
public class JavaTest {
    public int x;
    public static int y;
}
```

test.rb
```ruby
java_import 'JavaTest'

begin
    p JavaTest.new.x
rescue
    p $!
end

begin
    p JavaTest.y
rescue
    p $!
end
```

You can access java member variables on jruby 9.2.6.0

```
$ jruby-9.2.6.0/bin/jruby test.rb
0
0
```

### Actual Behavior

You can't access java member variables on jruby 9.2.7.0

```
$ jruby-9.2.7.0/bin/jruby test.rb
#<NoMethodError: undefined method `x' for #<Java::Default::JavaTest:0x3d45bd>>
#<NoMethodError: undefined method `y' for Java::Default::JavaTest:Class>
```

**Comment by headius** [comment] 2019-04-10 18:10
Hmm, did something changes with how we bind fields, @kares?

**Comment by kares** [comment] 2019-04-11 10:23
no changes there, starting to think this might relate to how the default package works (in terms of lookup)
`bin/jruby -e "p org.jruby.util.ByteList.new.begin"` ... works fine on current master

**Comment by kares** [comment] 2019-04-11 10:54
confirmed, only classes in the default package seem to be problematic, this is Java 8 thus no modules ...

**Comment by kares** [comment] 2019-04-11 12:02
problem seems to be the modulator check from https://github.com/jruby/jruby/commit/7f206352ca8dc6c03d727a13aecff1a3ed8fa4d0#diff-c00f12e0a2700d71b3ad1b39305d8f2bR21 (likely due `return false` for when it does not need to set). seems to me the condition logic has a typo - should have been `||` instead of `&&` ... will shoot up a PR with a test to see what CI thinks.

**Comment by kares** [comment] 2019-04-11 13:54
so the problem is `klass.getPackage().getName()` on Java 8 for default package this is a NPE
since the module system `getPackage()` returns an (unnamed) package object: https://github.com/headius/backport9/pull/1

**Comment by headius** [comment] 2019-04-11 16:41
backport9 v1.3 has been released and I've pushed update_backport9 branch for JRuby. When that's green I'll merge to master and let you take it from there @kares. I had some odd spec:ji failures locally that may mean my environment is dirty.

**Comment by headius** [comment] 2019-04-11 16:41
backport9 v1.3 has been released and I've pushed update_backport9 branch for JRuby. When that's green I'll merge to master and let you take it from there @kares. I had some odd spec:ji failures locally that may mean my environment is dirty.

**Comment by headius** [comment] 2019-04-11 18:51
@kares #5689 has been merged to master. Your tests look fine, so if that's green go ahead with it.

**Closed by headius** 2019-04-11 18:51 UTC
