### ISSUE TITLE
Using at_exit and Signal.trap possibly creates a race-condition

### ISSUE THREAD

**Issue by Adithya-copart** [jruby/jruby#5437] opened 2018-11-12 03:29 UTC
### Environment

Provide at least:
* JRuby version: `jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [darwin-x86_64]`
* Operating system and platform (e.g. `uname -a`): `Darwin MB-ADPENTELA.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

### Expected Behavior
* The `Signal.trap` and `at_exit` hooks are executed in different threads leading to a race-condition where both `at_exit` and `Signal.trap` are defined.

Example: Puma traps `SIGINT` and sucker_punch uses the `at_exit` hook leading to a `SystemExit` before sucker_punch workers are shutdown.
https://github.com/puma/puma/issues/1675
https://github.com/brandonhilkert/sucker_punch/issues/223

### Actual Behavior
MRI is using the same thread for both `at_exit` and `Signal.trap`. It would be nice if there is some synchronization.

```
### test.rb
at_exit do
  sleep(1)
  puts "Thread in at_exit: #{Thread.current}"
end

Signal.trap("SIGINT") do
 puts "Thread in trap: #{Thread.current}"
 exit
end

sleep

## JRuby
$ RUBYOPT=-d jruby test_in_jruby.rb 
Exception `Gem::MissingSpecError' at /Users/adpentela/.rvm/rubies/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:310 - Gem::MissingSpecError
^CThread in trap: #<Thread:0x19b33233>
Exception `SystemExit' at org/jruby/RubyKernel.java:735 - exit
Thread in at_exit: #<Thread:0x37d31475>

## MRI
 $ ruby test_in_jruby.rb 
^CThread in trap: #<Thread:0x00007fd94d085c40 run>
Thread in at_exit: #<Thread:0x00007fd94d085c40 run>
```
Let me know if I'm doing something wrong or if this is a duplicate issue.
I had a quick glance at https://github.com/jruby/jruby/issues/4956 but not sure if this is related.

Thanks!

**Comment by headius** [comment] 2018-11-12 16:30
Good find!

The main issue here is that the Signal.trap thread is not owned by us; it's provided by the JVM. Unfortunately there's no way to know that it's executing or if there's pending signals about to be processed.

One possible fix for this would be to modify our `trap` impl such that instead of running on the JVM signal-handling thread, it pushes a job onto a job queue that can be shared by at_exit.

**Comment by headius** [comment] 2019-04-08 22:36
The original PR for this led to some unexpected behavioral differences with CRuby that need to be addressed. Primarily, it seems that tests/specs expect `at_exit` to be run on the main thread, while #5441 attempts to shut everything off to the same non-main thread(s) (via an executor set up for signal handling).

Signals themselves also are frequently expected to run on the currently-executing thread, but we have never supported that behavior.

This can still be dealt with, but we need to clarify expected behavior for at_exit blocks with regards to main thread.

**Comment by Adithya-copart** [comment] 2019-07-25 17:23
@headius I was testing `at_exit` and noticed that `Signal.trap` actually waits for `at_exit`.
So, this issue can probably be closed.

```
at_exit do
  p 'In at_exit .....'
  sleep 5
  p 'done sleeping'
end

Signal.trap('INT') {exit; p 'never prints as expected'}

p 'Sleeping..'
sleep
```
I falsely concluded that the issue I encountered is caused by a race-condition as MRI uses the same thread for `at_exit` and `Signal.trap`. This behavior in Jruby is probably not a bug but a difference from MRI.

The below script will be unresponsive if `puma` is used but works fine with Webrick.
I will open an issue in the appropriate library if I track-down the root cause later.

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'sucker_punch'
  # gem 'puma'
  gem 'sinatra'
end

require 'sucker_punch'
require 'sinatra'

set :bind,'0.0.0.0'

class TestJob
  include SuckerPunch::Job

  def perform
    puts "The job #{self} is starting to sleep 5sec"
    sleep 5
    puts "The job #{self} woke up from sleep"
  end
end

get '/' do
  p "Hello"
  3.times {TestJob.perform_async}
  p 'Enqueued job'
end

Thread.new do
  sleep 1 # Wait for startup
  require 'net/http'
  Net::HTTP.get(URI 'http://0.0.0.0:4567/')

  # TERM works but INT doesn't kill the puma process.
  puts "Sending SIGINT.."
  Process.kill('INT', Process.pid) 
end
```

**Comment by headius** [comment] 2019-07-25 22:49
@Adithya-copart Thank you for the update!

**Closed by headius** 2019-07-25 22:49 UTC

**Comment by dentarg** [comment] 2019-07-26 07:12
> \# TERM works but INT doesn't kill the puma process.

@Adithya-copart (if you use Ruby 2.6) have you tried with Puma 4.0.x? that version should include fix for that (https://github.com/puma/puma/pull/1741)

**Comment by headius** [comment] 2019-07-26 08:25
@Adithya-copart INT is not by default trapped on JRuby because we did not want to interfere with the JVM's hard shutdown hook, but you can easily trap it and raise interrupt:

```ruby
Signal.trap(:INT) { raise Interrupt }
```

**Comment by Adithya-copart** [comment] 2019-07-26 16:03
@headius Thanks for the info. I'm not using the library `sucker_punch` anymore.
This issue is no longer affecting me directly.

_Here is a run down of what is going on to the best of my understanding:_

Puma traps the `SIGINT` [here](https://github.com/puma/puma/blob/1c9da362c8d2f09360ace3eedc12946dea39de05/lib/puma/launcher.rb#L406-L414). It calls `exit` that'll result in the execution of the `at_exit` handlers defined in [Sinatra](https://github.com/sinatra/sinatra/blob/eee711bce740d38a9a91aa6028688c9a6d74b23b/lib/sinatra/base.rb#L1541-L1554), [sucker_punch](https://github.com/brandonhilkert/sucker_punch/blob/d06ba290be4d56fbbd45d37f73c47bd441ad0224/lib/sucker_punch.rb#L53-L55) and [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby/blob/v1.1.5/lib/concurrent/utility/at_exit.rb), a dependency for `sucker_punch`.

SuckerPunch is a library that utilizes [JavaExecutorService](https://github.com/ruby-concurrency/concurrent-ruby/blob/v1.1.5/lib/concurrent/executor/java_thread_pool_executor.rb) via `concurrent-ruby` for executing some in-memory asynchronous tasks. The at_exit hook in sucker_punch is responsible for shutting down these threads.

For some reason, the puma process does not shutdown properly upon receiving a `SIGINT`.

It does shutdown properly when I added another at_exit handler with [Tracepoint enabled](https://gist.github.com/Adithya-copart/d5d500c82d9b81fcb8b5c4913b769dd9) while trying to debug this issue.

**Comment by Adithya-copart** [comment] 2019-07-29 00:16
Puma is trying to shutdown the server thread within a `Signal.trap` block and are joining this thread. This is working fine when the signals are handled on the main thread but this is not the case in JRuby.

**Comment by jhulford** [comment] 2020-03-12 16:45
I know this issue is closed, but I recently had to revert my jruby app from Puma 4 to Puma 3 (jruby 9.2.9) and then ran into this issue of suckerpunch queue threads blocking shutdown after reverting and stumbled on this issue.

If you need to use Puma version 3, here's how I worked around this:

Add the follow as an initializer somewhere after the puma server starts up (Rails initializer in my case)

```ruby
puma_trap = Signal.trap "SIGINT" do
  require 'sucker_punch/queue'
  SuckerPunch::Queue.shutdown_all
  puma_trap&.call
end
```

This adds your own SIGINT trap which shuts down the suckerpunch queues before then calling the main puma trap.

If you have different background thread pools, etc causing puma to hang, you'll want add additional logic for shutting those down too.

**Comment by headius** [comment] 2020-03-17 18:44
@jhulford I wonder if your issue might be fixed by either https://github.com/ruby-concurrency/concurrent-ruby/issues/839 or https://github.com/ruby-concurrency/concurrent-ruby/issues/817? sucker_punch does indeed depend on concurrent-ruby so I suspect it's the same non-daemon thread issue.

**Comment by Adithya-copart** [comment] 2020-03-17 20:09
@headius  Suckerpunch is explicitly [using](https://github.com/brandonhilkert/sucker_punch/blob/34a7d83db7807a158409213c5a84a03d29c1b5bf/lib/sucker_punch/queue.rb#L10-L15) `autoterminate: false` and assuming responsibility to shutdown using `at_exit` as per https://github.com/ruby-concurrency/concurrent-ruby/pull/840#issuecomment-572190066

The main thread exits in Puma 3 while the `at_exit` block is still terminating the thread pool due to an explicit `exit` in the trap handler that is removed in Puma 4 after you pointed it out in https://github.com/jruby/jruby/issues/5844#issuecomment-524203618

This was happening in Puma 3
```
at_exit do
  # Instead of sleep SuckerPunch requests threadpool shutdown after timeout.
  sleep
end

# Puma 3 implementation
Signal.trap('INT') { exit }

p 'Sleeping...'
sleep
```

**Comment by headius** [comment] 2020-03-17 20:23
@Adithya-copart Ok thank you for clarifying. So it seems the comment by @jhulford is the best workaround available currently, since this combination of SuckerPunch and Puma 3 has issues.

As always, if there's anything JRuby should do better, please file a new issue.

**Comment by Adithya-copart** [comment] 2020-03-18 07:20
If I bound the sleep call in above snippet, the `at_exit` blocks are executed properly as expected even after `exit` is called in the trap handler.

```
at_exit do
  sleep 2
  p "Done with at_exit"
end

Signal.trap('INT') do
  exit
end

p 'Sleeping...'
sleep

### Result in JRuby 9.2.9.0

$ ruby -d test_exit.rb 
"Sleeping..."
^CException `SystemExit' at org/jruby/RubyKernel.java:751 - exit
"Done with at_exit"
```
I was able to get this reproduction script where the `at_exit` blocks are not completely executed when `exit` is called in the trap in Puma 3.

The same `at_exit` blocks are completely executed in Puma 4 where the `exit` in the trap is removed.

**Doubt:** Why would  the `at_exit` blocks get executed in the first script but not in the following where both use `exit` in the trap handler?
```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'rack'
  gem 'puma', '~> 3'
end

require 'puma/cli'

rackup_file = "#{Gem::Specification.find_by_name("rack").gem_dir}/example/lobster.ru"

at_exit do
  5.times { |i| p i; sleep 0.2 }
end

def install_trap
  puma_trap = Signal.trap('INT') do
    trace = TracePoint.new do |tp|
      p "Path: #{tp.path}##{tp.lineno}, Method:#{tp.method_id}, Event: #{tp.event}"
    end
    trace.enable

    puma_trap.call
  end
end

server = Puma::CLI.new([rackup_file])

Thread.new {sleep 1; install_trap}

server.run
```

**Comment by headius** [comment] 2020-03-18 18:35
> Why would the at_exit blocks get executed in the first script but not in the following when both of them use exit in the trap handler?

I suspect it's because in the first case the "main" script is prevented from exiting until `exit` is called.

The sequence in Puma 3's SIGINT handler goes like this:

* Set `:stop` condition for the server loop.
* Use `graceful_stop` to interrupt the server and proceed toward termination.
* Call `exit` after `graceful_stop` has returned.

It seems likely that `graceful_stop`, which is executing inside a signal handler thread, has progressed the main thread into its final shutdown stages, which means it's in the process of executing the `at_exit` block when suddenly another `exit` event happens. That subsequent `exit` forces the main thread to abort shutdown early.

When I run your second script without the delay and with a longer `times` loop, it gets to about 50 iterations before it terminates... so it does indeed run, but is interrupted from completion by the additional hard `exit` call.

A similar behavior can be emulated in your first script like so:

```ruby
at_exit do
  sleep 2
  p "Done with at_exit"
end

Signal.trap('INT') do
  Thread.main.raise
  sleep 0.01
  exit
end

p 'Sleeping...'
sleep
```

The `raise` call here causes the main script to exit `sleep` and begin to shut down the runtime. The `sleep` allows it to progress to the `at_exit` processing. With this script above, most runs will never see "Done with at_exit" because the "second exit" event interrupts it.

There might be a valid issue here with multiple exits causing early termination during shutdown. Perhaps we want to ignore asynchronous exit events on the main thread after a first event has arrived, so long as we are actually progressing to shutdown? cc @enebo 

On the CRuby side, it *might* be possible to see similar behavior, but I could not reproduce this behavior there. In my example above, nothing after the `raise` call executes in the signal handler because CRuby immediately switches context back to the main thread, which exits the script and abandons all running threads.

**Comment by Adithya-copart** [comment] 2020-03-18 23:59
@headius Thanks for the explanation as always.

> Signals themselves also are frequently expected to run on the currently-executing thread, but we have never supported that behavior.

I noticed that CRuby executes the traps completely but in JRuby the signal handler terminates early if the main thread exits. Your comment explains CRuby behavior in the below example as the trap is executed in the main thread.

I don't have a real world issue but documenting this observation anyway.
```
at_exit do
  p 'Started at exit'
  sleep 0.2
  p 'Done with at_exit'
end

Signal.trap('INT') do
  p "Trap: #{Thread.current}, Main: #{Thread.main}"
  @stop = true
  a = 0
  100_000_000.times { a += 1 }
  p 'Not called in JRuby: exit inside trap'
  exit
end

@stop = false

server = Thread.new do
  p "Server started in #{Thread.current}"

  while true
    break if @stop

    100_000.times {|i| i}
  end
  p 'Server stop...'
end

server.join

p 'Never printed in C Ruby'

```

**Comment by headius** [comment] 2020-03-19 16:02
> in JRuby the signal handler terminates early if the main thread exits

Yes, that's it. The `at_exit` blocks are executed on the main thread, so when another thread triggers another `exit`, the `at_exit` logic gets interrupted. It's this behavior that makes me think we might want to fix it by ignoring additional exits during shutdown.

Here's a script that shows the difference more clearly:

```ruby
at_exit { puts 'here' }
at_exit do
  puts 'before exit'
  Thread.new { puts 'in thread'; exit }.join
  puts 'after exit'
end
```

On CRuby, this script prints all lines; the exit must be called, but it does not interrupt execution of the remaining `at_exit` code.

On JRuby, as you'd expect, it only prints "before exit" and "in thread".
