### ISSUE TITLE
Unsupported platform: unknown-linux (mips64el)

### ISSUE THREAD

**Issue by kszsa** [jruby/jruby#5330] opened 2018-09-27 02:43 UTC
### Environment
JRuby version:1.7.25

[root@node155 ~]# uname -a
Linux node155 2.6.32-0.48.ns6.mips64el #1 SMP Thu Oct 9 14:19:54 CST 2014 mips64el mips64el mips64el GNU/Linux

[root@node155 ~]# java -version
openjdk version "1.8.0_25"
OpenJDK Runtime Environment (build 1.8.0_25-rc24-b17)
OpenJDK 64-Bit Server VM (build 25.25-b02, mixed mode)

I am trying to get logstash (which uses jruby) to run on Linux using mips64el. When I run logstash I get the error "Unsupported platform: unknown-linux"

[root@node155 bin]# ./logstash -e ""
Sending Logstash's logs to /opt/logstash-5.1.1/logs which is now configured via log4j2.properties
LoadError: Unsupported platform: unknown-linux
          require at org/jruby/RubyKernel.java:1040
          require at /opt/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /opt/logstash-5.1.1/vendor/jruby/lib/ruby/shared/ffi/ffi.rb:69
          require at org/jruby/RubyKernel.java:1040
          require at /opt/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /opt/logstash-5.1.1/vendor/jruby/lib/ruby/shared/ffi.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /opt/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /opt/logstash-5.1.1/vendor/jruby/lib/ruby/shared/ffi.rb:1
           (root) at /opt/logstash-5.1.1/logstash-core/lib/logstash/util/prctl.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /opt/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
             LibC at /opt/logstash-5.1.1/logstash-core/lib/logstash/util/prctl.rb:3
           (root) at /opt/logstash-5.1.1/logstash-core/lib/logstash/util/prctl.rb:2
           (root) at /opt/logstash-5.1.1/logstash-core/lib/logstash/util.rb:1
  set_thread_name at /opt/logstash-5.1.1/logstash-core/lib/logstash/util.rb:20
          execute at /opt/logstash-5.1.1/logstash-core/lib/logstash/runner.rb:207
           (root) at /opt/logstash-5.1.1/lib/bootstrap/environment.rb:71

**Comment by kszsa** [comment] 2018-09-27 02:58
I transplant jruby 1.7.25 to mips64el
I compiled the source code of logstash(5.1.1)，build successful.
when i try to run logstash ,the error occurred.

**Comment by mprins** [comment] 2018-09-27 09:51
this seems a duplicate of https://github.com/jruby/jruby/issues/4246#issuecomment-257197576 which has been open for almost 2 years pending a version of jffi that has support for your mips64el platform

**Comment by headius** [comment] 2018-10-09 15:16
We no longer support 1.7, so that's one issue here. However, even the latest JRuby and JFFI do not have support for mips64el (or any mips at all, for that matter).

@kszsa You have access to a MIPS system, I assume? Perhaps you can help us get a build of the JFFI native bits for your platform? I think we may start to "just work" if we can get that into JRuby 9.2.1 (although you'd need to update to get the benefit, or possibly build your own JRuby 1.7.x with the update JFFI).

**Comment by kszsa** [comment] 2018-10-11 02:08
@headius ,I try it

**Comment by headius** [comment] 2020-07-23 16:05
This has long been resolved on the JRuby 9.2 line, with support for Linux on mips64el added several releases ago. This was reported against 1.7, but fixed sometime around 9.2.9.0.

**Closed by headius** 2020-07-23 16:05 UTC
